nextcloud/desktop

.drone.yml

Our 5.6 container is to old. Lets focus on the others for now

---

src/gui/creds/httpcredentialsgui.cpp

Have correct app password link

---

.drone.yml

No double building on PR's

---

.drone.yml
admin/linux/build-appimage.sh

The goal here is to have automatic AppImages build. For easier testing and debugging.

Automatically start building AppImages on PR's

---

doc/owncloudcmd.rst

Typo in documentation

---

CONTRIBUTING.md

Update ownCloud references to NextCloud

---

.drone.yml

Bump drone images to contain WebEngine

---

.drone.yml

Bump drone images

---

src/libsync/networkjobs.cpp

If status.php fails check <server>/nextcloud/status.php

---

src/gui/accountmanager.cpp

Better explanation for encryption passphrase

---

src/libsync/propagateupload.cpp

There seems to be some errors that would stop processing the upload but wouldn't unlock the folder

Make sure folder is unlocked on upload when some errors occour

---

src/gui/ignorelisteditor.cpp
src/gui/ignorelisteditor.h
src/gui/ignorelisteditor.ui

This PR should match the request https://github.com/nextcloud/client/issues/146
Now the user can remove all items from the ignore list, add and remove any items and if she regrets it, she can restore to the default system ignore patterns.

Edit system exclude list

---

.drone.yml

Build no debian while it fails

---

src/gui/folderstatusmodel.cpp

Issue https://github.com/owncloud/client/issues/6337

FolderStatusModel: Refresh folders on Problem sync #6337

---

src/libsync/networkjobs.cpp

NO_SHIBBOLETH: Fix warning

---

ChangeLog
src/libsync/accessmanager.cpp
src/libsync/connectionvalidator.cpp

PR https://github.com/owncloud/client/pull/6353
Issue https://github.com/owncloud/client/issues/6285

HTTP2: Only from Qt 5.9.4 #6285

---

src/gui/folderman.cpp
src/gui/folderman.h
src/gui/folderstatusmodel.cpp
src/gui/owncloudgui.cpp
src/libsync/syncresult.h

owncloud/client/pull/6329
Issue owncloud/client/issues/6277

Tray: Change icon for unresolved conflicts #6277

---

src/common/utility.cpp
src/common/utility.h
src/libsync/owncloudpropagator.cpp
test/syncenginetestutils.h
test/testsyncconflict.cpp
test/testutility.cpp

PR https://github.com/owncloud/client/pull/6364

Conflicts: Add user name to conflict file name #6325

---

src/common/syncjournaldb.cpp
src/common/syncjournaldb.h
test/testsyncengine.cpp
test/testsyncjournaldb.cpp

Issue https://github.com/owncloud/client/issues/6322
--> Be aware: this created a lot of conflicts.

SyncJournal: Don't use LIKE with paths

---

src/gui/application.cpp

PR https://github.com/owncloud/client/pull/6367
It also refers to https://github.com/owncloud/client/pull/6347

Set launch-on-startup when the first account is set up

---

src/gui/folder.cpp

Changed wording in folder.cpp as well as translation files client_en.ts and client_de.ts. 
Others are still missing.

scary wording on big changes #216 (translations missing)

---

src/gui/folderman.cpp

Signed-off-by: Mark Ziegler <mark.ziegler@rakekniven.de>

Fixed tiny grammar issue

---

test/testsyncengine.cpp

https://github.com/owncloud/client/pull/6366

test/testsyncengine: testNoLocalEncoding is for Linux

---

src/gui/settingsdialog.cpp
src/gui/settingsdialog.h
src/gui/settingsdialogmac.cpp
src/gui/settingsdialogmac.h

PR https://github.com/owncloud/client/pull/6351

SettingsDialogMac: Also start timer for notifications

---

CMakeLists.txt
config.h.in
src/common/utility.cpp
src/csync/config_csync.h.cmake
test/testutility.cpp

PR https://github.com/owncloud/client/pull/6371
Issue https://github.com/owncloud/client/issues/6318
--> Is this relevant for us?

Utility::fsCasePreserving: remove UNIT_TESTING ifdef

---

src/common/filesystembase.cpp
src/common/filesystembase.h
src/libsync/propagatorjobs.cpp

PR https://github.com/owncloud/client/pull/6349

Don't delete contents behind directory junctions #6322

---

src/gui/sharedialog.cpp

ShareDialog: macOS grey odditiy #5774

---

src/gui/connectionvalidator.cpp
src/libsync/account.cpp
src/libsync/owncloudpropagator.cpp
src/libsync/owncloudpropagator.h
src/libsync/propagateremotedelete.cpp
src/libsync/propagateremotemove.cpp
src/libsync/propagateuploadv1.cpp

PR https://github.com/owncloud/client/pull/6380

ConnectionValidator: change the minimum server version

---

src/csync/csync.cpp
src/csync/csync_private.h
src/csync/csync_update.cpp
src/csync/vio/csync_vio.cpp
src/gui/folder.cpp
src/gui/folder.h
src/gui/folderstatusmodel.cpp
src/gui/issueswidget.cpp
src/gui/issueswidget.h
src/gui/owncloudgui.cpp
src/gui/protocolwidget.cpp
src/gui/protocolwidget.h
src/gui/syncrunfilelog.cpp
src/libsync/discoveryphase.cpp
src/libsync/progressdispatcher.cpp
src/libsync/progressdispatcher.h
src/libsync/syncengine.cpp
src/libsync/syncengine.h
src/libsync/syncresult.cpp
src/libsync/syncresult.h
test/testsyncengine.cpp

PR https://github.com/owncloud/client/pull/6373

Make sure ignored and conflict files show up in the issues tab even with partial local discovery

---

src/libsync/discoveryphase.cpp
src/libsync/discoveryphase.h

PR https://github.com/owncloud/client/pull/6379

Discovery: Error if properties are missing #6317

---

doc/autoupdate.rst
doc/building.rst
doc/conffile.rst
doc/glossary.rst
doc/installing.rst
doc/introduction.rst
doc/navigating.rst
doc/troubleshooting.rst
doc/visualtour.rst

Signed-off-by: Marius Blüm <marius@lineone.io>

[documentation] Mac OS X is now macOS

---

src/gui/cloudproviders/cloudproviderwrapper.cpp

I merged #314 to soon (apperently we don't test on drone with the cloud providers stuff).
@juliushaertl please have a look.

Fix cloudproviders after merging #314

---

src/gui/sslbutton.cpp
src/libsync/account.h

Issue https://github.com/owncloud/client/issues/3146

SslButton: Add HTTP/2 info #3146

---

src/libsync/owncloudpropagator.h
src/libsync/propagateupload.cpp
src/libsync/propagateupload.h
src/libsync/propagateuploadng.cpp
src/libsync/propagateuploadv1.cpp

* Sometimes there was 'finished' and '_finished'
* Make each done() call automatically set _finished to true
--> Be aware: This has quite a bit of conflicts.

Upload: Simplify 'finished' flag

---

src/gui/sslbutton.cpp
src/gui/sslbutton.h

From 1+n*450msec to 1*450msec
Issue https://github.com/owncloud/client/issues/6031

SslButton: Improve speed (especially on macOS) #6031

---

admin/osx/macdeployqt.py
cmake/modules/MacOSXBundleInfo.plist.in

Issue owncloud/client/issues/5932

macdeployqt: Adjust minimum version based on our Qt #5932

---

src/csync/csync_update.cpp

Issue owncloud/client/issues/6414
PR owncloud/client/pull/6416

csync_update: add the checksum in the discovery log

---

src/csync/csync_update.cpp

Fix output add E2E again

---

src/libsync/owncloudpropagator.cpp
src/libsync/syncfileitem.h

PR owncloud/client/pull/6412
Issue owncloud/client/issues/6411

Blacklisting must prevent parent etag updates #6411

---

src/gui/sharelinkwidget.ui

PR owncloud/client/pull/6437
Issue owncloud/client/issues/6192

Share link: Update permission wording #6192

---

src/gui/folderstatusmodel.cpp

PR owncloud/client/pull/6438
Issue owncloud/client/issues/6277

Folders: Use "Problem" icon for unresolved conflicts #6277

---

src/gui/application.cpp
src/gui/logbrowser.cpp
src/gui/logbrowser.h
src/gui/owncloudgui.cpp
src/libsync/configfile.cpp
src/libsync/configfile.h
src/libsync/logger.cpp
src/libsync/logger.h

Issue owncloud/client/issues/6442
PR owncloud/client/pull/6448

Simple permanent logging

---

src/gui/socketapi.cpp

PR owncloud/client/pull/6444
Issues 
owncloud/client/issues/5382 
owncloud/client/issues/3819

macOS: Unload the Finder extension on exit #5382 #3819

---

shell_integration/MacOSX/OwnCloudFinderSync/FinderSyncExt/FinderSync.h
shell_integration/MacOSX/OwnCloudFinderSync/FinderSyncExt/FinderSync.m
shell_integration/MacOSX/OwnCloudFinderSync/FinderSyncExt/SyncClientProxy.h
shell_integration/MacOSX/OwnCloudFinderSync/FinderSyncExt/SyncClientProxy.m
src/gui/socketapi.cpp

macOS: Implement new dynamic Finder menu items #6328

---

src/gui/accountstate.cpp
src/gui/activitywidget.cpp
src/gui/activitywidget.h
src/gui/folder.cpp
src/gui/folder.h
src/gui/folderman.cpp
src/gui/updater/ocupdater.cpp
src/libsync/configfile.cpp
src/libsync/configfile.h
src/libsync/propagateupload.h
src/libsync/propagateuploadng.cpp
src/libsync/syncoptions.h

Use std::chrono::milliseconds to represent milliseconds

---

src/3rdparty/sqlite3/sqlite3.h

sqlite: Update bundled version to 3.23.1

---

doc/installing.rst

update supported linux platforms

---

src/gui/sharelinkwidget.cpp
src/gui/sharelinkwidget.h
src/gui/sharemanager.cpp

ShareLink: Preserve password when unrelated ui changes #6512

---

src/libsync/propagateupload.cpp
src/libsync/propagateupload.h
src/libsync/propagateuploadng.cpp
src/libsync/propagateuploadv1.cpp
test/testchunkingng.cpp

PropagateUpload: Remove unused PropagateUploadFileCommon::abort

---

src/common/syncjournaldb.cpp

For #6049
Issue owncloud/client/issues/6049
PR owncloud/client/pull/6526

macOS: Don't use WAL for sqlite3 in /Volumes

---

src/gui/folder.cpp
src/gui/folder.h

PR https://github.com/owncloud/client/pull/6377

Notify if an explicitly excluded folder is created #6222

---

src/gui/accountsettings.cpp
src/libsync/clientsideencryption.cpp
src/libsync/clientsideencryption.h
src/libsync/clientsideencryptionjobs.cpp

* Reorder openssl header import
* not => !

Fix windows build

---

cmake/modules/NSIS.template.in

Issue owncloud/client/issues/6515

 NSIS: SVG imageformats plugin DLL

---

admin/osx/macdeployqt.py

Fix macdeployqt

---

src/libsync/propagateuploadencrypted.cpp

Thread local storage don't work properly on OSX

---

admin/osx/macdeployqt.py
src/cmd/CMakeLists.txt
src/crashreporter/CMakeLists.txt
src/gui/CMakeLists.txt

More fixes for the OSX daily builds

---

shell_integration/windows/OCContextMenu/OCContextMenu.cpp

Issue owncloud/client/issues/6553

Windows Shell extention: Fix clicking on the menu entries

---

man/CMakeLists.txt

Issue owncloud/client/issues/6555

Fix make doc-man in shadow build

---

src/gui/accountsettings.cpp
src/gui/accountsettings.h
src/libsync/clientsideencryption.cpp
src/libsync/clientsideencryption.h

Fixes #157 
It is ugly but at least you can show it now.

Add a button to E2E accounts to show the mnemonic

---

src/gui/CMakeLists.txt
src/gui/accountmanager.cpp
src/gui/accountsettings.cpp
src/gui/mnemonicdialog.ui

Fixes https://github.com/nextcloud/desktop/issues/149

Use custom mnemonic dialog

---

src/gui/accountsettings.cpp

Hide decrypt option since it does only work for empty folders

---

.drone.yml

Add Qt-5.10 and Qt-5.11 drone builds

---

CMakeLists.txt

We require openssl 1.1

---

.drone.yml

Add clang build to CI

---

.drone.yml
admin/linux/build-appimage.sh

Build AppImage with Qt-5.11

---

.drone.yml
test/testsyncjournaldb.cpp
test/testutility.cpp
test/testxmlparse.cpp

Run unit tests on drone

---

src/libsync/theme.cpp

Remove default trademark text

---

README.md

.. also changes the positions of the emojis.

Adds item about Code of Conduct in the README.

---

src/gui/wizard/webview.cpp

Do not force to show the webview on construct

---

doc/conflicts.rst
doc/index.rst
src/gui/issueswidget.cpp
src/gui/issueswidget.h
src/gui/issueswidget.ui
src/libsync/theme.cpp
src/libsync/theme.h

The link url is themed.
PR owncloud/client/pull/6456

Issues: Show link to conflicts doc if there are some #6396

---

src/gui/CMakeLists.txt
src/gui/generalsettings.cpp
src/gui/generalsettings.h
src/gui/generalsettings.ui
src/gui/legalnotice.cpp
src/gui/legalnotice.h
src/gui/legalnotice.ui
src/libsync/theme.cpp

Add legal notice button to about dialog

---

src/gui/activityitemdelegate.cpp

Fixes #517: changes QPalette for more readability in the activities list.

---

src/gui/wizard/webview.ui

Web view scales vertically

---

src/3rdparty/sqlite3/sqlite3.h

sqlite: Update bundled version to 3.24.0

---

README.md

In the wiki it was already fix but not in the Readme

Fix cmake command for linux in README too

---

.drone.yml
admin/linux/build-appimage.sh

Updates the `qtkeychain` dependency.

qtkeychain: 0.8.0 -> 0.9.1

---

src/common/filesystembase.cpp

Issue owncloud/client/issues/6699

Windows: Release handle/fd when file open fails #6699

---

src/gui/application.cpp

Found by @hurradieweltgehtunter
PR owncloud/client/pull/6672

Settings: Attempt to fix rename issue on old macOS

---

translations/client_en.ts

It seems this job didn't run. So I'm pushing it manual for now.
I'll look into why the cronjob didn't run.

Update to translate strings

---

src/gui/wizard/owncloudsetuppage.cpp

Build fix: remove an unused QtSvg/QSvgRenderer include

---

src/gui/application.cpp
src/gui/owncloudsetupwizard.cpp
src/gui/socketapi.cpp

Use Nextcloud

---

src/gui/accountmanager.cpp

Signed-off-by: Mark Ziegler <mark.ziegler@rakekniven.de>

l10n. Added space for correct grammar.

---

src/gui/application.cpp

Fixes https://github.com/nextcloud/desktop/issues/809

More verbose error and proper app name on configuration read error

---

src/gui/wizard/owncloudsetuppage.cpp

Fix cmake build using WITH_PROVIDERS=OFF

---

src/gui/accountmanager.cpp

Signed-off-by: Mark Ziegler <mark.ziegler@rakekniven.de>

Fixed typo

---

src/gui/wizard/owncloudsetupnocredspage.ui

This changes the link for the "Host your own" link in the wizard.

Change link to docs for NC 15

---

shell_integration/nautilus/setappname.sh
shell_integration/nautilus/syncstate.py

Ref https://github.com/nextcloud/desktop/issues/804 please review @camilasan @juliushaertl @rullzer :)

Fix appname for Nautilus integration script

---

src/gui/wizard/owncloudsetuppage.cpp

Stylesheet String was not correctly defined (missing ";" after "%2") and caused an error in logging output.
After checking the fixed Style I removed it since it does not really look good.

Removed Stylesheet

---

admin/linux/debian/debian.disco/changelog
admin/linux/debian/drone-build.sh

This patch adds support for the next Ubuntu release, Disco Dingo.

Support Ubuntu Disco Dingo

---

src/gui/wizard/webview.cpp

Handle spaces in username properly in login flow

---

src/gui/clientproxy.cpp
src/gui/wizard/webviewpage.cpp
src/gui/wizard/webviewpage.h

I must admit why this works is puzzling me. However if I just use a system
proxy without this it doesn't work. I suspect a Qt bug but will have to
dig deeper to find out if that is the case.
For now this little hack will have to do.

Fix login flow with system proxy

---

src/gui/creds/webflowcredentials.cpp

Be less verbose with logging

---

.drone.yml
admin/linux/build-appimage.sh

Add Qt-5.12 to CI

---

.drone.yml

New drone config

---

src/libsync/propagateupload.h
src/libsync/propagateuploadng.cpp
src/libsync/propagateuploadv1.cpp

Downstream of https://github.com/owncloud/client/pull/6856
Fixes https://github.com/nextcloud/desktop/issues/1136

Fix memory leak with device pointer

---

src/libsync/configfile.cpp

issue #1115 default remote poll is updated to 5 seconds from 30000 seconds

updated default remote poll to 5 seconds #1115

---

src/gui/wizard/webview.cpp

Fixed typo in "certificate"

---

src/gui/sharedialog.cpp
src/gui/sharelinkwidget.ui
src/gui/sharemanager.cpp
src/gui/sharemanager.h
src/gui/shareusergroupwidget.cpp
src/gui/shareusergroupwidget.ui

Also displays the sharees that reshared it via share link.

Displays the uid_owner of a shared file.

---

src/libsync/theme.cpp

Minor text change in the link to help in the tab 'General'.

---

.drone.yml
admin/linux/debian/scripts/git2changelog.py

This patch re-adds the Debian build to new Drone config.

Reinstate Debian build in the new Drone config

---

ChangeLog

Updates ChangeLog.

---

src/gui/accountsettings.ui
src/gui/activitywidget.ui
src/gui/folderwizardsourcepage.ui
src/gui/folderwizardtargetpage.ui
src/gui/generalsettings.ui
src/gui/legalnotice.ui
src/gui/mnemonicdialog.ui
src/gui/networksettings.ui
src/gui/sslerrordialog.ui
src/gui/wizard/owncloudadvancedsetuppage.ui
src/gui/wizard/owncloudhttpcredspage.ui
src/gui/wizard/owncloudoauthcredspage.ui
src/gui/wizard/owncloudsetupnocredspage.ui
src/gui/wizard/owncloudwizardresultpage.ui
src/gui/wizard/webview.ui

I have fixed the strings mentioned in this thread:
https://help.nextcloud.com/t/nextcloud-client-translation-issues/52958

Marking unused strings as unstranslatable

---

src/gui/folder.cpp

UI improvement: Message box: Delete / Keep all files

---

src/csync/csync_exclude.cpp

The default file created by the application it is not empty.

Checks if exclude file is empty before creating the regular expressions.

---

doc/building.rst

Added links and a description how to clone the repo

Update building instructions

---

src/gui/sharelinkwidget.ui

l10n: Remove string from Transifex resource

---

src/gui/legalnotice.cpp

Just noticed that our current client shows -2018. Figured we could update this.

Happy new year

---

src/gui/creds/webflowcredentials.cpp
src/libsync/networkjobs.cpp
src/libsync/networkjobs.h

Probably we also have to do this check in the reauth part of the code?

Fall back to old login flow on GS as this is not yet ready

---

src/gui/folderstatusdelegate.cpp

Fix issue #1237: White text on almost-white background

---

src/gui/legalnotice.cpp

Updated year in legalnotice.cpp

---

doc/installing.rst

Windows 7 is out of support

---

src/gui/connectionvalidator.cpp

Changed product name to Nextcloud

---

src/gui/cloudproviders/cloudprovidermanager.cpp
src/gui/cloudproviders/cloudprovidermanager.h
src/gui/cloudproviders/cloudproviderwrapper.cpp
src/gui/cloudproviders/cloudproviderwrapper.h

Set a simple unique identifier per folder to ensure that it is always unique.
Fixes https://github.com/nextcloud/desktop/issues/1704

Make sure that the libcloudprovider integration is using a valid D-Bus path

---

src/gui/sharelinkwidget.cpp

Only save notes on submit. Else you will get spammed with a ton of
requests (and possibly mails)

Do not save notes on text change

---

src/gui/accountsettings.ui
src/gui/addcertificatedialog.ui
src/gui/folderwizardsourcepage.ui
src/gui/shareusergroupwidget.ui
src/gui/wizard/owncloudsetuppage.cpp

Fixed 6 issues reported at Transifex.

l10n: Changed grammar and triple dots to ellipsis

---

src/gui/addcertificatedialog.ui
src/gui/folderwizardtargetpage.ui
src/gui/networksettings.ui
src/gui/owncloudsetupwizard.cpp

l10n: Changes to improve source strings

---

src/gui/CMakeLists.txt
test/nextcloud_add_test.cmake

Found this while trying to develop my NO_WEBENGINE patch (#1808)

Fix cmake inclusion of Qml and Quick

---

src/gui/activitylistmodel.cpp

- Fixes issue #1780
- Limits the visual overhead

ActivityListModel: Show full date and time as a Tooltip only

---

src/gui/tray/ActivityListModel.cpp
src/gui/tray/UserModel.cpp

Fix MSVC warnings: Missing return value, cast type

---

admin/linux/debian/drone-build.sh

This patch extends the Ubuntu build with support for the next release, Focal Fossa.

Added build for Focal

---

admin/linux/debian/debian.focal/changelog
admin/linux/debian/debian.focal/control

These files are needed to properly build for Focal.

Added Focal-specific files

---

src/gui/sharee.cpp
src/gui/sharee.h
src/gui/sharemanager.h

Please test :) @daita @tobiasKaminsky

Allow sharing to circles

---

test/CMakeLists.txt
test/nextcloud_add_test.cmake

Also don't build the test for the updater, fix missing updater library.
In addition to: #1847

Updater: Fix Tests build (failed with BUILD_UPDATER=NO)

---

src/csync/csync_exclude.cpp
src/gui/networksettings.cpp
src/gui/wizard/webview.cpp
src/libsync/syncengine.cpp

Fix container detaching

---

shell_integration/dolphin/ownclouddolphinactionplugin.cpp
shell_integration/dolphin/ownclouddolphinpluginhelper.h
src/gui/socketapi.cpp

[dolphin] Add icon to context menu

---

src/gui/systray.cpp
src/gui/systray.h

This simplifies the code a bit.

Use QQmlApplicationEngine

---

src/gui/tray/UserModel.h

Use override

---

shell_integration/dolphin/ownclouddolphinactionplugin.cpp

[dolphin] Don't manually create menuAction

---

ChangeLog

Update ChangeLog with 2.6 series.

---

cmake/modules/DefineCMakeDefaults.cmake
src/gui/clientproxy.cpp
src/libsync/clientsideencryption.cpp
src/libsync/propagateuploadencrypted.cpp

Debian has a list of known typos in their checking tools.

Fix typos.

---

shell_integration/windows/OCUtil/FileUtil.cpp

Fix leak in FileUtil::IsChildFile

---

src/libsync/logger.cpp

The message handler globally installed by the logger silently drop
messages if the logger is not logging. On top of it, it doesn't log
debug messages by default.
Anything not logged is currently silently discarded. This can come as a
surprise to a developer trying to contribute for the first time and
adding some debug message for some reason.
We're thus trying to strike a middle ground which is that debug messages
get a regular output if the logger isn't interested in them.

Don't silently kill debug messages

---

src/3rdparty/qtsingleapplication/qtlocalpeer.cpp
src/3rdparty/qtsingleapplication/qtsingleapplication.cpp
src/cmd/cmd.cpp
src/common/checksums.cpp
src/common/ownsql.cpp
src/common/syncjournaldb.cpp
src/common/utility.cpp
src/csync/csync.cpp
src/csync/csync_exclude.cpp
src/csync/csync_update.cpp
src/csync/csync_util.cpp
src/csync/std/c_utf8.cpp
src/csync/vio/csync_vio.cpp
src/csync/vio/csync_vio_local_unix.cpp
src/gui/folderwizard.cpp
src/gui/headerbanner.cpp
src/gui/wizard/webview.cpp
src/libsync/logger.cpp

Use nullptr when appropriate

---

test/testoauth.cpp

Remove useless virtual, better use override only

---

src/common/syncjournaldb.cpp
src/csync/csync.cpp
test/testutility.cpp

Don't use int literals for bools

---

src/gui/cloudproviders/cloudprovidermanager.cpp
src/gui/cloudproviders/cloudprovidermanager.h
src/gui/cloudproviders/cloudproviderwrapper.cpp
src/gui/cloudproviders/cloudproviderwrapper.h
src/gui/systray.cpp
src/gui/systray.h
test/stubfolderman.cpp

This PR fixes a few memory leaks.

Fix a few leaks

---

test/testsyncjournaldb.cpp

Use using instead of typedef

---

src/csync/csync_util.cpp
src/libsync/clientsideencryption.cpp

Remove redundant void argument list

---

src/csync/vio/csync_vio_local_unix.cpp
src/csync/vio/csync_vio_local_win.cpp

Use make_unique when appropriate

---

src/common/checksums.cpp
src/csync/csync_exclude.cpp
src/gui/accountstate.cpp
src/gui/creds/flow2auth.cpp
src/gui/creds/oauth.cpp
src/gui/folderstatusmodel.cpp
src/gui/folderwatcher.cpp
src/gui/folderwatcher_linux.cpp
src/gui/folderwizard.cpp
src/gui/logbrowser.cpp
src/gui/synclogdialog.cpp
src/gui/syncrunfilelog.cpp
src/gui/wizard/owncloudsetuppage.cpp
src/gui/wizard/owncloudwizardresultpage.cpp
src/libsync/account.cpp
src/libsync/bandwidthmanager.cpp
src/libsync/clientsideencryption.cpp
src/libsync/cookiejar.cpp
src/libsync/networkjobs.cpp
src/libsync/owncloudpropagator.cpp
src/libsync/progressdispatcher.cpp
src/libsync/theme.cpp

Use = default for trivial ctors and dtors

---

src/gui/navigationpanehelper.cpp
src/gui/openfilemanager.cpp
src/gui/socketapi.cpp
src/gui/syncrunfilelog.cpp
src/gui/wizard/owncloudwizardcommon.cpp
src/libsync/abstractnetworkjob.cpp
src/libsync/clientsideencryptionjobs.cpp
src/libsync/configfile.cpp
src/libsync/networkjobs.cpp
src/libsync/syncengine.cpp
test/testutility.cpp

This is especially nice for Windows paths.

Use raw string literals when appropriate

---

src/3rdparty/QProgressIndicator/QProgressIndicator.cpp
src/gui/folderstatusdelegate.cpp
src/gui/folderstatusmodel.cpp
src/gui/folderstatusview.cpp
src/gui/generalsettings.cpp
src/gui/networksettings.cpp
src/gui/wizard/slideshow.cpp
src/libsync/syncengine.cpp
src/libsync/syncfilestatustracker.cpp
src/libsync/theme.cpp
test/testsyncfilestatustracker.cpp

This way we avoid repeating the return type while it is already known.

Use the return braced init list pattern

---

.clang-tidy
src/csync/csync_util.h

Remove the last redundant void arg I left behind

---

.github/workflows/rebase.yaml

I think I got the if clause wrong regarding limiting the command only to
member users. Let's move this out of the way for now.

Try to fix the rebase action

---

.gitmodules

Cleanup: These old binaries are not used anymore.

Remove Submodule binary (old upstream binaries)

---

src/libsync/clientsideencryption.cpp

Due to usage of early-returns, combined with malloc/free,
several buffers that get allocated are leaked when an error
occurs.
Several functions had potential leaks:
- `encryptStringSymmetric` leaked `ctext`
- `EncryptionHelper::fileDecryption` leaked `out`
- `EncryptionHelper::fileEncryption` leaked `out`
Most of the functions had leaks of the cypher context.
This patch uses `QByteArray` as the handler for the dynamically
allocated buffers for openssl to operate on. This also removes
the need for conversions from malloc'd buffers to `QByteArray`
variables previously present in the code.
It also introduces a `CypherCtx` thin wrapper class to provide
a leak-free handling of `EVP_CIPHER_CTX`.

Fixing memory leaks in the encryption module

---

doc/nextcloudcmd.rst

Signed-off-by: shile <13051960278@163.com>

Add install instructions for nextcloudcmd

---

.clang-tidy
test/syncenginetestutils.h

Add some more make_unique calls

---

src/gui/application.cpp
src/libsync/theme.cpp

Also allow the `-v` option to work for gui too.

Improve command line version info and help display (gui & cmd)

---

src/gui/owncloudsetupwizard.cpp

BEtter to now just display clickable links etc.

Don't show a message box if the entered url returned an error

---

admin/linux/build-appimage.sh

[stable-2.6] AppImage: Upgrade to Qt 5.12.8

---

src/common/utility_unix.cpp

Change default autostart to hide gui

---

shell_integration/windows/OCContextMenu/OCContextMenuFactory.cpp
shell_integration/windows/OCContextMenu/OCContextMenuRegHandler.cpp
shell_integration/windows/OCOverlays/OCOverlayFactory.cpp
shell_integration/windows/OCOverlays/OCOverlayRegistrationHandler.cpp
src/common/utility_mac.cpp
src/csync/csync.cpp
src/csync/csync_update.cpp
src/csync/csync_util.cpp
src/csync/std/c_utf8.cpp
src/csync/vio/csync_vio.cpp
src/csync/vio/csync_vio_local_unix.cpp
src/csync/vio/csync_vio_local_win.cpp
src/gui/accountsettings.cpp
src/gui/folderman.cpp
src/gui/folderwatcher_linux.cpp
src/gui/owncloudgui.cpp
src/libsync/bandwidthmanager.cpp
test/csync/encoding_tests/check_encoding.cpp

[stable-2.6] Simplify nullptr comparisons where appropriate

---

resources.qrc
src/gui/tray/HeaderButton.qml
src/gui/tray/Window.qml

Deduplicate the Button code by moving it into a separate file.
Also use the same background code for the apps button since as far as I can tell it didn't behave any different

Create HeaderButton QML component

---

src/gui/tray/UserModel.cpp
src/gui/tray/UserModel.h
src/gui/tray/Window.qml

Convert imperative QML code to declarative code using property bindings

Use properties to get user details

---

src/gui/tray/UserLine.qml
src/gui/tray/Window.qml
theme/Style/Style.qml

This should address all the points raised in #2012

Fix systray gui design paper cuts

---

src/libsync/account.cpp

Discovered on Windows in conjunction with `PAC` scripts:
- Already configured accounts worked
- Fresh client account setup did not work
Reason:
- Proxy was reset over and over again in `Account::setCredentials`

Default system proxy not working with Account Wizard (fixes #2108)

---

src/gui/tray/UserModel.cpp

Commit 07bede8 (PR #1892) introduced a new helper method `currentUser()` that didn't check for `_users.count()` thus causing to throw an "`index out of range`" exception when no accounts are configured:
https://github.com/nextcloud/desktop/blob/07bede8a562a07555ab093458d596260ca8c9749/src/gui/tray/UserModel.cpp#L785-L788
This commit uses the opportunity to add more sanity checks to `UserModel`.
Not meant to blame @nicolasfella 😉😇
I always wanted to revisit `UserModel` to add some checks, now the crash actually forced me to do so 😁

Fix crash in UserModel::currentUser() and add more sanity checks

---

src/gui/accountsettings.cpp
src/gui/accountsettings.h
src/gui/folderstatusmodel.cpp
src/libsync/CMakeLists.txt
src/libsync/capabilities.cpp
src/libsync/capabilities.h
src/libsync/clientsideencryption.cpp
src/libsync/clientsideencryption.h
src/libsync/clientsideencryptionjobs.cpp
src/libsync/clientsideencryptionjobs.h
src/libsync/encryptfolderjob.cpp
src/libsync/encryptfolderjob.h
src/libsync/owncloudpropagator.cpp
src/libsync/owncloudpropagator.h
src/libsync/propagatedownload.cpp
src/libsync/propagatedownloadencrypted.cpp
src/libsync/propagatedownloadencrypted.h
src/libsync/propagateremotemkdir.cpp
src/libsync/propagateremotemkdir.h
src/libsync/propagateupload.cpp
src/libsync/propagateuploadencrypted.cpp
src/libsync/propagateuploadencrypted.h
src/libsync/propagatorjobs.cpp
src/libsync/propagatorjobs.h

Fix subfolder encryption scheme

---

src/libsync/encryptfolderjob.cpp

Delete a space character before the line breaks

Delete a space character

---

src/gui/accountsettings.cpp

Change the space character to a dot in the text string

Change the space character to a dot

---

src/csync/csync.cpp
src/csync/csync_util.cpp
src/csync/vio/csync_vio_local_unix.cpp
src/csync/vio/csync_vio_local_win.cpp
src/gui/application.cpp
src/gui/creds/webflowcredentials.cpp
src/gui/socketapi.cpp
src/gui/wizard/flow2authwidget.cpp
src/gui/wizard/webview.cpp
src/gui/wizard/webviewpage.cpp
src/libsync/configfile.cpp
src/libsync/configfile.h
src/libsync/logger.cpp
src/libsync/logger.h

Cherry pick some of the logging related commits from the ownCloud client. Also repairs our message pattern which got broken a while ago. Finally, this PR also allows more control of the logging facilities straight from the config file (reducing the need for the related command line flags quite a bit).
Fix #1756

Repair and improve logging

---

src/common/syncjournaldb.cpp
src/gui/folderstatusmodel.cpp
src/gui/folderwizard.cpp
src/gui/selectivesyncdialog.cpp
src/libsync/propagatedownload.cpp
src/libsync/propagatedownloadencrypted.cpp
src/libsync/propagateremotemkdir.cpp
src/libsync/propagateupload.cpp
src/libsync/propagateuploadencrypted.cpp
src/libsync/propagatorjobs.cpp

Fix e2ee folder sync connection

---

src/libsync/propagateupload.cpp
src/libsync/propagateupload.h

Fix e2ee upload lock starvation

---

src/libsync/clientsideencryptionjobs.cpp

Fix url decoding for folder encryption status

---

src/gui/folder.cpp
src/gui/folder.h
src/libsync/networkjobs.cpp
src/libsync/networkjobs.h

[stable 2.6] Asemmar/issue 2137

---

src/gui/sharelinkwidget.cpp

- Fix #2175:
- Shows the correct default permissions
- Shows the permissions the user set

Share link display the correct permissions for files and folders.

---

src/libsync/clientsideencryption.cpp
src/libsync/clientsideencryptionjobs.cpp
src/libsync/networkjobs.cpp
src/libsync/networkjobs.h
src/libsync/propagateremotedelete.cpp
src/libsync/propagateremotedelete.h
src/libsync/propagateremotedeleteencrypted.cpp
src/libsync/propagateremotedeleteencrypted.h
src/libsync/propagateremotemkdir.cpp
src/libsync/propagateupload.cpp
src/libsync/propagateuploadencrypted.cpp

This is necessary for compatibility with upcoming E2E app 1.6

Improve e2e token compatibility with upstream

---

src/libsync/capabilities.cpp

Now that we adjusted our protocol to follow the slightly updated server
API, let's make sure we don't try to talk to a server with an older API.

Update our E2E API requirement

---

.drone.yml
admin/linux/build-appimage.sh

This depends on nextcloud/docker-ci#234 to be in and tagged first.

Improve drone config

---

src/csync/csync_reconcile.cpp
src/libsync/propagateuploadng.cpp
src/libsync/propagateuploadv1.cpp
test/testchunkingng.cpp
test/testuploadreset.cpp

This drastically reduces the execution time of that test suite. Also this should hopefully make it less flaky (although admittedly it didn't fail in the CI for a little while now).

Cherry pick TestChunkingNG related improvements

---

.github/issue_template.md

Add --logdebug parameter to instructions in issue_template for Github.

---

src/libsync/bandwidthmanager.cpp
src/libsync/bandwidthmanager.h

[stable-3.0] Support client builds on VS2019 (QLinkedList is deprecated)

---

src/libsync/bandwidthmanager.cpp
src/libsync/bandwidthmanager.h

[stable-2.6] Support client builds on VS2019 (QLinkedList is deprecated)

---

src/gui/tray/ActivityListModel.cpp
src/gui/tray/Window.qml

Should fix #2349 and fix #2362
This also gives better tooltip:

Improve qml activity list

---

src/gui/tray/ActivityListModel.cpp
src/gui/tray/Window.qml

[stable-3.0] Improve qml activity list

---

src/gui/tray/UserLine.qml
src/gui/tray/UserModel.cpp
src/gui/tray/Window.qml

Fix menu popup in main dialog

---

.drone.yml

Try to enable the CI on stable branches as well

---

src/gui/iconjob.cpp

Signed-off-by: Dan Griffin <github.mk@xiragon.com>
This is a re-do of #1899 onto master branch. Fixes leaking connections with QNetworkAccessManager.

Free IconJob after use

---

src/gui/tray/UserLine.qml
src/gui/tray/Window.qml

Make use of [QML accessibility framework](https://doc.qt.io/qt-5/qml-qtquick-accessible.html)
This is just a first draft and I think the code changes summary make any intentions clear. 
@nextcloud/desktop please review and add missing pieces here, as necessary.
Also testing: I only gave a shot with macOS VoiceOver. This seemed worked fine for me, but I'm neither an a11y expert nor had much time to test rn.
See also issue: #2315

Tray accessibility

---

src/gui/tray/Window.qml

Removal of spaces from text strings to facilitate translation in Transefix.

l10n: Remove space from string text

---

src/gui/tray/Window.qml
theme.qrc
theme/reply.svg

Since I was working on #2486... didn't feel like much work to add an icon for Talk notifications.
I talked to @jancborchardt before doing it. He suggested the icon.

Add a clickable icon for Talk notifications.

---

src/common/utility.cpp
src/common/utility.h
src/gui/creds/flow2auth.cpp
src/libsync/accessmanager.cpp

Use friendly user agent during authentication

---

src/gui/folderstatusmodel.cpp
src/gui/owncloudgui.cpp
src/gui/selectivesyncdialog.h

This fixes some deprecation warnings

Don't use nullptr for QFlags

---

src/gui/socketapi.cpp

Triple dot to ellipsis

---

src/gui/owncloudgui.cpp
src/gui/owncloudgui.h
src/gui/systray.cpp
src/gui/systray.h

Bring back the "Pause sync" action in the systray context menu

---

src/gui/CMakeLists.txt

Enable the QML debugger on debug builds

---

src/common/utility.h

We just need QRect included here.

Fix Windows compilation broken after QML debugging fix.

---

src/csync/csync_exclude.cpp

Add last / to exclude list file path.

---

admin/linux/build-appimage.sh

fix AppImage build by using v0.10.0 for qtkeychain

fix AppImage build

---

resources.qrc
src/gui/CMakeLists.txt
src/gui/tray/ActivityActionButton.qml
src/gui/tray/ActivityData.h
src/gui/tray/ActivityListModel.cpp
src/gui/tray/ActivityListModel.h
src/gui/tray/NotificationHandler.cpp
src/gui/tray/UserModel.cpp
src/gui/tray/Window.qml

Implemented notification action buttons and context menu for confirm/dismiss and other actions.
Fix #2114
Fix #2624
Fix #1229

Notification action buttons and context menu

---

doc/troubleshooting.rst

Minor change: bypasses => bypass.

Update documentation on how to generate debug logs.

---

src/gui/sharee.cpp
src/gui/sharee.h
src/gui/sharemanager.h

Added sharing via email.

---

src/gui/ocsshareejob.cpp
src/gui/ocsshareejob.h
src/gui/sharee.cpp
src/gui/sharee.h
src/gui/shareusergroupwidget.cpp
src/gui/shareusergroupwidget.h
theme.qrc
theme/magnifying-glass.svg

Fixed slow sharee search in the share dialog

---

src/gui/tray/HeaderButton.qml
src/gui/tray/Window.qml

The icon color is set with APPLICATION_WIZARD_HEADER_TITLE_COLOR in the
theme.

Use the icon color property to color the icons in the tray window header.

---

src/gui/generalsettings.ui
src/gui/settingsdialog.cpp

UI improvements: Settings dialog

---

src/gui/accountsettings.cpp

Changed triple dot to ellipsis

---

admin/linux/debian/drone-build.sh

This patch adds support for the next Ubuntu release, Hirsute Hippo.

Add support for Hirsute

---

doc/introduction.rst

Remove indentation for bullet points, it looked like a quotation of something.

Small fix layout

---

src/libsync/owncloudpropagator.cpp
src/libsync/owncloudpropagator.h
src/libsync/propagateremotemkdir.cpp
src/libsync/propagateupload.cpp

E2EE fix upload parallelism issue.

---

src/libsync/discovery.cpp
src/libsync/discovery.h

Fix e2ee folder move issue

---

src/libsync/configfile.cpp

Default to colored systray on linux

---

src/libsync/syncengine.cpp

Removed blank before colon

---

src/libsync/discovery.cpp
src/libsync/owncloudpropagator.h
src/libsync/propagateremotedelete.cpp
src/libsync/propagateremotedelete.h
src/libsync/propagateremotemkdir.cpp
src/libsync/propagateremotemkdir.h
src/libsync/propagateremotemove.cpp
src/libsync/propagateupload.cpp
src/libsync/propagateupload.h
src/libsync/propagateuploadencrypted.cpp
src/libsync/propagateuploadencrypted.h

Fixed issue of root E2EE folder becoming non-encrypted after rename.
Signed-off-by: allexzander blackslayer4@gmail.com

E2ee fix rename root folder issue & Fix upload stuck issue due to incorrect Lock/Unlock sequence

---

src/gui/tray/UserModel.cpp
src/gui/tray/UserModel.h
src/libsync/account.cpp
src/libsync/account.h
src/libsync/capabilities.cpp
src/libsync/capabilities.h
src/libsync/pushnotifications.cpp
src/libsync/pushnotifications.h
test/pushnotificationstestutils.cpp
test/testcapabilities.cpp
test/testpushnotifications.cpp

Use push notifications for Tray activities/notifications fetch trigger.

---

.github/stale.yml

This is a second try to make stale bot working again :)

Stale: issue must have bug and must not have approved label

---

src/gui/application.cpp

Do not add debug build to startup programs.

---

src/gui/folderman.cpp

l10n: Change sync message

---

src/libsync/vfs/cfapi/cfapiwrapper.cpp

NOTE: This is just a part of the issue investigation. This PR will be reverted once the test build is done.

Temp fix for vfs failure.

---

src/gui/CMakeLists.txt

Don't deploy bearer plugin on MacOS

---

VERSION.cmake

Bump version to 3.2.0.

---

cmake/modules/DefineCMakeDefaults.cmake

Remove non-functional default CMAKE_BUILD_TYPE

---

shell_integration/dolphin/CMakeLists.txt

Remove some stuff that is not needed.

[dolphin] Clean up CMake code

---

src/gui/owncloudsetupwizard.cpp
src/gui/sharedialog.cpp
src/libsync/propagatedownload.cpp
src/libsync/propagatorjobs.cpp

Spelling unification in Nextcloud applications.

l10n: Unify spelling

---

src/gui/accountstate.cpp
src/libsync/account.cpp
src/libsync/account.h
src/libsync/pushnotifications.cpp
src/libsync/pushnotifications.h
test/pushnotificationstestutils.cpp
test/pushnotificationstestutils.h
test/testpushnotifications.cpp

Push notifications: Ping server

---

admin/win/msi/Nextcloud.wxs

Not going to merge until 3.2.0 is out.

Do not schedule reboot when installing MSI in silent mode unless 'SCHEDULE_REBOOT is set.

---

src/gui/CMakeLists.txt

Use imported target for Threads

---

cmake/modules/FindSQLite3.cmake
src/csync/CMakeLists.txt
test/CMakeLists.txt

CMake: Require sqlite3 only on Unix

---

src/gui/navigationpanehelper.cpp

Display VFS sync folder within the navigation panel on Windows.

---

doc/architecture.rst

Documentation: Correct option to enable virtual files on Linux/macOS

---

doc/architecture.rst

Documentation. Fix incorrect format usage for images and subheaders.

---

doc/architecture.rst

Describe the relation between E2EE and VFS. Also, add a section on E2EE as I could not find that anywhere...

E2EE and VFS

---

doc/architecture.rst
doc/building.rst
doc/installing.rst
doc/nextcloudcmd.rst
doc/options.rst

Documentation. Fix incorrect syntax warnings and incorrect indentation before the 'image' element.

---

src/gui/sharemanager.cpp
src/gui/sharemanager.h
src/gui/shareusergroupwidget.cpp
src/gui/shareusergroupwidget.h
src/gui/shareuserline.ui

Fixes #3104
I'm not proud of that code, but it does what it should. There is a big overlap between UserGroupShare and LinkShare but I'm unsure if and how they can share the code. Probably needs at some point a bit refactoring.

Add note to user and group share

---

src/gui/shareuserline.ui

l10n: Change to an ellipsis

---

doc/installing.rst

add info in the installation page about the supported server versions

---

src/gui/sharedialog.cpp
src/gui/sharedialog.h
src/gui/sharelinkwidget.cpp
src/gui/sharelinkwidget.h
src/gui/sharelinkwidget.ui
src/gui/sharemanager.cpp
src/gui/sharemanager.h
src/gui/shareusergroupwidget.cpp

This adds a bunch of small and medium improvements to fix https://github.com/nextcloud/desktop/issues/3088.

Improve public link sharing dialog

---

src/gui/addcertificatedialog.ui
src/gui/connectionvalidator.cpp
src/gui/owncloudsetupwizard.cpp
src/gui/shareuserline.ui
src/libsync/propagatorjobs.cpp

l10n: Delete space and capital letter

---

src/gui/ocssharejob.cpp
src/gui/ocssharejob.h
src/gui/sharemanager.cpp
src/gui/sharemanager.h
src/gui/shareusergroupwidget.cpp
src/gui/shareusergroupwidget.h
src/gui/shareuserline.ui
src/libsync/capabilities.cpp
src/libsync/capabilities.h

This will close https://github.com/nextcloud/desktop/issues/3108

Obey enforced password for share by email.

---

src/gui/shareuserline.ui

l10n: Translation of ellipse

---

src/gui/shareuserline.ui

Here another PR for the same code line as #3238 

No need to translate ellipsis

---

src/libsync/account.cpp
src/libsync/account.h
src/libsync/pushnotifications.cpp
src/libsync/pushnotifications.h
test/testpushnotifications.cpp

Push notifications: reconnect forever if possible

---

src/gui/updater/updater.cpp

in order to be able to suuport legacy OS, also sends the OS name and
version
will be used to detect Windows 8.1 and similar legacy versions

send OS name and version to auto updater to allow selective upgrades

---

src/3rdparty/sqlite3/sqlite3.h

upgrade SQLite3 to 3.35.5

---

src/gui/accountsettings.cpp
src/libsync/vfs/cfapi/vfs_cfapi.cpp

Warn user if using e2ee and vfs together

---

src/common/syncjournaldb.cpp
src/common/syncjournaldb.h
src/libsync/discovery.cpp
src/libsync/discovery.h
src/libsync/syncengine.cpp

This will help to detect inconsistencies of the sync journal.

Track time of last sync

---

test/testutility.cpp

Added unit tests for Utility::isPathWindowsDrivePartitionRoot.

---

cmake/modules/Warnings.cmake

Check compiler against CMAKE_CXX_COMPILER_ID

---

src/common/checksums.cpp
src/common/checksums.h
src/common/syncjournaldb.cpp
src/common/syncjournaldb.h
src/libsync/configfile.cpp
src/libsync/configfile.h
src/libsync/propagatedownload.cpp
src/libsync/propagatedownload.h
test/testchecksumvalidator.cpp

Added config parameter that allows to bypass checksum validation failure

---

admin/linux/debian/drone-build.sh

This patch enables building for the next Ubuntu release, Impish Indri.

Add building for Ubuntu Impish

---

src/libsync/discovery.cpp
test/syncenginetestutils.cpp
test/syncenginetestutils.h
test/testsyncmove.cpp

Add unit test for move custom remote root

---

src/libsync/clientsideencryption.cpp
src/libsync/clientsideencryption.h

download server public key and check user certificate against it

---

doc/conffile.rst
src/gui/application.cpp
src/gui/main.cpp
src/gui/owncloudgui.h
src/gui/systray.cpp
src/gui/systray.h
src/gui/tray/UserModel.h
src/gui/tray/Window.qml
src/libsync/configfile.cpp
src/libsync/configfile.h

Show main dialog as normal window if tray icons not available

---

shell_integration/windows/WinShellExt.wxs.in
shell_integration/windows/WinShellExtConstants.h.in

Windows. Nextcloud Overlay Identifiers. Set 16 spaces before each identifier's name.

---

src/gui/systray.cpp
src/gui/tray/Window.qml

Position main dialog on at tray icon if not a regular window

---

doc/architecture.rst
doc/nextcloudcmd.rst
doc/troubleshooting.rst
man/nextcloudcmd.1.rst
src/gui/owncloudsetupwizard.cpp
src/libsync/networkjobs.cpp
src/libsync/theme.cpp
src/libsync/theme.h
test/syncenginetestutils.h
test/testallfilesdeleted.cpp
test/testremotediscovery.cpp
test/testxmlparse.cpp

Use dav instead of webdav

---

src/gui/folderman.cpp

Stumbled upon this one while developing.

Remove unused pushNotifications variable

---

src/gui/systray.h
src/gui/tray/Window.qml

Fixes: https://github.com/nextcloud/desktop/issues/3564

Open main dialog gnome always

---

src/gui/tray/Window.qml

This will enable users to minimize the dialog.

Make main dialog normal window when displayed as regular window

---

src/gui/creds/flow2auth.cpp

l10n: Change to uppercase

---

src/common/checksums.cpp
src/common/checksums.h
src/libsync/configfile.cpp
src/libsync/configfile.h
src/libsync/propagatedownload.cpp
src/libsync/propagatedownload.h
test/testchecksumvalidator.cpp

Revert: Added config parameter that allows to bypass checksum validation failure.

---

doc/introduction.rst

Update improvements and news in the documentation

---

VERSION.cmake
doc/installing.rst

Update supported server versions

---

src/common/filesystembase.cpp
src/gui/authenticationdialog.cpp
src/gui/cloudproviders/cloudproviderwrapper.cpp
src/gui/creds/flow2auth.cpp
src/gui/creds/httpcredentialsgui.cpp
src/gui/folder.cpp
src/gui/folderman.cpp
src/gui/folderstatusmodel.cpp
src/gui/folderwizard.cpp
src/gui/ignorelisteditor.cpp
src/gui/ignorelisttablewidget.cpp
src/gui/owncloudgui.cpp
src/gui/owncloudsetupwizard.cpp
src/gui/shareusergroupwidget.cpp
src/gui/wizard/owncloudadvancedsetuppage.cpp
src/libsync/discovery.cpp
src/libsync/filesystem.cpp
src/libsync/logger.cpp
test/testremotediscovery.cpp

l10n: Replace apostrophe with double quotation

---

src/csync/vio/csync_vio_local_unix.cpp
src/gui/accountsettings.cpp
src/gui/application.cpp
src/gui/folder.cpp
src/gui/folderman.cpp
src/gui/socketapi.cpp
src/gui/tray/UserModel.cpp
src/gui/userstatus.cpp
src/libsync/clientsideencryption.cpp
src/libsync/propagatedownload.cpp
src/libsync/propagateremotemove.cpp
src/libsync/propagateupload.cpp
src/libsync/propagatorjobs.cpp
test/CMakeLists.txt
test/pushnotificationstestutils.cpp
test/pushnotificationstestutils.h
test/testhelper.cpp
test/testhelper.h
test/testsyncvirtualfiles.cpp
test/testsyncxattr.cpp

Don't ignore setPinState() results and fix some other warnings

---

admin/osx/post_install.sh.cmake
admin/osx/pre_install.sh.cmake

Closes #3679
Follow-up for #3404

Fix macOS app bundle name in packaging scripts

---

.drone.yml
admin/linux/build-appimage.sh
admin/osx/CMakeLists.txt
shell_integration/dolphin/CMakeLists.txt
shell_integration/libcloudproviders/CMakeLists.txt
src/CMakeLists.txt

Update to Qt 5.15

---

CMakeLists.txt

Color compile ouput when using Ninja build file generator

---

VERSION.cmake

according to https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

support server versions for one year after it is end of life

---

resources.qrc
src/gui/tray/ActivityItem.qml
src/gui/tray/AutoSizingMenu.qml
src/gui/tray/Window.qml

For the `AutoSizingMenu` I see no other way to make a Menu that adjusts to the biggest MenuItem. I think the cost of that menu is okay given that not many elements are in that menu.

Fix qml warnings

---

src/gui/owncloudsetupwizard.cpp

This is needed because of the changes in 02bb5db544cf89a10b1af3e7e06f373525dfe104

Close wizard if done

---

src/cmd/cmd.cpp
src/common/syncjournaldb.cpp
src/common/syncjournaldb.h
src/common/utility.cpp
src/common/utility.h
src/common/utility_unix.cpp
src/gui/folderstatusmodel.cpp
src/gui/openfilemanager.cpp
src/libsync/account.cpp
src/libsync/configfile.cpp
src/libsync/logger.cpp
src/libsync/propagatedownload.cpp
src/libsync/propagateuploadng.cpp
src/libsync/propagateuploadv1.cpp
src/libsync/syncengine.cpp
src/libsync/syncfilestatustracker.cpp
src/libsync/theme.cpp
test/syncenginetestutils.cpp
test/syncenginetestutils.h
test/testcookies.cpp
test/testfolderwatcher.cpp
test/testinotifywatcher.cpp
test/testutility.cpp

Fix most of the deprecation warnings

---

src/gui/updater/ocupdater.cpp

Prompt reboot when runing the auto update.

---

src/gui/UserStatusSelector.qml
src/gui/updater/ocupdater.cpp

l10n: Correct a typo and spelling unification

---

src/gui/userstatusselectormodel.cpp
src/gui/userstatusselectormodel.h
src/libsync/account.cpp

Clear user status in main dialog after clearing it in user status selector dialog

---

src/gui/sharelinkwidget.h
src/gui/sharemanager.cpp
src/gui/sharemanager.h

It should fix #3102.
(also fixed indentation/new lines related to this changes)

Display share note

---

src/gui/UserStatusSelector.qml

TextInput by default do not allow selecting text by mouse

---

src/gui/generalsettings.cpp
src/gui/updater/ocupdater.cpp
src/gui/updater/ocupdater.h

General Settings window. Allow opening the update URL via mouse.

---

src/gui/invalidfilenamedialog.cpp

Fixed grammar

---

doc/architecture.rst

Make virtual files feature documentation more understandable

---

src/libsync/syncengine.cpp
src/libsync/syncengine.h

Remove Temporary solution for file restoration issue due to set the data-fingerprint.

---

.drone.yml
admin/linux/build-appimage.sh

Use build-appimage.sh from Brander

---

resources.qrc
src/gui/CMakeLists.txt
src/gui/application.cpp
src/gui/fileactivitylistmodel.cpp
src/gui/fileactivitylistmodel.h
src/gui/folder.cpp
src/gui/folder.h
src/gui/main.cpp
src/gui/socketapi/socketapi.cpp
src/gui/socketapi/socketapi.h
src/gui/systray.h
src/gui/tray/ActivityItem.qml
src/gui/tray/ActivityList.qml
src/gui/tray/ActivityListModel.cpp
src/gui/tray/ActivityListModel.h
src/gui/tray/FileActivityDialog.qml
src/gui/tray/Window.qml

The version that tries to reuse as much code as possible from the current Qml and Model code in comparison to #3329.
Fixes #3206

Add file activity dialog

---

src/cmd/cmd.cpp
src/gui/creds/oauth.cpp
src/gui/notificationconfirmjob.cpp
src/gui/sharedialog.cpp
src/gui/syncrunfilelog.cpp
src/libsync/creds/credentialscommon.cpp
src/libsync/discovery.cpp
src/libsync/discoveryphase.h
src/libsync/logger.cpp
src/libsync/networkjobs.cpp
src/libsync/propagatedownload.cpp
src/libsync/syncengine.cpp
test/mockserver/httpserver.cpp
test/testutility.cpp

Replace deprecated QRegExp with QRegularExpression.

---

src/gui/sharelinkwidget.cpp
src/gui/sharemanager.cpp
src/gui/sharemanager.h
src/gui/shareusergroupwidget.cpp
src/gui/shareusergroupwidget.h
src/libsync/capabilities.cpp
src/libsync/capabilities.h

This will fix #3848 and, will probably fix #3944

Implement expiration date for federated shares

---

admin/linux/build-appimage.sh

Take branding for vfs plugins into account

---

admin/osx/make_universal.py

Ref: https://github.com/nextcloud/desktop/issues/2659

Add a script to create a universal app package

---

doc/installing.rst

we run on Windows 8.1+

---

src/gui/tray/usermodel.cpp
src/libsync/capabilities.cpp
src/libsync/capabilities.h

Check if the server has user status app enabled

---

src/gui/tray/HeaderButton.qml
src/gui/tray/UserLine.qml
src/gui/tray/Window.qml

This improves considerably the keyboard navigation in the SystemTray.
But this is still not as good as the golden standard that is recommended
by this article: https://www.sarasoueidan.com/blog/focus-indicators/

Fix focus indicator

---

src/libsync/discovery.cpp

Added more logs to 'postProcessLocalNew'.

---

src/common/utility.cpp
src/common/utility.h
src/common/utility_mac.cpp
src/common/utility_unix.cpp
src/common/utility_win.cpp
src/gui/accountsettings.cpp

Cleanup system bindings from Windows when removing a local sync folder

---

src/libsync/bulkpropagatorjob.cpp

l10n: Changed case of word

---

src/gui/accountsettings.cpp
src/gui/folder.cpp
src/gui/folder.h
src/gui/folderman.cpp
src/gui/socketapi/socketapi.cpp
src/libsync/vfs/cfapi/cfapiwrapper.cpp

Enforce VFS. Disable 'Make always available locally'.

---

src/gui/CMakeLists.txt

Fix CMake error in ECMAddAppIcon for mac

---

src/libsync/discoveryphase.cpp

Do not crash on findAndCancelDeletedJob

---

src/libsync/owncloudpropagator.cpp

l10n: Remove parenthesis

---

src/gui/accountstate.cpp
src/gui/accountstate.h
src/gui/application.cpp
src/gui/connectionvalidator.cpp

Bugfix/force re-login on SSL Handshake error

---

admin/win/msi/CMakeLists.txt
admin/win/msi/Nextcloud.wxs
admin/win/msi/RegistryCleanup.vbs
admin/win/msi/RegistryCleanupCustomAction.wxs
admin/win/msi/make-msi.bat.in

Windows. MSI. Unregister Nextcloud folders in SyncRootManager on uninstall.

---

test/syncenginetestutils.cpp

check modified time sent by upload jobs in automated tests

---

src/libsync/discoveryphase.cpp

l10n: Fixed grammar

---

src/gui/sharedialog.cpp
src/gui/sharedialog.h
src/gui/sharedialog.ui
src/gui/sharelinkwidget.cpp
src/gui/sharelinkwidget.h
src/gui/sharelinkwidget.ui
src/gui/shareusergroupwidget.cpp
src/gui/shareusergroupwidget.h
src/gui/shareusergroupwidget.ui
src/gui/shareuserline.ui

Add scroll area for share links.

---

src/gui/UserStatusSelector.qml
src/gui/tray/ActivityItem.qml
src/gui/tray/UserLine.qml
theme/Style/Style.qml

Main dialog use system font size

---

src/libsync/vfs/cfapi/cfapiwrapper.cpp
src/libsync/vfs/cfapi/cfapiwrapper.h
src/libsync/vfs/cfapi/vfs_cfapi.cpp

use proper API to dehydrate a placeholder file

---

CMakeLists.txt
NEXTCLOUD.cmake
config.h.in
src/gui/generalsettings.cpp
src/gui/generalsettings.h

This will fix https://github.com/nextcloud/desktop/issues/3636

Always build with updater. Use 'beta/stable' channel selector in 'General Settins' dialog with default 'stable'.

---

src/libsync/discovery.cpp
src/libsync/discoveryphase.h
src/libsync/propagateremotemove.cpp
src/libsync/propagateupload.cpp
test/testlocaldiscovery.cpp
test/testsyncvirtualfiles.cpp

ensure we emit a rename command for renamed files

---

src/libsync/bulkpropagatorjob.cpp

l10n: Change to lowercase

---

src/gui/systray.cpp

This small PR shortens and simplified the code in the systray currentScreen method

Simplify currentScreen in systray.cpp

---

CMakeLists.txt
admin/win/tools/CMakeLists.txt
shell_integration/dolphin/CMakeLists.txt

https://github.com/nextcloud/desktop/issues/3572

require cmake 3.16

---

src/gui/tray/usermodel.cpp

This PR should prevent crashing when checking for dehydrated virtual files for thumbnail purposes

Fix for VFS crashes due to mimetype checking for thumbnails

---

admin/linux/build-appimage.sh
src/gui/generalsettings.cpp
src/gui/generalsettings.h

ensure we only store update channel not localized in settings

---

src/gui/application.cpp
src/gui/systray.h
src/libsync/theme.cpp
src/libsync/theme.h

Darkmode. Fix crash on exit.

---

VERSION.cmake
src/gui/generalsettings.cpp
src/gui/updater/sparkleupdater_mac.mm

This PR fixes the sparkle autoupdater in the desktop client.

Fix sparkle implementation in the desktop client

---

cmake/modules/MacOSXBundleInfo.plist.in

This should let us verify updates coming from the client updater server correctly

Add new and correct sparkle update signature

---

doc/navigating.rst

Signed-off-by: Carl Csaposs <carl@csaposs.com>

docs: Replace "preceded" with "followed"

---

src/gui/wizard/webview.cpp

only add OCS-APIREQUEST header for 1st request of webflow v1

---

src/gui/accountstate.cpp
src/gui/accountstate.h
src/gui/tray/notificationhandler.cpp
src/gui/tray/notificationhandler.h
src/gui/userstatusselectormodel.cpp
src/libsync/account.cpp
src/libsync/account.h
src/libsync/networkjobs.cpp
src/libsync/networkjobs.h
src/libsync/ocsuserstatusconnector.cpp
src/libsync/userstatusconnector.h

Use proper online status for user ('dnd', 'online', 'invisible', etc.) to enable or disable desktop notifications.

---

src/gui/sharedialog.cpp
src/gui/sharedialog.ui
src/gui/sharelinkwidget.cpp
src/gui/sharelinkwidget.h
src/gui/shareusergroupwidget.cpp
src/gui/shareusergroupwidget.h

Fix visual borking in the share dialog

---

src/gui/invalidfilenamedialog.cpp
src/gui/tray/activitylistmodel.cpp

Change three dots to an ellipsis and add a space

---

src/gui/creds/webflowcredentialsdialog.cpp
src/gui/wizard/webview.cpp
src/gui/wizard/webviewpage.cpp

Stretch WebView to fit dialog's height.

---

src/gui/tray/usermodel.cpp

Display chat message inside the OS notification.

---

src/gui/tray/ActivityItem.qml

Fix 'TypeError: Cannot readproperty 'messageSent' of undefined'.

---

sync-exclude.lst

Ignore Office temp folders on Mac ('.sb-' in folder name).

---

src/gui/tray/CallNotificationDialog.qml

Ensure call notification stays on top of other windows

---

src/gui/main.cpp

force OpenGL via Angle and using warp direct3d software rasterizer

---

src/gui/EmojiPicker.qml

Add a placeholder message for the recents tab of the emoji picker

---

src/gui/systray.cpp
src/gui/systray.h
src/gui/tray/Window.qml

backport of https://github.com/nextcloud/desktop/pull/4687

[stable-3.5] Clean up systray methods, make more QML-friendly

---

src/gui/generalsettings.cpp

Ensure debug archive contents are readable by any user

---

admin/linux/debian/drone-build.sh

Support for Impish has ceased, so it is removed. Kinetic is the next Ubuntu release.

Remove Ubuntu Impish, add Kinetic

---

admin/win/msi/Nextcloud.wxs
src/gui/updater/ocupdater.cpp

The previous fix was not sufficient. We need to use /norestart to prevent PC from rebooting

Do not reboot PC when running an MSI via autoupdate.

---

.drone.yml
.github/workflows/sonarcloud.yml
admin/linux/build-appimage.sh
src/gui/creds/webflowcredentials.cpp
src/gui/sharelinkwidget.cpp
src/libsync/clientsideencryption.cpp

will get an upgraded openssl
will get an upgraded Qt

switch to using the main client CI image based on ubuntu 22.04

---

src/gui/tray/UserLine.qml
src/gui/tray/Window.qml

Fix account switching and hover issues with UserLine component

---

src/gui/owncloudgui.cpp

Fix fileactivitylistmodel QML registration

---

src/gui/tray/Window.qml

Ensure strings in main window QML are presented as plain text and not HTML

---

.tx/config

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

Update after tx migrate

---

src/gui/generalsettings.cpp

Button signals were not correctly hooked up for macOS
Fixes #5077

Fix macOS autoupdater settings

---

shell_integration/nautilus/syncstate.py

Fix compatibility with newer python3-nautilus

---

src/gui/cocoainitializer_mac.mm

Fix stable-3.6 compile on macOS

---

src/gui/tray/CustomButton.qml

Fix bad backport of CustomButton changes in Stable-3.6

---

src/gui/accountmanager.cpp
src/gui/accountmanager.h
src/gui/accountsettings.cpp
src/gui/accountsettings.h
src/gui/mnemonicdialog.ui
src/libsync/account.cpp
src/libsync/account.h
src/libsync/clientsideencryption.cpp
src/libsync/clientsideencryption.h

backport of https://github.com/nextcloud/desktop/pull/5067 and https://github.com/nextcloud/desktop/pull/5148

Backport/5067/stable 3.6

---

src/gui/tray/usermodel.cpp
src/gui/tray/usermodel.h

backport of https://github.com/nextcloud/desktop/pull/5092

Backport/5092/stable 3.6

---

src/common/syncjournaldb.cpp
src/common/syncjournalfilerecord.h
src/gui/folderman.cpp
src/gui/folderman.h
src/gui/shellextensionsserver.cpp
src/gui/shellextensionsserver.h
src/gui/socketapi/socketapi.cpp
src/gui/socketapi/socketapi.h
src/libsync/account.cpp
src/libsync/account.h
src/libsync/bulkpropagatorjob.cpp
src/libsync/discovery.cpp
src/libsync/discoveryphase.cpp
src/libsync/discoveryphase.h
src/libsync/propagateremotemkdir.cpp
src/libsync/syncfileitem.cpp
src/libsync/syncfileitem.h
test/testfolderman.cpp

Implement context menu entry "Leave this share"

---

src/libsync/discovery.cpp
src/libsync/propagateremotemove.cpp
src/libsync/propagatorjobs.cpp
src/libsync/syncengine.cpp
test/syncenginetestutils.cpp
test/syncenginetestutils.h
test/testsyncengine.cpp

check that we update local file mtime on changes from server

---

src/gui/accountsettings.cpp
src/gui/folderman.cpp
src/gui/folderman.h

This is needed to successfully backport another PR

Add forcefoldersync method to folder manager

---

src/gui/folder.cpp
src/libsync/syncengine.h

Fix CI errors for Edit Locally.

---

.github/workflows/qml-label-check.yml
resources.qrc
src/gui/BasicComboBox.qml
src/gui/EmojiPicker.qml
src/gui/ErrorBox.qml
src/gui/PredefinedStatusButton.qml
src/gui/UserStatusSelector.qml
src/gui/UserStatusSelectorButton.qml
src/gui/tray/ActivityItemContent.qml
src/gui/tray/CallNotificationDialog.qml
src/gui/tray/CustomButton.qml
src/gui/tray/CustomTextButton.qml
src/gui/tray/EditFileLocallyLoadingDialog.qml
src/gui/tray/EnforcedPlainTextLabel.qml
src/gui/tray/NCToolTip.qml
src/gui/tray/SyncStatus.qml
src/gui/tray/UnifiedSearchResultFetchMoreTrigger.qml
src/gui/tray/UnifiedSearchResultItem.qml
src/gui/tray/UnifiedSearchResultNothingFound.qml
src/gui/tray/UnifiedSearchResultSectionItem.qml
src/gui/tray/UserLine.qml
src/gui/tray/Window.qml

[stable-3.6] Make use of plain text-enforcing qml labels

---

src/gui/conflictdialog.cpp
src/gui/creds/webflowcredentialsdialog.cpp
src/gui/invalidfilenamedialog.cpp
src/gui/invalidfilenamedialog.ui
src/gui/wizard/owncloudadvancedsetuppage.cpp
src/gui/wizard/owncloudadvancedsetuppage.ui

Format some QLabels as plain text

---

src/libsync/owncloudpropagator.cpp

do not use bulk upload for e2ee files

---

src/gui/socketapi/socketapi.cpp
src/gui/socketapi/socketapi.h
src/libsync/clientsideencryptionjobs.cpp
src/libsync/clientsideencryptionjobs.h
src/libsync/encryptfolderjob.cpp
src/libsync/encryptfolderjob.h

Add an "Encrypt" menu entry in file browser context menu for folders

---

src/gui/sharemanager.cpp
src/gui/sharemanager.h
src/gui/shareusergroupwidget.cpp

do not assert when sharing to a circle

---

src/gui/editlocallyjob.cpp

Edit locally. Do not lock if locking is disabled on the server.

---

src/common/preparedsqlquerymanager.h
src/common/syncjournaldb.cpp
src/common/syncjournaldb.h
src/libsync/abstractpropagateremotedeleteencrypted.cpp
src/libsync/clientsideencryption.cpp
src/libsync/clientsideencryption.h
src/libsync/clientsideencryptionjobs.cpp
src/libsync/clientsideencryptionjobs.h
src/libsync/encryptfolderjob.cpp
src/libsync/propagateuploadencrypted.cpp
src/libsync/syncengine.cpp

Always unlock E2EE folders, even when network failure or crash.

---

src/gui/caseclashfilenamedialog.ui

l10n: Correct word

---

src/gui/filedetails/sharemodel.cpp
src/gui/filedetails/sharemodel.h

Prevent ShareModel crash from accessing bad pointers

---

.github/workflows/check-translations.yml

If needed, we can also add other language checks.
This commit has a faulty German string, so that we see that it fails.
TODO
Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

check German translation for wrong wording

---

admin/linux/debian/drone-build.sh

Add Ubuntu Lunar

---

src/libsync/clientsideencryption.cpp

E2EE cut extra zeroes from derypted byte array.

---

src/libsync/clientsideencryption.cpp

sort encrypted files by their id to compute checksum

---

src/gui/folder.cpp
src/gui/folder.h
src/gui/folderwatcher.cpp
src/gui/folderwatcher.h

Unlock Office files when they are closed

---

src/gui/tray/SyncStatus.qml

Fix setting [undefined] to QFont in 'Sync now' button

---

src/gui/accountmanager.cpp

Attempt sign in when an account state is added in AccountManager

---

src/gui/tray/ActivityItem.qml
src/gui/tray/ActivityItemContent.qml
src/gui/tray/ActivityList.qml
theme/Style/Style.qml

align activity text with "Sync now" text

---

src/gui/filedetails/ShareDetailsPage.qml
src/gui/tray/UnifiedSearchInputContainer.qml

Fix dark mode switch issues in tray controls manually overriding palette colours

---

theme/colored/Nextcloud-macOS-icon.svg

This reverts commit 04d16b7824e633b66fbd9fbbed98c615e14e8c2d as unfortunately this breaks the app icon

Fix macOS icon

---

admin/linux/debian/drone-build.sh

Debian Bookworm has been recently released and this commit adds it to the automatic build targets.

Build for Debian Bookworm

---

admin/win/docker/Dockerfile

update docker container based on opensuse leap to cross build to windows

---

craftmaster.ini
doc/massdeploymentcommandline.rst

Fix residual typos found by codespell

---

src/gui/tray/activitylistmodel.cpp
src/gui/tray/activitylistmodel.h
src/gui/tray/usermodel.cpp
src/gui/tray/usermodel.h

Remove seen Talk notificatios from Tray window.

---

README.md

add link in readme to nextcloud-releases correct page with binaries

---

.drone.yml

chore(CI): Sign .drone.yml file

---

.drone.yml

[stable-3.9] chore(CI): Sign .drone.yml file

---

src/gui/filedetails/sharemodel.cpp

Fix build of sharemodel.cpp on MSVC

---

.drone.yml
.github/workflows/sonarcloud.yml

update main CI image to get newer Qt, Java and other dependencies

---

src/gui/accountsettings.cpp

Add warning prior to folder encryption, prevent unknowing users from creating unrecoverable encrypted folders

---

src/gui/folder.cpp
src/gui/folder.h
src/gui/folderwatcher.cpp
src/gui/folderwatcher.h

Update VFS placeholder in case of lastAccessTime changed for Word documents and .msg files

---

src/libsync/lockfilejobs.cpp

Remove locketimeout condition.

---

src/gui/ConflictDelegate.qml
src/gui/ResolveConflictsDialog.qml
src/gui/syncconflictsmodel.cpp

Display correct conflict part in multiple conflicts resolution dialog.

---

doc/visualtour.rst
shell_integration/MacOSX/NextcloudIntegration/NCDesktopClientSocketKit/LocalSocketClient.m
src/common/pinstate.h
src/gui/accountstate.cpp
src/gui/folderman.cpp
src/gui/folderstatusmodel.cpp
src/gui/folderwatcher.h
src/gui/selectivesyncdialog.cpp
src/libsync/account.cpp
src/libsync/creds/httpcredentials.h
src/libsync/owncloudpropagator.h
test/csync/std_tests/check_std_c_jhash.c
test/testsortedactivitylistmodel.cpp
test/testsynccfapi.cpp
test/testsyncengine.cpp
test/testunifiedsearchlistmodel.cpp

Fix new typos found by codespell

---

.github/workflows/macos-build-and-test.yml
craftmaster.ini
src/gui/folderwatcher_mac.cpp
src/gui/folderwatcher_mac.h

Add macOS CI (and fixes for newly-found FolderWatcher bugs)

---

src/common/utility.cpp
src/common/utility.h
src/libsync/propagateupload.h
src/libsync/propagateuploadng.cpp

Fix chunk v2 destination header

---

doc/installing.rst

we require version 12.0+ for macOS

---

src/common/checksumcalculator.cpp
src/common/checksumcalculator.h
src/common/checksums.cpp
src/common/checksums.h
test/testchecksumvalidator.cpp

Fix crash. Remove unnecessary dependency injection causing crash.

---

src/gui/updater/ocupdater.cpp

Fix for oc->nc

---

src/gui/application.cpp

Bugfix/missing translations in AppImage

---

shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj

full git path

---

shell_integration/windows/NCContextMenu/NCClientInterface.cpp

wait longer to get the contextual menu entries: may be necessary

---

src/gui/accountsettings.cpp
src/gui/connectionvalidator.cpp
src/gui/connectionvalidator.h
src/libsync/abstractnetworkjob.cpp

Backport of PR https://github.com/nextcloud/desktop/pull/6423

[stable-3.12] Improve how the UI shows that the client is actually syncing

---

src/gui/folder.cpp
src/libsync/discovery.cpp
src/libsync/lockfilejobs.cpp

add extra logs to investigate lock type issues

---

src/gui/folder.cpp
src/gui/folder.h

Fix crash when deleting a local sync folder during sync.

---

src/libsync/clientstatusreportingcommon.cpp
src/libsync/clientstatusreportingcommon.h
src/libsync/clientstatusreportingnetwork.cpp
src/libsync/discovery.cpp
src/libsync/owncloudpropagator.cpp
src/libsync/propagatedownload.cpp
src/libsync/syncengine.cpp
test/testclientstatusreporting.cpp

Client Status Reporting. Only report statuses listed on the server.

---

src/common/utility.cpp
src/common/utility.h
src/gui/accountsettings.cpp
src/gui/folder.cpp
src/gui/folder.h
src/gui/socketapi/socketapi.cpp
src/libsync/basepropagateremotedeleteencrypted.cpp
src/libsync/encryptfolderjob.cpp
src/libsync/encryptfolderjob.h
src/libsync/owncloudpropagator.cpp
src/libsync/owncloudpropagator.h
src/libsync/propagatedownloadencrypted.cpp
src/libsync/propagateremotemkdir.cpp
src/libsync/propagateuploadencrypted.cpp
src/libsync/updatee2eefoldermetadatajob.cpp
src/libsync/updatee2eefolderusersmetadatajob.cpp
src/libsync/vfs/cfapi/hydrationjob.cpp
test/testutility.cpp

Bugfix/e2ee v2 non-root sync

---

src/libsync/discovery.cpp

Bugfix. E2ee misleading log fix.

---

src/gui/tray/activitylistmodel.cpp
src/gui/tray/usermodel.cpp
src/gui/tray/usermodel.h

Fix for https://github.com/nextcloud/desktop/issues/6474

Bugfix. Remove seen call notifications from the list.

---

.drone.yml
admin/test/wait_for_server.sh

improving end-to-end tests

---

src/libsync/discovery.cpp
src/libsync/owncloudpropagator.cpp
src/libsync/owncloudpropagator.h
src/libsync/propagatorjobs.cpp
src/libsync/syncfileitem.h
test/syncenginetestutils.cpp
test/syncenginetestutils.h
test/testsyncengine.cpp

[stable-3.12] Bugfix/folder conflict disappear

---

src/common/vfs.h
src/csync/csync.h
src/gui/folder.cpp
src/libsync/discovery.cpp
src/libsync/owncloudpropagator.cpp
src/libsync/owncloudpropagator.h
src/libsync/progressdispatcher.cpp
src/libsync/vfs/cfapi/cfapiwrapper.cpp
src/libsync/vfs/cfapi/cfapiwrapper.h
src/libsync/vfs/cfapi/vfs_cfapi.cpp
src/libsync/vfs/cfapi/vfs_cfapi.h
src/libsync/vfs/suffix/vfs_suffix.h
src/libsync/vfs/xattr/vfs_xattr.h

if a virtual file change but bothing changed: set it as in sync

---

src/libsync/syncengine.cpp

Bugfix. Files lock. Fix incorrect readonly state.

---

src/gui/ConflictItemFileInfo.qml
src/gui/ResolveConflictsDialog.qml

Bugfix. Conflict dialog for multiple files. Fix checkbox border colors for dark mode on Windows.

---

src/gui/ConflictItemFileInfo.qml
src/gui/ResolveConflictsDialog.qml

[stable-3.12] Bugfix. Conflict dialog for multiple files. Fix checkbox border colors for dark mode on Windows.

---

src/gui/generalsettings.cpp

Backport/6598/stable 3.12

---

src/libsync/updatee2eefolderusersmetadatajob.cpp

chore(i18n): Improve grammar

---

admin/osx/post_install.sh.cmake

Do not open client on install as this breaks MDM deployments

---

doc/installing.rst

update doc with install requirements fom Qt6 supported platforms

---

.github/workflows/linux-appimage.yml
src/common/syncjournaldb.cpp

produce Appimage packages from github actions

---

admin/linux/build-appimage.sh

stable-3.13: Backport #6714

---

src/libsync/CMakeLists.txt
src/libsync/theme.cpp

In order to be able to compile it in Deepin v23 (Qt version  6.6.1, cmake version 3.28.3)

fix build failed

---

test/testsyncmove.cpp

[stable-3.12] Ci/test is mount root property

---

src/libsync/propagatedownload.cpp
src/libsync/vfs/cfapi/cfapiwrapper.cpp

- Print desktop client process id and the process id triggering the hydration.

Add cfapi debug logs

---

admin/linux/debian/drone-build.sh

This patch removes building for Ubuntu Mantic and adds Oracular.

Remove Ubuntu Mantic, add Oracular

---

shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension+ClientInterface.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension+Thumbnailing.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Info.plist
shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj

Adapt to critical changes in run up to 1.0

Upgrade to NextcloudFileProviderKit stable-1.0

---

shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension.swift

Remove ncAccount usages removed in NCFPK API

---

src/gui/editlocallyjob.cpp
src/gui/macOS/fileprovidereditlocallyjob.cpp

chore(i18n): Changed grammar

---

src/gui/tray/usermodel.cpp

Make multiple notifications text translatable

---

src/gui/tray/usermodel.cpp

Backport of PR https://github.com/nextcloud/desktop/pull/6991

[stable-3.12] Make multiple notifications text translatable

---

src/gui/main.cpp

will make all QWidget based user interface look more native

on windows use QWidget native platform style

---

src/gui/accountsettings.ui

remove the frame around the sync folders settings area

---

src/gui/ignorelisttablewidget.cpp
sync-exclude.lst
test/testexcludedfiles.cpp

those path may be in use on Windows and are legitimate
related to https://github.com/nextcloud/desktop/issues/1216 and https://github.com/nextcloud/desktop/pull/1231

do not ignore paths containing 2 "#" characters

---

src/libsync/discovery.cpp
src/libsync/propagatorjobs.cpp

Fix building of client on macOS 10.13 and 10.14

---

src/gui/owncloudgui.cpp

gui: add some context for translators

---

src/gui/filedetails/FileDetailsPage.qml
src/gui/filedetails/ShareDelegate.qml
src/gui/filedetails/ShareDetailsPage.qml
src/gui/tray/ActivityItemContent.qml
theme/Style/Style.qml

Fix alignment and size of buttons.

---

src/libsync/theme.cpp

Tries to clean double quotes and output JSON parse error.

Validate input of APPLICATION_SERVER_URL.

---

.github/ISSUE_TEMPLATE/BUG_REPORT.yml
.github/ISSUE_TEMPLATE/feature.md

docs: Update template to match org-templates

---

src/csync/csync.h
src/gui/application.cpp
src/gui/logbrowser.cpp
src/gui/owncloudgui.cpp
src/libsync/discovery.cpp
src/libsync/logger.cpp
src/libsync/logger.h
src/libsync/propagateremotedelete.cpp
src/libsync/propagatorjobs.cpp
src/libsync/syncfileitem.h
src/libsync/syncfilestatustracker.cpp

will log all deletions with the result of the discovery by the sync enginre
should enable analyze even long time after such a delete occured

create a permanent log of delete actions

---

src/gui/folder.cpp

message should say many not all: would be triggered by 200 files

---

src/gui/folder.cpp

Backport of https://github.com/nextcloud/desktop/pull/7251

[stable-3.12] message should say many not all: would be triggered by 200 files

---

.github/workflows/macos-build-and-test.yml

try to increase timeout of github actions for macOS

---

test/testsyncengine.cpp

related to https://github.com/nextcloud/desktop/pull/7282

test syncing of read-only .lnk windows shorcuts

---

src/libsync/syncengine.cpp

should hopefully allows to understand when local file system discovery is done or omitted

better logs to understand when a folder is locally discovered

---

src/gui/connectionvalidator.cpp

remove ownCloud wording in logging
Signed-off-by: Rello <Rello@users.noreply.github.com>

remove ownCloud wording in logging

---

shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension+ClientInterface.swift

Fix Swift 6-related CI errors with macOS VFS module

---

src/gui/macOS/ui/FileProviderStorageInfo.qml

Make sure storage headers do not collide with each other in macOS VFS settings

---

src/gui/accountstate.cpp

properly detect need to sign terms of service state

---

cmake/modules/MacOSXBundleInfo.plist.in

Update copyright year in macOS info.plist template

---

admin/osx/mac-crafter/Sources/Utils/Codesign.swift

Also escape codesign call with saving entitlements

---

admin/osx/mac-crafter/Sources/Utils/Codesign.swift

Do not treat bundles as executables in codesign check

---

admin/osx/mac-crafter/Sources/Utils/Codesign.swift

Only sign main executable at end (mac-crafter)

---

src/libsync/bulkpropagatorjob.cpp
src/libsync/propagateupload.cpp
src/libsync/vfs/cfapi/vfs_cfapi.cpp
test/syncenginetestutils.cpp
test/syncenginetestutils.h
test/testlocaldiscovery.cpp
test/testsyncconflictsmodel.cpp
test/testsyncengine.cpp

fix regressions in automated tests for bulk upload

---

src/gui/tray/MainWindow.qml

Fixes this bug:
Should also fix bugs with a transparent window on Windows 11

gui/tray: Fix tray window corners

---

src/libsync/propagatorjobs.cpp

chore(i18n): Aligned error messages

---

src/libsync/clientsideencryption.cpp

use modern non deprecated hash algorithm and parameters

---

VERSION.cmake

remove NC17 support

---

README.md

Name changed, see https://nextcloud.com/team/ to confirm.
Signed-off-by: sol8712 <sol87@protonmail.com>

url update in readme

---

.drone.yml
.github/workflows/documentation.yml

add a simple github action workflow to build test the documentation

---

admin/osx/mac-crafter/Sources/Utils/Codesign.swift
admin/osx/mac-crafter/Sources/main.swift
src/gui/updater/sparkleupdater_mac.mm

Requires https://github.com/nextcloud/client_updater_server/pull/176

updater: Upgrade to Sparkle 2

---

src/gui/legalnotice.cpp

update legal notice copyright years for Nextcloud

---

VERSION.cmake
craftmaster.ini

required for https://github.com/nextcloud-gmbh/brander/pull/903

Make Brander QT selection dynamic

---

src/libsync/clientsideencryption.cpp

follow up on typo in https://github.com/nextcloud/desktop/pull/7780

fix wrong if condition

---

src/libsync/theme.cpp

link to new documentation
https://docs.nextcloud.com/#desktop

Link to new documentation

---

.github/ISSUE_TEMPLATE/BUG_REPORT.yml

https://docs.nextcloud.com/#desktop

Update doc link in issue template

---

src/libsync/clientsideencryption.cpp

chore(i18n): Remove blank

---

src/gui/folderman.cpp
test/testfolderman.cpp

10 seconds for try 3 and 4
30 seconds for try 5 and 6
60 seconds for more

prevent infinite sync loop: delay retry after many errors

---

src/libsync/basepropagateremotedeleteencrypted.cpp
src/libsync/deletejob.cpp
src/libsync/deletejob.h
src/libsync/propagateremotedelete.cpp
src/libsync/propagateremotedeleteencryptedrootfolder.cpp
src/libsync/propagateremotemkdir.cpp
src/libsync/propagateupload.cpp
src/libsync/propagateuploadng.cpp
src/libsync/syncengine.cpp

when deleting a remote locked file, provide needed lock headers

---

src/gui/wizard/owncloudwizard.cpp

Fix build when BUILD_WEBENGINE=OFF

Fix build when BUILD_WEBENGINE=OFF

---

src/gui/ignorelisttablewidget.cpp
src/gui/ignorelisttablewidget.h

Modernise ignorelisttablewidget code

---

src/gui/tray/asyncimageresponse.cpp

gui: Remove now unneeded jpeg-related workarounds for macOS

---

src/gui/macOS/fileproviderdomainmanager_mac.mm
src/gui/macOS/fileproviderdomainsyncstatus_mac.mm
src/gui/macOS/fileprovidereditlocallyjob_mac.mm
src/gui/macOS/fileprovideritemmetadata_mac.mm
src/gui/macOS/fileprovidermaterialiseditemsmodel_mac.mm
src/gui/macOS/fileprovidersettingscontroller_mac.mm
src/gui/macOS/fileproviderutils.h
src/gui/macOS/fileproviderxpc_mac.mm
src/gui/macOS/fileproviderxpc_mac_utils.h
src/gui/macOS/fileproviderxpc_mac_utils.mm
src/gui/updater/sparkleupdater_mac.mm

gui/macOS: Fix memory issues in Objective-C++ code for FileProvider support

---

src/gui/macOS/fileprovidermaterialiseditemsmodel.cpp

gui/macOS: Sort materialised files by size

---

admin/osx/mac-crafter/README.md

feat(mac-crafter): Improve readme

---

test/testsyncengine.cpp

remove bogus check that tried to check for existing case clash conflict

---

src/common/filesystembase.cpp

stop using QFile api to delete a single local file

---

src/gui/folder.cpp
src/gui/folder.h
src/libsync/discovery.cpp
src/libsync/filesystem.cpp
src/libsync/filesystem.h
src/libsync/syncengine.cpp
src/libsync/syncengine.h
test/testpermissions.cpp

simplify deletions of invalid read-only items: do not interrupt sync

---

admin/win/msi/CMakeLists.txt
admin/win/msi/EnsureACL.js
admin/win/msi/Nextcloud.wxs

fix(msi): allow custom installation directory

---

src/common/filesystembase.cpp
src/common/filesystembase.h
src/libsync/owncloudpropagator.cpp

use platform specific API on Windows to set a file (not a folder) be read-write or read-only
should make it more reliable

fix(filesystem): ensure we set a file read-only or read-write on Windows

---

src/gui/tray/CurrentAccountHeaderButton.qml
src/gui/tray/UserLine.qml
theme/Style/Style.qml

- Before:
- After:
- Linux:
- MacOS:
- Windows:

fix(tray): align user status and server url in all platforms.

---

shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Sharing/ShareViewController.xib
src/gui/sharee.cpp

gui: rename Circle=>Team

---

shell_integration/MacOSX/CMakeLists.txt
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension+ClientInterface.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension+Thumbnailing.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Services/FPUIExtensionServiceSource.swift
shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj

feat(FileProvider): Adopt NextcloudFileProviderKit 2.1

---

src/libsync/discoveryphase.cpp
test/testsyncmove.cpp

fix(rename): avoid failing hard when rename is rejected by server

---

src/libsync/bulkpropagatorjob.cpp

fixes https://github.com/nextcloud/desktop/issues/4047

fix(UI): updater filename-space error message

---

src/gui/accountmanager.cpp
src/libsync/configfile.cpp
src/libsync/configfile.h

fix(migration): migrate general network settings.

---

src/gui/cloudproviders/cloudproviderwrapper.cpp
src/gui/cloudproviders/cloudproviderwrapper.h

duplicate of https://github.com/nextcloud/desktop/pull/4887
fixing the review comments
contribution from @coreyberla

cloudproviders elide text for recent files activity submenu

---

shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension+ClientInterface.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderSocketLineProcessor.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Services/ClientCommunicationProtocol.h
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Services/ClientCommunicationService.swift
src/csync/csync_exclude.cpp
src/csync/csync_exclude.h
src/gui/ignorelisttablewidget.cpp
src/gui/macOS/fileprovidersocketcontroller.cpp
src/gui/macOS/fileprovidersocketcontroller.h
src/gui/macOS/fileproviderxpc.h
src/gui/macOS/fileproviderxpc_mac.mm

feat(gui/macOS): Integrate client ignore list with File Provider Extension

---

admin/linux/build-appimage.sh

fix(AppImage): bundle client translations

---

src/gui/generalsettings.cpp
src/gui/generalsettings.h
src/gui/generalsettings.ui
src/gui/updater/ocupdater.cpp

feat(generalsettings): add option to restore default update channel.

---

src/libsync/vfs/cfapi/cfapiwrapper.cpp

fix(warning): avoid compilation warning by specifying type

---

shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension.swift
shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj

fix(shell_integration/macOS/FileProviderExt): Adapt to further changes in NCFPK 3.0

---

.github/workflows/windows-build-and-test.yml
src/common/filesystembase.cpp

fix(logs): less verbose logs

---

AGENTS.md
REUSE.toml

feat(AI) Create AGENTS.md for AI instructions

---

src/gui/accountsettings.cpp
src/gui/macOS/ui/FileProviderSettings.qml
translations/client_en.ts

Fix folder list background and restructure VFS settings - test branch only

Fix folder list background and restructure VFS settings - test branch only

---

src/gui/macOS/ui/FileProviderSettings.qml
src/gui/macOS/ui/FileProviderSyncStatus.qml

fix(mac): align file provider settings - test branch only

---

AGENTS.md

Agents should not touch /translations

Agent instructions on translations

---

shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension+ClientInterface.swift

fix(shell_integration/macOS/FileProviderExt): Adapt to latest Remote Change Observer changes in NCFPK 3.0

---

src/gui/folderwizard.cpp
src/gui/folderwizardtargetpage.ui

fix(folderwizard): change message tone from error to information.

---

src/gui/updater/sparkleupdater_mac.mm

fixes https://github.com/nextcloud/desktop/issues/8029

fix(startup) respect update checker during startup in macOS

---

src/libsync/discovery.cpp
test/testpermissions.cpp

we do not want to remote discover a folder just because the permissions are modified but not the etag
for any valid case, etag must change

fix: do not recurse inside a remote folder when etag did not change

---

admin/osx/mac-crafter/Sources/Commands/Build.swift
admin/osx/mac-crafter/Sources/Utils/Stopwatch.swift

In context of #8498, what is to be improved needs to be measured first.

feat(mac-crafter): Added time measurement of build phases to improve on.

---

src/common/syncjournaldb.cpp

fix(db): optimize SQL qeury for updating encryption status

---

src/gui/macOS/fileproviderdomainmanager_mac.mm

Just a few but important additions to make log messages about the macOS file providers more informative.

Extended logged information about file provider domains.

---

src/common/syncjournaldb.cpp
src/common/syncjournaldb.h
src/libsync/discovery.cpp
test/testsyncjournaldb.cpp

Close https://github.com/nextcloud/desktop/issues/8555

fix(quota): return unlimited free space for type changes.

---

src/libsync/vfs/cfapi/cfapiwrapper.cpp

The `hydrationRequestReady` signal could be emitted before it was connected to the event loop, resulting in the data transfer never being started.

fix(cfapi): set up connections before requesting hydration

---

src/libsync/abstractnetworkjob.cpp

Reported at Transifex
Replacement for #8558

fix(i18n): Fix grammar

---

src/gui/UserStatusSelector.qml

fix: refine user status selector layout

---

src/common/vfs.h
src/gui/sharemanager.h
src/gui/systray.h
src/gui/userstatusselectormodel.h
src/libsync/bulkpropagatordownloadjob.cpp
src/libsync/bulkpropagatordownloadjob.h
src/libsync/owncloudpropagator.cpp
src/libsync/owncloudpropagator.h
src/libsync/propagatedownload.cpp
src/libsync/userstatusconnector.h
src/libsync/vfs/cfapi/cfapiwrapper.cpp
src/libsync/vfs/cfapi/cfapiwrapper.h
src/libsync/vfs/cfapi/vfs_cfapi.cpp
src/libsync/vfs/cfapi/vfs_cfapi.h
src/libsync/vfs/suffix/vfs_suffix.cpp
src/libsync/vfs/suffix/vfs_suffix.h
src/libsync/vfs/xattr/vfs_xattr.cpp
src/libsync/vfs/xattr/vfs_xattr.h
test/testsynccfapi.cpp

Feature/bulk create windows placeholders per folders (V1)

---

src/gui/tray/CurrentAccountHeaderButton.qml
src/gui/tray/TrayFoldersMenuButton.qml
src/gui/tray/UserLine.qml

- white border
- use central style everywhere
- correct typo
- correct allignment

fix: small white border around user status indicators

---

shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Extensions/NKShare+Extensions.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Localizable.xcstrings
shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Sharing/ShareOptionsView.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Sharing/ShareViewController.xib
src/gui/filedetails/shareemodel.cpp
src/gui/filedetails/sharemodel.cpp
src/gui/filedetails/sharemodel.h
src/gui/sharee.cpp
src/gui/sharee.h
src/gui/sharemanager.h
test/testshareemodel.cpp
test/testsharemodel.cpp

fix: rename Circle->Team

---

src/gui/folderstatusmodel.cpp
src/libsync/theme.cpp
src/libsync/theme.h

feat: Neutral folder state icons

---

src/gui/UserStatusMessageView.qml

fix: correct emoji button bindings

---

src/gui/owncloudgui.cpp

fix: show account label in tray hover
