nextcloud/desktop

src/gui/systray.cpp
src/gui/systray.h
src/gui/tray/CallNotificationDialog.qml

This prevents already-notified and closed call notification dialogs from remaining allocated

Deallocate call notification dialog objects when closed

---

src/libsync/discovery.cpp

Might address https://github.com/nextcloud/server/issues/33785
@tobiasKaminsky 

Ensure that the file being processed has had its etag properly sanitised, log etag more

---

src/gui/BasicComboBox.qml
src/gui/ErrorBox.qml
src/gui/PredefinedStatusButton.qml
src/gui/UserStatusSelectorButton.qml
src/gui/tray/ActivityItemContent.qml
src/gui/tray/CallNotificationDialog.qml
src/gui/tray/CustomButton.qml
src/gui/tray/CustomTextButton.qml
src/gui/tray/NCToolTip.qml

Not a source of any vulnerabilities as the supported subset of HTML is very limited (see https://doc.qt.io/qt-5/richtext-html-subset.html) but should still eliminate any potential weirdness
Closes https://github.com/nextcloud-gmbh/h1/issues/267

Do not format text in QML components as HTML

---

src/gui/tray/ActivityList.qml

Adds a placeholder item for empty activity lists (e.g. file has no recent activities)
Below screenshot is a simulated example of an empty activity list in the system tray as I didn't have any files not modified in the past 6 months
Closes #4342

Add a placeholder item for empty activity list

---

src/gui/tray/activitylistmodel.cpp
src/libsync/bulkpropagatorjob.cpp
src/libsync/owncloudpropagator.cpp
src/libsync/progressdispatcher.cpp
src/libsync/propagatedownload.cpp
src/libsync/syncfileitem.h
src/libsync/syncresult.cpp

This PR introduces two changes:
1. File name clashes are treated as warnings and not sync-stopping errors, much like invalid filenames
2. Clicking on an activity for a file name clash opens the relevant file in the web UI, where the file name clash can be resolved
Closes #4963

Improve handling of file name clashes

---

src/gui/CMakeLists.txt
src/gui/owncloudgui.cpp
src/gui/tray/ActivityItem.qml
src/gui/tray/ActivityList.qml
src/gui/tray/activitydata.h
src/gui/tray/activitylistmodel.cpp
src/gui/tray/activitylistmodel.h
src/gui/tray/notificationhandler.cpp
src/gui/tray/sortedactivitylistmodel.cpp
src/gui/tray/sortedactivitylistmodel.h
src/gui/tray/usermodel.cpp
src/libsync/syncfileitem.h
test/testactivitylistmodel.cpp

This retains the benefits of #4736 while obviating the need for much of the error-prone sorting currently done in the ActivityListModel. 
The results in a far simpler ActivityListModel, and thanks to the QSortFilterProxyModel, a far less complicated and error-prone sorting method. The SortedActivityListModel will also allow us to more easily modify sorting details in the future.

Add a QSortFilterProxyModel-based SortedActivityListModel

---

src/csync/vio/csync_vio_local_win.cpp
src/libsync/discovery.cpp
src/libsync/vfs/cfapi/vfs_cfapi.cpp

Bring back .lnk files on Windows and always treat them as non-virtual files.

---

src/gui/EmojiPicker.qml

Word wrap requires the label to have a set width

Ensure placeholder message in emoji picker wraps correctly

---

src/gui/ErrorBox.qml
src/libsync/theme.cpp
src/libsync/theme.h
theme/Style/Style.qml

Makes it less strident and easier to read
versus before:
Code also includes a close button we will be using for #4929 to dismiss the error box
Closes #4946

Improve the error box QML component

---

src/gui/tray/SyncStatus.qml

|            | Dark | Light |
|------------|------|-------|
| With fix   |   ![Screenshot 2022-09-29 at 19 18 53](https://user-images.githubusercontent.com/70155116/193100729-0a7f4bf4-ab89-4719-a118-2296abe0044f.png)   |   ![Screenshot 2022-09-29 at 19 18 46](https://user-images.githubusercontent.com/70155116/193100779-3bae80ed-bbcc-449f-8e40-870bdf6a823e.png)   |
| Before fix | ![Screenshot 2022-09-29 at 19 20 48](https://user-images.githubusercontent.com/70155116/193100813-d4d982f4-13ec-439c-94c1-63d783301bda.png)   |  ![Screenshot 2022-09-29 at 19 20 54](https://user-images.githubusercontent.com/70155116/193100855-c83633e3-93e1-4a77-b4b4-0f36640ce686.png)   |

Fix sync progress bar colours in dark mode

---

src/gui/PredefinedStatusButton.qml
src/gui/UserStatusSelector.qml

With recent changes to text formatting being set to plain text rather than rich HTML text, some of the internal styling used for predefined status messages has broken. This PR fixes it.
With fix:
Before fix:

Fix predefined status text formatting

---

src/gui/systray.cpp

This PR prevents the context menu from being opened when the tray icon is clicked, in situations where the desktop client is build without the macOS application bundle. 
This prevents the following bug:

Don't set up tray context menu on macOS, even if not building app bundle

---

.github/workflows/clang-tidy-review.yml

should allow to keep our code tidy and maybe simplify reviews

check our code with clang-tidy

---

src/libsync/configfile.cpp

alway use constexpr for all text constants

---

src/3rdparty/kirigami/wheelhandler.cpp
src/gui/application.cpp
src/gui/creds/webflowcredentialsdialog.cpp
src/gui/folderstatusdelegate.cpp
src/gui/folderwizard.cpp
src/gui/selectivesyncdialog.cpp
src/gui/settingsdialog.cpp
src/gui/socketapi/socketapi.cpp
src/gui/tooltipupdater.cpp
src/gui/tray/sortedactivitylistmodel.cpp
src/gui/wizard/abstractcredswizardpage.cpp
src/gui/wizard/owncloudadvancedsetuppage.cpp
src/libsync/account.cpp
src/libsync/clientsideencryption.cpp
src/libsync/creds/httpcredentials.cpp
src/libsync/owncloudpropagator.cpp

ran
run-clang-tidy-14.py -header-filter='.*' -checks='-*,cppcoreguidelines-pro-type-static-cast-downcast' -fix
this can prevent casting to a type that is unrelated to the real type and later cause a crash because you go into undefined behavior domain

avoid possibly crashing static_cast

---

.drone.yml

switch AppImage CI to latest tag: client-appimage-6

---

src/gui/sharelinkwidget.cpp

Fix link shares default expire date being enforced as maximum expire date even when maximum date enforcement is disabled on the server

---

src/csync/csync.h
test/csync/vio_tests/check_vio_ext.cpp

ran
run-clang-tidy-14.py -header-filter='.*' -checks='-*,modernize-use-using' -fix

apply modernize-use-using via clang-tidy

---

src/common/syncjournaldb.cpp
src/common/syncjournaldb.h
src/libsync/discovery.cpp
src/libsync/discoveryphase.h
src/libsync/syncengine.cpp
src/libsync/syncengine.h
test/testlocaldiscovery.cpp

We have a bug where files are not unlocked after the lock timer expires. This is because there is no indication to the sync engine that a local lock state different to the server lock state needs to be acted on; on top of that, the call to update a file's metadata does not update the lock state of a file.
This PR fixes both of these issues by setting the instruction of an item with a local lock state different to the server to `CSYNC_INSTRUCTION_UPDATE_METADATA`, and also ensures that lock state is updated in the database in the call to `updateLocalMetadata`. It also starts a remote check when the file lock expires.
EDIT: This PR now also schedules sync runs for files that need one to check lock status after the lock times out. Sync runs are minimised by grouping files into buckets of …

Fix files not unlocking after lock time expired

---

.clang-format
.github/workflows/clang-format.yml

let's check the format via some github action

---

resources.qrc
src/gui/folderman.cpp
src/gui/folderman.h
src/gui/iconutils.cpp
src/gui/systray.cpp
src/gui/systray.h
src/gui/tray/EditFileLocallyLoadingDialog.qml
src/gui/tray/NCBusyIndicator.qml

Improve 'Handle local file editing' feature. Add loading popup. Add force sync before opening a file.

---

src/cmd/cmd.cpp
src/cmd/simplesslerrorhandler.cpp
src/libsync/account.cpp
src/libsync/account.h

Command-line client. Do not trust SSL certificates by default, unless '--trust' option is set.

---

src/libsync/vfs/cfapi/vfs_cfapi.cpp

do not ignore return value

---

src/gui/tray/activitylistmodel.cpp

improve logs when adding sync errors in activity list of main dialog

---

src/gui/UserStatusSelector.qml

Fix invisible user status selector button not being checked when user is in Offline mode

---

src/gui/updater/ocupdater.cpp
src/gui/updater/ocupdater.h

Fix https://github.com/nextcloud/client_updater_server/issues/96

use correct version copmparison on NSIS updater: fix update from rc

---

src/gui/application.cpp
src/gui/folderman.cpp
src/gui/folderman.h

Fix account not found when doing local file editing.

---

src/gui/accountmanager.cpp
src/gui/creds/webflowcredentials.cpp
src/gui/settingsdialog.cpp
src/gui/tray/usermodel.cpp
src/libsync/account.cpp
src/libsync/account.h

| With fix | Without fix |
|----------|-------------|
| ![image](https://user-images.githubusercontent.com/70155116/194385379-a1e91c17-3ede-4b04-a4ea-e5970252b3ae.png) | ![Screenshot_20221006_164418](https://user-images.githubusercontent.com/70155116/194344683-c45730fb-136d-47c6-aa64-a9cb57a46caa.png) |

Improve "pretty user name"-related strings, display in webflow credentials

---

src/libsync/clientsideencryption.cpp
src/libsync/clientsideencryption.h

validate certificate for E2EE against private key

---

src/gui/accountstate.cpp

FIX: https://github.com/nextcloud/desktop/issues/4807

emit missing signal to update folder sync status icon

---

README.md

CMake 3.14.0 released in March 2019 [1] added the command line config options `-S <source-dir>` and `-B <build-dir>` and the build argument `--build <build-dir>` [2]. These options are universally valid independent of the build system used (`make`, `nmake`, `ninja`, `MSBuild`,...), making the provided CMake commands more generic.
As reference Ubuntu 20.04 ships the CMake 3.16.3 [3] version.
- [1] https://gitlab.kitware.com/cmake/cmake/-/tags/v3.14.0
- [2] https://cmake.org/cmake/help/v3.14/release/3.14.html#command-line
- [3] https://packages.ubuntu.com/focal/cmake
Signed-off-by: NeroBurner <pyro4hell@gmail.com>

Update CMake usage in README build instructions

---

src/libsync/syncengine.cpp
src/libsync/syncengine.h

Small clean up that consists of:
- Placing Q_INVOKABLE and void setters in slots
- Removing getter for stopwatch unused anywhere in the code
- Constifying methods that could be constified

Clean up methods in sync engine

---

src/gui/systray.h

It's a small refactor but should bring Systray in line with other classes and let us hook into these methods for connections

Make Systray's void methods slots

---

src/libsync/owncloudpropagator.h
src/libsync/syncengine.cpp

Remove unneeded parameter from CleanupPollsJob constructor

---

src/gui/accountsettings.cpp
src/gui/folderman.cpp
src/gui/folderman.h
src/gui/tray/ActivityActionButton.qml
src/gui/tray/ActivityItem.qml
src/gui/tray/ActivityItemActions.qml
src/gui/tray/ActivityItemContent.qml
src/gui/tray/CustomButton.qml
src/gui/tray/HeaderButton.qml
src/gui/tray/SyncStatus.qml
src/gui/tray/Window.qml
src/gui/tray/usermodel.cpp
src/gui/tray/usermodel.h
theme/Style/Style.qml

Add a 'Sync now' button to the sync status header in the tray window

---

src/gui/accountmanager.cpp

Mostly just:
- More use of `constexpr`, `const auto` and `auto` where possible
- Removing `foreach`
- Replace inscrutable one or two letter variable names with readable names

Modernise and improve code in AccountManager

---

src/gui/folderman.cpp

Also do percent encoding to be safe

Validate and sanitise edit locally token and relpath before sending to server

---

src/gui/tray/SyncStatus.qml

FIX: https://github.com/nextcloud/desktop/issues/5096

Only show Sync Now button if account is connected

---

src/gui/cocoainitializer_mac.mm

use new public API to open an edit locally URL

---

src/gui/accountmanager.cpp
src/gui/accountmanager.h
src/gui/accountsettings.cpp
src/gui/accountsettings.h
src/gui/mnemonicdialog.ui
src/libsync/account.cpp
src/libsync/account.h
src/libsync/clientsideencryption.cpp
src/libsync/clientsideencryption.h

Mnemonic is now displayed in mono font and text can't be typed in the dialog (readonly).
Keys are not generated automatically (see the video), but only after the user clicks "Enable encryption".
https://user-images.githubusercontent.com/12224014/196701160-aab85ec0-352c-48c6-b34f-0f1db8e66e34.mp4

E2EE. Do not generate keypair without user request.

---

src/gui/tray/usermodel.cpp
src/gui/tray/usermodel.h

Fix incorrect current user index when adding or removing a user account. Also fix incorrect user avatar lookup by id.

---

src/gui/tray/ActivityActionButton.qml
src/gui/tray/CallNotificationDialog.qml
src/gui/tray/CustomButton.qml
src/gui/tray/NCButtonContents.qml
src/gui/tray/SyncStatus.qml

Ensure 'Sync now' button doesn't have its text elided

---

src/gui/filedetails/ShareDelegate.qml

Fix share delegate button icon colors in dark mode

---

src/gui/accountsettings.cpp

Do not use copy-assignment of QDialog.

---

src/gui/tray/usermodel.cpp

Remove unused remotePath in User::processCompletedSyncItem

---

.github/workflows/windows-build-and-test.yml
test/testfolderwatcher.cpp

properly escape a path when creating a test file during tests

---

admin/linux/build-appimage.sh
src/3rdparty/qtsingleapplication/qtlocalpeer.h
src/gui/CMakeLists.txt
src/gui/folder.cpp
src/gui/folderman.cpp

This PR prepares building with `CMAKE_UNITY_BUILD` enabled. This makes builds often a bit faster and the executables often a bit smaller.
I tried to keep the changes as small as possible and without renaming variables. This is why I exclude the file causing troubles from the unity build or added macros in order to avoid defining a variable multiple times. 
I timed the builds with `time ninja`
Unity build:  nextcloud 5.6M
```
real    0m42,137s
user    3m36,684s
sys     0m17,226s
```
Normal build: nextcloud 5.8M
```
real    0m46,048s
user    9m13,199s
sys     0m45,951s
```

Add support cmake unity build

---

src/gui/userstatusselectormodel.cpp

a simple fix of typo found by Debian Lintian.

Fix typo of connector

---

src/gui/tray/NCButtonContents.qml

Fixes a number of warnings in logs

Remove reference to inexistent property in NCCustomButton

---

src/gui/tray/ActivityList.qml

Whether we use anchors or width to set the ActivityList delegates, we consistently get issues accessing the parent, polluting the logs
This PR addresses this by only setting the delegate anchors if parent is available

Fix ActivityList delegate warnings

---

src/gui/folderman.cpp

This fixes the behaviour of the "Sync now" button when a folder has its syncing paused
https://user-images.githubusercontent.com/70155116/200875644-e2d30871-e3dd-458e-abbe-5226e8e5340a.mov

Ensure forcing a folder to be synced unpauses syncing on said folder

---

.github/workflows/windows-build-and-test.yml
craftmaster.ini

switch back to upstream craft

---

src/libsync/discovery.cpp
src/libsync/discovery.h
src/libsync/discoveryphase.h
src/libsync/propagatorjobs.cpp
src/libsync/propagatorjobs.h
src/libsync/syncengine.cpp
test/testsyncmove.cpp

currently broken test as we miss to rename recursively

fix renaming of folders with a deep hierarchy inside them

---

src/gui/accountmanager.cpp
src/gui/accountsettings.cpp
src/gui/application.cpp
src/gui/filedetails/sharemodel.cpp
src/gui/folderman.cpp
src/gui/networksettings.cpp
src/gui/socketapi/socketapi.cpp
src/gui/tray/asyncimageresponse.cpp
src/gui/tray/notificationhandler.cpp
src/gui/tray/unifiedsearchresultslistmodel.cpp
src/gui/tray/usermodel.cpp
src/libsync/creds/httpcredentials.cpp
src/libsync/discovery.cpp
src/libsync/syncengine.cpp
test/syncenginetestutils.cpp
test/testallfilesdeleted.cpp
test/testchunkingng.cpp
test/testfolderwatcher.cpp
test/testsyncconflict.cpp
test/testsyncjournaldb.cpp
test/testsyncmove.cpp

fix instances of: c++11 range-loop might detach Qt container warnings

---

.drone.yml
src/gui/folderman.h
test/CMakeLists.txt
test/endtoendtestutils.cpp
test/endtoendtestutils.h
test/nextcloud_add_test.cmake
test/teste2efiletransfer.cpp
test/teste2eserversetup.cpp

Fix #4234
This PR adds end-to-end testing to our CI.
Specifically, it:
1. Adds and sets up a real server to our Drone pipeline
2. Adds a end to end testing utilities class that makes it easier to test with the server set up in the CI
3. Adds a test checking the correct set-up of an account
4. Adds a test checking file transfer (down-syncing an existing file, creating and uploading a new file, and deleting said created file)
Addresses #4234

Add end-to-end tests to our CI

---

shell_integration/libcloudproviders/CMakeLists.txt

Commit b34a90183818 ("Use FindPkgConfig to find libcloudproviders and related libs") introduced the usage of cmake's FindPkgConfig module which provides `pkg_get_variable` since version 3.4 that can be used instead of the custom `PKGCONFIG_GETVAR` macro
Signed-off-by: Marvin Schmidt <marv@exherbo.org>

cmake: Use FindPkgConfig's pkg_get_variable instead of custom macro

---

src/gui/tray/Window.qml

At the moment we respect the tray window's margins in a very ad-hoc way, leading to small breakages and visual bugs (such as the header eating into the background border)
This PR properly addresses the sizing of the window contents
With fix:
Before fix:

Fix tray window margins, stop cutting into window border

---

src/libsync/propagateremotemove.cpp
src/libsync/propagatorjobs.cpp
src/libsync/vfs/cfapi/vfs_cfapi.cpp
src/libsync/vfs/suffix/vfs_suffix.cpp
src/libsync/vfs/suffix/vfs_suffix.h
src/libsync/vfs/xattr/vfs_xattr.cpp

fix regressions on pinState management when doing renames

---

src/gui/tray/ActivityActionButton.qml
src/gui/tray/ActivityItem.qml
src/gui/tray/CustomButton.qml
src/gui/tray/NCButtonContents.qml
theme/Style/Style.qml

Our custom buttons implementation has some bugs with alignments and sizings that makes our buttons sometimes look either weird or broken. This PR fixes these issues
| With fix | Before fix |
|---------|-----------|
| ![Screenshot 2022-11-18 at 18 19 46](https://user-images.githubusercontent.com/70155116/202764930-c23ff5d7-a892-4f80-9a44-c65402c7857e.png) | ![Screenshot 2022-11-18 at 18 21 53](https://user-images.githubusercontent.com/70155116/202764989-79ca99f4-8c99-40e4-abf2-758ad780bc6d.png) |
| ![Screenshot 2022-11-18 at 18 22 59](https://user-images.githubusercontent.com/70155116/202765044-8bf5a0dd-af10-4c44-bfb1-cf40e0b6ad10.png) | ![Screenshot 2022-11-18 at 18 22 16](https://user-images.githubusercontent.com/70155116/202765085-4d080e17-233e-44d1-b4ed-68c4b393efd0.png) | …

Fix bad custom button alignments, sizings, etc.

---

src/gui/accountsettings.cpp

Prevent bad encrypting of folder if E2EE has not been correctly set up

---

src/gui/accountsettings.cpp

Remove close/dismiss button from encryption message

---

shell_integration/MacOSX/OwnCloudFinderSync/OwnCloudFinderSync.xcodeproj/project.pbxproj

We updated the minimum system requirements to 10.14 a while ago but the deployment targets for the shell integration components have not been updated
This addresses this

Update macOS shell integration deployment targets

---

src/gui/accountsettings.cpp

Should clarify situation for users
Part of #5126 

Differentiate between E2EE not being enabled at all vs. E2EE being enabled already through another device in account settings message

---

src/gui/tray/UnifiedSearchResultItem.qml
src/gui/tray/UnifiedSearchResultNothingFound.qml
src/gui/tray/UnifiedSearchResultSectionItem.qml
src/gui/tray/UserLine.qml

Ensure more QML text components are rendering things as plain text

---

src/gui/accountsettings.cpp
src/libsync/clientsideencryption.cpp

l10n: Correct spelling

---

.github/workflows/qml-label-check.yml
resources.qrc
src/gui/BasicComboBox.qml
src/gui/EmojiPicker.qml
src/gui/ErrorBox.qml
src/gui/PredefinedStatusButton.qml
src/gui/UserStatusSelector.qml
src/gui/UserStatusSelectorButton.qml
src/gui/filedetails/FileDetailsPage.qml
src/gui/filedetails/NCTabButton.qml
src/gui/filedetails/ShareDelegate.qml
src/gui/filedetails/ShareView.qml
src/gui/tray/ActivityActionButton.qml
src/gui/tray/ActivityItemContent.qml
src/gui/tray/ActivityList.qml
src/gui/tray/CallNotificationDialog.qml
src/gui/tray/EditFileLocallyLoadingDialog.qml
src/gui/tray/EnforcedPlainTextLabel.qml
src/gui/tray/NCButtonContents.qml
src/gui/tray/NCToolTip.qml
src/gui/tray/SyncStatus.qml
src/gui/tray/TextButtonContents.qml
src/gui/tray/UnifiedSearchResultFetchMoreTrigger.qml
src/gui/tray/UnifiedSearchResultItem.qml
src/gui/tray/UnifiedSearchResultNothingFound.qml
src/gui/tray/UnifiedSearchResultSectionItem.qml
src/gui/tray/UserLine.qml
src/gui/tray/Window.qml

This PR:
- Replaces all use of Label and Text components in our QML code for a new EnforcedPlainTextLabel
- Adds a basic check in our CI for the use of Label components (of which there should only be one, in EnforcedPlainTextLabel)

Make use of plain text-enforcing qml labels

---

src/gui/editlocallyjob.cpp
src/gui/editlocallyjob.h
src/gui/editlocallymanager.cpp

Lock file when editing locally

---

src/gui/UserStatusSelector.qml

This should avoid any unpleasant or unexpected surprises
**This PR also contains some fixes that are visible when compiling with Qt 6** 

Explicitly size and align user status selector text input to avoid bugs with alternate QtQuick styles

---

src/gui/accountsettings.cpp
src/libsync/account.cpp
src/libsync/account.h
src/libsync/clientsideencryption.cpp

This stops the user getting spammed with annoying pop-ups on launch asking for the mnemonic when they have no intention of enabling encryption on their current system/account
Closes #4778 

Only show mnemonic request dialog when user explicitly wants to enable E2EE

---

src/gui/systray.cpp
src/gui/systray.h
src/gui/systray.mm
src/gui/tray/usermodel.cpp
src/gui/tray/usermodel.h

This PR makes the client differentiate between normal notifications and Talk notifications, emitting reply-able notifications for Talk on macOS
https://user-images.githubusercontent.com/70155116/200644355-8232b10f-7bfc-4f98-9f6c-a50b0c498d86.mov
Closes #4851
Interested parties: @jospoortvliet :)

Add interactive NC Talk notifications on macOS

---

src/gui/filedetails/FileDetailsPage.qml
src/gui/filedetails/FileDetailsView.qml
src/gui/filedetails/ShareDelegate.qml
src/gui/filedetails/ShareDetailsPage.qml
src/gui/filedetails/ShareView.qml
src/gui/systray.cpp
src/gui/systray.h
src/gui/tray/ActivityItem.qml
src/gui/tray/ActivityItemActions.qml
src/gui/tray/ActivityItemContent.qml
src/gui/tray/Window.qml
src/gui/tray/activitylistmodel.cpp
src/gui/tray/activitylistmodel.h

https://user-images.githubusercontent.com/70155116/200318092-a0bf475b-76f1-4ee2-a418-531153574617.mov
Closes #4937 
Please note that this PR depends on #5129

Show file details within the tray dialog, rather than in a separate dialog

---

admin/nix/flake.nix
shell_integration/MacOSX/OwnCloudFinderSync/OwnCloudFinderSync.xcodeproj/project.pbxproj
shell_integration/MacOSX/OwnCloudFinderSync/OwnCloudFinderSync.xcodeproj/xcshareddata/xcschemes/FinderSyncExt.xcscheme

Nix flakes makes it very easy to create builds and dev shells of the desktop client with minimal maintenance load, by using nix and nixpkgs.
This nix flake includes support for both macOS and Linux.  The Linux build is fully reproducible — nix downloads and builds the necessary dependencies independently of system packages. Unfortunately the macOS build is “impure” as we need to use the system Xcode to build the finder sync extension, but besides that everything else is shared with the Linux build
Adopting this will make it easier to build the desktop client and create a dev environment for contributors and for ourselves, as well as make it easier to package the desktop client if we adopt this for our build infra

Add a nix flake for easy building and dev environments 

---

src/gui/filedetails/ShareDelegate.qml
src/gui/filedetails/ShareDetailsPage.qml
src/gui/filedetails/sharemodel.cpp
src/gui/filedetails/sharemodel.h
src/gui/filedetails/sortedsharemodel.cpp
src/gui/sharemanager.h
test/sharetestutils.cpp
test/testsharemodel.cpp
test/testsortedsharemodel.cpp

Re-implements a feature that we previously had in the QWidgets version

Add an internal link share to the share dialog

---

.github/workflows/windows-build-and-test.yml
craftmaster.ini

sets a fixed version for pixman when buildign desktop client via Craft

---

test/testsyncengine.cpp

The localstate is getting destroyed on the stack, hence, later on, pointers to FileInfo inside it become invalid. This is a quick fix for this failing test.

Fix SyncEngineTest failure when localstate is destroyed.

---

src/gui/accountmanager.cpp
src/gui/folder.cpp
src/gui/folderman.cpp

fix migration from old settings configuration files

---

src/gui/connectionvalidator.cpp
src/gui/creds/webflowcredentials.cpp
src/gui/editlocallyjob.cpp
src/gui/filedetails/shareemodel.cpp
src/gui/filedetails/sharemodel.cpp
src/gui/folderstatusmodel.cpp
src/gui/settingsdialog.cpp
src/libsync/creds/dummycredentials.cpp
src/libsync/creds/httpcredentials.cpp
src/libsync/discovery.cpp
src/libsync/discoveryphase.cpp

Fixes several instances of bad/incorrect/missing use of `emit`

Make correct use of Qt signal 'emit' keyword

---

src/gui/folderstatusdelegate.cpp
src/gui/remotewipe.cpp
src/libsync/bulkpropagatorjob.cpp
src/libsync/propagateremotemove.cpp

Removes unused variables and procedures throughout the desktop client

Remove unused variables

---

src/gui/creds/oauth.cpp
src/gui/editlocallyjob.cpp
src/gui/notificationconfirmjob.cpp
src/gui/syncrunfilelog.cpp
src/libsync/logger.cpp
src/libsync/networkjobs.cpp
src/libsync/propagatedownload.cpp
src/libsync/theme.cpp

QRegularExpressions are expensive to create, but they can be declared statically to not do unneeded work. Hence Clazy complains when they are not declared statically.
This PR ensures all QRegularExpressions are declared statically

Declare all QRegularExpressions statically

---

src/gui/socketapi/socketapi.cpp

l10n: Remove space

---

src/libsync/theme.cpp

This PR replaces our incomplete dark mode palette with a much better complete one taken from https://github.com/Jorgen-VikingGod/Qt-Frameless-Window-DarkStyle/ (thanks!)

Improve backup dark mode palette for Windows

---

src/gui/CMakeLists.txt
src/gui/accountsetupcommandlinemanager.cpp
src/gui/accountsetupcommandlinemanager.h
src/gui/accountsetupfromcommandlinejob.cpp
src/gui/accountsetupfromcommandlinejob.h
src/gui/application.cpp
src/gui/application.h

Allow setting up an account with apppasword and folder via command-line arguments. For deployment.

---

src/libsync/propagatedownload.cpp
src/libsync/propagatedownload.h
test/testsyncconflict.cpp

Update file's metadata in the local database when the etag changes while file remains unchanged. Fix subsequent conflict when locking and unlocking.

---

src/gui/settingsdialog.cpp
src/gui/settingsdialog.h
src/gui/wizard/slideshow.cpp
src/gui/wizard/slideshow.h
src/libsync/theme.h

Clazy runs reveal several poorly defined QPROPERTYs in the codebase which are missing a CONSTANT or NOTIFY declaration
This PR fixes these

Fix warnings on QPROPERTY-s

---

src/gui/folderwatcher_mac.cpp

FSEventStreamScheduleWithRunLoop is now deprecated since macOS 13.0

Replace now deprecated FSEventStreamScheduleWithRunLoop with FSEventStreamSetDispatchQueue

---

shell_integration/MacOSX/OwnCloudFinderSync/FinderSyncExt/FinderSync.m
shell_integration/MacOSX/OwnCloudFinderSync/FinderSyncExt/LineProcessor.m

Some of the `init` for FinderSync classes are faulty. This PR addresses their issues

Fix macOS shell integration class inits

---

src/gui/BasicComboBox.qml
src/gui/PredefinedStatusButton.qml
src/gui/UserStatusSelector.qml
src/gui/UserStatusSelectorButton.qml

Qt Quick Controls 1 where deprecated with Qt 5.11 [1]. Nextcloud still depends on Quick Controls 1 by importing QtQuick.Dialogs. Removing those imports will cause the QMl script to use the according API from Quick Controls 2, which are, fortunately largely API-comptible.
This helps distribution to deprecate and remove Quick Controls 1 [2].
1: https://doc.qt.io/qt-6/qtquickcontrols-changes-qt6.html#migrating-from-qt-quick-controls-1
2: https://bugs.gentoo.org/889772

Drop dependency on Qt Quick Controls 1

---

src/gui/tray/unifiedsearchresultslistmodel.cpp
src/gui/tray/unifiedsearchresultslistmodel.h

The full-text search app provides incomplete resource URLs unlike all other search result apps, meaning our default behaviour for opening search results in the browser does not work
This PR adds a procedure to compensate for this
Closes #5113 and https://github.com/nextcloud/fulltextsearch/issues/728

Fix full-text search results not being opened in browser

---

src/libsync/propagateuploadencrypted.cpp

Always generate random initialization vector when uploading encrypted file

---

src/gui/folderstatusmodel.cpp

Fix bad string for translation.

---

src/gui/accountmanager.cpp

Fix migration from legacy client when override server url is set

---

src/gui/tray/UnifiedSearchResultListItem.qml

For some reason, the unified search result item is disabled if it is a "Fetch More" entry, preventing user interaction
This fixes this issue

Fix fetch more unified search result item not being clickable

---

src/gui/application.cpp
src/gui/application.h
src/gui/generalsettings.cpp
src/gui/generalsettings.ui
src/libsync/configfile.cpp
src/libsync/configfile.h
src/libsync/theme.cpp
src/libsync/theme.h

This legacy setting is not used anywhere so it makes sense to remove it

Remove unused monochrome icons setting

---

src/gui/application.cpp
src/gui/application.h
src/gui/generalsettings.cpp
src/gui/generalsettings.ui
src/libsync/configfile.cpp
src/libsync/configfile.h
src/libsync/theme.cpp
src/libsync/theme.h

This reverts commit 5c42da4de5facbea9b06cf7086bee17005be59b2, reversing changes made to e4b24490307f4337b390b6b484e8d77befffaf1b.
Caused issues on macOS, will find a better way to remove the monochrome icons option when it does nothing

Revert "Merge pull request #5366 from nextcloud/bugfix/remove-mono-icons-setting"

---

src/gui/application.cpp
src/libsync/configfile.cpp
src/libsync/configfile.h

Due to changes in the config file name, there has been issues when the desktop client.
We already had code that did migrate configs from different folders, now this change would check for previous config files independent of the name. It will back up the previous config and rename the file to the new application name when there is an update of the client version.
1. I am sure there might be drawbacks to this. wdyt?
2. There is already a notification in place to tell the user there is a previous config. 
Previous config:
Notification:
New config:
After another upgrade, it should proceed to doing backups:

Migrate old configs

---

src/gui/tray/activitylistmodel.cpp
src/gui/tray/usermodel.cpp

Fix displaying of file details button for local syncfileitem activities

---

src/gui/application.cpp
src/gui/application.h
src/gui/wizard/owncloudadvancedsetuppage.cpp

Should fix #5383.
For reference please check #5329

Only accept folder setup page if overrideLocalDir is set

---

src/gui/application.cpp
src/gui/application.h
src/gui/wizard/owncloudadvancedsetuppage.cpp

Backport/5385/stable 3.7

---

src/libsync/logger.cpp

Having to sift through the log files can be a pain, so it makes sense to log to stdout as normal when we build in debug mode
With this we can check logging directly in Qt Creator or in the terminal

Log to stdout when built in Debug config

---

src/gui/accountsettings.cpp
src/gui/foldercreationdialog.cpp
src/gui/foldercreationdialog.h

Fix "Create new folder" menu entries in settings not working correctly on macOS

---

src/gui/accountmanager.cpp
src/gui/accountsettings.cpp
src/gui/accountsettings.h
src/gui/accountstate.cpp
src/gui/accountstate.h
src/libsync/account.cpp
src/libsync/clientsideencryption.cpp
src/libsync/clientsideencryption.h

This PR cleans up some of our code relating to account creation and deletion. It also improves some of the logging

Clean up account creation and deletion code

---

src/gui/filedetails/sharemodel.cpp

Restrictive file sharing defaults from the server can cause the client to assume the worst at the start, and then we don't try to reinitialise the share manager when we get more permissive sharing permissions from the server -- causing the infinite loop as sharing is allowed, but the manager is never initialised
Now we reinitialise the manager if we have received nice permissions on PROPFIND
Fixes #5411

Fix share dialog infinite loading

---

src/libsync/account.cpp

the only correct id for an user is Account::_davUser

fix edit locally job not finding the user account: wrong user id

---

src/libsync/clientsideencryption.cpp

we cannot decrypt a file without a name
for now we will ignore them
we should probably do much more for the user but I fail to see how to generate errors from e2ee module

skip e2e encrypted files with empty filename in metadata

---

src/libsync/theme.cpp

Aligned end of sentences in about dialog.

l10n: Added dot to end of sentence

---

src/libsync/discovery.cpp
test/testlocaldiscovery.cpp

Always discover blacklisted folders to avoid data loss when modifying selectivesync list.

---

shell_integration/dolphin/ownclouddolphinactionplugin.cpp
src/3rdparty/kmessagewidget/kmessagewidget.cpp
src/gui/application.cpp
src/gui/cloudproviders/cloudprovidermanager.cpp
src/gui/cloudproviders/cloudproviderwrapper.cpp
src/gui/remotewipe.cpp
src/gui/wizard/slideshow.cpp
src/libsync/account.cpp
src/libsync/owncloudpropagator.h
test/syncenginetestutils.h
test/testchecksumvalidator.cpp
test/testdownload.cpp
test/testfolderwatcher.cpp
test/testsyncengine.cpp
test/testsyncfilestatustracker.cpp
test/testxmlparse.cpp

mainly done using clazy and old-style-connect check
close #5426

use new connect syntax

---

src/libsync/vfs/cfapi/cfapiwrapper.cpp

CF_UPDATE_FLAG_DEHYDRATE is apparently needed to get dehydration to always succeed

with cfapi when dehydrating files add missing flag

---

src/gui/settingsdialog.cpp

At creation time of the toolbar actions, the avatars are never yet available. This PR fixes this issue by dispatching a user info job that fetches the avatar at the time of creation of the toolbar action and updates the avatar image accordingly
With fix:
https://user-images.githubusercontent.com/70155116/220126929-b6e5f590-c552-42af-b7e5-af2caf4eb5b6.mov
Before fix:
https://user-images.githubusercontent.com/70155116/220127113-1d57aba0-6d2a-4a19-9710-701f7b3a20cd.mov
Closes #5447

Fix avatars not showing up in settings dialog account actions until clicked on

---

src/gui/tray/SyncStatus.qml

Fix text labels in Sync Status component

---

src/gui/filedetails/sharemodel.cpp

We erroneously prevent the share manager from being initialised if public link shares are disabled on the server. Since we can have situations where link shares are disabled but user shares are enabled, this is wrong.
This PR fixes this bug and prevents the placeholder link share from being presented if public link shares are disabled
Fixes #5470

Fix infinite loading in the share dialog when public link shares are disabled on the server

---

src/gui/filedetails/ShareView.qml
src/gui/filedetails/ShareeDelegate.qml
src/gui/filedetails/ShareeSearchField.qml
src/gui/filedetails/shareemodel.cpp
src/gui/filedetails/shareemodel.h
src/gui/owncloudgui.cpp
src/gui/sharee.cpp
src/gui/sharee.h
test/testshareemodel.cpp

Display 'Search globally' as the last sharees list element

---

src/gui/wizard/webview.cpp
src/gui/wizard/webview.h

When the login dialogue displays the login page itself the WebView widget did not resize according to
the dimensions of the login page.
Fixes #5160

Resize WebView widget once the loginpage rendered

---

src/gui/tray/usermodel.cpp

Fix for issue #5421: add server notifications to the activities list when the user needs to act on it.
It should also work for other notifications:

Fix display of 2FA notification.

---

src/gui/tray/Window.qml

Closes #5491 
This PR adds the Account server name to the tray main window, if more than 1 account exists.
Reason for change: If a user has the same user name across multiple servers, it's hard to know which account is currently selected.
Example:
*First time using QML, comments/improvements welcome!*

Show server name in tray main window

---

src/gui/tray/activitydata.h
src/gui/tray/notificationhandler.cpp
src/gui/tray/usermodel.cpp

follow shouldNotify flag to hide notifications when needed

---

src/gui/folderman.cpp
src/gui/folderman.h
src/gui/folderwizard.cpp
src/gui/wizard/owncloudadvancedsetuppage.cpp
test/testfolderman.cpp

may lead to inadvertant data loss, not sure if that could be an issue

when local sync folder is overriden, respect this choice

---

src/libsync/clientsideencryption.cpp
src/libsync/clientsideencryption.h

will only accept a checksum that can be computed from proper data
should still be safe

try different permutation to try to recover the broken checksum

---

src/gui/folder.cpp

Do not display error status and messages when aborting a sync during hydration request in VFS mode

---

src/libsync/clientsideencryption.cpp

in case server has no private key, let e2ee init fail

---

src/gui/editlocallyjob.cpp
src/gui/editlocallyjob.h

Make sure a folder sync gets restarted immediately after file opening is finished. A folder sync is restarted only if it was syncing before EditLocally got triggered.

Edit locally. Restart current folder sync immediately after file opened.

---

src/common/syncjournaldb.h
src/gui/accountsettings.h
src/gui/accountsetupfromcommandlinejob.h
src/gui/editlocallyjob.h
src/gui/filedetails/shareemodel.h
src/gui/folderman.cpp
src/gui/folderman.h
src/gui/socketapi/socketapi.h
src/gui/systray.h
src/gui/tray/usermodel.h
src/libsync/clientsideencryption.h
src/libsync/syncengine.h
src/libsync/updatefiledropmetadata.h

will make all signals and slots be using fully qualified data types
makes code safer

fix compilation with clazy and fully-qualified-moc-types checks enabled

---

src/gui/wizard/owncloudadvancedsetuppage.cpp

Alway add the item at the end of the layout.

---

src/common/syncjournaldb.cpp
src/common/syncjournalfilerecord.h
src/csync/csync.h
src/libsync/discovery.cpp
src/libsync/encryptfolderjob.cpp
src/libsync/owncloudpropagator.cpp
src/libsync/propagatedownloadencrypted.cpp
src/libsync/propagateremotedeleteencrypted.cpp
src/libsync/propagateremotedeleteencryptedrootfolder.cpp
src/libsync/propagateremotemkdir.cpp
src/libsync/propagateuploadencrypted.cpp
src/libsync/syncfileitem.cpp
src/libsync/syncfileitem.h
test/testfolderman.cpp

before this patch we may put the e2ee version format to v1.2 when it was not the case

properly preserve the format of e2ee metadata during DB operations

---

src/libsync/logger.cpp
src/libsync/logger.h

We are encountering a possible thread-unsafe race condition. Fix is to put this under the existing mutex.

Fix crash on entering new log file after file size of 512kb reached

---

src/gui/editlocallyjob.cpp
src/gui/editlocallyjob.h
src/gui/editlocallymanager.cpp

This should fix situations where the edit locally loading dialog is presented but never destroyed when an error is met during setup

Properly handle all fatal errors during edit locally setup procedure

---

doc/nextcloudcmd.rst

Debian has a package in its repository for nextcloudcmd. Adding an Ubuntu ppa to Debian might work, but is not the preferable solution.
Signed-off-by: mayonezo <haselnuss87@gmail.com>

Update nextcloudcmd.rst to include dedicated install method for Debian instead of using a Ubuntu ppa.

---

src/common/syncjournaldb.cpp

Fix https://github.com/nextcloud/desktop/issues/4950

Fix MacOS UTF-8 normalization issue

---

src/gui/filedetails/shareemodel.cpp

Parse sharees 'lookup' key to include federated sharees.

---

resources.qrc
src/gui/filedetails/NCRadioButton.qml
src/gui/filedetails/ShareDelegate.qml
src/gui/filedetails/ShareDetailsPage.qml
src/gui/filedetails/ShareView.qml
src/gui/filedetails/sharemodel.cpp
src/gui/filedetails/sharemodel.h
src/gui/ocssharejob.cpp
src/gui/ocssharejob.h
src/gui/sharemanager.cpp
src/gui/sharemanager.h
theme/Style/Style.qml

Implement missing share settings

---

craftmaster.ini

no longer override the pixman default version

---

src/gui/editlocallyjob.cpp
src/gui/editlocallyjob.h

Edit locally. Fix crash on _chekTokenJob pointer deref.

---

src/common/ownsql.cpp
src/common/ownsql.h

Thousands of useless lines make investigating logs really hard. Time to get rid of those. We can always add them if needed for specific case.

Remove some SQL debug logs to unclutter the output.

---

theme/colored/Nextcloud-macOS-icon.svg

This is an update to #4631 adding extensive inline annotations and CSS variables in order to make it easier to create alternate versions of the icon with different logos and/or different backgrounds.
The icon should be visually identical to the previous version.
At the beginning of the document, the following text appears in an XML comment:
> ## Purpose Statement
> 
> This SVG document is set up with human-readable definitions and instances so that the markup can easily be tweaked or have the logo and/or squircle replaced with other shapes. If you import this SVG document into Illustrator, it will probably come out unrecognizable if it even works at all.
> 
> I've added inline comments explaining almost every single SVG entity in this document in order to make it easier to understand.
> …

Annotated version of Big Sur icon

---

src/gui/accountmanager.cpp
src/libsync/account.cpp
src/libsync/account.h
src/libsync/clientsideencryption.cpp
src/libsync/clientsideencryption.h
src/libsync/owncloudpropagator.cpp
src/libsync/syncengine.cpp

E2EE. Fix freeze on metadata checksum validation.

---

src/gui/generalsettings.cpp
src/gui/generalsettings.h
src/libsync/configfile.cpp

This PR does two things:
1. Fix a check that would led to a bad comparison of the translated channel with the config-stored channel
2. More safely return the update channel to set in the config file from the input in the settings combo box, defaulting to stable where possible
3. Prevent setting or returning of bad update channels from the config file
Fixes #5455

Fix update request channel being set to wrong localised string

---

src/gui/folderstatusdelegate.cpp

We draw a custom widget for the folder status in the account settings, using QStyle's various drawing methods to render the  internal widgets. This works great 99% of the time, except on macOS where `QMacStyle` has a bug with drawing progress bars and does not respect X or Y settings in the `QStyleOptionProgressBar` rect QRect. This means the progress bar gets drawn out of position at the top-left of the folder view.
In cases where we are running macOS, default to drawing this progress bar with the Fusion style instead.
This PR also includes a number of code clean ups in the relevant `paint` function for the folder delegate
With fix:
Before fix:

Fix folder progress bar positioning in account settings on macOS

---

src/gui/accountmanager.cpp
src/gui/accountmanager.h
src/gui/application.cpp
src/gui/folderman.cpp
src/libsync/configfile.cpp
src/libsync/configfile.h

The two key fixes in this PR are:
1. Making folder migration procedures accept absolute file paths instead of relative file paths, allowing the migration steps to migrate config files from clients under old names
2. Migrating accounts with "dummy" authtype that are technically webflow users
This PR also cleans up a bunch of really old and unnecessarily difficult to read code

Fix account migration from legacy desktop clients (again)

---

resources.qrc
src/gui/CMakeLists.txt
src/gui/filedetails/FileDetailsPage.qml
src/gui/filedetails/FileTag.qml
src/gui/filedetails/filedetails.cpp
src/gui/filedetails/filedetails.h
src/gui/filetagmodel.cpp
src/gui/filetagmodel.h
src/libsync/CMakeLists.txt
src/libsync/networkjobs.cpp
src/libsync/networkjobs.h
test/CMakeLists.txt
test/syncenginetestutils.cpp
test/syncenginetestutils.h
test/testfiletagmodel.cpp

Display file tags in File Details

---

src/gui/editlocallyjob.cpp
src/gui/editlocallyjob.h
src/gui/folder.cpp
src/libsync/syncengine.cpp
src/libsync/syncengine.h

It was impossible to open for local editing anything if it was located in the topmost (root) local sync folder.

Allow opening a file or folder in the local sync root.

---

src/gui/filedetails/ShareDelegate.qml
src/gui/filedetails/ShareDetailsPage.qml
theme/Style/Style.qml

https://github.com/nextcloud/desktop/assets/70155116/626c885d-a4cd-42e9-8935-c6737070a157
https://github.com/nextcloud/desktop/assets/70155116/739a732c-128d-49fa-8835-4fefeeae9f56
Closes #5669

Provide feedback on share link copy

---

src/gui/accountmanager.cpp
src/gui/accountmanager.h
src/gui/application.cpp

Displays dialog asking user to confirm if they'd like to attempt an import of legacy accounts.
Also adds a command line argument to force imports if needed
Closes #5556

Ask before importing accounts from legacy clients

---

src/gui/folderwatcher.cpp

we create a file inside the sync folder to test file system monitoring
ensure this file is hidden (i.e. has the proper hidden property)

ensure that the file to test monitoring is hidden

---

shell_integration/MacOSX/CMakeLists.txt

We were using a wrong hard-coded path when set to Debug

Fix Debug builds of File Provider module

---

src/gui/tray/ActivityItemContent.qml

`model` property is not the entire activity item model, `activityData` custom property must be used

Bugfix. Conflict resolution button not clickable.

---

.drone.yml
.github/workflows/sonarcloud.yml
src/common/pinstate.h
src/gui/editlocallyjob.cpp
src/gui/folder.cpp
src/gui/folder.h
src/gui/tray/ActivityItemContent.qml
src/gui/tray/activitylistmodel.cpp
src/gui/tray/activitylistmodel.h
src/gui/tray/usermodel.cpp
src/gui/tray/usermodel.h
src/libsync/bulkpropagatorjob.cpp
src/libsync/bulkpropagatorjob.h
src/libsync/discovery.cpp
src/libsync/discoveryphase.cpp
src/libsync/discoveryphase.h
src/libsync/owncloudpropagator.cpp
src/libsync/owncloudpropagator.h
src/libsync/progressdispatcher.h
src/libsync/propagatedownload.cpp
src/libsync/propagateremotedelete.cpp
src/libsync/propagateremotemkdir.cpp
src/libsync/propagateremotemove.cpp
src/libsync/propagateupload.cpp
src/libsync/propagateupload.h
src/libsync/propagatorjobs.cpp
src/libsync/syncengine.cpp
src/libsync/syncengine.h
src/libsync/vfs/cfapi/cfapiwrapper.cpp
test/testactivitylistmodel.cpp

display subject when we have sync issues like network errors

---

src/gui/filedetails/NCRadioButton.qml

Fix colouring of NCRadioButton

---

src/gui/tray/ActivityItemActions.qml
src/gui/tray/ActivityItemContent.qml

https://github.com/nextcloud/desktop/assets/70155116/d061b3a4-cb1c-4638-847a-b991bc6975bd

Fix reply button visibility after reply field opened and reply text sent

---

shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj

Fix xcodebuild parallel build warning

---

src/gui/cloudproviders/cloudproviderwrapper.cpp

prevent crash by resetting common pointer after deleting gobject menu

---

craftmaster.ini
src/common/checksumcalculator.cpp
src/libsync/putmultifilejob.cpp

force an empty body when we bulk upload empty files
force a "valid" checksum to be computed for empty files as bulk upload server side expects a checksum even for empty files
Close #5824

fix bulk upload of empty files

---

src/libsync/propagatedownload.cpp
test/testpermissions.cpp
test/testsyncengine.cpp

make sure that a file locked that would not be modifiable by the current client is read-only on storage
also make sure we make a file read/write when modification can happen again
Close #5537

always propagate locked status to read-only or read/write for real file

---

.github/workflows/windows-build-and-test.yml
src/gui/tray/activitylistmodel.cpp
src/gui/tray/notificationhandler.cpp
src/gui/tray/notificationhandler.h
src/gui/tray/usermodel.cpp
src/gui/tray/usermodel.h

Fix crash in `_finalList `removal loop. Fix incorrect implementation of seen chat notifications removal. Improved notifications fetch code to avoid multiple calls from different threads.

Fix crash and incorrect implementation of seen chat notofications removal

---

src/csync/csync_exclude.cpp
test/testexcludedfiles.cpp

Proposal to solve https://github.com/nextcloud/desktop/issues/3826, by excluding silently windows reserved word like $RECYCLE.BIN.
Signed-off-by: tomdereub <pbtom@lamonerie.net>

windows reserved word silently excluded - csync exclude.cpp

---

src/gui/filedetails/FileDetailsPage.qml
src/gui/filedetails/filedetails.cpp
src/gui/filedetails/filedetails.h

Disable share view completely when server does not support/has disabled file sharing

---

src/common/pinstate.h
src/gui/folder.cpp
src/gui/folder.h
src/gui/folderwatcher.cpp
src/gui/folderwatcher.h
src/libsync/vfs/cfapi/cfapiwrapper.cpp
src/libsync/vfs/cfapi/vfs_cfapi.cpp
src/libsync/vfs/cfapi/vfs_cfapi.h

Setting PinState to Excluded ensures the syncing icon is not shown for ignored items. 
If the PinState is not set to Excluded, also all parent directories are shown as being synced, which is very inconvenient for the end user as it seems that some folder are never fully synced by Nextcloud which isn't the case. 
As long as .lnk files are not converted to placeholder files, also set them to Excluded to hide the syncing icon.
Closes #5524
Closes #5594
Closes #5825

Set VFS PinState to Excluded for ignored files.

---

src/gui/filedetails/NCInputTextField.qml
src/gui/filedetails/ShareDetailsPage.qml

This PR fix several bugs when it comes to properly resetting the expire date field after modification. It also better notifies users when the value they are providing is invalid due to, for instance, a limit of days on the expire date.

Fix expire date field in Share settings

---

src/gui/iconutils.cpp

As part of `IconUtils::createSvgImageWithCustomColor` we try to see if there is a pre-existing image with the desired colour combination string at a given path. However, we do not check if the file exists and instead try directly to create the image; this creates an unnecessary error when we could just check for the existence of the file at the path. 
`2023-05-09 14:49:16:215 [ warning qt.svg unknown:0 ]:	Cannot open file ':/client/theme/black/share.svg', because: No such file or directory`
This PR adds this file check first, avoiding the error.
Additionally, this PR includes some clean up of the relevant code.

Fix SVG rendering error in SvgImageProvider

---

src/common/filesystembase.cpp
src/gui/generalsettings.cpp
src/gui/generalsettings.ui

Add option to move deleted files to trash instead of permanently deleting them

---

src/gui/generalsettings.cpp
src/gui/updater/sparkleupdater.h
src/gui/updater/sparkleupdater_mac.mm
src/gui/updater/updater.cpp

Our current implementation of the sparkle updater is not optimal. It does not communicate with our Qt GUI at all which leads to things like the update status QLabel in the settings window not being updated, and the "Check for updates" button being permanently disabled. Additionally, our handling of edge cases such as the application not being put in the `Applications` folder is not good
This PR addresses these issues and improves our integration with the updater; it also fixes several internal updater and UI bugs along the way
Fixes #5429

Improve macOS Sparkle updater

---

admin/linux/debian/drone-build.sh

Kinetic is not supported anymore, and Mantic is being developed.

Remove Ubuntu Kinetic, add Mantic

---

src/gui/systray.mm

The code here lacks constness, proper indentation, and uses old property accessing methods in Obj-C -- this can be improved with some basic changes :)

Clean up systray.mm (macOS)

---

admin/linux/debian/drone-build.sh

This is the backport of #5915 to stable-3.9. It did not work with the /backport command.

Remove Kinetic, add Mantic to stable-3.9

---

src/csync/csync.h
src/gui/folder.cpp
src/libsync/discovery.cpp
src/libsync/discoveryphase.cpp
src/libsync/discoveryphase.h
src/libsync/vfs/cfapi/cfapiwrapper.cpp
src/libsync/vfs/cfapi/cfapiwrapper.h
src/libsync/vfs/cfapi/vfs_cfapi.cpp
test/testsynccfapi.cpp

Note that Windows may convert a placeholder file to a regular file when it is replaced by another file, even if the old and new file (inode, modified time, file size) are identical.
Steps to reproduce the the issue:
- Create file "a"
- Create folder "A"
- Copy file "a" to "A"
- Let the client sync the local changes to the server.
- Copy file "a" again to "A" (and let Windows replace the file)
- "A/a" will indefinitely show the syncing icon.

Convert VFS file to placeholder again if needed

---

src/common/filesystembase.cpp
src/common/filesystembase.h
src/libsync/syncengine.cpp
test/syncenginetestutils.cpp
test/syncenginetestutils.h
test/testsyncengine.cpp

This prevents the file metadata changing when it doesn't have to, causing conflicts in certain user applications
Close #5842

Do not modify discovered files on disk if not necessary

---

src/gui/filedetails/ShareDelegate.qml
src/gui/filedetails/ShareDetailsPage.qml
src/gui/filedetails/ShareView.qml
src/gui/filedetails/sharemodel.cpp
src/gui/filedetails/sharemodel.h
src/gui/sharemanager.cpp
src/gui/sharemanager.h
src/gui/sharepermissions.h

Add "Allow resharing" option to share dialog

---

src/libsync/discovery.cpp
test/testsyncengine.cpp

inspired by https://github.com/owncloud/client/pull/6820
Close #5935

on windows file names can always be encoded: fix wrong test

---

src/libsync/discovery.cpp
test/testsyncengine.cpp

Bugfix/fix filename encoding test on windows stable 3.9

---

src/libsync/syncengine.cpp
test/testlockfile.cpp
test/testsynccfapi.cpp
test/testsyncvirtualfiles.cpp

update read-only status of virtual files when needed for lock state

---

src/gui/filedetails/ShareDetailsPage.qml

Hide password field in share settings when share type does not support passwords

---

src/gui/filedetails/ShareView.qml
src/gui/filedetails/sharemodel.cpp
src/gui/filedetails/sharemodel.h

Generate a suggested password when server requires password for share creation

---

src/gui/filedetails/FileDetailsPage.qml
src/gui/filedetails/FileDetailsView.qml
src/gui/filedetails/NCTabButton.qml
src/gui/filedetails/ShareDelegate.qml
src/gui/filedetails/ShareDetailsPage.qml
src/gui/filedetails/ShareView.qml
src/gui/tray/Window.qml

Make file details tray follow current account accent colour

---

src/gui/accountsettings.cpp

The current message always says to wait until sync is done, even if sync *is* done

Fix user-facing message about why encryption cannot yet be done

---

src/libsync/logger.cpp

do not force a flush every time a log line is added to a file to speed up the logging process

only flush debug log files when closing them

---

src/gui/accountmanager.cpp
src/libsync/account.cpp
src/libsync/account.h

Display correct server colour prior to acquiring server capabilities

---

src/cmd/cmd.cpp

first check status.php for version and then capabilities, only use version string if not empty
this also fixes 'File names containing the character ":" are not supported on this file system.' errors in nextcloudcmd (on Linux): The invalidFilenameRegex was set to a static default in case the server version was not set correctly. As newer versions of nextcloud do not return the version in capabilities but status.php, the server version was empty.
As I did not find a way to fullfil your requirements in my first PR, I created a new one. This one has a commit message with a correct Signed-off line. It also has no other changes as I did not enable the actions in this fork.

fixed detection of server version in cmd client similar to gui client (2nd try, signed off)

---

src/gui/generalsettings.ui

Fix visual bug with folder size confirmation combo box in general settings

---

resources.qrc
src/gui/CMakeLists.txt
src/gui/filedetails/NCInputDateField.qml
src/gui/filedetails/ShareDetailsPage.qml
src/gui/filedetails/datefieldbackend.cpp
src/gui/filedetails/datefieldbackend.h
src/gui/owncloudgui.cpp
test/CMakeLists.txt
test/testdatefieldbackend.cpp

Rather than deal with messy dates and times (and timezones) using JS dates in QML, this PR moves the inner workings of the date input field into a C++ class using QDates, fixing lots of issues on this front.
Fixes #5627
Fixes #5495

Rewrite share expiration date field's date handling, fixing issues

---

src/libsync/logger.cpp

Fixes issues with certain locales being used to create filenames that are incompatible with the filesystem

Use a standardised locale to create log file filenames

---

src/libsync/propagatedownload.cpp

will avoid calling done method multiple times on a signle file item causing a crash via ENFORCE function
Close #5473

once we call done on a sync file item, return is needed

---

src/libsync/discovery.cpp

we want to schedule a new sync attempt if a file is likely to have been unlocked due to timeout expiring on server
but if the timeout is null (equal to 0), there will be no timeout on server and no automated unlocking, so do not schedule a sync every 5 seconds to check for it

do not check every 5 seconds files with infinite timeout (= 0)

---

src/gui/macOS/fileprovidersocketcontroller.cpp

FileProvider: Add missing AccountState State case for notifying account state to extension

---

.github/dependabot.yml

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

Automatically update GitHub Actions

---

src/gui/folderwizard.cpp
src/gui/folderwizard.h

We had originally fixed this for the remote path, but not for the local path. Without this fix the warning is unreadable
Fixes #5852

Fix folder wizard warning color for local path in dark mode

---

CHANGELOG.md
admin/win/nsi/lib/fileassoc.nsh
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Database/NextcloudItemMetadataTable.swift
src/gui/tray/activitylistmodel.cpp
src/libsync/abstractnetworkjob.h
src/libsync/discoveryphase.cpp
test/testpermissions.cpp

I have changed a local variable name from:
```cpp
for (const auto &activ : activities) {
const auto json = activ.toObject();
```
to:
```cpp
for (const auto &activity : activities) {
const auto json = activity.toObject();
```

Fix residual typos found by codespell

---

admin/osx/post_install.sh.cmake

Open Nextcloud after installation on macOS

---

src/libsync/propagateuploadng.cpp

Fix Chunk v2 upload headers

---

src/common/syncjournaldb.cpp
src/libsync/discovery.cpp
src/libsync/discoveryphase.h

A bit of speed improvements for #4424

Optimize CaseConflictRecords search in local DB during the sync.

---

src/gui/filedetails/ShareView.qml

We already generate a new password when the share password dialog is created, so there is really no need to clear the field when it closes. This prevents the field being cleared before the password is sent into the C++ code, leading to no password actually being sent to the server

[stable-3.10] Prevent empty password being passed into share creation

---

src/gui/filedetails/ShareView.qml

We already generate a new password when the share password dialog is created, so there is really no need to clear the field when it closes. This prevents the field being cleared before the password is sent into the C++ code, leading to no password actually being sent to the server
Closes #6081

Prevent empty password being passed into share creation

---

src/libsync/discovery.cpp

Unhide discovery logs for file deleted on the server and for discovered file

---

doc/nextcloudcmd.rst
doc/options-cmd.rst
man/nextcloud.1.rst
man/nextcloudcmd.1.rst

as em-dashes enters the manpages the man pages, did show wrong options and also the sections got lost.
Additionally some more cosmetic cleanup for man pages.

Fix issues on manpages

---

src/common/vfs.h
src/gui/CMakeLists.txt
src/gui/folder.cpp
src/gui/folder.h
src/gui/vfsdownloaderrordialog.cpp
src/gui/vfsdownloaderrordialog.h
src/gui/vfsdownloaderrordialog.ui
src/libsync/vfs/cfapi/hydrationjob.cpp
src/libsync/vfs/cfapi/hydrationjob.h
src/libsync/vfs/cfapi/vfs_cfapi.cpp

For https://github.com/nextcloud/desktop/issues/6132

Show more informative error message when VFS hydration fails. Displaya popup and put an error into activity list. More detailed logs.

---

src/gui/generalsettings.cpp
src/gui/generalsettings.ui
src/gui/networksettings.cpp
src/gui/networksettings.ui
src/libsync/theme.cpp
src/libsync/theme.h

For #5142 
https://github.com/nextcloud/desktop/assets/12224014/d0700c19-8a73-4320-915e-2d50a8e47043
https://github.com/nextcloud/desktop/assets/12224014/0c258384-e7a1-404c-99dd-b219a145cff4

Improve Settings dialog design.

---

cmake/modules/MacOSXBundleInfo.plist.in
shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj

- Mac OS Monterey should be the minimun OS version since Apple stopped supporting anything bellow.

Upgrade to Mac OS 12.0.0.

---

src/libsync/bulkpropagatorjob.cpp
src/libsync/bulkpropagatorjob.h

Fix. Bulk upload. Accumulate sent bytes. Fix negative value in UI.

---

src/gui/tray/notificationhandler.cpp

Basically what the title says. These log lines don't really represent error conditions, so when I did `grep -v info` on my Nextcloud client logs (to try and diagnose an unrelated issue) these lines were basically noise.
I tested both lines of this patch locally.

Don't log notification successes as warnings

---

src/libsync/syncengine.cpp

avoid single file sync to switch to data fingerprint restore sync mode if a data fingerprint has been saved in the database but missed during single file sync

avoid restore algorithm by setting the data fingerprint from sync DB

---

doc/troubleshooting.rst

Fixes #3189 (at least the documentation piece)
A follow-up may be desirable to also add a warning in the user interface when the debug archive is created.

docs(troubleshooting): Add warning about sensitive data in logs

---

.github/workflows/stale.yml

This more closely unifies stale handling of issues tagged as `bugs` with other Nextcloud repos[1], by not closing issues that have merely not yet been fully reviewed while still keeping it easy for bug reports that require additional info from the reporter to auto-close if the reporter fails to provide the necessary additional information.
---
Context:
Currently issues tagged as `bugs` must also be tagged `approved` to not be auto closed within 4 weeks in this repo.
Realistically issues are not always able to be triaged for basic validity that quickly or tagging as `approved` is overlooked. Additionally, follow-up info is routinely needed/requested, so tagging as `approved` is inappropriate.
This PR limits the auto-closing of `bugs` to only those tagged as `needs info`. Otherwise it's …

Update stale.yml: Unify "needs info" handling with other NC repos

---

src/gui/folder.cpp
src/gui/folderman.cpp

Backport of https://github.com/nextcloud/desktop/pull/6223

[stable-3.10] Bugfix/vfs toggle fix

---

src/gui/updater/sparkleupdater_mac.mm

Otherwise we can't tell why things are failing by default

Change logging for sparkle update to qCInfo

---

src/libsync/bulkpropagatorjob.cpp
src/libsync/propagateupload.cpp
src/libsync/propagateuploadng.cpp
src/libsync/propagateuploadv1.cpp
src/libsync/syncfileitem.cpp
src/libsync/syncfileitem.h

currently unlock can happen during the sync
in that case, it may be possible that the propagator will lose the lock state changes and override them when updating teh etag after a file has been uploaded
detect that case and ensure we keep consistent state about files

maintain lock state if unlock happens during sync

---

src/libsync/discovery.cpp

Feature. Do not allow move of external storage mounted folders.

---

src/libsync/discovery.cpp

Backport of https://github.com/nextcloud/desktop/pull/6264

[stable-3.10] Feature. Do not allow move of external storage mounted folders.

---

src/gui/tray/TrayFoldersMenuButton.qml
src/gui/tray/Window.qml
theme/Style/Style.qml

Fix https://github.com/nextcloud/desktop/issues/6290

Bugfix. Fix incorrect size of the folderbutton size and scaling.

---

src/libsync/discovery.cpp
test/testsynccfapi.cpp
test/testsyncengine.cpp

Will probably fix https://github.com/nextcloud/desktop/issues/6272

Bugfix. Do not treat item type change as metadata update.

---

src/common/utility.cpp
src/common/utility.h
test/testutility.cpp

Sort of reverts https://github.com/nextcloud/desktop/commit/9004fd6d11326f4a0d851f1ad27ffcab7bcf3f0d

Display terabyte again

---

doc/conffile.rst
src/gui/wizard/owncloudsetuppage.cpp
src/gui/wizard/owncloudsetuppage.h
src/gui/wizard/owncloudwizard.cpp
src/gui/wizard/owncloudwizard.h
src/libsync/configfile.cpp
src/libsync/configfile.h
src/libsync/networkjobs.cpp
src/libsync/networkjobs.h

This patch allows a user to set the config variable:
forceLoginV2=true
This will make the client use the browser login flow instead of the webview. This is useful for making the user experience equal on Windows, Linux and Mac. Currently only Macs use the v2 flow and it was only possible to get this behaviour in the Windows and Linux clients at build time using a CMAKE flag.
The default behaviour is kept the same, and nothing changes for the user unless the flag is manually set in the config file. A setter is included in this patch, although it is not yet used in the GUI.

GUI/LIBSYNC: force login flow V2 with config setting

---

shell_integration/libcloudproviders/CMakeLists.txt

Only install the .ini if the target version doen't support the .desktop file declaration.
Closes: #6218

Avoid duplicate declarations with latest libcloudproviders

---

src/libsync/clientstatusreportingnetwork.cpp
test/testclientstatusreporting.cpp

Spell-correction for e2e_errors

---

CMakeLists.txt

globally enable use of the xcode hardened runtime

---

src/gui/accountmanager.cpp

- It was being displayed even on a fresh install:
- We are already displaying a notification when there are accounts to be imported and we ask the user on what to do.
fixes #6380

Fix: remove failure to import legacy account notification.

---

admin/linux/debian/drone-build.sh

This patch removes support for Ubuntu Lunar, which is not supported anymore, and adds Noble, the next release.

Remove Ubuntu Lunar, add Noble

---

src/CMakeLists.txt
src/libsync/CMakeLists.txt
src/libsync/configfile.cpp

partial build fix when TOKEN_AUTH_ONLY is enabled at configure time

---

src/gui/systray.cpp
src/gui/systray.h

This PR simplifies the calculation of safe spaces for the tray window to be positioned in by using Qt's inbuilt available screen geometries, rather than us trying to manually calculate the taskbar geometry
Requires testing on Linux and Windows

Simplify window positioning compute, more flexibly handle different available geometries

---

.github/workflows/linux-clang-compile-tests.yml
.github/workflows/linux-gcc-compile-tests.yml

partial move of some checks done with drone to github actions

---

src/libsync/networkjobs.cpp

I caught a random crash caused by my changes in https://github.com/nextcloud/desktop/pull/6336. This needs to be released in RC2 too.

Bugfix. Random crash in LsColJob after recent changes.

---

src/libsync/encryptedfoldermetadatahandler.cpp
src/libsync/updatee2eefolderusersmetadatajob.cpp

fix(i18n): uppercase ID

---

src/libsync/clientsideencryption.cpp

is needed to avoid failing builds due to warnings
unclear when we will tackle the work of removing the use of deprectaed APIs

suppress deprecated warnings from openssl

---

.swift-format.json
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Database/NextcloudFilesDatabaseManager+Directories.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Database/NextcloudFilesDatabaseManager+LocalFiles.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Database/NextcloudFilesDatabaseManager.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Database/NextcloudItemMetadataTable+NKFile.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Database/NextcloudItemMetadataTable.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Extensions/Logger+Extensions.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Extensions/NKError+Extensions.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Extensions/Progress+Extensions.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderEnumerator+SyncEngine.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderEnumerator.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension+ClientInterface.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension+Thumbnailing.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderItem.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderMaterialisedEnumerationObserver.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderSocketLineProcessor.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/LocalFilesUtils.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/NextcloudAccount.swift

Swift-format FileProviderExt

---

src/gui/connectionvalidator.cpp

I overlooked this in my PR #6405 
I was getting empty systray messages when there was no error.

Do not create systray notification if there are no errors.

---

doc/conffile.rst

Came up while working on #6222 and nextcloud/documentation#11295.
Updates the documented defaults to match the latest code.

docs(conffile) Update chunk sizes to match v2 chunking PR defaults

---

src/gui/folderman.cpp

Also includes some nice clean ups

Fix undefined sync status reporting in tray icon

---

src/gui/filedetails/ShareDelegate.qml
src/gui/filedetails/ShareDetailsPage.qml
src/gui/filedetails/ShareeSearchField.qml
src/gui/filedetails/sharemodel.cpp

clean up some qml code for share dialog

---

src/gui/generalsettings.ui

Settings dialog. Nextcloud version label should be visible even if auto-updates are turned off in config.

---

src/gui/caseclashfilenamedialog.cpp

Similar, to how we had an issue with `.lnk` files (https://doc.qt.io/qt-6/qfileinfo.html#symbolic-links-and-shortcuts) on Windows with VFS mode on, we now have a freeze when trying to get mime-type for a non-hydrated(online-only) file in CaseClash conflict resolution dialog. This PR switches to using a Windows API-specific function to get the mime-type (same result as with QMimeDatabase() but without causing a freeze on placeholder files).

Use 'FindMimeFromData' from Win API instead of QMimeDatabase() functions to get the mimetype. Prevents freeze from VFS placeholders.

---

src/libsync/foldermetadata.cpp

This one is a fix for https://github.com/nextcloud/desktop/issues/6452

E2EE. Allow decryption v1.0 and v1.1 folders.

---

src/gui/tray/activitylistmodel.cpp
test/activitylistmodeltestutils.cpp
test/testactivitylistmodel.cpp

Bugfix. Federated share activity show 'Decline' action button.

---

src/libsync/syncengine.cpp
src/libsync/syncfilestatustracker.cpp
src/libsync/syncfilestatustracker.h
test/testsyncfilestatustracker.cpp

Bugfix. Exclude list. Fix stuck 'excluded' status in Windows Explorer after removing the exclude pattern.

---

src/libsync/discovery.cpp
src/libsync/discoveryphase.cpp
src/libsync/discoveryphase.h
src/libsync/propagatorjobs.cpp
test/testsyncmove.cpp

Prevent double MOVE instructions for a single file by fixing one place that forgot to track such MOVE instructions
add an automated test to reproduce teh error scenario
add a fix for the wrong behavior
to prevent the issue from coming back also add an assert ensuring a moved file exists
Close #6462

when moving a file, checks that it exists at origin or destination

---

resources.qrc
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderConfig.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderEnumerator+SyncEngine.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderEnumerator.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Services/ClientCommunicationProtocol.h
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Services/ClientCommunicationService.swift
shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj
src/gui/macOS/fileprovider.h
src/gui/macOS/fileprovider_mac.mm
src/gui/macOS/fileprovidersettingscontroller.h
src/gui/macOS/fileprovidersettingscontroller_mac.mm
src/gui/macOS/fileproviderxpc.h
src/gui/macOS/fileproviderxpc_mac.mm
src/gui/macOS/ui/FileProviderFastEnumerationSettings.qml
src/gui/macOS/ui/FileProviderSettings.qml
theme/Style/Style.qml

Add option to perform fast synchronisation runs in File Provider sync engine

---

shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderItem.swift
src/gui/macOS/fileprovidersettingscontroller.h
src/gui/macOS/fileprovidersettingscontroller_mac.mm
src/gui/macOS/ui/FileProviderEvictionDialog.qml
src/gui/macOS/ui/FileProviderFileDelegate.qml
src/gui/macOS/ui/FileProviderStorageInfo.qml
theme/Style/Style.qml

Adds an "evict local items" button in the storage section of the file provider settings and allows users to remove local copies of items to free up space

Enable eviction of materialised copies of virtual files in File Provider (macOS)

---

src/gui/CMakeLists.txt
src/gui/socketapi/socketapi.cpp

This is necessary in Wayland sessions for the clipboard related actions of the socketapi to work. Indeed, QClipboard does its job only if we got a window with the focus in such session.
In the case of the socketapi, it is generally the file manager asking the desktop client to put something in the clipboard. At this point in time no window of the client have the focus, so nothing gets added to the clipboard.
KSystemClipboard on the other hand, uses the wlr data control protocol under wayland sessions ensuring something ends up in the clipboard as expected. When not in a wayland session it falls back to QClipboard so no behavior is lost.

[socketapi] Replace QClipboard with KSystemClipboard when available

---

src/libsync/owncloudpropagator.cpp

always store newly created folders in DB even if it is missing

---

.drone.yml
.github/workflows/linux-clang-compile-tests.yml
.github/workflows/linux-gcc-compile-tests.yml
.github/workflows/sonarcloud.yml
CMakeLists.txt
admin/linux/build-appimage.sh
src/common/filesystembase.h
src/libsync/CMakeLists.txt
src/libsync/filesystem.cpp
src/libsync/filesystem.h
src/libsync/owncloudpropagator.cpp
src/libsync/propagatedownload.cpp
src/libsync/propagatedownload.h
src/libsync/propagatorjobs.cpp
test/syncenginetestutils.cpp
test/testpermissions.cpp
test/testsyncengine.cpp

newly created folders will be read-only when needed

---

src/libsync/foldermetadata.cpp

Bugfix. E2EE. Use 'double' for legacy metadata.

---

.github/workflows/linux-clang-compile-tests.yml
.github/workflows/linux-gcc-compile-tests.yml
.github/workflows/sonarcloud.yml
src/gui/accountstate.cpp
src/gui/connectionvalidator.cpp
src/gui/connectionvalidator.h

only display changed network errors during validation of connection

---

src/libsync/propagatedownload.cpp

Bugfix. Files-lock. Incorrect readonly state for TokenLock.

---

src/gui/application.cpp
src/gui/remotewipe.cpp

allow wipe feature to delete data of a wiped user account

---

src/common/utility.cpp
src/common/utility.h
src/gui/filedetails/sharemodel.cpp
src/gui/folderman.cpp
src/gui/sharemanager.cpp
src/gui/sharemanager.h
src/gui/socketapi/socketapi.cpp
src/libsync/basepropagateremotedeleteencrypted.cpp
src/libsync/discovery.cpp
src/libsync/discoveryphase.cpp
src/libsync/discoveryphase.h
src/libsync/encryptedfoldermetadatahandler.cpp
src/libsync/encryptedfoldermetadatahandler.h
src/libsync/encryptfolderjob.cpp
src/libsync/foldermetadata.cpp
src/libsync/foldermetadata.h
src/libsync/propagatedownloadencrypted.cpp
src/libsync/propagateuploadencrypted.cpp
src/libsync/updatee2eefoldermetadatajob.cpp
src/libsync/updatee2eefolderusersmetadatajob.cpp
src/libsync/updatee2eefolderusersmetadatajob.h
src/libsync/updatemigratede2eemetadatajob.cpp
src/libsync/updatemigratede2eemetadatajob.h
src/libsync/vfs/cfapi/hydrationjob.cpp
src/libsync/vfs/cfapi/hydrationjob.h
src/libsync/vfs/cfapi/vfs_cfapi.cpp
test/testclientsideencryptionv2.cpp
test/testsecurefiledrop.cpp

E2EE. Fix root metadata fetching path for non-root remote sync folder. Refactoring. Stabilizing paths.

---

shell_integration/windows/NCContextMenu/NCClientInterface.cpp
src/gui/socketapi/socketapi.cpp

may need the user to wait a bit longer but should prevent missing the context menu
should still be robust since we only wait indefinitely if desktop client sent a first reply

if desktop client sent a first reply: wait for the menu data

---

src/gui/connectionvalidator.cpp

Addressing @jancborchardt's https://github.com/nextcloud/server/pull/43281#pullrequestreview-1905819693 comment.

User 'Connection issue' instead of 'Network error' in systray notification

---

doc/conffile.rst

The default was changed to false in #1201
https://github.com/nextcloud/desktop/blob/0071daad61916a57fc8cd6d76002f121a0134a9d/src/libsync/configfile.cpp#L1020

fix(docs): parameter promptDeleteAllFiles defaults to false not true

---

src/libsync/configfile.cpp

use the proper name when reading system exclude config file

---

src/common/vfs.h
src/gui/socketapi/socketapi.cpp
src/libsync/discovery.cpp
src/libsync/vfs/cfapi/vfs_cfapi.cpp
src/libsync/vfs/cfapi/vfs_cfapi.h
src/libsync/vfs/suffix/vfs_suffix.cpp
src/libsync/vfs/suffix/vfs_suffix.h
src/libsync/vfs/xattr/vfs_xattr.cpp
src/libsync/vfs/xattr/vfs_xattr.h
test/testsynccfapi.cpp
test/testsyncvirtualfiles.cpp
test/testsyncxattr.cpp

context menu: do not recursively check pin and availability states

---

src/libsync/filesystem.cpp
src/libsync/filesystem.h
src/libsync/owncloudpropagator.cpp
src/libsync/propagatedownload.cpp
src/libsync/propagatedownload.h
src/libsync/propagatorjobs.cpp
test/syncenginetestutils.cpp
test/testpermissions.cpp

std::filesystem is not supported on macOS under 10.15

Fix macOS legacy build breakage caused by std::filesystem

---

.github/workflows/macos-build-and-test.yml
.github/workflows/windows-build-and-test.yml
craftmaster.ini

fix windows and macOS ci checks

---

src/gui/folder.cpp
src/gui/folderwatcher.cpp
src/gui/folderwatcher.h
src/libsync/filesystem.cpp
src/libsync/filesystem.h
src/libsync/syncengine.cpp
src/libsync/syncengine.h
test/testfolderwatcher.cpp
test/testlockfile.cpp

Feature/office files lock newly created. Plus refactoring.

---

admin/win/msi/Nextcloud.wxs

creating the registry keys via installer for the current user is not enough to have the feature enabled for all user accounts on a given machine

create registry keys needed for edit locally in local machine category

---

src/common/vfs.h
src/csync/csync.h
src/gui/folder.cpp
src/libsync/discovery.cpp
src/libsync/owncloudpropagator.cpp
src/libsync/owncloudpropagator.h
src/libsync/progressdispatcher.cpp
src/libsync/vfs/cfapi/cfapiwrapper.cpp
src/libsync/vfs/cfapi/cfapiwrapper.h
src/libsync/vfs/cfapi/vfs_cfapi.cpp
src/libsync/vfs/cfapi/vfs_cfapi.h
src/libsync/vfs/suffix/vfs_suffix.h
src/libsync/vfs/xattr/vfs_xattr.h

some software (at least outlook native software) may fiddle with CfApi placeholder metadata and set a .msg file to be out of sync state when opening it
in that case, we will let the sync engine go over it and decide what to do
it is then possible in that case that we would just put it back in "in sync" state

if a virtual file change but nothing changed: set it as in sync

---

src/libsync/discovery.cpp

do not cause implicit hydration of virtual files during sync

---

src/gui/folder.cpp
src/gui/folderwatcher.cpp
src/gui/folderwatcher.h
src/libsync/filesystem.cpp
src/libsync/filesystem.h
src/libsync/syncengine.cpp
src/libsync/syncengine.h
test/testfolderwatcher.cpp
test/testlockfile.cpp

[stable-3.12] Detect office files for locking on new upload. Notify FolderWatcher.

---

src/libsync/discovery.cpp

invalid item name warning: use file or folder when appropriate

---

src/common/utility_mac.mm
src/gui/CMakeLists.txt
src/gui/accountsettings.cpp

Fixes several broken things caused by Qt6 transition

Fix macOS build on master

---

test/CMakeLists.txt

skip tests currently broken on macOS: enable mandatory tests for macOS

---

test/testlocaldiscovery.cpp

fix one automated test knowing the platform limitations of windows

some files just cannot sync on windows: get automated tests to work

---

src/gui/macOS/fileprovidersocketcontroller.cpp

Censor account details string in file provider logging

---

src/libsync/syncfileitem.cpp

Fix incorrect date parsing.

---

src/libsync/syncfileitem.cpp

you cannot call non const method on a temp const QString

---

src/gui/socketapi/socketapi.cpp

Fixes: #5460 
**Reviewers' test is needed.**

Replace "Edit" with "Open in browser"

---

doc/conffile.rst

Fix white space that broke render of rst table on github

fix doc configuration file

---

src/gui/filedetails/NCInputTextEdit.qml

Fixes text colour for `NCInputTextEdit` in dark mode
After fix:
Before fix:

Fix text colour for NCInputTextEdit

---

src/libsync/discovery.cpp

will ensure we do not erroneously use this instruction when we should not

only use VFS update instruction when sync engine would do nothing

---

src/gui/accountmanager.cpp
src/gui/accountmanager.h
src/gui/accountstate.cpp
src/gui/accountstate.h
src/gui/macOS/fileproviderdomainmanager_mac.mm
src/libsync/account.h

Fix crash when updating enabled File Provider domains (macOS VFS)

---

src/libsync/propagatedownload.cpp
src/libsync/vfs/cfapi/cfapiwrapper.cpp

Backport of PR https://github.com/nextcloud/desktop/pull/6846

[stable-3.12] Add cfapi debug logs

---

src/libsync/discovery.cpp
src/libsync/propagateremotedelete.cpp
test/testsyncvirtualfiles.cpp

Preventing their deletion is a more confusing and counterintuitive behaviour

Allow deletion of virtual suffix placeholder files

---

src/cmd/cmd.cpp
src/gui/folder.cpp
src/libsync/syncengine.cpp
src/libsync/syncoptions.cpp
src/libsync/syncoptions.h
test/testsyncengine.cpp

- Fix for https://github.com/nextcloud/desktop/issues/3144
- Makes warning more concise:
- warning when deleting all files in the server
- before: 
- after:
- warning when deleting all local files
- before: 
- after:

Bugfix nextcloudcmd when syncing results in deleting all files

---

src/gui/filedetails/sharemodel.cpp

Fix sharePath for virtual paths using suffix vfs mode

---

src/libsync/vfs/cfapi/cfapiwrapper.cpp

with those logs, hydrating is causing too much log to be written and after some time (with big fixles), hydration is failing

avoid logs too verbose and with binary data

---

src/libsync/vfs/cfapi/cfapiwrapper.cpp

our current infrastructure will cause a deadlock for any hydration requests coming from desktop files client itself
the main thread is responsible for executing the hydration request but if the same thread is already blocked waiting for the hydration to happen, both (open system call and hydration request handling) process will never be completed and wait for each over in a stuck cycle

avoid deadlock: cancel hydration requests coming from itself

---

src/libsync/vfs/cfapi/cfapiwrapper.cpp

Backport of PR https://github.com/nextcloud/desktop/pull/6868

[stable-3.12] avoid deadlock: cancel hydration requests coming from itself

---

src/gui/owncloudsetupwizard.cpp
src/libsync/abstractnetworkjob.cpp
src/libsync/account.cpp
src/libsync/networkjobs.cpp

- I am trying to solve this: the client was complaining about invalid certificates even though the certificate was valid with
"The host name did not match any of the valid hosts for this certificate"
- I only could reproduce what was reported with stable-3.13 and Qt 5 on Linux.
- We might have hit a Qt5 bug, but I couldn't find reports. 
- The issue was gone once the setting of ssl options were removed in https://github.com/nextcloud/desktop/commit/52996774b588b3bba9d99d9d18a3e7c41a421a33.

Fix "The host name did not match any of the valid hosts for this certificate" notification even when the certificate was valid

---

src/libsync/discovery.cpp
test/testsyncmove.cpp

- The rename check was not happening since since it was hitting "Move without permission to rename base file"
- The file was then processed as a new file
Possible workaround for #6549 and [#4958](https://github.com/nextcloud/desktop/issues/4958)
- This fix was the hint for me: #6535

Check if sync item is actually a folder before processing it

---

src/gui/macOS/fileproviderxpc_mac.mm

Don't wait forever for the file provider extension to reply to the client's request, time out after 3 seconds

Fix permanent freeze upon opening macOS VFS settings

---

admin/linux/debian/drone-build.sh

Two optimizations are implemented:
- the initial version setup is done using a configuration on the first distribution-specific branch to check fewer log entries
- the Debian packages are uploaded into a single package on the OpenSUSE Build Service, so the source archive needs to be uploaded only once (among other benefits)
If you approve, please, also merge the commit, as some of the checks seem to fail due to reasons not under my control, and I have no permissions to merge in such a case.

Optimize Ubuntu/Debian build

---

.github/workflows/macos-build-and-test.yml

Build file provider module in CI runs

---

admin/osx/mac-crafter/Sources/main.swift

Add additional options to make cross-compiling client feasible with Mac Crafter

---

src/gui/macOS/ui/FileProviderFastEnumerationSettings.qml
src/gui/macOS/ui/FileProviderSettings.qml

Stop them filling the entire container width, as this makes what looks like whitespace clickable

Fix clickable area of macOS VFS settings checkboxes

---

.github/workflows/clang-tidy-review.yml

* Fix cmake command line for qt6 (as already has been done for other CI tests)
* Switch to the ci-client-qt6 image for consistency with other tests and to eliminate package install step
Let's see how the CI run likes it in the first pass...

ci(clang-tidy-review): Fix for qt6 + swap to docker-ci container

---

src/gui/CMakeLists.txt
src/gui/application.cpp
src/gui/cocoainitializer_mac.mm
src/gui/editlocallyjob.cpp
src/gui/editlocallyjob.h
src/gui/editlocallymanager.cpp
src/gui/editlocallymanager.h
src/gui/editlocallyverificationjob.cpp
src/gui/editlocallyverificationjob.h
src/gui/macOS/fileprovider.h
src/gui/macOS/fileprovider_mac.mm
src/gui/macOS/fileproviderdomainmanager.h
src/gui/macOS/fileproviderdomainmanager_mac.mm
src/gui/macOS/fileprovidereditlocallyjob.cpp
src/gui/macOS/fileprovidereditlocallyjob.h
src/gui/macOS/fileprovidereditlocallyjob_mac.mm

Add Edit Locally support to macOS virtual files module

---

shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension+ClientInterface.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension+EnumerationListener.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension.swift
shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj
src/gui/application.cpp
src/gui/application.h
src/gui/macOS/fileprovider.h
src/gui/macOS/fileprovider_mac.mm
src/gui/macOS/fileprovidersocketcontroller.cpp
src/gui/macOS/fileprovidersocketcontroller.h
src/gui/macOS/fileprovidersocketserver.cpp
src/gui/macOS/fileprovidersocketserver.h
src/gui/macOS/fileproviderxpc.h
src/gui/macOS/fileproviderxpc_mac.mm
src/gui/owncloudgui.cpp

**DEPENDS ON #6929**
Closes #6899

Reflect File Provider domain sync status in tray icon (macOS VFS)

---

src/libsync/abstractnetworkjob.cpp

forward the redirected signal from QNetworkReply to detect them

---

src/libsync/propagatedownload.cpp

we use the proper method from QByteArray to forward the data received by GETFileJob to the socket connected to teh fetch data CfApi callback
Close https://github.com/nextcloud/desktop/issues/6769

use QByteArray::left to send the newly received data during hydration

---

src/gui/generalsettings.cpp

When adding a new account, the combo box would list each update channels twice.

Make sure to not repeat the update channels list when loading the settings for a second account.

---

src/gui/socketapi/socketapi.cpp

when receiving a shell integration socket command for ENCRYPT, a generic interface and generic code paths was used
the assumption was that the listener socket would need (and remain) valid while hanlding teh request
some code paths need to display error messages to the user via a QMessageBox
the issue is that this will execute a Qt event loop that will handle the socket disconnection while the socket variable from the caller seems it will stay valid and alive
prevent that by not using a blocking method invocation such that life time mishandling about the socket listener is not possible

prevent event loop reentrance when handling ENCRYPT socket requests

---

src/gui/socketapi/socketapi.cpp

Backport of PR https://github.com/nextcloud/desktop/pull/6958

[stable-3.12] prevent event loop reentrance when handling ENCRYPT socket requests

---

src/libsync/abstractnetworkjob.cpp

seems to work around some timers expiring too early

use very coarse timers for network timeout

---

src/gui/accountmanager.cpp
src/gui/application.cpp
src/gui/connectionvalidator.cpp
src/gui/generalsettings.cpp
src/gui/openfilemanager.cpp
src/gui/proxyauthhandler.cpp
src/libsync/accessmanager.cpp
src/libsync/account.cpp
src/libsync/configfile.cpp
src/libsync/creds/httpcredentials.cpp
src/libsync/creds/keychainchunk.h
src/libsync/iconjob.cpp
src/libsync/syncengine.cpp
src/libsync/theme.cpp

we require Qt > 6.0 so any conditionnal code for older releases can be deleted

remove deprecated code only usefull for very old Qt releases

---

src/libsync/accessmanager.cpp

Nextcloud server documentation is recommending enabling http2 for performance resons
https://docs.nextcloud.com/server/latest/admin_manual/installation/server_tuning.html#enable-http-2-for-faster-loading

always enable http2

---

src/gui/PredefinedStatusButton.qml
src/gui/filedetails/FileTag.qml
src/gui/filedetails/NCTabButton.qml
src/gui/tray/ActivityItemActions.qml
src/gui/tray/CallNotificationDialog.qml
src/gui/tray/EditFileLocallyLoadingDialog.qml
src/gui/tray/HeaderButton.qml
src/gui/tray/TrayFolderListItem.qml
src/gui/tray/TrayFoldersMenuButton.qml
src/gui/tray/UnifiedSearchResultListItem.qml
src/gui/tray/UserLine.qml
src/gui/tray/Window.qml
theme/Style/Style.qml

with transparent backgrounds, most of teh time the result is hard to read
that is mostly unintended and unless there is some blur added, the UI becomes unusable
Close https://github.com/nextcloud/desktop/issues/6992

remove most usages of transparent background: fix visual regressions

---

src/gui/sslbutton.cpp

fix(settings): Use broken lock icon when not using https

---

src/gui/shellextensionsserver.cpp

If someone wants cropped thumbnails this can be put behind an option in the settings but I see no use case for this.
Fixes: #6154

Keep aspect ratio for thumbnails

---

.github/ISSUE_TEMPLATE/BUG_REPORT.yml

fix: Update bug reporting package list + misc tweaks

---

.github/ISSUE_TEMPLATE/BUG_REPORT.yml

Fixing my mistake in #7006 with the quotes that broke the form!

fix bug report breakage

---

doc/advancedusage.rst
doc/troubleshooting.rst
doc/wizardaccountsetupcommandline.rst

Fix doc building warnings

---

src/gui/folder.cpp
src/gui/proxyauthhandler.cpp

detected via https://github.com/KDE/clazy/blob/master/docs/checks/README-auto-unexpected-qstringbuilder.md#auto-unexpected-qstringbuilder
also reported by g++ via compile time warnings

avoid wrong usage of QStringBuilder via auto type deduction

---

admin/linux/debian/drone-build.sh
admin/linux/debian/scripts/git2changelog.py

The changes last made to the Ubuntu/Debian build scripts do not work well on the stable branches, as it is not detected properly if we are dealing with a release or not. This patch fixes this problem.

Fix release kind detection

---

CMakeLists.txt
config.h.in
src/CMakeLists.txt
src/gui/CMakeLists.txt
src/gui/creds/webflowcredentialsdialog.cpp
src/gui/creds/webflowcredentialsdialog.h
src/gui/wizard/owncloudwizardcommon.h
src/gui/wizard/webview.cpp
src/libsync/networkjobs.h

properly detect and enable Qt6 WebEngine integration

---

doc/conffile.rst

Since #5698 / #3362 this option is no longer restricted to Linux. (It's also now in the GUI too).

docs: conf file option moveToTrash is no longer Linux specific

---

src/gui/accountsettings.cpp

will omit Encrypt menu item for child fodlers as displayed in selective sync folders tree in settings dialog

only add Encrypt context menu entry for top folder in settings dialog

---

src/csync/vio/csync_vio_local_win.cpp

it seems that there is a possibility for the type detection to report a folder as being a file
with this change, I am pretty sure that cannot happen any longer

ensure detection of entry type on windows is reliable

---

src/libsync/syncfileitem.cpp

This reverts commit 04c0125bd10c3961af11f233f32b0408f0c21401.

Revert "Fix incorrect date parsing."

---

src/libsync/filesystem.cpp

add missing exception handling

---

admin/osx/make_universal.py

Fix make_universal.py not taking into account 64-bit bundle dylibs

---

src/gui/folderman.cpp
src/gui/folderman.h
src/gui/owncloudgui.cpp
src/gui/systray.cpp
src/gui/systray.h
src/libsync/syncengine.h

This pull request adds some more details to the tray icon tooltip text.
There was some unused code that updated some status bar text, so I opted to re-use that.  As of now it displays what the old code did -- the file size to be synced and the estimated time left if applicable.
On my Linux (KDE) system it will display that information per folder:
On Windows it will only display if there is only one folder to be synced.  The tooltip message will roughly look like that (still need to check that it doesn't get truncated):

Add some extra syncing details to the tray icon tooltip

---

admin/osx/mac-crafter/Sources/Utils/Codesign.swift
admin/osx/mac-crafter/Sources/main.swift

Code-sign client via mac-crafter so it may pass notarisation

---

src/gui/tray/notificationhandler.cpp
src/gui/tray/notificationhandler.h

Do this regardless of what the server's response is

Make sure we do not renotify notifications when we have received the same etag as during the last check

---

src/libsync/discovery.cpp
test/testsyncmove.cpp

Backport of PR https://github.com/nextcloud/desktop/pull/7102

[stable-3.12] Bugfix/fix one rename issue

---

mirall.desktop.in

There can only be one instace of the client running
Mark it as such in the .desktop file
This allows desktop environments to adjust their UI accordingly

Mark as single window app

---

src/libsync/discovery.cpp
src/libsync/propagateremotemove.cpp

Backport of PR https://github.com/nextcloud/desktop/pull/6717

[stable-3.12] Bugfix/fix vfs folder state when remote move is forbidden

---

admin/osx/mac-crafter/Sources/Utils/Shell.swift

Correctly kill processes spawned by mac-crafter if mac-crafter quits/is killed/etc

---

admin/osx/mac-crafter/Sources/Utils/Craft.swift
admin/osx/mac-crafter/Sources/Utils/Packaging.swift
admin/osx/mac-crafter/Sources/main.swift

Adds the ability to create a pkg directly from mac crafter

Add packaging capability to Mac Crafter

---

src/libsync/accessmanager.cpp

Revert always enable http2

---

admin/linux/build-appimage.sh

Fix for https://github.com/nextcloud/desktop/issues/7128.
See https://github.com/linuxdeploy/linuxdeploy-plugin-qt/pull/186.

Use version of linuxdeploy-plugin-qt from PR in the project.

---

src/libsync/configfile.cpp
src/libsync/syncoptions.h
test/testuploadreset.cpp

goal is to have better performance and uniform behavior between all files clients

changing default chunk size to 100MB

---

src/libsync/discovery.cpp
test/testlocaldiscovery.cpp
test/testsyncvirtualfiles.cpp

Only check for leading/trailing space for files on Windows.

---

src/common/utility.h

should decrease the cost of their usage when compared to preprocessor conditional directives

use constexpr function for platform detection

---

admin/osx/mac-crafter/Sources/main.swift

Depends on https://github.com/nextcloud/desktop-client-blueprints/pull/18

Add support for the new craft blueprint options relating to override server urls

---

admin/osx/mac-crafter/Sources/Utils/Codesign.swift

Fix QtWebEngineProcess crash on macOS when building with mac-crafter

---

src/libsync/configfile.cpp
src/libsync/configfile.h
src/libsync/syncengine.cpp
src/libsync/syncengine.h

count the files deletion and warn if threshold is exceeded

---

src/common/remotepermissions.cpp
src/gui/tray/usermodel.cpp
src/libsync/cookiejar.cpp
src/libsync/discovery.cpp
src/libsync/discoveryphase.cpp
src/libsync/owncloudpropagator.cpp
src/libsync/syncfileitem.cpp

will make the logs less verbose and improve performance

remove too verbose logs during discovery

---

src/libsync/logger.cpp

category of logs accessed via log context can be null in such a case, strcmp will crash

ensure log context category is valid before reading it

---

src/gui/folderman.cpp

remove extra argument from QString::arg: string has only 1 placeholder

---

src/gui/tray/activitylistmodel.cpp
src/libsync/owncloudpropagator.cpp
src/libsync/syncengine.cpp

making logs more useful using logs collected from complex situations
trying to make them less verbose and more targeted toward useful information (i.e. being able to understand sync issues)

Cleaning logs

---

shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension+ClientInterface.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderSocketLineProcessor.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Services/ClientCommunicationProtocol.h
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Services/ClientCommunicationService.swift
src/gui/macOS/fileprovidersocketcontroller.cpp
src/gui/macOS/fileproviderxpc_mac.mm

Depends on https://github.com/claucambra/NextcloudFileProviderKit/pull/22
Improve the authentication phase of the File Provider Extension by:
* Verifying account details are correct before signalling the extension is ready to perform file operations
* Reattempting authentication check if necessary due to bad connection
* Adding timeouts for said authentication check to prevent server overloading
* Properly using user and userId roles to fix LDAP authentication issues
Fixes #6783

Fix authentication issues for macOS File Provider Extension

---

src/libsync/discovery.cpp

Fix for the core issue behind https://github.com/nextcloud/desktop/pull/7296

Fix poor translation strings for blacklisted error reason strings

---

src/gui/generalsettings.cpp

Make string more readable for translators.

---

src/gui/folder.cpp

improve wordings of confirmation dialog when many files are deleted

---

src/gui/macOS/fileprovidersocketcontroller.cpp

Fix crash caused by null accountstate due to bad domain identifier parsed from FPExt
Turns out since we are forced to replace colons with hyphens we need to replace them back to colons when we receive the domain identifier from the file provider extension. If we do not then we get a null accountState pointer in the socket controller and this causes a crash
Closes #7277

Fix crash caused due to null accountstate in FileProviderSocketController

---

theme/colored/Nextcloud-macOS-sidebar.svg

Fixes https://github.com/nextcloud/desktop/issues/3695
According to the Apple documentation, "template" images must be exclusively ["monochromatic images that are drawn just using black and transparency"](https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/Finder.html), but `desktop/theme/colored/Nextcloud-sidebar.svg` looks like this:
Since this bug popped up without changes in the code or assets in question, my guess is that the current version of Xcode or macOS is being clever and interpreting the white as a color to be inverted, while previously it treated the white as just an opaque transparency mask. This seems to be due to a change in how non-monochrome "template" images are supported with the release of SF Symbols 3. Among other things, SVG …

Fix Finder sidebar icon to work as a "template" image

---

src/gui/CMakeLists.txt
src/gui/foregroundbackground_cocoa.h
src/gui/foregroundbackground_cocoa.mm
src/gui/foregroundbackground_interface.h
src/gui/foregroundbackground_mac.mm
src/gui/owncloudgui.cpp
src/gui/wizard/owncloudwizard.cpp

Branched from #2959.
This pull request adds code to make it so that the onboarding wizard and the settings dialogue both behave like foreground windows on macOS. When either window opens, the application spawns a dock icon and displays a menubar, and when the window is closed, the dock icon despawns, and the menubar is replaced with whatever other application is now in the foreground.
On Linux (or, at least GNOME), this behavior is automatically implemented when the [`Qt::Window` flag](https://doc.qt.io/qt-5/qt.html#WindowType-enum) is used. The behavior is especially important on macOS, because a `Qt::Window` can be maximized, but without a menubar, the application is unable to show the titlebar containing the “stoplight” buttons, so it is very difficult to un-maximize it. (The dock icon …

Show/Hide Menubar and Dock Icon on macOS

---

src/libsync/discovery.cpp
src/libsync/propagateremotemove.cpp

even if local item has disappeared, record the result of a remote MOVE when receiving the reply
enable better state tracking when syncing rename or move operations

on receiving reply of a remote MOVE: always record it

---

src/gui/macOS/fileproviderdomainsyncstatus_mac.mm

This selector was only made available on macOS 11.3. Just to be safe we should check for the availability

Check for availability of Big Sur (under 11.3) before using VFS progress tracking method

---

src/gui/tray/usermodel.cpp
src/gui/tray/usermodel.h

Caused by bad paths not being found locally -- usually double-slashes. Ensure we parse received group folder paths correctly even if the server makes a mistake

Fix opening of locally available groupfolders in web browser from tray drop-down

---

src/gui/filedetails/sharemodel.cpp
src/gui/filedetails/sharemodel.h

Make shares distinguishable if there are sharees with the same display name

---

craftmaster.ini

Pin Craft Qt version to 6.7.2 and binary cache version to 24.08

---

src/gui/accountsettings.cpp
src/gui/accountstate.cpp
src/gui/accountstate.h
src/gui/application.cpp
src/gui/connectionvalidator.cpp
src/gui/connectionvalidator.h
src/gui/folder.cpp
src/gui/owncloudgui.cpp
src/gui/owncloudgui.h
src/libsync/account.h
src/libsync/discoveryphase.cpp

will query the sign state for the terms of service and automatically pause or resume sync

detect the terms of service app is requiring the user to sign them

---

src/gui/accountstate.cpp
src/gui/accountstate.h
src/gui/connectionvalidator.cpp
src/gui/connectionvalidator.h

will trigger a check of the server connectivity in case of content access denied reporting when listing folders during discovery
should allow discovering early that terms of service need to be signed

content access denied error during discovery: verify server access

---

src/gui/accountstate.cpp
src/gui/accountstate.h
src/gui/connectionvalidator.cpp
src/gui/owncloudgui.cpp
src/gui/owncloudgui.h

improve again state tracking with terms of service app

---

src/gui/wizard/owncloudsetuppage.cpp

This matches the mobile clients

Only display server name in multiple override servers dropdown

---

src/gui/accountmanager.cpp
src/gui/accountmanager.h
src/gui/generalsettings.cpp
src/gui/generalsettings.h
src/gui/settingsdialog.cpp
src/libsync/account.cpp
src/libsync/account.h
src/libsync/configfile.cpp

I was just hoping to catch the issue of reports about it - like the channel changing without the user interaction.

Bugfix update channels

---

src/libsync/logger.cpp

Respect the user's debug and expiration settings when changing temporary log dir setting

---

src/gui/macOS/fileproviderxpc.h
src/gui/macOS/fileproviderxpc_mac.mm

Every time we compute the overall sync state we check if the File Provider Extension is reachable so we can display if this has encountered a problem. The issue is that if it is not reachable, we wait 3 seconds to receive a reply, and if we do not, we wait all of those 3 seconds. Now have that happen every single time we need to compute the sync state.
This PR addresses the problem by slashing the wait time down to 1 second and adding a reachability check timeout of 300 seconds, so we will (worst case) encounter a 1 second freeze every 5 minutes instead

Fix stuttering and freezing of client while computing sync state changes (macOS VFS)

---

src/gui/macOS/fileprovidersettingscontroller_mac.mm

Fix materialised storage use calculation (macOS VFS)

---

src/gui/accountmanager.cpp

Prevent error on deletion when the proxy password does not exist

Only present proxy password delete error if it is not a "does not exist" error

---

doc/troubleshooting.rst

Add section on Apple ATS to docs troubleshooting section

---

admin/osx/mac-crafter/Sources/main.swift

Depends on https://github.com/nextcloud/desktop-client-blueprints/pull/21

Add option to create developer builds of client via mac crafter

---

src/gui/owncloudsetupwizard.cpp
src/gui/wizard/owncloudwizard.cpp
src/gui/wizard/owncloudwizard.h

When the wizard window is closed, kill off the account setup wizard instance

Fix closed account wizard being brought up when clicking tray icon

---

src/libsync/filesystem.cpp

Adds an additional null check for `resultDacl` after calling `GetSecurityDescriptorDacl` since the value can be null for FAT32/exFAT file systems.
#7484

Fix crash on setting folder permission on non-NTFS file systems on Windows

---

src/common/utility.h
src/common/utility_win.cpp
src/gui/accountsettings.cpp
src/gui/folderman.cpp
src/gui/folderman.h
src/gui/navigationpanehelper.cpp

- Always remove the folder icon when removing a sync folder from the client.

Always remove folder icon when removing folder.

---

src/gui/iconutils.cpp

makes no sense as I have to always patch it out to be able to run a debug build

remove assert that is being hit always when running debug builds

---

src/gui/filedetails/NCInputTextField.qml
src/gui/filedetails/ShareView.qml
src/gui/filedetails/ShareeSearchField.qml

Fixes following errors:
```
2024-10-21 02:01:40:645 [ warning default qrc:/qml/src/gui/filedetails/ShareeSearchField.qml:53 ]:	qrc:/qml/src/gui/filedetails/ShareeSearchField.qml:53:17: QML QQuickRectangle: The current style does not support customization of this control (property: "background" item: QQuickRectangle(0x600001d42140, parent=0x0, geometry=0,0 0x0)). Please customize a non-native style (such as Basic, Fusion, Material, etc). For more information, see: https://doc.qt.io/qt-6/qtquickcontrols2-customize.html#customization-reference
2024-10-21 02:01:40:645 [ warning default qrc:/qml/src/gui/filedetails/NCInputTextField.qml:57 ]:	qrc:/qml/src/gui/filedetails/NCInputTextField.qml:57:17: QML QQuickRectangle: The current style does not support customization of this control (property: …
```

Fix QML errors caused by illegal customisation of text field backgrounds on native styles

---

src/libsync/theme.cpp

Fixes issues when displaying names of multiple override server urls (e.g. those that contain umlauts)

Fix encoding used for override server url

---

admin/linux/build-appimage.sh

Fix https://github.com/linuxdeploy/linuxdeploy-plugin-qt/pull/186 for Qt6 has been released.

Update url to dowload linuxdeploy-plugin-qt tool latest version.

---

shell_integration/MacOSX/NextcloudIntegration/FinderSyncExt/FinderSync.m
shell_integration/MacOSX/NextcloudIntegration/FinderSyncExt/FinderSyncSocketLineProcessor.m
shell_integration/MacOSX/NextcloudIntegration/FinderSyncExt/SyncClient.h

Fix crash when setting badge for a path that results in a nil URL (macOS FinderSyncExt)

---

src/gui/application.cpp
src/gui/application.h
src/gui/main.cpp
src/gui/networksettings.ui
src/libsync/theme.cpp
src/libsync/theme.h
theme/Style/Style.qml

Revert dark mode regressions on Windows 10

---

admin/osx/mac-crafter/Sources/Utils/Codesign.swift

Ensure paths are passed properly escaped into codesign command in mac-crafter

---

src/gui/macOS/fileproviderxpc_mac.mm

Silly oversight during rebase conflict resolution broke everything, sorry

Add missing brace in FileProviderXPC's fileProviderExtReachable

---

admin/osx/mac-crafter/Sources/Utils/Codesign.swift

Fix codesign path for app bundle main binaries

---

admin/osx/mac-crafter/Sources/Utils/Codesign.swift

Escape code sign entitlement paths in mac crafter

---

src/common/syncjournaldb.cpp
src/common/syncjournalfilerecord.h
src/libsync/discovery.cpp
src/libsync/discoveryphase.cpp
src/libsync/discoveryphase.h
src/libsync/syncfileitem.cpp
src/libsync/syncfileitem.h
test/syncenginetestutils.cpp
test/syncenginetestutils.h
test/testlocaldiscovery.cpp

Live photos uploaded to the server are composed of an image file (usually a .jpeg or a .heic) and a video file (a .mov file), which get presented to the user via the iOS and Web UIs as a single "live photo", like in the Apple Photos applications
To maintain this representation the server treats these image/video pairs as inseparable -- the video cannot be deleted by itself, only a delete of the image will lead to the deletion of the video. This means we cannot issue deletes for the videos, as the server will reject this and we will end up showered in sync errors.
This PR therefore changes the local discovery behaviour to not propagate the local deletion of live photo mov files to the server, and to instead simply re-download the file if it has been deleted

Fix sync errors when trying to delete video component of live photos

---

src/gui/macOS/fileproviderdomainmanager_mac.mm
src/gui/macOS/fileprovidersocketcontroller.cpp
src/gui/macOS/fileproviderxpc_mac.mm

Handle NeedToSignTermsOfService account state in file provider components

---

admin/osx/mac-crafter/Sources/Utils/Codesign.swift

I believe this should be the final step

Fix recursive codesign steps and final bundle codesign in mac-crafter

---

src/gui/filedetails/filedetails.cpp
src/gui/filedetails/filedetails.h
src/gui/filetagmodel.cpp
src/gui/filetagmodel.h
src/gui/folder.h

Fix file tag fetching for files in sync folders that have non-root remote target

---

resources.qrc
src/gui/tray/MainWindow.qml
src/gui/tray/UnifiedSearchPlaceholderView.qml
src/gui/tray/UnifiedSearchResultNothingFound.qml
theme/Style/Style.qml

> [!Important]
> Depends on #7498 
Replaces the activity view when the unified search field is focused

Pull up the unified search view immediately on unified search field focus

---

admin/osx/mac-crafter/Sources/Utils/Codesign.swift
admin/osx/mac-crafter/Sources/Utils/Shell.swift

Fix mac-crafter codesign executable detection

---

src/libsync/logger.cpp
src/libsync/logger.h

should help not loosing too much logs in case of a crash or similar not nominal stop of the client

flush logs every 5 lines written

---

src/libsync/theme.cpp

we initialize all colors in the palette, so this init methos is most probably not doing anything useful
crashes when doing in automated tests

remove this call that is probably useless and crashing tests

---

admin/osx/mac-crafter/Sources/Utils/Codesign.swift
admin/osx/mac-crafter/Sources/main.swift

Fix mac-crafter codesign executable check path building

---

src/gui/filedetails/ShareView.qml
src/gui/filedetails/sharemodel.cpp
src/gui/filedetails/sharemodel.h
src/gui/ocssharejob.cpp
src/gui/tray/usermodel.cpp
src/gui/tray/usermodel.h

Show received share information in share view

---

src/common/filesystembase.cpp
src/gui/tray/activitylistmodel.cpp
src/libsync/discovery.cpp
src/libsync/propagatedownload.cpp
src/libsync/propagatorjobs.cpp
src/libsync/vfs/cfapi/cfapiwrapper.cpp
src/libsync/vfs/cfapi/vfs_cfapi.cpp

Improve read only virtual files support on Windows

---

src/gui/generalsettings.cpp
src/gui/macOS/fileproviderxpc.h
src/gui/macOS/fileproviderxpc_mac.mm
src/gui/macOS/ui/FileProviderSettings.qml

Removes need for users to create the debug logs separately for macOS VFS

Bundle macOS File Provider module logs into main debug archive

---

src/gui/accountmanager.cpp
src/gui/accountmanager.h
src/gui/accountstate.cpp
src/gui/application.cpp
src/gui/application.h
src/gui/owncloudgui.cpp
src/gui/owncloudgui.h
src/gui/owncloudsetupwizard.cpp
src/gui/settingsdialog.cpp
src/gui/tray/TrayFoldersMenuButton.qml
src/libsync/account.cpp
src/libsync/account.h

- when adding account on mac OS and skipping the folder configuration step, it would crash and it would add an empty user as an account.
- the dialog for configuring folder it was never going away once the user would click on skip.

Fix adding account and skipping folder configuration crash.

---

src/gui/UserStatusSelector.qml

fix spelling os UserStatus qml type when setting user status

---

src/gui/folder.cpp

will prevent truncating the modification time when changing the lock state of a file
could be visible when using an office software to open an office file with automated locking happening after the file gets opened

when updating a virtual file after lock/unlock: avoid setting modtime

---

src/gui/ResolveConflictsDialog.qml
src/gui/application.cpp
src/gui/filedetails/FileDetailsWindow.qml
src/gui/macOS/ui/FileProviderEvictionDialog.qml
src/gui/tray/CallNotificationDialog.qml
src/gui/tray/EditFileLocallyLoadingDialog.qml
src/gui/tray/MainWindow.qml

enable reversed locale layout in QML

---

src/gui/userstatusselectormodel.cpp

Changing text strings to correctly import them into Transifex.
Issue #3776.

Fix text strings

---

src/gui/editlocallyjob.cpp
src/gui/editlocallyjob.h
src/gui/folder.cpp
src/gui/socketapi/socketapi.cpp
src/libsync/account.cpp
src/libsync/account.h
src/libsync/lockfilejobs.cpp
src/libsync/lockfilejobs.h
test/testlockfile.cpp

the file being locked may have been changed sinc the client synced it
so the server side file may have a modified etag. In such cases we do not want to lock the file and would rather sync the nex server changes before being able to lock the file
that would ensure that on client side the file being locked is matching teh state of teh file on server side and would prevent inadvertently overriding server changes

when locking a file set If-Match header to ensure etag is correct

---

src/gui/tray/ActivityItemContent.qml
src/gui/tray/activitylistmodel.cpp
src/gui/tray/activitylistmodel.h
test/testactivitylistmodel.cpp

Fixes colouring of activity icons in dark mode as well as in dark/light mode switch
Fixes #7560

gui/tray: Fix activity icon colours

---

src/gui/accountsettings.cpp
src/gui/macOS/ui/FileProviderSettings.qml

After:
https://github.com/user-attachments/assets/19aae083-fbb7-46f0-9835-4ec20206e587
Before:
https://github.com/user-attachments/assets/617f8333-9424-4fc1-8a30-e89c289bd3e2

gui: Remove content margins account settings subsections

---

src/gui/tray/TrayWindowHeader.qml

gui/tray: Ensure colour of featured app icon is consistent with other header buttons

---

doc/macosvfs.rst

Fixes the following entry (should display macOS Virtual Files client)

doc: Rename first header on macos vfs doc entry, fixing title in index

---

admin/osx/mac-crafter/Sources/Utils/Codesign.swift

mac-crafter: Close isExecutable command outpipe file handle after use

---

src/libsync/clientsideencryption.cpp

Backport/7642/stable 3.15

---

src/gui/caseclashfilenamedialog.cpp

Include folders when displaying the local metadata about a conflict.

---

AUTHORS.md

populated via
`git log --format='%aN <%aE>' | LC_ALL=C.UTF-8 sort -uf`
...as a first step before adding/moving to SPDX headers

Add authors file

---

src/libsync/abstractnetworkjob.cpp

Remove assert for when the timestamp is not empty.

---

src/gui/application.cpp

Fixes #7581
The motivation is explained in the issue.
I confirmed that this compiles and runs on my end,
but did not perform any other tests.

Call setDesktopFileName without `.desktop` suffix

---

src/cmd/netrcparser.cpp
test/testnetrcparser.cpp

Fixes: #7177
It seems that the current Tokenizer-implementation splits the netrc tokens on a (string) separator of " \n\t" instead of splitting on any of the whitespace characters which leads to the issue described in #7177.
This implementation splits the content of netrc on any whitespace character using a regex instead, but should otherwise use the same strategy for parsing. I'm not very familiar with C++ (or QT) and does not completely understand the code, so although this solution seems to work for me, I would appreciate a review :slightly_smiling_face: 
Thanks!

Fix .netrc parsing

---

NEXTCLOUD.cmake

keep application name and short name the same or different for the dev and prod build or some migration behaviour will work differently for each build
for example [`Application::setupConfigFile in src/gui/application.cpp:L519`](https://github.com/kaikli/nextcloud-desktop-client/blob/fix-dev-app-name/src/gui/application.cpp#L519):
- prod: `$XDG_DATA_DIR/Nextcloud` -> `$XDG_CONFIG_DIR/Nextcloud`
- dev: `$XDG_DATA_DIR/NextDev` -> `$XDG_CONFIG_DIR/Nextcloud`

fix dev application name to keep a consitant migration behaviour for the dev and prod build

---

src/gui/folder.cpp

ensure proper read write access to root folder and db files

---

src/gui/macOS/ui/FileProviderFileDelegate.qml
src/gui/macOS/ui/FileProviderSettings.qml
src/gui/macOS/ui/FileProviderStorageInfo.qml
src/gui/tray/ActivityList.qml
src/gui/tray/ListItemLineAndSubline.qml
src/gui/tray/NCBusyIndicator.qml
src/gui/tray/UnifiedSearchResultFetchMoreTrigger.qml
src/gui/tray/UnifiedSearchResultItem.qml

gui/tray: Fix colour for secondary text items being too pale

---

src/gui/wizard/flow2authwidget.cpp
src/gui/wizard/flow2authwidget.ui

update runwizard introduction screen

---

src/gui/owncloudgui.cpp

gui/tray: Fix sync state icon showing paused state when using macOS VFS with no standard sync folders

---

.github/ISSUE_TEMPLATE/BUG_REPORT.yml
.github/ISSUE_TEMPLATE/feature.md

github: Implement issue types in issue templates

---

src/gui/accountsettings.cpp
src/libsync/theme.cpp

Avoid converting string to color

---

src/libsync/clientsideencryption.cpp

Close #5989
only support sha1 for depreceted read-only usage
use sha256 for new encrypted write operations

switch client side encryption to use sha256 hash algorithm

---

src/libsync/syncengine.cpp

Accumulating all discovery paths into one string causes major slowdowns: #7377 
This fixes the issue by immediately writing the names out instead of accumulating them. Additionally a check is added to skip the loop entirely if logging is disabled for the given log level.

Log path strings directly instead of accumulating

---

src/gui/tray/CallNotificationDialog.qml

Use the link in the activity's 'links'
Fixes https://github.com/nextcloud/desktop/issues/6147

notifications: Do not assume root activity link is the correct "join call" link

---

src/gui/creds/webflowcredentials.cpp
src/gui/owncloudsetupwizard.cpp

When setting up an account through the wizard for the first time, the credentials are not saved properly.  This requires the user to sign in again after an application restart.
At least for the login flow v2 case, the `WebFlowCredentials` class eventually persists the retrieved credentials, whereas the class used within the wizard (`OCC::Flow2AuthCredsPage`) doesn't.

persist credentials retrieved through the wizard

---

craftmaster.ini

craft: Upgrade to binary cache 25.01

---

src/libsync/syncengine.cpp

only use debug log level for discovery traces to decrease cost

---

shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension+ClientInterface.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension+Thumbnailing.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Locking/LockViewController.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/MetadataProvider.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Sharing/ShareController.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Sharing/ShareOptionsView.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Sharing/ShareTableViewDataSource.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Sharing/ShareViewController.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Sharing/ShareeSuggestionsDataSource.swift
shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj

Adds support for trash enumeration, chunked uploads, etc. in VFS

shell_integration/macOS: Upgrade to NextcloudFileProviderKit 2.0

---

src/libsync/filesystem.cpp

Adds some extra info when throwing exception with setting folder permissions.

---

src/gui/owncloudgui.cpp

gui/tray: Fix defaulting to "problem" state in sync tray icon when using macOS VFS

---

src/libsync/propagatedownload.cpp
src/libsync/propagatedownload.h

that would also cover code paths for virtual files

set the parent folder read/write always when downloading a new file

---

src/common/filesystembase.cpp

fix deletion of .lnk files on Windows with paths containing special characters

---

shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Extensions/NKShare+Extensions.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Sharing/ShareTableItemView.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Sharing/ShareTableViewDataSource.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Sharing/ShareViewController.swift

Closes https://github.com/nextcloud/desktop/issues/6778

shell_integration/macOS: Add ability to share macOS VFS files via internal link shares

---

src/gui/macOS/fileproviderdomainmanager_mac.mm

- Avoid accidentally turning File Provider domain locations into bundles (Closes #7694)
- Fix conversion of sanitised domain identifiers into account identifiers

gui/macOS: Improve/fix illegal File Provider domain handling for macOS VFS

---

shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Locking/LockViewController.swift
shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj

shell_integration/macOS: Do not try to lock macOS VFS file if locking is unavailable on the server

---

shell_integration/nautilus/syncstate.py

Hello,
today I stumbled across issue #3803.
After some testing I found out that the culprit are the two Python classes `MenuExtension_ownCloud` and `SyncStateExtension_ownCloud`. They are defined by the Nextcloud and the ownCloud integration.
If the names are changed to something else, like `MenuExtension_Nextcloud`, then both integrations are working again.
Since you are using the code from the ownCloud integration (https://github.com/owncloud/client-desktop-shell-integration-nautilus), the names of the classes should normally be changed by the `setappname.sh` script. But this name is branded to "Nextcloud" in this repository. This means the "ownCloud" strings in the integration (`syncstate.py`) won't get replaced. So I changed the branding back to "ownCloud" and now the strings are …

fix: Nautilus integration conflicts with ownCloud 

---

src/gui/tray/ActivityItemContent.qml

gui/tray: Prevent talk reply text field being too wide and breaking layout

---

src/libsync/foldermetadata.cpp

Bugfix. E2EE. Always migrate from 1.2 to 2.0, even with nested folders.

---

src/gui/accountmanager.cpp
src/gui/application.cpp
src/gui/folder.h
src/gui/folderman.cpp
src/libsync/configfile.cpp
src/libsync/configfile.h

Bugfix migration from legacy clients.

---

src/gui/ResolveConflictsDialog.qml
theme/Style/Style.qml

Problem:
-With multiple conflicts to fix, sometimes the dialog box would expand beyond the screen in height and could not be resized to a smaller height.
Solution: 
-Adjusted height based on content
-Set more reasonable minimum height
Fixes #7785 #6228

Fix Height for Resolve Conflicts Dialog

---

src/gui/folderman.h
test/CMakeLists.txt
test/syncenginetestutils.h
test/testfolderstatusmodel.cpp

add test skeleton for OCC::FolderStatusModel

---

src/gui/application.cpp

- see https://medium.com/@zrhmz12/how-to-detect-virtual-machines-and-hypervisors-programmatically-in-c-6ac196a38fe2
- todo:

Attempt to detect if client is running in a Vmware to disable graphic acceleration

---

src/gui/tray/CallNotificationDialog.qml

also enforce a non-transparent base background colour (required for Win11)
tested on macOS, Linux, and Win11

fix rounded corners in the call notification

---

resources.qrc
src/gui/filedetails/NCInputTextArea.qml
src/gui/filedetails/NCInputTextEdit.qml
src/gui/filedetails/NCInputTextField.qml
src/gui/filedetails/ShareDelegate.qml
src/gui/filedetails/ShareDetailsPage.qml
src/gui/filedetails/ShareView.qml
src/gui/filedetails/sharemodel.cpp
src/gui/filedetails/sharemodel.h
src/gui/tray/NCBusyIndicator.qml
test/testsharemodel.cpp

This fixes #7847 by using the [`TextArea`](https://doc.qt.io/qt-6/qml-qtquick-controls-textarea.html) QML control instead of the plain [`TextEdit`](https://doc.qt.io/qt-6/qml-qtquick-textedit.html) for share note field; it's already styled properly as it's part of Qt Quick Controls, **and** it allows for a proper placeholder text!
Also fixed some more icons appearing dark in dark mode.
on the Fluent style the text field is larger as well, indicating that it allows for multi-line text entry:
<table>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tbody>
</table>

Fix looks of share note text field

---

src/gui/tray/syncstatussummary.cpp
src/gui/tray/syncstatussummary.h

Provide macOS VFS sync states in tray window GUI

---

src/gui/folder.cpp

Small improvements in Folder.

---

src/gui/folder.cpp

Check if folder exists before deleting sync db and VFS sync root conection.

---

src/gui/macOS/fileproviderdomainmanager.h
src/gui/macOS/fileproviderdomainmanager_mac.mm
src/gui/owncloudsetupwizard.cpp
src/gui/wizard/owncloudadvancedsetuppage.cpp
src/gui/wizard/owncloudadvancedsetuppage.h
src/gui/wizard/owncloudwizard.cpp

* Enables the option to configure (or not configure) the VFS environment for macOS
* Displays macOS VFS-specific info

gui/wizard: Integrate macOS VFS (File Provider) configuration into account wizard

---

src/gui/CMakeLists.txt
src/gui/accountsettings.cpp
src/gui/accountstate.cpp
src/gui/accountstate.h
src/gui/connectionvalidator.cpp
src/gui/owncloudsetupwizard.cpp
src/gui/owncloudsetupwizard.h
src/gui/tray/SyncStatus.qml
src/gui/tray/syncstatussummary.cpp
src/gui/tray/usermodel.cpp
src/gui/tray/usermodel.h
src/gui/wizard/flow2authcredspage.cpp
src/gui/wizard/owncloudadvancedsetuppage.cpp
src/gui/wizard/owncloudadvancedsetuppage.h
src/gui/wizard/owncloudhttpcredspage.cpp
src/gui/wizard/owncloudwizard.cpp
src/gui/wizard/owncloudwizard.h
src/gui/wizard/owncloudwizardcommon.h
src/gui/wizard/termsofservicecheckwidget.cpp
src/gui/wizard/termsofservicecheckwidget.h
src/gui/wizard/termsofservicecheckwidget.ui
src/gui/wizard/termsofservicewizardpage.cpp
src/gui/wizard/termsofservicewizardpage.h
src/gui/wizard/webviewpage.cpp
src/libsync/owncloudpropagator_p.h

improve ToS handling

---

src/libsync/bulkpropagatorjob.cpp
src/libsync/bulkpropagatorjob.h
src/libsync/owncloudpropagator.cpp
test/testsyncengine.cpp

*) first try to upload a batch with the current size
*) 504 errors would divide the current batch size by a factor of 2
*) all errors still put the small files in the blacklist for bulk upload

Remove file from bulk upload black list only when upload succeeded.

---

src/gui/accountsettings.cpp

fixed html formatting on encrypted warning message

---

src/gui/folderstatusmodel.cpp
src/gui/folderstatusmodel.h

otherwise the icons will end up being loaded from the system each time, which on Windows takes quite long (I saw many calls to `shell32.dll!SHDefExtractIcon` during profiling)
Fixes #7372, tested on Win11, Linux, macOS

FolderStatusModel: only create a single QFileIconProvider object

---

src/gui/UserStatusSelector.qml

otherwise the status text won't be set on macOS as the text box never loses its focus
`Qt.StrongFocus` is the default focusPolicy on all platforms except for macOS, there it's `Qt.TabFocus`
the other buttons of the UserStatusSelector don't need that focusPolicy as they do not modify the model from values in the view
see also:
- https://bugreports.qt.io/browse/QTBUG-110295
- https://codebrowser.dev/qt6/qtdeclarative/src/quicktemplates/qquickabstractbutton.cpp.html#_ZN27QQuickAbstractButtonPrivate4initEv

UserStatusSelector: set focusPolicy on accept button

---

src/gui/tray/usermodel.cpp

Corrected the way the plural forms was being handled according to the Qt documentation for better translation:
https://doc.qt.io/qt-6/i18n-source-translation.html
Would fix issue #7887

Added plural forms handling correction to notification message

---

src/gui/tray/usermodel.cpp

chore(i18n): Use correct plural syntax

---

src/gui/generalsettings.ui
src/libsync/theme.cpp

- Update help url to https://docs.nextcloud.com/server/latest/user_manual/en/desktop/index.html
- Remove "for more information" text
- Adjust space
Before
After

Improve UI of settings

---

src/gui/accountsettings.cpp

at least Android doesn't display it for group folders/shares either: https://github.com/nextcloud/android/blob/3f8527ef66f7838d228dd22efffd6a93c918b4f8/app/src/main/java/com/owncloud/android/files/FileMenuFilter.java#L255-L256

do not display encrypt action for external folders

---

.github/workflows/needsinfohelper.yaml

just taking care some small annoyance I noticed during issue triaging, sometimes I'm faster adding the label before the workflow runs through... I hope this works as expected ;-)
- replaces syntax to yaml multi-line, apparently `${{ ... }}` was only needed because the expression starts with a `!`
- since GitHub workflows only have literals for booleans, null, number, and string, we need to use `fromJSON` in order to create an array as per the example given in the docs for `contains`
see also:
- https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idif
- https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#example-matching-an-array-of-strings
- …

don't remove "needs info" label from maintainers

---

doc/envvars.rst
doc/lowdiskspace.rst
src/libsync/owncloudpropagator.cpp

Changed critical free space to 512MB and free space to 1GB. Also updated the relevant documentation with the changes.
Should solve issue #3398

Increased default limit of free space and critical free space

---

src/gui/generalsettings.cpp
src/gui/generalsettings.h
src/gui/generalsettings.ui

Changed the set properties to the designer file and added a way for the remotePollInterval selector to hide in the settings if notify push is available. This is a follow up to #7926

Added hiding remotePollInterval selector in settings if notify push available

---

src/gui/macOS/ui/FileProviderSettings.qml
src/gui/macOS/ui/FileProviderSyncStatus.qml

It's not necessary. Space can be saved by simplifying the text for the button and moving it alongside the sync status item
After changes:

gui/macOS: Remove "advanced settings" section for macOS VFS settings

---

.github/workflows/linux-appimage.yml
craftmaster.ini

update AppImage builds to Qt 6.8.2

---

src/gui/UserStatusSelector.qml
src/gui/tray/TrayWindowHeader.qml

gui/tray: Fix some tray view papercuts

---

src/gui/tray/MainWindow.qml

This reverts commit 0963856a941e85881cc82b254585fc76bf5b3aa0.
turns out it's fine on Sonoma, whereas it breaks on Sequoia (the window now gets stuck below the menubar) -- maybe I'll open up a QTBUG later if I can reproduce this with a minimal example

Revert "gui: do not allow MainWindow to be resized"

---

src/libsync/basepropagateremotedeleteencrypted.cpp
src/libsync/deletejob.cpp
src/libsync/deletejob.h
src/libsync/discovery.cpp
src/libsync/discoveryphase.cpp
src/libsync/discoveryphase.h
src/libsync/propagateremotedelete.cpp
src/libsync/propagateremotedeleteencryptedrootfolder.cpp
src/libsync/syncfileitem.h

make use of the new `x-nc-skip-trashbin` header

---

src/libsync/accessmanager.cpp

always set a user if we got asked for one

---

admin/osx/mac-crafter/Sources/Utils/Packaging.swift
admin/osx/mac-crafter/Sources/main.swift

mac-crafter: Add ability to produce DMGs

---

src/libsync/creds/keychainchunk.cpp

Call deleteLater only when writeJob is not a nullptr.

---

src/gui/macOS/fileproviderdomainmanager.h
src/gui/macOS/fileproviderdomainmanager_mac.mm
src/gui/owncloudsetupwizard.cpp
src/gui/wizard/owncloudadvancedsetuppage.cpp
src/gui/wizard/owncloudadvancedsetuppage.h
src/gui/wizard/owncloudwizard.cpp

[stable-3.16] gui/wizard: Integrate macOS VFS (File Provider) configuration into account wizard

---

src/gui/systray.cpp
src/gui/systray.h
src/gui/tray/CurrentAccountHeaderButton.qml

gui/tray: Hide resume all menu item when no local sync folders are configured

---

src/gui/filedetails/sharemodel.cpp
src/gui/sharemanager.cpp
src/gui/sharemanager.h

Previously the sharing dialog would only include the shares created by the owner, with this change reshares by others will now be included as well.

display reshares in sharing dialog

---

src/gui/macOS/fileprovidersocketcontroller.cpp

gui/macOS: Do not log account detail-related messages that were not sent on dead file provider socket

---

src/libsync/encryptfolderjob.cpp
src/libsync/propagateupload.cpp

will make sure the client internal database keeps proper encryption information

ensure user receiving an encrypted share maintain proper state

---

src/gui/macOS/fileproviderdomainmanager_mac.mm

Do not assume existence of an account for a given domain identifier -- users can modify the config in unexpected ways

gui/macOS: Avoid UB in edge cases where there is no matching accountstate for a domain

---

src/gui/main.cpp

The _Universal_ QML style has a theme that uses the colour scheme from the system.  This can be set by either configuring `qtquickcontrols2.conf` or setting the environment variable `QT_QUICK_CONTROLS_UNIVERSAL_THEME=System`.
Unfortunately, due to [QTBUG-128825], setting the theme in the configuration file/environment variable results in the dark/light mode setting only be set during startup, not during runtime.  Not ideal, but still better than not having a broken dark mode theme at all.
Fixes #7991
[QTBUG-128825]: https://bugreports.qt.io/browse/QTBUG-128825

gui: fix dark mode change on Windows 10 with universal style

---

src/libsync/bulkpropagatorjob.cpp

will fix missing checksum for bulk upload
will ensure consistent behavior between bulk upload, plain old upload and chunked upload

use standard way to find the checkum type and really send it to server

---

src/libsync/bulkpropagatorjob.cpp

`cl` didn't quite like it:
```
error C2445: result type of conditional expression is ambiguous: types 'QByteArray' and 'const char [1]' can be converted to multiple common types
```
just changing the `auto` to `QByteArray` results in the same compile error

fix Windows build

---

src/gui/macOS/fileprovidersocketcontroller.cpp
src/gui/macOS/fileprovidersocketcontroller.h

Fixes crash on account removal

gui/macOS: Do not assume accountState will always be valid in socket controller

---

src/gui/macOS/fileproviderdomainsyncstatus_mac.mm
src/gui/macOS/progressobserver.m

https://github.com/user-attachments/assets/3e5992f1-1e65-46f4-8f7d-561b2c799157

gui/macOS: Fix broken file provider domain progress reporting in settings window

---

src/gui/tray/CurrentAccountHeaderButton.qml

As discussed, it's supposed to be the same colour as the header background indeed.

gui/tray: change the status icon background colour again

---

src/gui/macOS/ui/FileProviderEvictionDialog.qml
src/gui/macOS/ui/FileProviderStorageInfo.qml

gui/macOS: Use less technical language in FileProvider settings views

---

README.md

Problem:
Tried to use instructions in README to set up my own environment, but noticed the cmake option -DCMAKE_INSTALL_PREFIX is in here twice. It did not make sense what the <dependencies> folder was supposed to be replaced with, but in terms of running this from the build directory, the second use of the option "." made more sense.
Removed this and it succeeded.
Solution: 
Remove (invalid) use of cmake option -DCMAKE_INSTALL_PREFIX
Fix small typo :)

Fix Install Instructions

---

CMakeLists.txt
admin/osx/macosx.pkgproj.cmake
cmake/modules/MacOSXBundleInfo.plist.in
craftmaster.ini
shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj

Qt 6.8 now requires macOS 12.0 as per https://doc.qt.io/qt-6.8/macos.html  
for comparison, Qt 6.7 supported 11.0 and newer: https://doc.qt.io/qt-6.7/macos.html
also update the Packages project to refuse to install on anything older than Monterey (12.0)

fix(mac): bump deployment target to 12.0

---

src/gui/tray/activitylistmodel.cpp
src/gui/tray/activitylistmodel.h
src/gui/tray/usermodel.cpp
test/testactivitylistmodel.cpp
test/testsortedactivitylistmodel.cpp

As discussed internally: these are informative notifications without any need/possibility to act on immediately -- if a file is not synced it will be visible from the shell integration anyway.
An eventual follow-up to this change would be to have a dialogue with an overview of all files that were ignored (including the entry in the ignore list that caused a specific file to be ignored).
Closes #6712

fix(gui): remove ignored file notifications from Activity list

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/BUG_REPORT.yml
.github/dependabot.yml
.github/workflows/check-translations.yml
.github/workflows/clang-format.yml
.github/workflows/clang-tidy-review.yml
.github/workflows/linux-appimage.yml
.github/workflows/linux-clang-compile-tests.yml
.github/workflows/linux-gcc-compile-tests.yml
.github/workflows/macos-build-and-test.yml
.github/workflows/needsinfo.yml
.github/workflows/needsinfohelper.yaml
.github/workflows/pr-feedback.yml
.github/workflows/qml-label-check.yml
.github/workflows/sonarcloud.yml
.github/workflows/stale.yml
.github/workflows/windows-build-and-test.yml
LICENSES/AGPL-3.0-or-later.txt
LICENSES/BSD-2-Clause.txt
LICENSES/BSD-3-Clause.txt
LICENSES/GPL-2.0-or-later.txt
LICENSES/LGPL-2.0-or-later.txt
LICENSES/MIT.txt
REUSE.toml

A very very first and basic step of me starting to add reuse compliance by adding the respective SPDX headers. More to come in follow-up PRs
---
* Bad licenses: 0
* Deprecated licenses: 0
* Licenses without file extension: 0
* Missing licenses: 0
* Unused licenses: 0
* Used licenses: BSD-2-Clause, MIT, LGPL-2.0-or-later, BSD-3-Clause, GPL-2.0-or-later, AGPL-3.0-or-later
* Read errors: 0
* Files with copyright information: 847 / 1891
* Files with license information: 150 / 1891

docs(reuse): Add SPDX header and license files

---

src/libsync/propagatorjobs.cpp

we never read the value computed
computing it means a recursive visit of the whole folder hierarchy which could be taking a long time

remove costly availability check that is never used

---

admin/osx/macosx.pkgproj.cmake

fix: move array to correct value in dict

---

src/libsync/owncloudpropagator.cpp
test/testsyncengine.cpp

With the upcoming release of the desktop client (version 3.16.3), the **bulk upload feature will be temporarily disabled**.
We understand that some of you may rely on this feature, and this decision wasn't made lightly. However, we've encountered ongoing technical issues involving the interaction between the client, server, and underlying systems—including network stack and Qt dependencies—that impact the stability of the feature.
In prioritizing a smoother and more reliable experience for all users, we believe it's best to disable bulk upload for now. The overall benefit of the feature does not currently outweigh the potential for disruption.
If you're unable to update to version 3.16.3 right away, we recommend manually disabling the feature on the server side to avoid any issues:
🔧 [How …

disable use of bulk upload for small files

---

src/gui/folder.cpp
test/testsynccfapi.cpp

LibreOffice/Microsoft office might touch the files for unknown reasons,
creating a constant sync state (icon) visible in the parent folder.
This fix excludes PinState changes from a new sync if the trigger
might have been an external application.

fix(PinState): don't trigger sync when file's PinState changed to Unspecified.

---

src/gui/CMakeLists.txt
src/gui/accountsettings.cpp
src/gui/accountsetupfromcommandlinejob.cpp
src/gui/folderman.cpp
src/gui/folderman.h
src/gui/generalsettings.cpp
src/gui/owncloudsetupwizard.cpp

Since NavigationPaneHelper only includes functionality relevant to Windows and its introduction causes compile warnings on other platforms, this PR excludes the NPH from non-Windows builds
The ifdefs that cause warnings on other platforms have been modified to fix them if in the future NavigationPaneHelper is used on other platforms too

Exclude NavigationPaneHelper from non-Windows compile

---

src/gui/accountmanager.cpp
src/gui/accountmanager.h
src/gui/application.cpp
src/gui/connectionvalidator.cpp
src/gui/creds/webflowcredentials.cpp
src/gui/folderman.cpp
src/gui/folderman.h
src/gui/networksettings.cpp
src/gui/owncloudgui.cpp
src/gui/owncloudgui.h
src/gui/owncloudsetupwizard.cpp
src/libsync/account.cpp
src/libsync/account.h
src/libsync/creds/httpcredentials.cpp
test/testpushnotifications.cpp

Use AccountPtr in Account signals instead of raw pointer

---

craftmaster.ini

use specific revision for KDE blueprints that matches the craft cache

---

.github/workflows/macos-build-and-test.yml
.github/workflows/windows-build-and-test.yml
craftmaster.ini

pin Craft revision to a specific commit 

---

src/common/filesystembase.cpp
src/libsync/filesystem.cpp

revert to QFile::remove to remove a single file
still use std::filesystem::remove to remove a single empty folder
QDir::rmdir does not provide any error message when failing to delete a folder

revert to QFile::remove to remove single files

---

src/gui/folder.cpp
src/gui/folder.h
src/gui/invalidfilenamedialog.cpp
src/gui/tray/activitylistmodel.cpp

File names like `"c:blah"` would break the usage of the dialogue, displaying a path like `"c://blah"` instead; whereas file names like `"test:this"` would work.
Apparently `QDir::filePath` checks if the passed file name is an absolute file name using `!QFileInfo::isRelative`, which is the case if the second character in the string is a colon -- probably indicating a drive letter.

fix(gui): handle invalid file name edge case on Windows

---

src/gui/owncloudgui.cpp

fix(gui): Fix set but unused warning in switch statement for sync status compute

---

src/gui/filedetails/ShareeSearchField.qml

Some QtQuick themes don't make it obvious that the search results list is scrollable, leading to a confusing user experience.
With this PR the results list expands to the available space in the window.  In the case the results do not fit the window, a scroll bar will be present as well now.
<table>
<thead>
<tr>
<th>Theme</th>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<th rowspan="2">Universal</th>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<th rowspan="2">FluentWinUI3</th>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>

fix(gui): resize sharee search results list dependent on required space

---

.github/workflows/windows-build-and-test.yml
src/gui/navigationpanehelper.cpp
src/libsync/account.cpp
src/libsync/account.h

Hi,
as mentioned in [#7049 ](https://github.com/nextcloud/desktop/issues/7049), it is not possible to distinguish multiple shortcuts to Nextcloud folders in Windows Explorer when using the same name in the accounts.
I suggest reverting it to the old behavior.
Greetings
Jens

Include server path to windows explorer shortcut

---

src/gui/application.cpp
src/gui/application.h

This reverts commit https://github.com/nextcloud/desktop/commit/a6745bc594ebe388ffadaf6b55fedccce9d0e0d4.
Fix for https://github.com/nextcloud/desktop/issues/8176.

revert: remove duplicated code when copying legacy config to new path.

---

admin/osx/CMakeLists.txt
admin/osx/mac-crafter/Sources/Utils/Codesign.swift
admin/osx/mac-crafter/Sources/main.swift
admin/osx/macosx.entitlements.cmake

We currently do not code-sign the macOS version of the client with any entitlements. This means the system believes we are accessing another application's group container when creating or accessing the sockets we create for Finder and FileProvider integration within the group container, as we do not provide any entitlements — and by extension, the expected app group entitlement corresponding our group container.
This PR addresses this by generating a valid entitlements file which we apply during codesigning steps in mac-crafter

fix(macOS): Fix prompting of user for permission to access "other" apps' data

---

admin/linux/build-appimage.sh

This allows the AppImage build to find and load the experimental VFS plugins, and not crash with:
[ critical plugins /home/user/src/common/vfs.cpp:250 ]: Could not load plugin: not existent or bad metadata "nextclouddevsync_vfs_suffix"
[ fatal default /home/user/src/gui/folderman.cpp:326 ]: Could not load plugin
[1]    72936 IOT instruction (core dumped)  ./nextclouddev-master-x86_64.AppImage
Fixes #7135
Fixes #7194
Fixes #7465

fix(appimage): move VFS plugins to AppDir

---

src/libsync/discovery.cpp
src/libsync/discovery.h
src/libsync/discoveryphase.cpp
src/libsync/discoveryphase.h
src/libsync/propagateupload.cpp
src/libsync/syncengine.cpp
src/libsync/syncfileitem.h
test/syncenginetestutils.cpp
test/syncenginetestutils.h

fix(quota): throw error only for files that exceed the quota.

---

src/gui/accountsettings.cpp
src/gui/accountsettings.h

I am a new user to Nextcloud. I would consider myself a power-user,  but I got totally thrown under a bus by the e2e configuration AND the misleading wording in the UI. Specifically, the UI uses the "enabled", "supported", "activated", "set up", "start", "reset", etc. in an inconsequential, often interchangable way. It's all over the place and makes it really hard to understand what is going on in the UI, as well as in the code itself.
I also noticed the iOS client mixes the verbiage even more, by also using "activated" and "start":
```
"_e2e_settings_"                    = "End-to-end encryption";
"_e2e_settings_start_"              = "Start end-to-end encryption";
"_e2e_settings_activated_"          = "End-to-end encryption activated";
"_e2e_server_disabled_"             = "End-to-end …
```

Improve configuration-related e2ee wording

---

src/libsync/filesystem.cpp
test/testpermissions.cpp

fix(readonly): apply ACL also to files inside read-only folders

---

src/gui/macOS/fileproviderxpc_mac.mm

fix(gui/macOS): Fix default value for File Provider fast sync enablement setting

---

src/common/filesystembase.cpp

we need platform native separators for file paths that will be used in native Windows platform specific APIs

fix(readonly): use native separator in paths before calling windows API

---

shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/DocumentActionViewController.swift

fix(shell_integration/macOS/FileProviderUIExt): Properly mark action as complete when evicting item

---

shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension.swift

fix(shell_integration/macOS/FileProviderExt): Correctly build NSFileProviderErrors

---

src/gui/macOS/fileprovidersettingscontroller_mac.mm

feat(gui/macOS): Present explanatory message after enabling macOS VFS for an account

---

src/gui/macOS/fileprovideritemmetadata_mac.mm

fix(gui/macOS): Add required availability checks around typeAndCreator access for NSFileProviderItem wrapper

---

src/gui/conflictsolver.cpp
src/gui/conflictsolver.h
src/gui/syncconflictsmodel.cpp

A quick one for 3.17 :)
<table>
<thead><tr>
<th>(Legacy) QWidget conflict dialog</th>
<th colspan="2">QML-based conflict dialog</th>
</tr><tr>
<th>single file only</th>
<th>single file</th>
<th>multiple files</th>
</tr></thead><tbody><tr>
<td>
</td><td>
</td><td>
</td></tr></tbody></table>
Fixes #7446

gui: add a "Yes to all" button when resolving multiple conflicts at once

---

shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderConfig.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/FileProviderExtension.swift
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Services/ClientCommunicationProtocol.h
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Services/ClientCommunicationService.swift
src/gui/macOS/fileprovidersettingscontroller.h
src/gui/macOS/fileprovidersettingscontroller_mac.mm
src/gui/macOS/fileproviderxpc.h
src/gui/macOS/fileproviderxpc_mac.mm
src/gui/macOS/ui/FileProviderSettings.qml

feat(shell_integration/macOS/FileProviderExt): Add option to disable deletion of items in Trash

---

.github/workflows/macos-build-and-test.yml

fix(ci): Upgrade macOS actions to Sequoia and Xcode 16.2

---

src/libsync/discovery.cpp

if we did not query the server info, we have no quota info so do not prevent upload because of no quota info available

fix(quota): do not prevent upload when quota info are not available

---

admin/osx/mac-crafter/Sources/Utils/Codesign.swift

This step sometimes fails with an error such as: "A timestamp was expected but was not found.".  Any code-signing errors will result in the notarisation step to fail.
Apparently this might be due to intermittent network issues.  Let's just retry codesigning a couple of times in the case it fails ...
See also: https://developer.apple.com/documentation/security/resolving-common-notarization-issues#Include-a-secure-timestamp

feat(mac-crafter): retry code-signing attempts

---

src/gui/main.cpp

Earlier versions of Windows will render each character as a square when DirectWrite is in use.
See also: https://github.com/nextcloud/desktop/issues/8064#issuecomment-2890237591
(passing platform parameters via the command line still seems to work!  tried it with `-platform windows:directwrite` and experienced the same behaviour as before this commit).

fix(gui): disable DirectWrite on Win10 versions before 1809

---

src/common/filesystembase.cpp
src/libsync/propagatorjobs.cpp
test/testpermissions.cpp
test/testsyncengine.cpp

fix(delete): fix move to trash in read-only folders

---

src/common/syncjournaldb.cpp
src/common/syncjournalfilerecord.h
src/libsync/discovery.cpp
src/libsync/discoveryphase.cpp
src/libsync/discoveryphase.h
src/libsync/encryptfolderjob.cpp
src/libsync/foldermetadata.cpp
src/libsync/foldermetadata.h
src/libsync/owncloudpropagator.cpp
src/libsync/propagatedownload.cpp
src/libsync/propagateremotemkdir.cpp
src/libsync/propagateupload.cpp
src/libsync/syncengine.cpp
src/libsync/syncfileitem.cpp
src/libsync/syncfileitem.h
src/libsync/updatemigratede2eemetadatajob.cpp
test/testclientsideencryptionv2.cpp

we may not currently properly store certificate hash for encrypted items and later fails to find which public or private key pairs to use
for now, it is better to remove it and ensure we have a reliable way to handle certificate migration

fix(encryption): remove currently broken certificate hash handling

---

src/common/remotepermissions.cpp
src/common/remotepermissions.h
src/gui/tray/activitydata.cpp
src/libsync/discovery.cpp
test/sharetestutils.cpp
test/syncenginetestutils.cpp
test/testfolderman.cpp
test/testpermissions.cpp
test/testremotediscovery.cpp
test/testsyncengine.cpp
test/testsyncmove.cpp

if Readable permissions is missing, do nto try to download the file
if a file was downlaoded but Readable permission is now missing, remove it

fix(permissions): handle properly CanRead permission from server

---

src/gui/sslerrordialog.cpp
src/libsync/accessmanager.cpp

This commit implements enabling enableStrictTransportSecurityStore and setStrictTransportSecurityEnabled in the AccessManager- provided QNetworkAccessManager.
On first connection, this will make QNetworkAccessManager save the HSTS status of the host in cache if it was enabled by the server. On future connections, this setting is loaded and if the server presents an invalid certificate and the HSTS hint is not expired, the connection fails without showing the dreaded "Cannot connect securely to ..." dialog.
Fix https://github.com/nextcloud/desktop/issues/7166
Replaces https://github.com/nextcloud/desktop/pull/8275
Signed-off-by: François Guerraz <francois@orographic.uk>

fix(gui/SslErrorDialog): implements parsing the Strict-Transport-Security header using QNetworkAccessManager

---

src/gui/folderwizard.cpp

https://doc.qt.io/qt-6/qfiledialog.html#Option-enum
finder currently shows all - there is an option to only show folders

fix(ui): limit sync folder selection to dirs only

---

src/libsync/lockfilejobs.cpp
test/testlockfile.cpp

fix(lockfilejobs): ensure using correct file path

---

admin/win/msi/Nextcloud.wxs

A value of `ReallySuppress` will not display a reboot prompt whenever the `ForceReboot` action was run, or whenever a reboot was scheduled (e.g. by `FilesInUse`).  Apparently this will not reboot the machine on its own either.
`winget` sets this property [in the manifest], and according to reports in issue #5369 this seems to work.
See also: https://learn.microsoft.com/en-us/windows/win32/msi/reboot
[in the manifest]: https://github.com/microsoft/winget-pkgs/blob/0b40904d1480f67d48c6d8e2ac7f27b31aa566c7/manifests/n/Nextcloud/NextcloudDesktop/3.16.5/Nextcloud.NextcloudDesktop.installer.yaml#L16

fix(msi): set the REBOOT property in the MSI

---

src/libsync/propagatedownload.cpp

if a file that uncompresses to a file size under 10 MiB, Qt will allow it
for files with an higher size, they must not have higher compression ratio than what Qt network stack expect
https://doc.qt.io/qt-6/qnetworkrequest.html#setDecompressedSafetyCheckThreshold
we will use a 2 times bigger threshold
Close https://github.com/nextcloud/desktop/issues/7470

fix(get/file): avoid failing to download files under 20 MiB

---

test/testsyncengine.cpp

unfortunately does not cpature the requirements for proper long path handling on Windows
maybe an end-to-end test could capture this requirement

fix(test/sync): add a single sync engine test with long paths

---

src/libsync/vfs/cfapi/cfapiwrapper.cpp

use the dedicated flag from CfApi to prevent self implicit hydration requests
should ensure even more reliable handling of virtual files

fix(windows/virtualFiles): prevent implicit hydration at API level

---

src/gui/tray/activitylistmodel.cpp

the sharing/activity button was supposed to be hidden, but a later change forgot to adapt the variable used for querying the file metadata so it never could determine the e2e-status

fix(activitylistmodel): fix activities for e2ee files

---

src/libsync/owncloudpropagator.cpp

in release builds we would happily try to remove an element from QList with invalid index (-1) if the job is not found
avoid doing this in release builds and keep teh assert in debug builds

fix(crash): debug builds would not try to remove a not found job

---

src/common/remotepermissions.cpp
src/libsync/discovery.cpp
src/libsync/discoveryphase.cpp
test/syncenginetestutils.cpp
test/syncenginetestutils.h
test/testpermissions.cpp
test/testsyncengine.cpp

ensure we use currently existing server API to get the "no download" permission
requires parsing some share-attributes new DAV property

fix(permissions): decode share "no download" permission

---

src/gui/folder.cpp

fix(lockFileJobs): avoid accumulating connections about lock jobs

---

admin/osx/mac-crafter/Sources/Utils/Install.swift
admin/osx/mac-crafter/Sources/main.swift

wget is used but not automatically installed, if missing.

Fix: mac-crafter installs wget on demand.

---

.github/CODEOWNERS

fix(github): Update code owners

---

cmake/modules/MacOSXBundleInfo.plist.in
src/gui/macOS/fileprovidersettingscontroller.h
src/gui/macOS/fileprovidersettingscontroller_mac.mm
src/gui/macOS/fileproviderutils.h
src/gui/macOS/fileproviderutils_mac.mm
src/gui/macOS/ui/FileProviderSettings.qml

feat(macOS): Add button in settings window to fully reset File Provider-based virtual files

---

.github/workflows/macos-build-and-test.yml
.github/workflows/windows-build-and-test.yml
admin/osx/mac-crafter/Sources/main.swift

The fix we needed was merged this week 🎉
https://invent.kde.org/packaging/craftmaster/-/merge_requests/7

ci: switch back to upstream CraftMaster

---

translations/client_en.ts

`en` is used as the fallback/default language for when no specific translation is available.
Newer strings that require a plural form would end up with the source text, which could show up as e.g. `"1 minute(s) ago"` in the GUI.
The translations file for `en` used to be updated via the Transifex bot until February 2020.

fix(l10n): fix plural forms in source language

---

admin/osx/mac-crafter/Sources/Commands/Codesign.swift
admin/osx/mac-crafter/Sources/Commands/CreateDMG.swift
admin/osx/mac-crafter/Sources/Commands/Package.swift

For some reason using `ParsableCommand` structs as subcommands of an `AsyncParsableCommand` does not correctly handle all passed CLI arguments.
The behaviour before this commit was as follows:
```
% mac-crafter create-dmg
Error: Missing expected argument '<app-bundle-path>'
Help:  <app-bundle-path>  Path to the desktop client app bundle.
Usage: mac-crafter create-dmg <app-bundle-path> [--product-path <product-path>] [--build-path <build-path>] [--app-name <app-name>] [--apple-id <apple-id>] [--apple-password <apple-password>] [--apple-team-id <apple-team-id>] [--package-signing-id <package-signing-id>] [--sparkle-package-sign-key <sparkle-package-sign-key>]
See 'mac-crafter create-dmg --help' for more information.
% mac-crafter create-dmg /tmp/Nextcloud.app
OVERVIEW: Create a DMG for the …
```

fix(mac-crafter): use AsyncParsableCommand everywhere

---

src/gui/tray/activitylistmodel.cpp
src/gui/tray/activitylistmodel.h

Figuring out whether a sync conflict occurred by iterating through the entire activity list each time a new activity was added is really slow, even more so when there already are thousands of previous activities.  
This was especially noticeable during complete initial full syncs involving more than ~10000 files.

perf(activitylistmodel): store conflicts in a separate list

---

src/common/filesystembase.cpp
src/common/filesystembase.h
src/gui/folder.cpp
src/gui/folderman.cpp
src/gui/folderman.h
src/gui/remotewipe.cpp
src/gui/remotewipe.h
src/libsync/filesystem.cpp
test/syncenginetestutils.h
test/testhelper.h
test/testremotewipe.cpp

also use `FileSystem::removeRecursively` to properly handle deletion of read-only directories/files
There's now an integration test for this feature after all those years as well ;-)

fix(remotewipe): do not reopen sync db before wiping

---

REUSE.toml
shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

The committed file automatically generated on dependency resolution of the NextcloudIntegration project of the desktop client which contains the macOS system extensions. You can compare it to the `package-lock.json` of NPM or `composer.lock` of PHP Composer.
It is official recommendation to commit such files to version control for top-level projects like our desktop client is, it is not just a library meant to be consumed by other projects.

Added Package.resolved of NextcloudIntegration project to version control.

---

.github/workflows/check-translations.yml

feat: checks Qt managed translations for tripple dots instead of elipsis

---

src/gui/wizard/owncloudadvancedsetuppage.cpp

Resolves #8508
tested with:
- macOS VFS build: option appears
- macOS non-VFS build `showExperimentalOptions=false` and `suffix` plugin present: option does not appear
- macOS non-VFS build `showExperimentalOptions=true` and `suffix` plugin present: option appears
- macOS non-VFS build `showExperimentalOptions=true` and `suffix` plugin absent: option does not appear
- windows, `cfapi` plugin absent: option does not appear
- windows, `cfapi` plugin present: option appears

fix(wizard): show VFS option during account setup when using a mac-VFS build

---

src/libsync/logger.cpp

As already present for Visual Studio on Windows, the logging needs a little extra switch for debug builds so their logging output conveniently appears in the Xcode console, too, and not just a logging file or elsewhere. This improves the developer experience in the platform-specific standard development environment.
I extracted this from my personal work in progress feature branch in which several independent things piled up since yesterday morning.

Enable Log Output in Xcode Console

---

.tx/config

See 
- https://github.com/nextcloud/swiftnextcloudui/issues/3
- https://github.com/nextcloud/docker-ci/issues/809
For now the resources have been locked to prevent translators from wasting time by re-translating all the time, but that breaks the normal sync of the desktop client:
```
nextcloud.client - Uploading file
nextcloud.client-desktop - Uploading file
nextcloud.client-fileprovider - Uploading file
nextcloud.client-fileproviderui - Uploading file
nextcloud.client-fileprovider - 409, conflict: This action cannot be performed..
nextcloud.client-fileproviderui - 409, conflict: This action cannot be perform..
nextcloud.client-desktop - Done
nextcloud.client - Done
ERR
```
So for now I suggest to remove the resources from the sync, so the other translations at least still sync.

fix(l10n): Don't sync xcstrings for now

---

shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Localizable.xcstrings
shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Localizable.xcstrings

I copied the string catalogs from `master` because cherry picking did not work out. This should suffice in this case. `stable-3.17` had an intermediate state of what is on `master` now.

Stable 3.17 File Provider Localization

---

src/gui/macOS/fileprovidersocketcontroller.cpp

The sync state would be stuck with `SyncPrepare` after VFS was initialised otherwise.  
This resulted in the systray icon displaying the *Syncing* icon when the app is launched until a file got down/uploaded from the configured VFS directory.
I _think_ this broke with ee3ae980a8a41922cb99575682af42592cb37fe7, that commit removed the EnumerationListener which reported the sync state while items were being enumerated.

fix(macOS): report `Success` as the initial sync state for VFS

---

admin/win/msi/Nextcloud.wxs
admin/win/msi/make-msi.bat.in

Using `"*"` will result in a different GUID with each invocation of the linker (`light.exe`), which can break automated installations when a localised version of the installer was loaded.
Resolves #8610

fix(msi): ensure the same ProductCode is used for embedded transforms

---

src/gui/owncloudsetupwizard.cpp

fix(wizard): avoid creating useless folders when setting up a VFS connection on Mac

---

src/common/utility.cpp
test/testutility.cpp

Discussed in forum (https://help.nextcloud.com/t/heist-1m-einen-monat-oder-eine-minute/230353).
e .g. "5m" is not correct
Corrrect form is "5min"
See https://en.wikipedia.org/wiki/Minute for reference

fix(i18n): Use SI symbol for minute

---

src/gui/UserStatusSelector.qml
src/gui/UserStatusSelectorPage.qml
src/gui/tray/CurrentAccountHeaderButton.qml
src/gui/tray/MainWindow.qml
src/gui/tray/UserLine.qml

Separate the status selector and the status message

feat: split user status tray menu

---

src/gui/generalsettings.ui
src/libsync/configfile.cpp

This PR adresses issue #8479. I figured the only thing really that had to be done was changing the spinBox minimum from 30 to 5 seconds, as the original poster of the issue had already pointed out. 
The comment behind the macro `DEFAULT_REMOTE_POLL_INTERVAL` in `configfile.cpp` appeared redundant to me, so I removed it. I hope that's alright. 
Thanks for reviewing!

fix(generalsettings): change remote pollinterval spinBox-minimum from 30 to 5 seconds, to align with configfile

---

.github/workflows/linux-appimage-comment.yml
.github/workflows/linux-appimage.yml

The creation/deletion of Pull Request comments does not work if the PR was initiated from a fork.  This resulted in the AppImage CI job failing with an error despite the build itself worked fine.
See also: https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/

fix(ci): separate workflow for creating a PR comment for built AppImages

---

CMakeLists.txt

if possible we detect systemd and enable install of the user service
try to improve user feedback when configure is run such that people may be able to figure out what is hapenning

chore: always produces systemd service and install it when possible

---

.github/workflows/needsinfohelper.yml

I forgot that these aren't JavaScript expressions...
https://docs.github.com/en/actions/reference/workflows-and-actions/expressions#operators

fix(needsinfohelper): use correct not-equals operator in expression

---

src/gui/tray/ActivityList.qml
theme/Style/Style.qml

This PR aims to resolve the discussion pertaining to issue #5536. Authors are @mike0609king and me. Thanks a lot for the reviews!
**Previously:**
Though most of the original problems mentioned in this thread seem to have been resolved, there appeared to be a remaining dissatisfaction with the usability of the ActivityList's Scrollbar among users. From what we were able to extract from the discussion this mainly stems from the fact that 
- (mainly on windows11) the ScrollBar is quite slim, 
- it's thumb can get really small and
- then also having to hover over this small area for the ScrollBar to appear.
**Changes:**
- The ScrollBar is attached to the right of the traymenu. This resembles the style that can be found in many other desktop applications like webbrowsers, the Windows file …

fix(ActivityList): attach vertical scrollbar, having minimum width and thumbsize, to the right of the traymenu 

---

shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

Now pointing to:
https://github.com/nextcloud/nextcloudfileproviderkit/releases/tag/3.1.0
Which contains the updated file provider extension database location to avoid crashes in some use cases due to insufficient permissions within the sandbox.

Updated NextcloudFileProviderKit Reference

---

src/gui/creds/flow2auth.cpp
src/libsync/account.cpp
src/libsync/account.h

feat(login): use stored credential user ID when authenticating again

---

src/gui/macOS/ui/FileProviderSyncStatus.qml

similar to how it's done in `src/gui/tray/SyncStatus.qml`

fix(FileProviderSyncStatus): disable rotation of status icon

---

src/gui/connectionvalidator.cpp
src/gui/tray/MainWindow.qml
src/gui/tray/usermodel.cpp

config.h has a constant for the application name, use this everywhere in user facing messages

fix(applicationName): ensure correct application name is shown to users

---

src/gui/tray/UnifiedSearchInputContainer.qml

> UnifiedSearchInputContainer: Binding loop detected for property "implicitWidth":
qrc:/qt-project.org/imports/QtQuick/NativeStyle/controls/DefaultTextField.qml:16:5
> UnifiedSearchInputContainer: Binding loop detected for property "rightPadding":
qrc:/qml/src/gui/tray/UnifiedSearchInputContainer.qml:28:5
> UnifiedSearchInputContainer: Binding loop detected for property "rightPadding":
qrc:/qml/src/gui/tray/UnifiedSearchInputContainer.qml:28:5
> UnifiedSearchInputContainer: Binding loop detected for property "rightPadding":
Updated the unified search TextField paddings to derive from the leading and trailing control widths, removing the binding loop that stemmed from referencing the field’s own width.

fix: log - Binding loop detected

---

src/gui/accountmanager.cpp
src/gui/generalsettings.cpp
src/gui/generalsettings.h
src/gui/generalsettings.ui
src/gui/tray/usermodel.cpp
src/gui/tray/usermodel.h
src/libsync/account.h
src/libsync/configfile.cpp
src/libsync/configfile.h
src/libsync/discovery.cpp
src/libsync/discovery.h
src/libsync/syncengine.cpp

This pull request addresses issue #892 and implements
- if the storage usage exceeds the threshold of 80, 90 and 95 percent, then a notification will be sent to the user. This notification also appears on the activity list
- configuration to turn quota warnings on and off
This commit been authored by @barisbasar1209 and me.

Implement more prominent quota warning

---

cmake/modules/ECMAddAppIcon.cmake

It started to warn about elseif() without a condition [1].
[1] https://gitlab.kitware.com/cmake/cmake/-/commit/74c62a180dccfd2cb7d594474f93e0facccdd60d

fix(ECMAddAppIcon): Avoid warning with cmake >= 4.1

---

src/gui/tray/MainWindow.qml

fix: alias desktop client import

---

src/gui/tray/syncstatussummary.cpp
src/libsync/theme.cpp
src/libsync/theme.h
theme.qrc.in

The in-app sync status should receive the new neutral icons. no application logos within the app itself
https://github.com/nextcloud/desktop/pull/8791

feat: neutral in-app icons

---

src/gui/folderstatusdelegate.cpp
src/gui/folderstatusdelegate.h
src/gui/folderstatusmodel.cpp

QIcon can take care of painting and scaling the icon on its own.
Apparently a small warning icon was supposed to be painted over the sync status as well if something occurred during sync.  That never seemed to work however; even after changing that `if` to always evaluate to true, I didn't see any paint events for that one in GammaRay.  I removed that from the paint code and cleaned up some (now-)unused roles from the model as well.
<table><thead>
<tr><th>Before</th><th>After</th>
</thead><tbody>
<tr><td><img width="467" height="419" alt="Folder status view with chunky icons" src="https://github.com/user-attachments/assets/fb5674b7-899f-4765-b5c0-02afef1eeafc" /></td><td><img width="467" height="419" alt="Folder status view with smooth icons" …

 fix(folderstatusdelegate): improve rendering of status icons on HiDPI screens 

---

src/gui/accountmanager.cpp
src/gui/accountsettings.cpp
src/gui/connectionvalidator.cpp
src/libsync/account.cpp
src/libsync/clientsideencryption.cpp
src/libsync/clientsideencryption.h
src/libsync/updatee2eefolderusersmetadatajob.cpp

fix(encryption/token): try to init the token again after errors

---

src/gui/main.cpp

For some reason this caused the macOS style to not be applied, still would like to figure out what's the actual cause for that.
cc @Rello

fix(gui): do not set fallback QML style ourselves

---

src/gui/settingsdialog.cpp

I accidentally messed up https://github.com/nextcloud/desktop/pull/2959. Fixes https://github.com/nextcloud/desktop/issues/700.

Allow Maximizing Settings Window

---

REUSE.toml
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Assets.xcassets/Contents.json
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Assets.xcassets/FileProviderDomainSymbol.symbolset/Contents.json
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Assets.xcassets/FileProviderDomainSymbol.symbolset/FileProviderDomainSymbol.svg
shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Info.plist
shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Assets.xcassets/Contents.json
shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Assets.xcassets/FileProviderDomainSymbol.symbolset/Contents.json
shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Assets.xcassets/FileProviderDomainSymbol.symbolset/FileProviderDomainSymbol.svg
shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Info.plist
shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj

Probably due to the constant rebuilding and changes on my system I had to reboot before I could see the right symbol. I do not expect this to happen in ordinary use cases. macOS also has some caching of symbols.

Branded file provider extension SF Symbol

---

src/gui/tray/asyncimageresponse.cpp
src/gui/tray/asyncimageresponse.h

With this change some warnings from QObject like these are gone now:
QObject: Cannot create children for a parent that is in a different thread.
I suspect this might have been causing some "random" crashes during normal usage as well.  QNAMs are supposed to be used from the same thread they were created in, which (as far as I could tell anyway) isn't the case within async image providers...
This change is similar to how the `ImageResponse` class inside `src/gui/tray/usermodel.cpp` fetches a remote resource: https://github.com/nextcloud/desktop/blob/fb20bb281088567a80e3302dbc8573b2b1a21113/src/gui/tray/usermodel.cpp#L1772-L1784

fix(asyncimageresponse): fetch remote resources in the same thread as `Account`
