nextcloud/desktop

src/gui/owncloudgui.cpp
src/gui/owncloudgui.h

Make headers be only included when building with libcloudprovider support (fixes #93)
@dagayaru

Fix build on windows

---

src/gui/creds/httpcredentialsgui.cpp

An URL that had base like "http://localhost/nextcloud/"
would get the last slash '/' removed and then appended
with "index.php..." resulting in
http://localhost/nextcloudindex.php

Fix URL in dialog that requests password

---

src/gui/owncloudgui.cpp

Removes 'Log in to all accounts' and 'Log out to all accounts' from the primary client menu as requested:
"The option to log out of all accounts should be removed from the primary client menu. This is not an often used option and it should be fine if this can only be done from within the settings dialog."

Removes 'Log in to all accounts' and 'Log out to all accounts' from the primary client menu.

---

src/gui/servernotificationhandler.cpp

Uses QString::number to get a string equivalent of the notification_id number 

---

src/common/syncjournaldb.cpp
src/common/syncjournaldb.h
src/common/syncjournalfilerecord.h
src/csync/csync.cpp
src/csync/csync.h
src/csync/csync_update.cpp
src/libsync/propagatedownload.cpp
src/libsync/propagatedownloadencrypted.cpp
src/libsync/propagateremotedelete.cpp
src/libsync/propagateupload.cpp
src/libsync/propagateuploadencrypted.cpp
src/libsync/syncfileitem.cpp

This tries to fix #156 but it seems a lot more work has to be done

Remove table for e2e and add an e2eMangledName column

---

admin/linux/debian/debian.artful/nextcloud-client-dolphin.install
admin/linux/debian/debian.bionic/nextcloud-client-dolphin.install
admin/linux/debian/debian/nextcloud-client-dolphin.install
shell_integration/dolphin/CMakeLists.txt

When building for Xenial the Dolphin plugins go into the incorrect directory. This patch sets the KDE_INSTALL_USE_QT_SYS_PATHS cmake variable to ON, which seems to be the most generic way to solve this issue.

Dolphin plugin path correction

---

admin/linux/debian/debian.stable/control
admin/linux/debian/debian/control

It has been suggested that the libgnome-keyring0 package is useful when one wants to use the GNOME keyring. So the nextcloud-client package now recommends libgnome-keyring0.
This resolves #181.

Recommends relation to libgnome-keyring0

---

src/gui/syncrunfilelog.cpp
src/gui/syncrunfilelog.h

#221 
I have changed the location from the logfiles from the synced folders to the appData folder from:
../Nextcloud/SyncedFolder1/.owncloudsync.log
../Nextcloud/SyncedFolder2/.owncloudsync.log
to [QStandardPaths::AppDataLocation](http://doc.qt.io/qt-5/qstandardpaths.html) 
Linux: ~/.local/share/Nextcloud/SyncedFolder1_sync.log 
~/.local/share/Nextcloud/SyncedFolder2_sync.log
macOS: ~/Library/Application Support/Nextcloud/SyncedFolder1_sync.log "
~/Library/Application Support/Nextcloud/SyncedFolder2_sync.log " 
Win: C:/Users/<USER>/AppData/Roaming/Nextcloud/SyncedFolder1_sync.log "
C:/Users/<USER>/AppData/Roaming/Nextcloud/SyncedFolder2_sync.log "
Remaining question is whether or not, the ".owncloudsync.log" pattern should be removed from "ignore this file and dont even show it in the Not …

Put log files somewhere else #221 

---

src/libsync/nextcloudtheme.cpp

Hello, 
This fix Deprecated trUTF8 by QT. 
error : 
`/drone/src/github.com/nextcloud/client/src/libsync/nextcloudtheme.cpp:50:12: warning: 'static QString OCC::NextcloudTheme::trUtf8(const char*, const char*, int)' is deprecated [-Wdeprecated-declarations]
re += trUtf8("<p><small>By Klaas Freitag, Daniel Molkentin, Jan-Christoph Borchardt, "
^
In file included from /opt/qt59/include/QtCore/qobject.h:46:0,
from /opt/qt59/include/QtCore/QObject:1,
from /drone/src/github.com/nextcloud/client/src/libsync/theme.h:18,
from /drone/src/github.com/nextcloud/client/src/libsync/nextcloudtheme.h:18,
from /drone/src/github.com/nextcloud/client/src/libsync/nextcloudtheme.cpp:15:
/drone/src/github.com/nextcloud/client/src/libsync/nextcloudtheme.h:28:5: note: declared here
Q_OBJECT
^`

Fix Use of Deprecated trUtf8

---

src/gui/syncrunfilelog.cpp

I found a problem regarding my last pull request #253, already talked to @camilasan.
The problem is, if the user adds several folders with the same (local) name, the logfiles get merged.
I thought this is straightforward to fix, but the only function input _folderPath_ carrys not enough information to fix this.
So I had to lable the logfiles (I added the according folderPath into the beginning of the logfile).
**Downside is**: I have to read the files again, which is always open to manipulation and errors, but the worst outcome, if someone is changing the logs is that: **A: new logfile gets created even if there is an existing one. B: logfiles get merged.**
I used the following nameing scheme so far (add "_1"). Do you have any ideas to improve this?
**Example:**
syncing all 3 folders: …

Put log files somewhere else #221 (name conflict)

---

src/CMakeLists.txt
src/gui/CMakeLists.txt
src/gui/creds/credentialsfactory.cpp
src/gui/creds/webflowcredentials.cpp
src/gui/creds/webflowcredentials.h
src/gui/creds/webflowcredentialsdialog.cpp
src/gui/creds/webflowcredentialsdialog.h
src/gui/wizard/owncloudsetuppage.cpp
src/gui/wizard/owncloudwizard.cpp
src/gui/wizard/owncloudwizard.h
src/gui/wizard/owncloudwizardcommon.h
src/gui/wizard/webview.cpp
src/gui/wizard/webview.h
src/gui/wizard/webview.ui
src/gui/wizard/webviewpage.cpp
src/gui/wizard/webviewpage.h
src/gui/wizard/webviewpage.ui
src/libsync/networkjobs.cpp
src/libsync/networkjobs.h

Finally support the new login flow that was introduced with NC 12.
This requires at QWebEngine.
It will simply open a webview to the login flow and fetch an apptoken from that endpoint.
This is all stored in the Keychain.
If for some reason a reauth is required the user is prompted to login again.

Add weblogin flow for NC > 12

---

src/gui/accountstate.cpp
src/gui/accountstate.h
src/gui/ocsjob.cpp
src/gui/ocsjob.h
src/gui/ocsnavigationappsjob.cpp
src/gui/ocsnavigationappsjob.h
src/gui/owncloudgui.cpp
src/gui/owncloudgui.h

I am trying to use the 304 ETag response header to check for changes in the server. But I am not sure if I can do much better than just changing the list of navigation apps once I get 200 or not changing it when I get 304 since the system tray menu is built every time it is displayed and I always need the user menu to be created before I can insert the navigation apps menu.

Checks for 304 response in the navigation apps request

---

shell_integration/nautilus/syncstate.py

The nautilus plugin doesn't actually define get_columns(), so pretending
to be a ColumnProvider lead to a critical warning on startup.
PR owncloud/client/pull/6415

Nautilus integration: Not a ColumnProvider

---

shell_integration/dolphin/ownclouddolphinpluginhelper.cpp

"As per XDG Base Directories specification:
> If $XDG_RUNTIME_DIR is not set applications should fall back
> to a replacement directory [...]
In practice, the ownCloud client has the fallback, but the plugin
helper does not, and if $XDG_RUNTIME_DIR is not set, the plugin
mysteriously does not work."
PR https://github.com/owncloud/client/issues/6402

Dolphin plugin: fall back if $XDG_RUNTIME_DIR is empty

---

src/libsync/syncengine.cpp

PR https://github.com/owncloud/client/pull/6363

SyncEngine: Use separate state for two unicode conversions

---

shell_integration/nautilus/syncstate.py

Use b'\n' in the call to rfind, as the _remainder is bytes, not a string.
Remove most of the debug message which happens during normal operation.
They are mostly spamming the nautilus console, and can also cause bug
as they may throw exception in case of wrong encoding.
Relates to issue: owncloud/client/issues/6406
PR owncloud/client/pull/6490

Nautilus: Fix Python3 and remove many debug

---

shell_integration/nautilus/syncstate.py

Issue owncloud/client/issues/6406

Nautilus shell integration: Print python version on startup #6406

---

src/gui/folder.cpp
src/libsync/owncloudpropagator.cpp

We otherwise normalize all path in the C form, so we must have
the Folder's path normalized the same. Or all comparizon will fail
(such as knowing if a file from the SocketAPI or the FilesystemWatcher
are part of the folder)
Issue owncloud/client/issues/4424

Folder: normalize the local path.

---

src/gui/accountsettings.cpp
src/gui/accountsettings.h

The specs forbid the encryption or decryption of a
non empty folder. so...
1 - check for the sync status, if it's not synced return
as there's no way that I can say that there's items on the
server right now without waiting for the sync to finish
2 - verify if the folder is empty locally
as the user could have send some files to the folder.

Forbid to encrypt or decrypt a non-empty folder.

---

src/libsync/propagateuploadv1.cpp

We otherwise normalize all path in the C form, so we must have
the Folder's path normalized the same. Or all comparizon will fail
(such as knowing if a file from the SocketAPI or the FilesystemWatcher
are part of the folder)
Issue owncloud/client/issues/6403

propagateuploadv1: don't finalize after a done()

---

doc/architecture.rst
src/csync/csync_exclude.cpp
test/csync/csync_tests/check_csync_exclude.cpp

The Desktop.ini exclude was added for 2.4 because we add such a file to
the synced folder on Windows. It doesn't need to cover subdirectories.
PR owncloud/client/pull/6404

Excludes: Expand doc, Desktop.ini only in root folder

---

admin/osx/post_install.sh.cmake

Some users have disabled Finder, and the postinstall will always reenable Finder, unless it checks Finder status first.
PR owncloud/client/pull/6271

postinstall macOS: check if Finder is running

---

src/gui/folderstatusmodel.cpp
src/gui/folderstatusmodel.h

OCC::FolderStatusModel::slotUpdateDirectories: ASSERT: "parentInfo->_fetching" in file /home/olivier/kdegit/owncloud/mirall/src/gui/folderstatusmodel.cpp, line 599
This can happen if the structure of a folder is change while the user
expands the root folder. In this case, resetSubs() is called which
resets _fetching to false.
Instead, we need to keep a pointer to the job so we can abort it by
deleting it.
PR owncloud/client/pull/6408

FolderStatusModel: fix potential assert

---

src/common/syncjournaldb.cpp

Issue owncloud/client/issues/6431

SyncJournalDb::setSelectiveSyncList: Always use a transaction

---

src/gui/activitywidget.h

With the 4.5sec timeout, it was very easy to accidently hit the wrong notification
when the previous one dissapeared so late.

Notifications: Lower hiding timeout

---

src/gui/ocsshareejob.cpp
src/gui/ocssharejob.h
src/gui/owncloudgui.cpp
src/gui/owncloudgui.h
src/gui/sharedialog.cpp
src/gui/sharedialog.h
src/gui/socketapi.cpp
src/gui/socketapi.h

* The new menu option will fetch shares and create a new link share if
no "context menu share" currently exists.
* Various cleanup of common operations in socketapi happened as well,
in particular there's now FileData::get() that calculates all the
relevant paths that are useful for most socketapi actions.
PR owncloud/client/pull/6434

SocketApi/Sharing: Add "copy public link" to menu #6356

---

src/common/syncjournaldb.h
src/libsync/propagateuploadng.cpp
src/libsync/propagateuploadv1.cpp
src/libsync/syncengine.cpp
test/testchunkingng.cpp

Since commit 4dc49ff3, we store an entry in the upload info table even
for non chunked uploads. However, if this fails we don't want to remove
non-existant stale chunks if the upload fails.
Without this commit, we would send a DELETE command to clean non-existant
chunks in the dav/uploads/ namespace.
PR owncloud/client/pull/6428

Uploads: Don't delete unexisting chunks

---

src/libsync/abstractnetworkjob.cpp
src/libsync/abstractnetworkjob.h
src/libsync/networkjobs.cpp
src/libsync/propagatedownload.cpp
src/libsync/propagateremotedelete.cpp
src/libsync/propagateremotemove.cpp
src/libsync/propagateupload.h

The old code printed "QNetworkReply::NoError"
PR owncloud/client/pull/6464

Logging: Avoid the word "Error"

---

cmake/modules/Warnings.cmake
src/gui/networksettings.h

The option -Wno-discarded-qualifiers only exists with GCC, clang warns that
it has no effects.
Also it warns when some virtual fuction are marked with override but not
all of them.

Fix a bunch of warning with clang

---

src/libsync/owncloudpropagator_p.h

Because it sometimes appears in conjunction with server bugs and we
don't want to halt all syncing for other files in these cases.
Issue owncloud/client/issues/6516
PR owncloud/client/pull/6533

Propagation: Connection closed is a normal error #6516

---

src/libsync/propagateupload.cpp
src/libsync/propagateupload.h
src/libsync/propagateuploadng.cpp
src/libsync/propagateuploadv1.cpp

Some servers have virus scanners and the like that can delay the
response of the final chunked upload assembly significantly, often
breaking the current 5min (!) timeout. See owncloud/enterprise#2480
for details.
Issue owncloud/client/issues/6527
PR owncloud/client/pull/6532

Upload: Adjust timeout for final job based on size #6527

---

src/common/syncjournaldb.cpp

With WAL mode sqlite seems to occasionally crash when the
underlying filesystem goes away.
Issue owncloud/client/issues/6049
PR owncloud/client/pull/6530

SyncJournal: Check file existence even for open dbs #6049

---

src/common/syncjournaldb.h
src/common/syncjournalfilerecord.h
src/common/utility.cpp
test/testchunkingng.cpp
test/testexcludedfiles.cpp
test/testsyncconflict.cpp
test/testsyncmove.cpp

From "_conflict-user-yyyymmdd-hhmmss"
to   " (conflicted copy user yyyy-mm-dd hhmmss)"
Issue https://github.com/owncloud/client/issues/6365
PR https://github.com/owncloud/client/pull/6417

Conflicts: Change tags to be more user friendly #6365

---

src/gui/socketapi.cpp
src/gui/socketapi.h

With the previous changes the "Share..." action was shown but it didn't
work yet.
PR owncloud/client/pull/6481

SocketAPI: Allow opening share dialog if contents still syncing #4608

---

src/gui/folderstatusmodel.cpp

Add indicator to e2e folders

---

src/gui/CMakeLists.txt
src/gui/application.cpp

Reason: Windows desktop translation was only working when moving all translation files to the root of the install folder. Pretty messy.

Windows: moves translation files to /i18n.

---

src/gui/networksettings.cpp

Fixes f6a075ef54a3434e758dcddc6a29b218c4f2a247 for #5885
When no host is given it shouldn't just *appear* that there is no
proxy, there actually shouldn't be a proxy set then.
PR owncloud/client/pull/6491

Proxy settings: Fix bad behavior with empty host

---

src/gui/wizard/webview.cpp

This way the server will properly translate it for you if it has
translations.

Set Accept-language header for webview requests

---

CMakeLists.txt
admin/linux/debian/scripts/git2changelog.py

The Ubuntu/Debian build script used the repository tags to determine the main version of the packages (which worked with the theming repo). However, it seems that this repo is not being tagged. So this patch modifies the build (actually, the changelog generator) script  to use the contents of the ```VERSION.cmake``` file to determine the version.
However, I am wondering if the repository should be rather tagged, as currently there is no way to determine if a version is a beta or a release one. While still an experimental PPA is used for uploads, eventually it would be good to be able to differentiate between a beta and a release version and hence PPA.

Use the VERSION.cmake file to determine Ubuntu/Debian main package version

---

README.md

Also note that github doesn't render irc:// links, so it just showed the name

Link IRC to webchat so people without a client can do something

---

README.md

- Adds a shorter version of how to build the client but the extended version will be kept on the Wiki.
- Makes the instructions available if you clone the repo and work offline 
Thanks @tobiasKaminsky for pointing this out :)

Updates the README with build instructions.

---

cmake/modules/MacOSXBundleInfo.plist.in

without that key, the client automatically runs on the dedicated gpu (if
present). now it allows the system to use the integrated one.
closes #501

allow to switch to the integrated gpu on MacOS

---

admin/linux/debian/drone-build.sh

This patch modifies the Ubuntu/Debian build script to upload the source packages to the beta PPA to allow for more extended testing.

Use the beta PPA for builds (re #402)

---

src/gui/owncloudgui.cpp

- The crash was happening when the user could not connect and it would
crash on trying to retrieve and display the navigation apps.
- Checks AccountStatePtr earlier in the function
slotNavigationAppsFetched.
- Cast of pointer stored in QVariant to QMenu was not done correctly -
qvariant_cast works best for user type defined or QMetaType known to
QVariant.

Fixes crash on mac OS and linux.

---

src/gui/activitywidget.cpp
src/gui/activitywidget.h
src/gui/activitywidget.ui

- Minor changes: removes white background and changes frame style to the
same used in the accountsettings for consistency.

Fixes #533: Removes the copy activities/notifications button

---

src/gui/activityitemdelegate.cpp

Fixes #518: adds more margin for the text in the activity 

---

src/gui/settingsdialog.cpp

Up until and including Qt 5.6, the QAction constructor required at least one argument (see http://doc.qt.io/qt-5.6/qaction.html#QAction vs. http://doc.qt.io/qt-5/qaction.html#QAction). This patch provides it.
The reason for this fix is that the omission of the argument breaks the build on Xenial. Xenial has Qt 5.5, but since the argument was required also in Qt 5.6, which is officially supported by the client, I think the right way to fix it is to provide the argument. (As opposed to providing a patch specifically for Xenial.)

Provide parent to QAction

---

src/gui/shareusergroupwidget.cpp

The constructor of QAction that receives a string as the first argument, also requires a parent on Qt 5.6.

Further QAction constructor fixes

---

.gitmodules
src/gui/owncloudgui.cpp
src/gui/owncloudgui.h

- The fork has the functions needed to add separators in the toolbar.
- Removes dynamic cast when building navigation apps.

Fixes mac build

---

src/gui/sharelinkwidget.cpp
src/gui/sharelinkwidget.h
src/gui/sharelinkwidget.ui
src/gui/shareusergroupwidget.cpp

- Fixes #534: interactions with expiration date and password.
- Fixes call for slot when date is set - it was the password
slot for that.
- Adds QProgressIndicator and function to toggle animation.
- Fixes: when date was set, the date was not being correctly set and
displayed.
- Fixes: hides and 'deletes' passsword and expire. date widgets when
the user unchecks it in the toolbox menu.
- Fixes #534: can edit permission were always disabled. 
- Properly checks files and folder share permissions when displaying can edit checkbox - which can also be partially checked - and listing
permissios in the tollbutton menu.
- Fixes click on can edit checkbox - which can also change state of
permissions in the toolbutton menu.
- Enhancement #534: hide tool button when there is no share link.
- Fixes …

Fixes issues in the share dialog

---

src/gui/activitylistmodel.cpp

Fix #515 
The tooltip role did not receive any treatment. It was then in my understanding jumping to the next case and returning the subject of the activity, that is repeating the same text as in the activity itself.
Dropping this case, allows to return with the default and do nothing.

Drop the ToolTipRole from the activity list

---

src/gui/wizard/owncloudsetuppage.cpp

Fix #576 
Once the user clicks Log in. That button disappears, the register with a provider is kept as deleting it would imply needing to put a back button which is way harder. It also turns out to be more intuitive if you click login and you get as prompt to put a server address. The fact that the register with a provider button remains, helps you understand that you need a provider to continue.
There are some minor cosmetic changes, that clang formatter did for me according to your style guide file.

Hide login button on setup screen

---

test/testoauth.cpp

Fix a strange warning seen on the log from the CI on Windows in
https://github.com/owncloud/client/pull/6621
The test shows, at the beginning
QObject::connect: No such signal DesktopServiceHook::destroyed(QObject*)
And crashes at the and.
My guess is that when QDesktopServices::setUrlHandler is called, the
QMetaObject is not yet initialized
But this is probably not the reason of the crash

TestOAuth: Don't have global static QObject

---

src/libsync/creds/httpcredentials.cpp

The server reply with a code 400 when the token is invalid,
the client was understanding this error as a network error, and was retying
again with the same token.
Instead, we must rely on what the json is saying, even if the reply is
not a 200 code.
Issue https://github.com/owncloud/enterprise/issues/2777

OAuth: Fix infinite loop when the refresh token is expired

---

src/gui/wizard/webview.cpp

The QWebEngine uses a different certificate store/system. So we can't
just pass wour accepted certificates in there.
As a work around we now trust the url we set by definition. As this has
to already be approved before we access this.
Replaces #630

Allow to use the login flow with a self signed certificate

---

src/libsync/configfile.cpp

Fixes #766
I didn't test yet as my windows VM does funny things. So a quick run appreciated @camilasan

Copy over config file to new location on windows

---

admin/linux/debian/debian.xenial/post-patches/qt5.5-compat.patch

While Nextcloud officially requires Qt 5.6, Ubuntu Xenial ships with Qt 5.5, so some effort is being made to keep the client compile with that version of Qt and thus for Xenial.
A recently merged pull request (#645) broke compatibility with Qt 5.5, by calling a ```QMenu::addAction``` function with a lambda function argument. 
This pull request adds a patch strictly for Xenial which changes this call to an "old-fashioned" variant requiring a slot function and connecting the ```triggered``` signal to that slot. The patch is applied when producing the source package for Xenial. Other distributions use unaltered source code.

Qt 5.5 compatibility patch for Xenial

---

src/gui/generalsettings.cpp

For some reason, QLabel with rich text and word wrapping enabled
calculates quite a bit too large size hint. Luckily, it's rich text
that is already divided to paragraphs so that wrapping makes actually
very little visual difference. For example, on my screen, when the
settings dialog is resized horizontally to the minimum, the only word
that actually wrapped was "2017". After this patch, it naturally won't
wrap anymore, but the General Settings page also doesn't leave a large
gap at the bottom. As a result, the minimum height of the dialog went
down from 581 to 525. The exact values depend on the style and fonts.
Fixes #91.

SettingsDialog: disable unnecessary wrapping for the about label

---

src/libsync/networkjobs.cpp

If we use the source format it can result in fully black images. As the
basic generated avatar doesn't have an alpha channel.
Before:
After:

Use a format that supports alpha channels for avatars

---

src/gui/accountsettings.cpp
src/gui/accountsettings.h
src/gui/settingsdialog.cpp
src/gui/settingsdialog.h

TO test:
1. Have an account setup
2. Sync a file 'foo.txt'
3. Close the client
4. Edit foo.txt on the web
5. edit foo.txt local
6. Open the sync client
You get an image like:
Before: click and nothings happens
Now: click and the window is changed :)

Actually open the activity view on a click for more info

---

src/gui/servernotificationhandler.cpp

... in addition to fixing up the scheme and host.
For example, the survey app sends "/settings/admin/survey_client" as
a link. Clicking the "More information" button wouldn't lead to the
correct place if NC was running on a custom port.

Fixup the port in server notification URLs

---

src/gui/settingsdialog.cpp

SettingsDialog::accountAdded() uses the height of the toolbar to
calculate the desired default size for toolbuttons. Make sure to have
the "General" and "Network" tool buttons in place before calling
accountAdded() to avoid cramped first button.

SettingsDialog: fix a little glitch in the account tool button size

---

src/gui/settingsdialog.cpp

If selected text is light, provide a light icon too when selected.

SettingsDialog: tweak color aware icons

---

src/gui/elidedlabel.cpp
src/gui/elidedlabel.h
src/gui/sharedialog.ui
src/gui/sharelinkwidget.cpp
src/gui/sharelinkwidget.h
src/gui/sharelinkwidget.ui
src/gui/shareusergroupwidget.cpp
src/gui/shareusergroupwidget.ui
src/gui/shareuserline.ui

Share dialog alignment

---

src/gui/activitylistmodel.cpp
src/gui/activitylistmodel.h
src/libsync/capabilities.cpp
src/libsync/capabilities.h

Fixes #788
Fixes #834
1. Disable activities app on the server
2. Open client
3. Open activities tab
Before:
- observe a :hankey:-ton of requests to your server
After:
- No :hankey:-ton of requests to your server

Do not fetch activities if they are not enabled

---

src/gui/activitylistmodel.cpp
src/gui/activitylistmodel.h

We should stop fetching the moment the activity stream is empty when
fetched. It doesn't matter if the current list is empty.

Fix the activity loop

---

src/gui/syncrunfilelog.cpp

Fixes #873
Not all folder names are proper latin1.

Write the actual folder to the log

---

src/libsync/configfile.cpp

For #566
Since we only showed the user exclude list (and some extra items) the
system exclude list was still used.
This copies over the system exclude list (if it isn't there).
If it fails we use the system one still.
However if you now remove items from your own list it will really be
gone.

Do not read system exclude list if user exclude is present

---

src/gui/wizard/webview.cpp

When using the newest Qt Framework (Qt 5.12.0) there is an error during build:
```
src/gui/wizard/webview.cpp:164:25: error: member access into incomplete type 'const QWebEngineCertificateError'
if (certificateError.error() == QWebEngineCertificateError::CertificateAuthorityInvalid) {
```
Including `QWebEngineCertificateError` fixes it.

Added missing Include

---

shell_integration/dolphin/CMakeLists.txt

Get rid of a bunch of such warnings from configuring the Dolphin plugin:
```
CMake Deprecation Warning at /usr/share/ECM/kde-modules/KDEInstallDirs.cmake:345 (message):
BIN_INSTALL_DIR is deprecated, use KDE_INSTALL_BINDIR instead.
Call Stack (most recent call first):
/usr/share/ECM/kde-modules/KDEInstallDirs.cmake:433 (_define_relative)
shell_integration/dolphin/CMakeLists.txt:23 (include)
```
Modified from https://github.com/owncloud/client/pull/6922
Original author: Dominik Schmidt <dev@dominik-schmidt.de>

Fix KDEInstallDirs deprecation warnings

---

src/gui/creds/webflowcredentialsdialog.cpp
src/gui/creds/webflowcredentialsdialog.h
src/gui/wizard/webview.cpp
src/gui/wizard/webview.h

Inspired by https://github.com/electron/electron/pull/15028
Closes https://github.com/nextcloud/desktop/issues/941
Closes https://github.com/nextcloud/desktop/issues/950

Make sure _profile and _page are deleted in the correct order

---

src/gui/wizard/owncloudadvancedsetuppage.cpp
src/gui/wizard/owncloudadvancedsetuppage.h
src/gui/wizard/owncloudadvancedsetuppage.ui

Initial commit :)
This is a small improvement for the wizard.
- It checks if there is enough free space on the local folder
- if the local folder doesn't exist, it checks the free space for the user's home directory if it is part of the path)
- If not, it displays an error message
Cheers

Wizard: show an error message if there is no enough free space in the local folder

---

CONTRIBUTING.md
src/gui/activitywidget.cpp

modified:   src/gui/activitywidget.cpp
Removed whitespace from string, as described in issue #928

Removed whitespace from string

---

src/gui/wizard/webviewpage.cpp

If the entered url ends with a slash we should not add another one.

Do not add double slash to login flow url

---

src/gui/activitywidget.cpp

Related to #1068 
Reported at forums with screenshots. See 
https://help.nextcloud.com/t/client-2-5-1-linux-typo/46796
Signed-off-by: Mark Ziegler <mark.ziegler@rakekniven.de>

Fixed l18n issue. Added space for separating string

---

src/gui/activitylistmodel.cpp
src/gui/activitylistmodel.h
src/gui/activitywidget.cpp

Fixes #685
The view doesn't live update for me. But I think that is a different (and less urgent) issue.
To test:
1. create some notifications for a user (@ mention them in comments for example)
2. start the client for that user see the notifications in the activities
3. dismiss a notification on server
4. wait a little while
5. switch to account and back to activity
before: All notifications still there
now: only active notifications still there

Do not display dismissed notifications

---

src/gui/wizard/webview.cpp

This is a quick hack to make self signed certificates work.
I'm not to fond of it the real solution should be to request the url
with QNAM and then see if it fails.

Add invalid certiticate messagebox

---

src/gui/creds/httpcredentialsgui.cpp

Since some versions ago, the path/url for the app password settings is `/settings/user/security#security` instead of `/settings/personal#apppasswords`

correct app passwords link

---

src/gui/wizard/owncloudsetupnocredspage.ui

Or is this some special flag for the shortcuts?
Thanks to @cowai for finding this.

Fix typo in translation string

---

src/gui/cloudproviders/cloudprovidermanager.cpp
src/gui/cloudproviders/cloudproviderwrapper.cpp

On `cloudprovidermanager.cpp`
* I changed the callback to use the on_name_acquired as on_bus_acquired is a little bit early, there might be something else owning the name.
* I also added `on_name_lost` so that the memory is correctly freed when unused.
On `cloudproviderwrapper.cpp`:
* I removed `qstring_to_gchar` which was prone to lots of memory leaks when not correctly used.
* I used the QString object when dealing with string formating and only used C strings when giving the string to CloudProvider Objects (GLib expects UTF-8 strings, I therefore used `.toUtf8().data()`)
* `cloud_providers_account_exporter_set_menu_model` and `cloud_providers_account_exporter_set_action_group` are not consuming the reference of `getMenuModel()` and `getActionGroup()` I therefore added some …

Fix several memory leaks in cloudproviders and add translation support

---

src/libsync/configfile.cpp
src/libsync/syncengine.cpp
test/testallfilesdeleted.cpp

Configuration default value is set to false because  users are getting
the popup message too often.

Uses configuraion to determine if it should show empty folder popup.

---

README.md

@camilasan this is what I used some time ago for setting up. For me it worked and made the dev setup process much much simpler. (I think we talked about it some months ago, found I didn’t open a pull request for it back then.)
Please review @nextcloud/desktop

Simplify cmake command to make copy-pastable

---

src/gui/folderwatcher.cpp
src/gui/folderwatcher.h
test/testfolderwatcher.cpp

I have only tested this on my Linux installation, but it shouldn't depend on anything platform specific. Any and all feedback is welcome and appreciated.

This should fix issue #1000

---

src/gui/wizard/webview.cpp

The path returned from the server encodes a space in the username with `+` and if the username contains a `+` sign it is encoded as `%2B` (cf. https://www.php.net/manual/function.urlencode.php).
Fix: Don't (double) decode the URL path and then replace `+` with space (introduced in issue #279 resp. commit 9ec61a84ce682399b4c39182887e488c99f1d87a). Instead first replace `+` with space, then decode percent encoding.
Tested with a username containing a space, a username containing a `+`sign and a username containing just A-Za-z0-9- (with Nextcloud 16).
(fixes issue #1266)

WebView: Properly handle usernames with spaces and plus signs in it

---

src/gui/ocsshareejob.cpp
src/gui/ocssharejob.cpp
src/gui/sharedialog.cpp
src/gui/shareusergroupwidget.cpp

If the initiator or the recipient is not the current user,
show the list of sharees without any options to edit it.
Minor change: updates api to v2.

Adds parameter to retrieve shares with its reshares.

---

.gitignore
src/3rdparty/kmessagewidget/kmessagewidget.cpp
src/3rdparty/kmessagewidget/kmessagewidget.h
src/gui/CMakeLists.txt
src/gui/accountmanager.cpp
src/gui/accountsettings.cpp
src/gui/accountsettings.h
src/gui/accountsettings.ui
src/libsync/clientsideencryption.cpp
src/libsync/clientsideencryption.h

Instead of immediately popping up the mnemonic dialogue,
only show a notification bar on the account setup page.
For the cases where the user does not want to use E2E,
this is significantly less intrusive than the old approach.
This is related to #917 and #753

Added a nice UI for the E2E-enabled account first connect

---

src/gui/activitylistmodel.cpp
src/gui/activitywidget.cpp
src/gui/folder.cpp
src/gui/folder.h
src/libsync/owncloudpropagator.cpp
src/libsync/owncloudpropagator_p.h
src/libsync/progressdispatcher.cpp
src/libsync/propagatedownload.cpp
src/libsync/syncfileitem.h
src/libsync/syncfilestatustracker.cpp
src/libsync/syncresult.cpp
src/libsync/syncresult.h

It filters the error out of the list of blocking errors. It now shows up
in the Activities and Notificattions list as a warning.
It also logs the error:
[OCC::ActivityWidget::slotItemCompleted 	Item  "welcome.txt"  retrieved resulted in error  "File locked"

Add error category for http file lock error status 423.

---

admin/linux/debian/debian.xenial/post-patches/qt5.5-compat.patch

Since Ubuntu Xenial provides Qt 5.5 only, the client code needs to be patched. This pull request updates the existing patch, so that the latest versions also compile under Xenial. The patch is applied when building for Xenial only.

Update Qt 5.5 compatibility patch for Xenial

---

admin/linux/debian/debian.eoan/changelog
admin/linux/debian/drone-build.sh

This patch removes the building of a Ubuntu Cosmic source package, as Cosmic is not supported anymore. It also adds building for Eoan, the next release.

Remove Ubuntu Cosmic and add Eoan package

---

src/gui/wizard/owncloudsetuppage.cpp

If the cert has a chain of certs we should send them all properly
This doesn't solve the issue with the webview not accepting client side certificates unfortunatly :S

Add proper CA to client side certificate connection

---

admin/linux/debian/debian.eoan/control

The libgnome-keyring0 package does not exist on Ubuntu Eoan, and is not needed for the Nextcloud client.

Remove dependency on libgnome-keyring0 on Eoan

---

src/gui/creds/webflowcredentials.cpp
src/gui/creds/webflowcredentials.h
src/gui/wizard/flow2authcredspage.cpp
src/gui/wizard/owncloudsetuppage.cpp
src/gui/wizard/owncloudwizard.h

The previous commit 50cd6af394f666065f386d1d55e7d6a90e0d9c9e - Build a webflowcredentials
changed:
src/gui/wizard/flow2authcredspage.cpp in line 135 to use WebFlowCredentials
instead of HttpCredentials.
But the WebFlowCredentials class didn't include code to store and load SSL client
certificates and keys from the keychain.
This commit migrates the useful stuff from the old HttpCredentials class
into WebFlowCredentials.
Successfully tested on Windows. Please test on other systems and verify it's safe! :)

Adds SSL client cert storage to webflow + Login Flow v2

---

src/gui/creds/webflowcredentials.cpp
src/gui/creds/webflowcredentials.h

Saving all client CA's within one credential may result in:
Error: "Credential size exceeds maximum size of 2560"
Client CA certificates are now being stored in separate slots
within the keychain and are being processed by a queue mechanism.
<br/>
IMPORTANT TODO:
forgetSensitiveData(): Invoked by "Log out" & "Remove account"
- Remove client CA certs and KEY!
(uncomment "//deleteKeychainEntries();" )
Disabled as long as selecting another cert is not supported by the UI.
<br/>

Windows: Workaround for CredWriteW used by QtKeychain

---

src/gui/sslerrordialog.cpp

@martin-sucha Thank you! :-) 👍 
I've created this new pull request to speed up getting this into master for our new release on Friday 😏 
@rullzer Please have a short look and approval since we both still have our heads in SSL stuff ^^
Original text:
MD5 has been broken for a long time now and SHA1 has been
deprecated as well. SHA1 is not used when issuing new
publicly trusted certificates since 1 January 2016[1] and
there are more and more effective attacks[2][3] against it,
so display SHA1 fingerprint only for old certificates
to encourage use of safer digests by users.
So, we display SHA-256 and SHA-512 fingerprints instead in
the common case.
[1] https://cabforum.org/wp-content/uploads/CA-Browser-Forum-BR-1.6.5.pdf
[2] https://shattered.io/static/shattered.pdf
[3] …

Use newer digest algorithms in TLS error dialog

---

src/libsync/clientsideencryptionjobs.cpp

Fixes at least: 
https://github.com/nextcloud/server/issues/12365
https://github.com/nextcloud/end_to_end_encryption/issues/87
#560 
#868 
#977 
#830 
Summary/problem: After E2E-activation on the server, desktop client fails on initial setup (wizard) or sync (when already configured).
Summary/bug: Missing content-type setting on QNetworkRequest when doing sendrequest() for the corresponding API job.

Fixing E2E CSR transmission failure for new connections

---

src/libsync/propagateupload.cpp

There in no "return" in
PropagateUploadFileCommon::slotStartUpload in if (prevModtime != _item-
>_modtime) {... }
There is possibility that
PropagateItemJob::done(status, errorString)
maybe called two times from PropagateUploadFileCommon::slotStartUpload
1. in if (prevModtime != _item->_modtime) {... }
2. in if (fileIsStillChanging(*_item)) {..}
if changes in files are frequent the second call is possible.
This two calls has effect in PropagatorCompositeJob::slotSubJobFinished
and job is removed two times in _runningJobs.remove(i);
(the second time with argumetnt -1 (because first call removed job).
This return was removed in commit
efc039863b096f0e39543001b6cb53937808bebf - by accident I think.
Good simulation is to synchronize firefox profile with frequent page
refresh.

Fix for #1382 "linux client crashes for no discernable reason"

---

src/gui/socketapi.cpp

Instead of only Nextcloud it says "Share via Nextcloud".

Changes wording in the share context menu.

---

src/gui/socketapi.cpp

'Share...' -> 'Share options'
'private link' -> 'internal link'
Removes 'to clipboard' from 'copy link' options.
Blame @jancborchardt :heart:

Improve wording of the context menu in the file manager extension.

---

src/libsync/account.cpp

Fixes #836
Finally found the time to track this down:
When the client has just started, the user shown in the tray menu is actually correct.  While establishing the connection, `davUser` is replaced by the DAV username from the server's JSON response:
https://github.com/nextcloud/desktop/blob/a1407209016bb8754ffae2f63ee8d634f123f2a1/src/gui/connectionvalidator.cpp#L303-L308
This PR replaces `davUser()` in `displayName()` with `credentials()->user()` which results in the actual username (that the user is aware of) being shown in the menu.

Use user-provided username in `displayName()` - Fix #836

---

.drone.yml

This patch modifies ```.drone.yml``` to trigger the Debian builds on the ```stable-2.6.0``` branch when it is tagged. This way the next releases will hopefully be built automatically.

Trigger builds for tagging on the 2.6.0 branch

---

src/gui/owncloudgui.cpp
src/gui/owncloudgui.h

This is a patch for #833:
Instead of adding the "Apps" menu after the apps are fetched, add it from the start (together with other actions) but in a disabled state, and enable it after the apps data is ready.
This way the menu items stay in place and don't jump below the Windows taskbar or go off screen.

Prevent jumping of tray menu

---

src/csync/csync_exclude.cpp
src/gui/socketapi.cpp
test/testsyncconflict.cpp
test/testsyncjournaldb.cpp
test/testsyncmove.cpp

Small optimization. Used const references in range-based loops to avoid copying every items

 Avoiding copying in range-based loops

---

src/gui/creds/flow2auth.cpp

The webserver lighttpd rejected POST requests without a Content-length header
with "411 Length Required".
See: https://github.com/nextcloud/desktop/issues/1473

Add a 'Content-Length: 0' header to initial POST requests

---

admin/osx/macdeployqt.py

Qt 5.12 needs this library to use the correct style for Light / Dark Mode:
- styles/libqmacstyle.dylib
The interface looks like from the 1990's without this library ;-)

Add new "styles" plugin to macOS deployment script for Qt 5.12.5

---

src/gui/application.cpp
src/gui/application.h

Problem: When you quit Nextcloud it shows the "New connection" wizard briefly before exit every time.
I nailed it down to the `accountRemoved` signal of `AccountManager` which is handled in `Application::slotAccountStateRemoved()`. That handler runs the connection wizard when there are no accounts left. Because all the accounts are removed from `AccountManager` during application shutdown, this event gets triggered at that time.
As a "fix" I added a new flag `_isQuitting` to the Application class that is set in the `aboutToQuit` handler (`slotCleanup`). This is probably a little ugly and there might be a better way to do it, e.g. remove the signal handler for `accountRemoved` instead of setting a flag, but I'm not 100% sure this would not break something, so I chose a safer route 😃

Don't run connection wizard when quitting the application

---

src/gui/CMakeLists.txt

With Qt 5.12.5 this OC crash also applies to the Nextcloud Desktop Client on macOS.
For reference please see:
- https://github.com/owncloud/client/issues/6930
- https://github.com/guruz/qtmacgoodies/commit/0dc7bc33282bdf3ea262cbd1e6c380a8ab9d6dcf
For the required changes in the qtmacgoodies submodule see:
https://github.com/camilasan/qtmacgoodies/pull/1

Pick from upstream: Update qtmacgoodies for an OSX crash fix #6930

---

src/gui/activitylistmodel.cpp
src/gui/activitylistmodel.h
src/gui/activitywidget.cpp

:warning: the text in the final version is: "Files from the ignore list as well as symbolic links are not synced. This includes:" instead of "Files listed..."
Related issues #1440, #1437.

Merge the list of ignored files/symlinks into one Activity notification.

---

src/CMakeLists.txt

The recently merged #1526 caused the MSVC Builds on Windows to fail.
This patch sets the new CMake flag only if the compiler it not MSVC.

MSVC Fix for PR #1526: Fix clang's variadic macro warnings

---

.drone.yml

Main improvement is that this image contains the libsecret.
So when building qtkeychain that should be used.

Bump Qt5.12 image

---

.drone.yml
CMakeLists.txt
cmake/modules/SanitizerFlags.cmake

Added a new cmake flag SANITIZE_ADDRESS,  which allows to perform address sanitizing.
Enable sanitizer for build and test in Drone ci.
I disabled leaks detecting, because  it requires a special environment, such as sanitized qt build.

Enabled address sanitizing for tests

---

src/gui/owncloudgui.cpp

As noted in comments in #1477 if you open tray context menu more than once, there will be duplicate items in the Apps menu. To fix it we should clear `_navLinksMenu` before adding items to it in `buildNavigationAppsMenu`.

Fix duplicate items in Apps menu (a bug introduced in #1477)

---

admin/linux/debian/debian.xenial/post-patches/qt5.5-compat.patch

Recently, HTTP/2 support was added by commit cf1532acf18a7e9f530a42b100ec9a437a0057fd. However, Qt 5.5, available in Ubuntu Xenial, does not support HTTP/2, hence the code does not work there. This patch reverts the effects of the commit in question for Xenial only.

Remove HTTP/2 support from Xenial

---

.drone.yml
admin/linux/build-appimage.sh
admin/linux/upload-appimage.sh

- Upgrades the AppImage build for Qt 5.12.5 in docker-ci
- Makes the upload optional and adds a timeout
- Small enhancements

Upgrade for Qt 5.12.5 in docker-ci

---

admin/osx/create_mac.sh.cmake

Use the --timestamp option for 'productsign' to add a secure timestamp.
See: https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution/resolving_common_notarization_issues

Add timestamp to Mac installer code signing

---

src/gui/creds/webflowcredentials.cpp
src/libsync/account.cpp
src/libsync/account.h

The app password for the remote wipe was constantly being written in `WebFlowCredentials::slotFinished` to the keychain, leading to unnecessary write and log overhead on the system.
This fix introduces a check to only store the app password once in a lifetime of the Account class. Also the method used to store the password will be renamed from `setAppPassword` to `writeAppPasswordOnce` to be more expressive.
Should solve these issues:
- #1592 
- #1607 
- #1638 
- #1639

Fix remote wipe keychain storage (issue #1592)

---

cmake/modules/MacOSXBundleInfo.plist.in

Happy new year for Mac too ;)
See PR #1641 
Fixes issue #1541

Fix copyright year in MacOSXBundleInfo.plist.in for 2019

---

shell_integration/dolphin/ownclouddolphinpluginhelper.h
src/gui/accountsettings.cpp
src/gui/folderstatusmodel.cpp
src/gui/owncloudgui.cpp
src/gui/owncloudsetupwizard.cpp
src/gui/selectivesyncdialog.cpp
src/gui/socketapi.cpp
src/gui/updater/ocupdater.cpp
src/gui/wizard/owncloudadvancedsetuppage.cpp
src/libsync/theme.cpp

Too many translations fail to keep the trailing space (it's invisible on transifex).
> ![image_2019-11-14_22-29-30](https://user-images.githubusercontent.com/213943/68897761-6efa2a00-072e-11ea-925b-5642d0b0646a.png)
So instead a placeholder is now used.

Improve the translation of "Share via …"

---

src/gui/activitydata.cpp

There is no need to call toMSecsSinceEpoch() as QDateTime implements an
comparison operator itself. This is more efficient, because the
QDateTimes comparison operator doesn't call localtime() in all cases. Thus, we
don't read /etc/localtime for every comparison. This improves
performance in some cases.
This should fix #942 .

Compare QDateTime objects more efficient

---

src/gui/creds/webflowcredentials.cpp
src/gui/creds/webflowcredentials.h
src/gui/remotewipe.cpp
src/libsync/account.cpp
src/libsync/account.h

With QtKeychain on Windows, storing larger keys in one keychain entry causes the following error due to limits in the Windows APIs:
`Error: "Credential size exceeds maximum size of 2560"`
To avoid overhead on the other platforms and balance code duplication, this approach puts some read- and write-parts into Windows-only defines.
For reference also see previous fixes:
- https://github.com/nextcloud/desktop/pull/1389
- https://github.com/nextcloud/desktop/pull/1394
This (again) fixes the re-opened issue:
- https://github.com/nextcloud/desktop/issues/863
Heavily tested on:

[WIP] Windows: Workaround for storing >= 4k (4096 bit) client-cert SSL keys

---

src/gui/activitylistmodel.cpp

Add checks to `ActivityListModel::combineActivityLists` in order to avoid adding empty Activity entries to the `_finalList`.
The previous implementation always added an empty entry to the top of the list because `_notificationIgnoredFiles` was appended without checking `(_listOfIgnoredFiles.size() > 0)`.

Fix Activity List: Add check to avoid first empty entry

---

src/gui/accountsettings.cpp
src/gui/accountsettings.h
src/gui/activityitemdelegate.cpp
src/gui/activityitemdelegate.h
src/gui/activitylistmodel.cpp
src/gui/activitylistmodel.h
src/gui/activitywidget.cpp
src/gui/activitywidget.h
src/gui/folderstatusdelegate.cpp
src/gui/folderstatusdelegate.h
src/gui/settingsdialog.cpp
src/gui/sharelinkwidget.cpp
src/gui/shareusergroupwidget.cpp
src/gui/wizard/owncloudadvancedsetuppage.cpp
src/gui/wizard/owncloudadvancedsetuppage.h
src/gui/wizard/owncloudhttpcredspage.cpp
src/gui/wizard/owncloudhttpcredspage.h
src/gui/wizard/owncloudsetuppage.cpp
src/gui/wizard/owncloudsetuppage.h
src/gui/wizard/owncloudwizard.cpp
src/gui/wizard/owncloudwizard.h
src/libsync/theme.cpp
src/libsync/theme.h

- Adjust error link colour in `AccountSettings::showConnectionLabel` to ease readability
- Dark-/Light-Mode switching: 
- Make `AccountSettings` and `ActivitySettings` background-aware
- Make `ActivityItemDelegate` background- and **selection**-aware
- Also implement cached member icons in `ActivityListModel` and return their `enum`'s to
`ActivityItemDelegate` instead of always recreating them for each call to `paint()`.
- Make `OwncloudWizard` and its pages background-aware
- Make all `ProgressIndicator`'s background-aware
- Mac and high-dpi displays: Add workaround in `ActivityItemDelegate` to show full uncropped activity's `actionText` and `timeText`
- Change Dark Mode link colour
- Some refactoring

Fix macOS GUI (Qt 5.12) No. 2 (continuation of #1651)

---

src/gui/activitylistmodel.cpp

Adds date and time to the activity log entries:
Takes the local timezone and format into account.
This fixes issue #1683.

Show date and time in activity log (fixes issue #1683)

---

src/gui/activitylistmodel.cpp

- Fixes a crash when double-clicking on Activity list rows (#1693).
- After fixing the crash in the previous commit, double-clicking on Activity list rows still didn't work.
This fix partly reverts commit 8546d53 in `ActivityItemDelegate::PathRole` of `ActivityListModel::data`, but adds a new check for `relPath`'s existence in line 74.
I'm assuming the previous change there has been done to shorten the code and avoid opening the user's home folder upon clicking entries which file value is "`App Password`". The new path-check takes care of that too now.

Activity List: Fix crash and folder opening

---

src/gui/CMakeLists.txt
src/gui/creds/keychainchunk.cpp
src/gui/creds/keychainchunk.h
src/gui/creds/webflowcredentials.cpp
src/gui/creds/webflowcredentials.h

With `QtKeychain` on Windows, storing larger keys or certs in one keychain entry causes the following error due to limits in the Windows APIs:
`Error: "Credential size exceeds maximum size of 2560"`
This fix implements the new wrapper class `KeychainChunk` with wrapper jobs `ReadJob` and `WriteJob` to encapsulate the `QKeychain` handling of `ReadPasswordJob` and `WritePasswordJob` with `binaryData` but split every supplied keychain entry's data into 2048 byte chunks, on Windows only.
The wrapper is used for all keychain operations in `WebFlowCredentials`, except for the server password.
For reference also see previous fixes:
- https://github.com/nextcloud/desktop/pull/1389
- https://github.com/nextcloud/desktop/pull/1394
This should finally fix the re-opened issue:
- …

Heavy refactoring: Windows workaround for >= 4k (4096 bit) client-cert SSL keys and large certs

---

src/gui/activitywidget.cpp

The local date and time value was converted into a string, just to be converted
into another string, to be converted to a value once again, returning zero as
the result. This caused the widget to always display "now". 🤪
Looks like this was a simply copy and paste mistake from this line in
`ActivityListModel::slotActivitiesReceived`:
`a._dateTime = QDateTime::fromString(json.value("date").toString(), Qt::ISODate);
`
This also belongs to issue #1683.
cc @camilasan Funny one ^^

Fix date in ActivityWidget and remove unnecessary string conversion

---

src/gui/sharedialog.cpp
src/gui/sharedialog.h
src/gui/socketapi.cpp

Fixes #1485
This was missed when creating the new share dialog.
Now it pops up with a nice share password dialog to enter for your link
share.
To test. Just enforce password protection on your system.
Before: :boom:
Now: :rocket:

Ask for password on password protected link shares

---

src/gui/navigationpanehelper.cpp

- Ensure that the folder integration stays persistent in Explorer,
the uninstaller removes the folder upon updating the client.
Recreate all entries upon start. This has the benefit of removing
old remains of non-working, outdated entries.
- Don't crash on the other systems when the user clicks the option
button "Show sync folders in Explorer's Navigation Pane".
Even though the option currently doesn't work on the other platforms,
crashing is never good...

Fix Explorer integration on Windows and the crash on other systems

---

src/libsync/discoveryphase.cpp

Throw error for broken shared folder/file but allow syncing to continue without causing Desktop client to break totally.
https://github.com/nextcloud/desktop/issues/908
https://github.com/nextcloud/desktop/issues/819

BugFix: Handle broken shared file error gracefully

---

src/gui/connectionvalidator.cpp
src/gui/socketapi.cpp
src/gui/socketapi.h
src/libsync/account.cpp
src/libsync/account.h
src/libsync/capabilities.cpp
src/libsync/capabilities.h
src/libsync/networkjobs.cpp
src/libsync/networkjobs.h

- Allow direct editing _"Edit"_ when an editor is available for the mime type
- Show _"Open in browser"_ if editing is unavailable (as previously, both now on top of the menu list)
- Rename the menu title to the app name, _"Nextcloud"_ instead of _"Share via ..."_
- Fetch in `ConnectionValidator::slotCapabilitiesRecieved`
- Add editors to a list made of the new `DirectEditor` class
**TODO:**
- Add support for re-fetch and continuously check for changes (ETag)
- `JsonApiJob`: Add method `usePOST` to allow anonymous `POST` requests
Thanks to @tobiasKaminsky and @juliushaertl for guidance! ❤️ 
And to @camilasan for the super helpful PR #1442 🚀

Add direct editing to the file manager extension

---

admin/linux/build-appimage.sh

Fixes failing AppImage building due to wrong qmldir path

Testing fix for qmldir import with linuxdeployqt AppImage

---

src/gui/iconjob.cpp

Recent change cd80c749d66596ab13d9c4ffb74509b1ab042eda started to usage symbol `QNetworkRequest::FollowRedirectsAttribute` which is introduced only in Qt 5.6, hence the code stopped compiling for Ubuntu Xenial which has Qt 5.5. 
This patch makes the usage of this symbol conditional on the Qt version.

Qt 5.5 compatibility ifdef

---

src/libsync/propagatedownload.cpp
test/syncenginetestutils.h
test/testdownload.cpp

The patchup is still from owncloud.
As the Qt bug report suggests, Qt only auto resend using http1 and the maintainer suggest implement http2 resend by ourself.
The detailed bug report from Qt:
https://bugreports.qt.io/browse/QTBUG-75573
https://bugreports.qt.io/browse/QTBUG-73947

apply http2 qt resend patch from owncloud

---

src/gui/clientproxy.cpp

If the client has never been setup before and no configuration file is present yet, the client should use the system proxy by default. Otherwise the setup wizard will fail to run the server check when setting up the connection in https://github.com/nextcloud/desktop/blob/master/src/gui/owncloudsetupwizard.cpp#L158-L161

Use system proxy by default if no config file is present

---

src/gui/sharelinkwidget.cpp

Do not show the note edit field for empty new shares.

Am empty note is not a valid note

---

admin/linux/debian/debian/nextcloud-client.install

These two files were missing from the packaging making libcloudproviders unaware of nextcloud service

Install libcloudproviders files by default on debian

---

admin/linux/debian/debian.xenial/nextcloud-client.install

Since `libcloudproviders` does not exist on Xenial, the related code is not compiled there. Hence the associated directories are also missing and trying to install them into the package causes a build failure. 
This patch adds a Xenial-specific `nextcloud-client.install` file to fix this problem.

Do not install files related to cloud providers under Xenial

---

src/gui/shareuserline.ui

Using "username" like on > 200 strings over the whole Nextcloud project.
Signed-off-by: rakekniven mark.ziegler@rakekniven.de

l10n: Changed spelling of "user name" to "username"

---

src/libsync/propagateuploadng.cpp

Should fix at least the core issue in #1182 (comments in issue started to furiously mix different use and error cases, so I'm cautious with the "fix" wording here). An If-Match extra header was set with an wrongly encoded path. toUtf8() on the destination resulted in an unreadable path when it contains umlauts, alway resulting in an error when propagating the final MOVE instruction to the server after a file with such umlauts has changed.

Fix wrong encoding when specifying extra header with if-match path

---

src/gui/updater/updater.cpp
src/libsync/configfile.cpp
src/libsync/configfile.h

Used to throttle down desktop release rollout in order to keep the update servers alive at peak times.
See: https://github.com/nextcloud/client_updater_server/pull/36
Targeted issues: #1795, #1800

Updater: Add query-parameter 'updatesegment' to the update check

---

src/gui/generalsettings.cpp
src/gui/navigationpanehelper.cpp

- Fixes issue #1807
- Hides the option check-box on non-Windows systems because currently there is no implementation for this option on other platforms.
This is an addition to PR #1720

Fix Explorer integration re-save and hide option on non-Windows

---

src/libsync/accessmanager.cpp

Disable HTTP/2 for now due to Qt bug but allow enabling it via env var,
see: https://github.com/owncloud/client/pull/7620 and: https://github.com/nextcloud/desktop/pull/1806
Issue: https://github.com/nextcloud/desktop/issues/1503
The build had to be fixed for older Qt versions, so this PR supersedes #1806 to reintroduce the `#if`.

Disable HTTP/2 for now due to Qt bug, allow enabling it via env var

---

src/gui/creds/webflowcredentials.cpp

Fixes issue #1741
cc @rullzer @camilasan

WebFlowCredentials: Make username comparison case-insensitive (fix #1741)

---

shell_integration/windows/OCContextMenu/OCContextMenu.cpp
src/gui/socketapi.cpp
src/gui/socketapi.h

Fixes #1599
- Add fallbacks for Explorer Shell commands
- Incorporate upstream patch: https://github.com/owncloud/client/pull/7056

Fix Explorer pinning: Add fallbacks for Shell commands (fixes #1599)

---

admin/linux/debian/scripts/git2changelog.py
admin/osx/macdeployqt.py
admin/win/nsi/l10n/bin/build_locale_nsi.py
shell_integration/nautilus/syncstate.py

Fix some Python 3 related syntax errors, undefined names, etc.
[flake8](http://flake8.pycqa.org) testing of https://github.com/nextcloud/desktop on Python 3.8.1
$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./shell_integration/nautilus/syncstate.py:301:29: F821 undefined name 'isDir'
elif state_sync and isDir:
^
./admin/win/nsi/l10n/bin/build_locale_nsi.py:168:56: E999 TabError: inconsistent use of tabs and spaces in indentation
NSIDeclarations.append( tostr('Var %s\n' % label) )
^
./admin/linux/debian/scripts/git2changelog.py:144:15: E999 SyntaxError: invalid syntax
print baseVersion, kind
^
./admin/osx/macdeployqt.py:77:9: E999 SyntaxError: invalid syntax
print 'Usage: %s <bundle.app> <path-to-qmake>' % sys.argv[0]
^
3     E999 SyntaxError: invalid syntax …
```

Use print() function in both Python 2 and Python 3

---

src/gui/application.cpp
src/gui/legalnotice.cpp
src/gui/legalnotice.h
src/gui/legalnotice.ui
src/libsync/theme.cpp
src/libsync/theme.h

- Show missing `--version` syntax in `--help` screen:
```
[...]
Options:
-h --help            : show this help screen.
--version            : show version information.
--logwindow          : open a window to show log output.
[...]
```
- Show Qt platform plugin, OS and CPU arch in `--version` output:
```
Nextcloud version 2.7.0daily (build 20200306)
Git revision aa5556b7d077a5854d7baf49e96cf4a90291ec4d
Using Qt 5.12.5, built against Qt 5.12.5
Using Qt platform plugin 'cocoa'
Using 'OpenSSL 1.1.1d  10 Sep 2019'
Running on macOS Mojave (10.14), x86_64
```

Enhance Version info display (minimal info, hide details)

---

.drone.yml
CMakeLists.txt
NEXTCLOUD.cmake
admin/linux/build-appimage.sh
src/gui/CMakeLists.txt
src/gui/application.cpp
src/gui/generalsettings.cpp
src/gui/generalsettings.h
src/gui/generalsettings.ui
src/gui/main.cpp
src/gui/updater/ocupdater.cpp
src/libsync/configfile.cpp
src/libsync/configfile.h

- Add checkbox and button to UI
- Add new parameter autoUpdateCheck to ConfigFile
- Fix OCUpdater: Also change status on network error or invalid XML
- Default: `BUILD_UPDATER` = `NO`
To ease builds for distro packages and contributors (regardless of the specified update URL)
- Enable updater build for Drone CI and AppImage builds
- Resurrect auto-update functionality (macOS (Sparkle) work in progress, Windows next)
- Add support for update channels: stable, beta

Updater: Enhance UI, make build optional

---

src/gui/wizard/webview.cpp

Discovered while playing around with Qt's language tool `lupdate`, it produced a warning.
cc @rullzer @camilasan

WebView: Add missing Q_OBJECT macros

---

admin/linux/debian/debian.oldstable/nextcloud-client.install

The Debian oldstable distribution does not have libcloudproviders, and the build fails when it wants to install the files in the directories that are present only if libcloudproviders is used.
This patch adds a specific .install file, which does not contain any reference to those directories.

Provide specific install file for Debian oldstable

---

src/gui/systray.cpp

This allows the notification server to map a notification to the program's desktop file, which allows the server to do extra things. For example KDE Plasma adds the Nextcloud icon to the notification and allows to configure notifications from Nextcloud.
This is a standard hint from https://specifications.freedesktop.org/notification-spec/notification-spec-latest.html#hints

Add desktop-entry hint to notifications

---

src/gui/systray.cpp
src/gui/systray.h

It it never set by calling code so the default value of 10000 is used. It is only used in the call to QSystemTrayIcon, which uses 10000 as default value too.

Remove timeout parameter from showMessage

---

src/common/checksums.cpp

clazy suggests that it is more efficient since it doesn't allocate.

Use qEnvironmentVariableIsEmpty

---

shell_integration/dolphin/ownclouddolphinpluginhelper.cpp
shell_integration/dolphin/ownclouddolphinpluginhelper.h

config.h needs to be included in the header already since we use APPLICATION_ICON_NAME there. This got introduced in 6fc877577c84e2ed3b175ee1425255e52d1d37b4

Fix build of Dolphin integration

---

shell_integration/dolphin/ownclouddolphinoverlayplugin.cpp

When the filename contains a ':' it gets split too much and tokens[2] does not contain the full filename any more. Read the name from the original line instead.
Fixes #686

[dolphin] Fix overlays when filename has a colon

---

src/libsync/syncengine.cpp

Xenial uses Qt 5.5 which does not yet support qAsConst. This patch adds a definition for it if Qt is earlier than 5.6.

Qt 5.5 compatibility #ifdef

---

src/libsync/networkjobs.cpp

QPainterPath is no longer included via qtransform.h (since
5.15.0-beta2, 50d2acdc93b4de2ba56eb67787e2bdcb21dd4bea in
qtbase.git).

Fix build with Qt 5.15

---

src/gui/cloudproviders/cloudproviderwrapper.cpp

The _recentMenu pointer ref should not be freed, when building the
menu.
This fixes #1920 and #1818

CloudProviders: Don't clear the _recentMenu pointer

---

admin/linux/debian/drone-build.sh

Ubuntu Disco is no longer supported by Launchpad, and the next Ubuntu release, Groovy is available.

Remove Ubuntu Disco, add Groovy

---

admin/linux/debian/debian.groovy/changelog
admin/linux/debian/debian.groovy/control

Some Debian control files must be updated for Groovy to build the binary packages successfully.

Add Groovy-specific files

---

admin/linux/debian/drone-build.sh
admin/linux/debian/scripts/git2changelog.py

Two major changes are introduced by this PR related to the Debian builds:
- Currenty the version numbers are generated from the timestamps of commits. However, it sometimes happens that an older commit is merged later than a newer one, in which case the version number of the commit merged later is smaller than that of the commit merged earlier. This is then rejected by Launchpad. The first commit makes the version to be generated from the build's timestamp. It also adds the commit ID in case two builds were run at exactly the same time and also for an easier identification of the commit the build was generated from.
- Currently there are two PPAs: one for stable builds and another for "beta" ones. The "beta" here means the builds from the master branch, which are arguably more like …

Debian versioning updates

---

src/gui/iconjob.cpp

I have been experiencing the following two issues with the desktop client on linux:
https://github.com/nextcloud/desktop/issues/1769
https://github.com/nextcloud/desktop/issues/1876
After a bit of digging, I can that the IconJob class is creating a new QNetworkAccessManager every time an icon is downloaded (as part of the activity widget and servernotificationhandler.cpp.
Technically, only one QNetworkAccessManager should be needed per application, so creating one per download is not great. However, the IconJob class is also never explicitly freed and does not have a QObject parent, so cannot be freed by Qt.
So we have a memory leak. Over time more and more QNetworkAccessManagers are created and never freed, eventually leading to the errors experienced in the named tickets.
This PR is a …

Free IconJob after use

---

admin/linux/debian/drone-build.sh
admin/linux/debian/scripts/git2changelog.cfg
admin/linux/debian/scripts/git2changelog.py

The Debian ownCloud maintainers team (https://salsa.debian.org/owncloud-team) created official Debian packages for the desktop client some time ago. They worked independently of me so they used different package names and a somewhat different package structure as well. It meant that if someone has installed their version and then wanted to upgrade to the PPA version, there were file conflicts.
Because of this and to avoid duplicate work, I have contacted the Debian team and based on our discussions I have updated the build scripts to work with a more Debian-y way to structure the repo. The main difference is that there are now branches for the various distributions and main tracks (e.g. debian/dist/bionic/master or debian/dist/eoan/stable-2.6) which are branched out from the corresponding …

Reorganize Debian build

---

shell_integration/nautilus/syncstate.py

Fixes issue #1948
The client already resolves symlinks when adding new paths to the
sync-list, but the Nautilus plugin did not do this yet, causing it
to not recognise synced folders if they were accessed via a symlink.

Resolve symlinks when checking for registered paths.

---

src/gui/CMakeLists.txt
src/gui/main.cpp

This works around a bug in KDE's qqc2-desktop-style which breaks buttons
with icons not based on a name. By forcing a style name the KDE Plasma
platformtheme plugin won't try to force qqc2-desktops-style anymore.
Can be removed once the bug in qqc2-desktop-style is gone.

Force the default QQC2 style

---

src/gui/tray/Window.qml

This is necessary with some window managers which would otherwise
consider they can reposition and resize the tray window as they wish
(yes, even though the user can't do it directly).
This is for instance the case if you use the tiling mode scripts of
KWin. It automatically ignores dialogs but might force windows to be
fullscreen (which would badly break the layout in our case).

Indicate this is a dialog and not a regular window

---

admin/linux/debian/drone-build.sh

With the recently introduced QQC2, Qt 5.5 and thus Xenial cannot be supported anymore. This patch removes the build for Xenial.

Do not build for Xenial anymore

---

CMakeLists.txt
cmake/modules/SanitizerFlags.cmake

This PR adds support for more sanitizers than only `AddressSanitizer`
in the CMake configuration.

Improve sanitizer support

---

src/libsync/networkjobs.cpp
test/testxmlparse.cpp

In case of denormalized paths in the dav href (presence of . or .. in
the path) simple string startsWith comparison wasn't enough to know if
said href ended up in the right namespace. That's why we're now using
QUrl (pretending local file since we don't have a full URL in the href)
to normalize the path before comparison.
This could happen with broken proxies for instance where we would
wrongly validate the dav information resulting in potentially surprising
syncing and name collisions.

Properly handle denormalized href

---

README.md

Update the issue and open PR links with the new repository URL.
The old URL is forwarded, but feels not completely right.

Update github links to desktop repository

---

src/common/syncjournaldb.h
src/common/syncjournalfilerecord.h
src/gui/folder.h
src/gui/folderstatusmodel.h

This PR introduces default member initialization, a C++
feature available since C++11, in a few locations to
replace the explicit definition of a default constructor.

Use default member initialization

---

admin/linux/debian/drone-build.sh

Since the code on the master branch now requires at least Qt 5.12, the code cannot be built in any meaningful way on some distributions. This patch removes such builds, but also adds Debian testing.

Do not build master for distributions without Qt 5.12 or later

---

src/libsync/abstractnetworkjob.cpp

This is the same value than the initializer value in the header, no need
to repeat it.

Remove redundant initializer

---

test/testutility.cpp

This test was failing locally for me. Indeed, through QStandardPaths it
was finding the user settings of my production client and not having the
initial state it expected. Using QStandardPaths test mode then it starts
from a clean slate every time.

testLaunchOnStartup shouldn't fail on dev setup

---

cmake/modules/MacOSXBundleInfo.plist.in

Required for our build server that uses an older SDK to support previous macOS versions.
See: https://developer.apple.com/documentation/appkit/nsappearancecustomization/choosing_a_specific_appearance_for_your_macos_app

macOS: Opt In to Dark Mode for building against older macOS SDKs < 10.14

---

src/common/utility_unix.cpp

Previously we wrote 'nextcloud', but our icon name is 'Nextcloud'.

Use APPLICATION_ICON_NAME for autostart icon

---

src/common/utility_unix.cpp

Backport of #2065
(cherry picked from commit bce93b052b24c23d76a9f9b8864d71b0ad5b040e)

[stable-2.6] Use APPLICATION_ICON_NAME for autostart icon

---

src/gui/tray/Window.qml

The app menu has a width based on the header button size which is
way too narrow to display its content, see #2012.
This PR changes the width based on the contents (menu items) of
the menu, however, limiting the maximum width to half the window width.

Change width of app menu

---

shell_integration/windows/OCUtil/RegistryUtil.cpp

Merging PR #2057 caused the Windows build to fail:
`shell_integration\windows\OCUtil\RegistryUtil.cpp(43): error C2664: 'LSTATUS RegOpenKeyExW(HKEY,LPCWSTR,DWORD,REGSAM,PHKEY)': cannot convert argument 3 from 'nullptr' to 'DWORD'`
The previous implementation prior the PR supplied NULL as the argument 3 to RegOpenKeyEx, so it was silently accepted and translated to zero, satisfying the DWORD's type requirement.
See also: https://docs.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-regopenkeyexw
```
LSTATUS RegOpenKeyExW(
HKEY    hKey,
LPCWSTR lpSubKey,
DWORD   ulOptions,
REGSAM  samDesired,
PHKEY   phkResult
);
```

Fix nullptr regression in RegistryUtil::ReadRegistry

---

shell_integration/windows/OCContextMenu/OCContextMenuFactory.cpp
shell_integration/windows/OCContextMenu/OCContextMenuRegHandler.cpp
shell_integration/windows/OCOverlays/OCOverlayFactory.cpp
shell_integration/windows/OCOverlays/OCOverlayRegistrationHandler.cpp
src/common/utility_mac.cpp
src/csync/csync.cpp
src/csync/csync_update.cpp
src/csync/csync_util.cpp
src/csync/std/c_utf8.cpp
src/csync/vio/csync_vio.cpp
src/csync/vio/csync_vio_local_unix.cpp
src/csync/vio/csync_vio_local_win.cpp
src/gui/accountsettings.cpp
src/gui/folderman.cpp
src/gui/folderwatcher_linux.cpp
src/gui/owncloudgui.cpp
src/gui/systray.cpp
src/gui/tray/UserModel.cpp
src/libsync/bandwidthmanager.cpp
test/csync/encoding_tests/check_encoding.cpp

This is a continuation of #1988 and #2057.
Make the codebase consistent, we already have a lot of implicit pointer comparisons.
Exception: Stay explicit on `return`'s, example:
`return _db != nullptr;`

Simplify nullptr comparisons where appropriate

---

src/common/utility.h
src/common/utility_win.cpp
src/gui/systray.cpp
src/gui/systray.h
src/gui/tray/Window.qml

tl;dr: Linux DEs are an unstandardized mess (no flaming, it is how it is.). Apart from that the whole positioning should now be really stable on Windows, macOS and KDE/Plasma. This is what I tested with (multiple monitors, single monitors, taskbar/panels in all possible orientations and layouts, with and without highDPI scaling).

Major multi monitor improvements and rewrite of tray window positioning

---

src/gui/systray.cpp
src/gui/tray/UserLine.qml
src/gui/tray/Window.qml

Context properties are deprecated and will be removed in Qt 6. QML singletons are the better option here, especially given that the types already are singletons.

Port from context properties to singletons

---

src/gui/socketapi.cpp

We were calling accountState() on a "folder" member which could be
nullptr. In fact this would happen any time one right click on a file
outside of a sync dir under Windows, this thus led to a crash.
Since the capabilities variable was unused anyway, we just removed it.
This should fix #1804 and fix #2054.

Don't call method on potentially null object

---

src/gui/application.cpp
src/gui/application.h
src/gui/main.cpp
src/gui/owncloudgui.cpp
src/gui/owncloudgui.h

This tries to fix #1772.
That being said it doesn't address the right click case on the Linux desktop completely (per the explanations in the relevant commit and in my comments on #1772).

Ease access to main dialog

---

sync-exclude.lst

Add photothumb.db file that is thumbnails generated by Photoscape application (generated in every folder with graphic files).

Add photothumb.db to sync-exclude.lst

---

src/gui/connectionvalidator.cpp
src/gui/owncloudsetupwizard.cpp
src/libsync/clientproxy.cpp
src/libsync/clientproxy.h

Build failed on Windows, missing `libsync` export for `printQNetworkProxy` after moving `ClientProxy` class from `gui` to `libsync` in #1886.

Fix libsync exports for proxy changes in #1886

---

src/gui/tray/Window.qml
theme/Style/Style.qml

The lightgray menu border color `#ededed` introduced in
commit f147e5a66f43657805542904b43e0b4e662ffe04 (by PR #2095)
is way too light for my display (and probably others).
Thus the menus have no clear border which looks odd and broken.
This commit simply darkens the menu border to `#808080`.

Darken menu border color

---

src/gui/owncloudgui.cpp
src/gui/systray.cpp
src/gui/systray.h

Commit a12205f322d43476230881192616e47c9cf786ef (PR #1891) introduced a circular ownership: `qmlRegisterSingletonType<Systray>(...)` makes the `QQmlEngine` own the resulting singleton `Systray` instance, however, the `QQmlEngine _trayEngine` itself is owned by the `Systray` instance. This circular ownership results in a crash when the destructor of `Systray` calls the destructor of `_trayEngine` which attempts to call the destructor of `Systray` again.
This commit solves this problem by making `ownCloudGui`, which is the parent of `Systray`, the parent of `_trayEngine`.

Fix SEGV (due to circular ownership) at exit

---

src/gui/owncloudgui.cpp
src/gui/systray.cpp
src/gui/systray.h
src/gui/tray/Window.qml

Update systray behavior and context menu:
- left click brings up the new QtQuick based dialogs on all latforms
- right click brings up the new QtQuick based dialog on Mac OS only
- right click brings up a context menu on all other platforms than Mac OS
- "Quit Nextcloud" => "Quit"
- Add "Open Main Dialog" option: add new slot to show the main dialog and fix
open settings slot to correctly show the settings.
Fix #2085

Fix issue 2085

---

src/gui/accountsettings.cpp
src/gui/accountsettings.h
src/gui/userinfo.cpp

The code handling the api response was not up to date with the latest
api changes.
fixes #2143

Don't display quota information when the user has no quota.

---

src/common/syncjournaldb.cpp
src/common/syncjournalfilerecord.h
src/csync/csync.cpp
src/csync/csync.h
src/csync/csync_reconcile.cpp
src/csync/csync_update.cpp
src/libsync/clientsideencryption.cpp
src/libsync/clientsideencryption.h
src/libsync/owncloudpropagator.cpp
src/libsync/owncloudpropagator.h
src/libsync/syncengine.cpp
src/libsync/syncengine.h

This deals with all types of move involving E2E which are now treated as delete + upload. Unfortunately that includes also renames local to the same folder, but that would require further changes, I'll consider that as an optimization we can keep for later.
Fix #940

Fix e2e moves handling

---

src/gui/tray/UserLine.qml
src/gui/tray/Window.qml

Could also be done in other ways, this seemed to be the most consistent regarding the other hover adjustments in Window.qml.
before:
after:

Fix hover cutoff in apps menu

---

src/gui/tray/Window.qml

Turns out that the ListView embedded in the Menu (reachable via
contentItem) would create a binding loop if we're using its
childrenRect. But really we're interested in the total width for the
instantiated delegate *inside* the ListView. That's why we go one level
deeper and get the childrenRect of the inner contentItem instead.

Reach out to the contentItem inside of the ListView to find the width

---

src/gui/tray/Window.qml

The menus may become too large if they have too many items
(the account menu has this in case of many accounts, the apps
menu in case of many apps).  This commit limits the maximum
height such that the menus do not hide the header.
Fixes #2160.

Set maximum height of account and app menu

---

src/libsync/networkjobs.cpp

If we try to produce the avatar before we managed to connect we'd end up
trying to paint in a null image. Just return early, which will allow the
caller to do something else instead.

Handle properly null avatar

---

src/cmd/cmd.cpp

PR #1451 changed the behavior of makeDbName which now returns an
absolute path. This obviously then failed in nextcloudcmd which
prepended to it the path to the local folder to sync. We just stop doing
this to have the journal db end up at the right place in that case as
well.

Adjust to makeDbName returning an absolute path

---

.drone.yml
src/csync/csync.h
src/gui/elidedlabel.cpp
src/gui/folderstatusdelegate.cpp
src/gui/systray.cpp
src/libsync/clientsideencryption.cpp
src/libsync/creds/httpcredentials.cpp
src/libsync/syncfilestatus.cpp

Although clang-tidy was invoked on Drone, its errors were not recognized as errors. This is fixed now. Moreover, the output of clang-tidy is filtered to reduce noise, and the upcoming clang-tidy errors are fixed.

Fix clang-tidy issues on Drone

---

src/gui/ocssharejob.cpp
src/gui/sharepermissions.h
src/gui/shareusergroupwidget.cpp

- The default displayed was not in sync with the server because
the client was setting permissions when creating a share while it
should get the default permissions from the server to display it to the
user first.
server:
client:

Display the correct default permissions when creating a share.

---

src/libsync/propagateremotemkdir.cpp

Turns out that when we added a new e2e folder during sync, we were
passing the wrong path to the e2e object. We have several path
convention in the sync code, just happened to be the wrong one.
I still long for the day when we'll use the type system to deal with
paths. All those strings are error-prone.

Properly register folder as encrypted during sync

---

src/libsync/syncengine.cpp

This is merely a hotfix for https://github.com/nextcloud/desktop/issues/1433 as finding the real cause obviously seems to be a bigger task. However this check shouldn't bring any drawbacks so it's probably a good option for the moment.
Summary of the situation:
- There are reports about the client deleting everything on the server
- Reports are quantitatively low, but exist as independent occurences for a longer time period including current stable release
- After inspecting logs and the csync algorithm it seesm to me that "Deleting everything" happens in the reconciliation phase. Specifically, as those occurrences happen with DELETE instructions in the UP direction (sending deletes for all root folders to …

Prevent empty FileMap in local csync to be processed if folder not empty

---

src/libsync/syncengine.cpp

Backport of #2183 
(cherry picked from commit d47e570ff3562b9d5d5e9178269b297775626746)
(cherry picked from commit f8920f969fc4aeb90e5b50ec1c7aa087150cbc04)

[stable-2.6] Prevent empty FileMap in local csync to be processed if folder not empty

---

admin/linux/debian/drone-build.sh

The changelog generator used for Debian builds depends on tags being present. However, it seems Drone does not fetch the tags, so the patch adds a command to the build script to do so.

Fetch tags for Debian build

---

src/gui/folderman.cpp

Attempt to fix #2186 
When the changes to the syncjournal db file locations to rely in OS specific AppData folders where implemented in #1451 , no migration of possibly existing db files was considered. As these files may contain persistent settings and states like sync settings seen in the issue above, this should be the case.
This PR implements a simple, conditional move (`QFile::rename`) of old files to the new ones within existing migration functions.
Testing needed, this is a first draft.
Regarding the downgrade-comment on the issue: No, they were not hanging around, but deleted (which is generally what makes sense, leaving cleaned up files as trash behind just in case a downgrade will happen can't be a …

Move existing syncjournal db files from client ver <2.7

---

src/gui/systray.cpp

Fix #2166 
Previously we were using QCursor::pos() in the Linux case, which is a
fair heuristic except it will always be relative to the primary screen
and not the current screen. This explains why we had to adjust with the
virtual geometry.
In the Windows and Mac case we got the position out of QSystemTrayIcon
and that one was already relative to the current screen.
So now we use QCursor::pos(currentScreen()) which ensures we give the
coordinates relatively to the current screen also in the Linux case.
Since all platforms are now having that point in the same coordinate
system we don't need to mess around with the virtual geometry to
compensate.

Make sure the tray icon point is in screen coordinates

---

doc/conflicts.rst

Signed-off-by: Jacob Neplokh <me@jacobneplokh.com>
Resolves nextcloud/documentation#2171
--
This changes an ownCloud reference in the docs to Nextcloud.

Change ownCloud reference to Nextcloud

---

.drone.yml
admin/linux/upload-appimage.sh

Uploading _AppImage_'s to `transfer.sh` often fail and cause the CI to wait for the 15 minutes timeout.
This new approach uses a bot user to create releases in a dedicated `ci-builds` repository. Each PR (or master) will get a dedicated release with the _AppImage_ supplied as a release asset. Older assets will be deleted prior uploading the recent build.
The bot will then (in case of a PR) create a comment in the PR, containing the download link.
Home of the CI releases: https://github.com/nextcloud-desktop-bot/ci-builds/releases
Inspired by: https://github.com/nextcloud/android/blob/master/scripts/uploadArtifact.sh

Drone: Upload AppImage to GitHub using nextcloud-desktop-bot

---

src/gui/owncloudgui.cpp
src/gui/systray.cpp
src/gui/systray.h

Fixes #2207 
Fixes #2206 
Changes:
1. Fix of a (apparently) copy/paste bug where the same signal (pause) was used for resume and pause slots.
2. Proper initial setting of _syncIsPaused state variable on Systray creation method (e.g. when accounts are populated and set up, if existing) to ensure correct qml gui dropdown entry text

Fix pause sync states

---

.drone.yml
admin/linux/build-appimage.sh
admin/linux/upload-appimage.sh

Update CI for Qt 5.12.9
Also remove the `jq` package installation from the AppImage upload script because the package is included in the new Docker image (see nextcloud/docker-ci#231 and #2213).

Update CI for Qt 5.12.9

---

src/gui/owncloudgui.cpp
src/gui/systray.cpp
src/gui/systray.h

The context menu offers to open the main dialog and the settings
even if no accounts are configured.  In this case, the main dialog
is useless and the settings are probably confusing.  Hence, this
commit replaces these actions in the context menu by an action
to open the wizard (which also opens on left click, so this is
the most natural thing to do).

Let context menu open wizard if there are no accounts

---

src/gui/tray/Window.qml

- Fix #2173.
- Removed the workaround for the left round corner which was also
fixed with the OpacityMask.

Add OpacityMask to fix mouse hover on round corner. 

---

src/gui/systray.cpp

The context menu should allow access to the Settings even when no accounts are configured.
Users may specify proxy / startup / update and other settings at any time.
This slipped through in #2164.

Always show Settings in the context menu (amends #2164)

---

src/CMakeLists.txt

See:
https://docs.microsoft.com/en-us/windows/win32/secbp/control-flow-guard
https://docs.microsoft.com/en-us/cpp/build/reference/safeseh-image-has-safe-exception-handlers
Also interesting to play around with for verifying security flags:
https://blog.netspi.com/verifying-aslr-dep-and-safeseh-with-powershell/ (<- [Repo](https://github.com/NetSPI/PESecurity))
For running in processes (in _PowerShell_):
`Get-ProcessMitigation -Name .\nextcloud.exe -RunningProcesses`

Windows: Enable CFG and SafeSEH linker security flags

---

src/gui/folderman.cpp

We update properly the CLSID of folders to integrate them with the
Explorer pane when they are added or removed from the GUI. That said,
there might be cases of users adding folders to sync straight from the
GUI. In such a case the CLSID might be missing on config load so now we
assign one on the fly when that happens.

Make sure we always have a CLSID when Explorer integration is used

---

src/gui/accountsettings.cpp

We lost the ability to display the E2EE mnemonic during the GUI
redesign and the info message wasn't displayed again on restart. So now
we display it every time, it still can be dismissed and the button text
is different in such a case to make the intent clearer.
Fix #2251 
Fix #2252

Keep the E2EE info message around to allow displaying mnemonic

---

src/common/c_jhash.h

The file ```src/common/c_jhash.h``` is included from a C file, ```test/csync/std_tests/check_std_c_jhash.c```. As this file is C code, when it is compiled, ```stdint.h``` should be used instead of ```cstdint```.

Include cstdint only when compiling C++ code

---

src/libsync/syncfilestatustracker.cpp

It happens that sometimes we leak a directory path ending with a slash,
but that violates fileStatus' precondition so let's catch it early and
skip such path.
Of course the right fix would be a larger swipe in the sync engine and
around it to not use naked strings anymore but rely on the typesystem.

Make sure we don't assert when calling fileStatus

---

src/libsync/syncfilestatustracker.cpp

It happens that sometimes we leak a directory path ending with a slash,
but that violates fileStatus' precondition so let's catch it early and
skip such path.
Of course the right fix would be a larger swipe in the sync engine and
around it to not use naked strings anymore but rely on the typesystem.

[stable-3.0] Make sure we don't assert when calling fileStatus

---

src/gui/accountsettings.cpp

Turns out that showing the button straight from the page ctor is a bit
too early. At that point the account might not be connected yet and thus
we wouldn't have proper information. Currently we were displaying that
button all the time, now we wait for the account to be connected to
decide to show it or not.

Show the "Display mnemonic" button only when we know e2e is supported

---

src/gui/accountsettings.cpp

Turns out that showing the button straight from the page ctor is a bit
too early. At that point the account might not be connected yet and thus
we wouldn't have proper information. Currently we were displaying that
button all the time, now we wait for the account to be connected to
decide to show it or not.

[stable-3.0] Show the "Display mnemonic" button only when we know e2e is supported

---

src/gui/socketapi.cpp
src/gui/socketapi.h
src/gui/tray/ActivityListModel.cpp

Those files and folders are not shareable and the "Edit" or "Open in
browser" actions will lead to showing an error in the web GUI. No need
to lead users there so just disable them.

Disable context menu actions for E2EE files and folders

---

.clang-tidy
src/common/utility_unix.cpp
src/gui/creds/webflowcredentials.cpp
src/gui/creds/webflowcredentialsdialog.cpp
src/gui/ocssharejob.cpp
src/gui/owncloudgui.cpp
src/gui/remotewipe.cpp
src/gui/socketapi.cpp
src/gui/tray/ActivityListModel.cpp
src/gui/wizard/flow2authcredspage.cpp
test/stubremotewipe.cpp

This flagged mostly unused parameters. Didn't enable the
misc-non-private-member-variables-in-classes check as we got a lot of
those. Hopefully we'll get to fix them at some point but that feels too
early and too much work for now.

Enable all the misc clang-tidy check except one

---

src/libsync/clientsideencryption.cpp
src/libsync/propagateuploadencrypted.cpp

We don't do much with that mimetype on our end, but other clients
somehow don't expect inode/directory to let's lie. ;-)
Fix #2319

Use httpd/unix-directory mimetype for E2EE folders

---

.drone.yml
test/csync/csync_tests/check_csync_exclude.cpp
test/csync/csync_tests/check_csync_misc.cpp
test/csync/csync_tests/check_csync_update.cpp
test/csync/encoding_tests/check_encoding.cpp
test/csync/torture.h
test/csync/vio_tests/check_vio.cpp
test/csync/vio_tests/check_vio_ext.cpp

This depends on nextcloud/docker-ci#241 being merged and tagged as client-5.12-11 first.

Fix clang tidy errors in csync tests

---

src/common/syncjournaldb.cpp

Add an index on the e2eMangledName column in the metadata table
to speed up file sync by orders of magnitude on directories with
a large number of files.
Signed-off-by: Jan Schmidt <jan@centricular.com>
-- Someone in our house dropped 1.4 million files / 800GB into their Nextcloud directory, and the desktop client spent the next few days chewing 100% CPU, almost entirely doing lookups on e2eMangledName in the metadata table. With this index, it was up and synching in a few minutes.

syncjournaldb: index e2eMangledName column in metadata

---

src/gui/socketapi.cpp

I wrongly (and stupidly) assumed the int in QBitArray was treated as a
hash as well but it is an index so it must be positive. Also to make
things even worse I misread on which expression clang-tidy was
complaining regarding the implementation specific narrowing
conversion... This is happening after the modulo operator and not
before. We're in a safe range of values at that point, so it's fine to
let the narrowing happen.

Leave the implicit uint to int cast

---

src/gui/tray/UserModel.cpp

Fix #2384
Users get rightfully confused with the "You changed ..." messages in the
activity list for syncs. Indeed, some of those changes might be coming
from the server in which case we don't really know who did the change.
So now we use the old "Synced ..." messages for changes pulled from the
server and we have a more precise "You changed ..." (renamed, deleted,
created) when the changes were initiated locally (since there we know
the user reading the message did it).
Also changed how the messages are constructed so that they can be
properly translated.

Don't use a confusing "royal you" in the sync messages

---

src/gui/systray.cpp

Under Wayland QCursor::pos() is unlikely to give us anything meaningful,
so fallback to the primary screen information.
Fix #2405

Use QGuiApplication::primaryScreen() as fallback for Systray::currentScreen()

---

src/gui/tray/Window.qml

The info text is now included in the tooltip.
The tooltip timeout was also removed.
I dislike when the tooltips close themselves when I'm reading them. Many frameworks seem to recommend tooltips to show for as long as possible - while also making them easy to disappear when the mouse moves away - which Qt seems to handle well.

Include list info in tooltip

---

.clang-tidy

Turns out this clang-tidy check can give false positives coming from
headers outside the project while it shouldn't.

Disable bugprone-forward-declaration-namespace check

---

src/gui/folderman.cpp

Reason: Silly _return_ within upgrade routine, breaking the overall folder iteration. Assuming this is caused because a "break" is indeed needed within this branch, but _continue_ is the way to go here.
Fixes #2279

Fix incomplete journal upgrade from 2.x to 3.x

---

src/gui/folderwatcher_mac.cpp
src/gui/folderwatcher_mac.h

Fixes #2176 (and I think I remember similar issues, may or may not be closed duplicates already).
Fixes #1681 
Fixes #1630
Fixes #1083 
Summary:
- On macOS, [FSEventStreamCreate](https://developer.apple.com/documentation/coreservices/1443980-fseventstreamcreate?language=objc) is used for monitoring folder changes
- In general, move and copy operations are handled differently in terms of IO on most unxoids
- Due to the way FSEventStreamCreate works, move operations of folders into the NC folder may coalesce into a single event (means: Only the moved folder path is contained within the event stream)
- Due to the way NC code works, the path list passed from the folderwatcher_xxx.cpp is assumed to be complete …

Fix missing subdirectory discovery on move operations in macOS

---

src/gui/tray/ActivityListModel.cpp

Otherwise we get lots of "No description available" lines in the
activity list which is basically noise. Also trains the user to ignore
the secondary line.

If there's no description just say nothing

---

src/gui/tray/ActivityListModel.cpp

After the tooltip update, I noticed that the "info" message tooltip has "This Includes:" as the info text, which looks a bit odd now.
I thus removed the text. However, I'm not sure about other places this could happen.
One possible other way to fix this would be to switch the info and title in the tooltip, but then that wouldn't match the list view unless that was also swapped as well.
(I'm not sure how this should be designed, or if this current fix is ok)

Remove "This includes" due to tooltip order

---

src/gui/main.cpp

This makes the text renderer use the same text rendering as the rest of the OS. I find the way Qt renders QML text to be "blurrier" than how the OS handles text rendering. 
It is mostly noticeable on the top part of the text.
Before (Arch KDE and Windows):
After (Arch KDE):
Note: depending on the Qt version, there [have been issues](https://bugreports.qt.io/browse/QTBUG-67007) with native text rendering at non-integer scaling. This has been [fixed in Qt 5.14](https://bugreports.qt.io/browse/QTBUG-70481), so the version check could be higher as a quick fix to avoid issues with older qt versions. [A similar fix like KDE](https://invent.kde.org/frameworks/qqc2-desktop-style/-/blob/f8e56a22721057107bccdf319da36ff82ca2a804/org.kde.desktop/Label.qml#L25) could also be applied for lower than …

Use native text rendering for qml windows

---

src/gui/tray/NotificationHandler.cpp
src/gui/tray/UserModel.cpp

And correct the object name returned by the api - the id was always 0 so
no new systray messages were displayed.

Connect signal guiLog to slot to display systray message.

---

src/gui/folderwatcher_mac.cpp

[stable-2.6] macOS: Fix memory leak in FolderWatcherPrivate::startWatching

---

admin/win/msi/Nextcloud.wxs
doc/installing.rst

- Adopt MSI docs from upstream
Even though we had to start from scratch with MSI, our implementation is compatible ;-)
- Add the `SKIPAUTOUPDATE` property for the `skipUpdateCheck` registry setting
- Minor tweak: Update macOS system requirement info

Windows MSI: Update Docs & add SKIPAUTOUPDATE property

---

src/gui/updater/ocupdater.cpp

This is necessary for downloads coming from Github for instance. They
are systematically redirected and we'd just fail the download.

Handle redirects when downloading updates

---

src/gui/CMakeLists.txt
src/gui/application.cpp
src/gui/generalsettings.cpp
src/gui/generalsettings.h
src/gui/generalsettings.ui
src/libsync/configfile.cpp
src/libsync/logger.cpp
src/libsync/logger.h

EDIT: Adding a screenshot for a first impression ;)

Make it easier for user to provide debug information

---

src/libsync/wordlist.h

This is due to #2520 which forgot to export the newly used symbols.
This made it to stable-3.0 as #2524 so this one will need to be backported as well.

Repair the Windows build

---

src/gui/tray/UserLine.qml
src/gui/tray/UserModel.cpp
src/gui/tray/UserModel.h
src/gui/tray/Window.qml

By using properties and property bindings the QML code gets more declarative rather than imperative, which is considered better.
This patch:
- Introduces a currentUserId property in UserModel that replaces the equivalent Q_INVOKABLE call
- Introduces an avatar property in User that contains the avatar's image provider url without any fallback
- Introduces new image provider urls for fallback images
- Moves the fallback image selection to QML since we want different fallbacks according to where it is used
- Wires up the necessary signals to propagate a changing avatar

Make QML code more declarative by using properties

---

src/gui/tray/Window.qml

Combining translated strings like this makes them hard to translate since the order of words is different between languages.
Use proper placeholder strings instead.

Avoid string translation puzzle

---

src/common/utility_unix.cpp

Bookmarks are stored into `~/.config/gtk-3.0/bookmarks` since quite some time.

Update bookmarks location

---

src/gui/wizard/owncloudsetupnocredspage.ui
src/gui/wizard/owncloudsetuppage.cpp

Fix #1158
Fix #1160
This now looks like this:
And on the login page:
When an error happens (didn't really change that behavior but previously it was doing weird things with the lock icon):

Connection wizard improvements

---

src/gui/sharedialog.cpp
src/gui/sharelinkwidget.cpp
src/gui/sharemanager.cpp

Without those changes, the spinner would be displayed forever when adding a new link and hitting cancel on the input box asking for the enforced password.

Fix share dialog animation for enforced password policy

---

src/gui/folderstatusmodel.cpp

LsColJob was still being used after delete was called.

Fix crash when clicking on folder with status 403 in the main dialog.

---

src/libsync/clientsideencryption.cpp
src/libsync/clientsideencryption.h
src/libsync/clientsideencryptionjobs.cpp
src/libsync/clientsideencryptionjobs.h

OK, so after all I'll go for changing the depth of the incriminated PROPFIND call and do the recursive traversal by hand (which means more roundtrips which is a bit unfortunate). I finally did this for several reasons:
* we get the fix delivered faster in the hand of users;
* even if we optimized it on the server to somehow complete, it'd still be potentially expensive;
* also I found today this depth was used in other code paths than the first call when the sync starts which made things worse (and that was clearly the client at fault there so needed fixing anyway).
Fixes #2347 
Fixes nextcloud/end_to_end_encryption#189

Avoid depth infinity propfind for e2ee

---

src/gui/owncloudgui.cpp
src/gui/settingsdialog.cpp

As discussed with @er-vin in #2197's review.
- `ownCloudGui::slotShowSettings` already got what it takes to create it only when we try to show it for the first time:
https://github.com/nextcloud/desktop/blob/2b16ab2565ae7c7a8bfdb86f58daa1d26d342e6e/src/gui/owncloudgui.cpp#L556-L564
This however has some implications:
Pros:
- Only created when needed, while testing saved ca. 20 MB of RAM and got freed again after closing the dialog.
- Since we defaulted to the new Tray UI from 3.0, this is an added bonus for users don't opening the settings.
Cons:
- Resources like the avatar image have to be refetched everytime the dialog is recreated.
This may be desired as well, because it ensures displaying no outdated info (e.g. on connection issues).
- Fix crash in `SettingsDialog` with delayed …

Delay initialization of SettingsDialog

---

src/gui/systray.cpp
src/gui/systray.h
src/gui/tray/Window.qml

This is quick enough that no flickering should appear in practice.
We end up doing this because for some reason on Windows (I dug up deep
into the Windows QPA without nailing it down) not showing that systray
window at least once prevents the app object to return from exec() when
the session ends.
It's as if that window would be in some limbo state (neither opened nor
closed) which would prevent quitting. Clearly what we're doing here is a
workaround...

Ensure we quickly show/hide the systray window on startup

---

src/gui/folderwatcher_mac.cpp

When we skip a watcher event on mac, we log the file path but not the
event flags which came with it. Let's add it, it should help figure out
what's going on with #2578.

Also output the event flags in the debug logs

---

src/gui/conflictdialog.cpp

I switched from "remote" to "server" but apparently left one behind by
mistake...
Fix #2588

Remove last left over of the "remote" wording

---

src/common/utility.h
src/common/utility_win.cpp
src/gui/navigationpanehelper.cpp
src/gui/systray.cpp

This fixes the following issues with the desktop app on Windows 7:
1. Registry key `HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Desktop\NameSpace` does not exist
2. Task bar position is not calculated properly because `HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\StuckRects3` does not exist, but `StuckRects2` can be used instead

Misc fixes for Windows 7

---

src/gui/accountstate.cpp

This was right now on the check connectivity beat which is too much when
you got many users. Be more conservative there and only update the list
of apps when the account gets connected.

Fetch apps when we get connected only

---

src/gui/owncloudgui.cpp

Because of PR #2580 the settings dialog doesn't always exist. We need to
check for it first before placing calls to it.

Make sure the settings dialog exist before hiding it

---

src/cmd/cmd.cpp
src/common/syncjournaldb.cpp
src/common/syncjournaldb.h
src/gui/folder.cpp
src/gui/folder.h
src/gui/folderman.cpp

So after wondering which path to follow regarding this topic I finally went for moving them back to the sync folder... This was the easiest route code wise as well.
Incidentally while updating the migration code I found a couple of concatenations which looked fishy, thus I'm wondering if they were not the cause of the remaining "it lost my selective sync settings" issues which got reported.
It works in my own testing but I definitely welcome more testing with potentially exotic setups since I likely didn't think of everything. Like the previous time it is somewhat a risky move so we'd better be extra careful.

Move journaldb files back to sync folders

---

.drone.yml

Since this fails every time we bump the version number and takes time to
catch up while failing every following PRs, let's prevent this pipeline
from failing the CI.

Issue a warning for Debian pipeline failures but don't fail the CI

---

src/gui/tray/UserLine.qml
src/gui/tray/UserModel.cpp
src/gui/tray/UserModel.h
src/gui/tray/Window.qml
src/libsync/theme.cpp
src/libsync/theme.h
theme/Style/Style.qml

Use a method from Theme to generate a path for online/offline account state icon.
Also, added a signal/slot connection from connection state change to GUI so the online/offline icon will get refreshed without reopening the window.
Signed-off-by: allexzander blackslayer4@gmail.com

Use dynamic path for account online/offline state icon. Refresh GUI on connection state change.

---

src/common/utility.h

Removed QML dependency from nextcloudcmd target.

Fix QML debugging by removing incorrect dependency

---

src/gui/folder.cpp
src/gui/folderwatcher.cpp
src/gui/folderwatcher.h
src/gui/folderwatcher_linux.cpp
src/gui/folderwatcher_linux.h
src/gui/folderwatcher_mac.h
src/gui/folderwatcher_win.cpp
src/gui/folderwatcher_win.h
test/testfolderwatcher.cpp

Cherry-picked:
- [Folderwatcher: On linux, fix paths after dir renames](https://github.com/owncloud/client/commit/55cf407337a5db93511f1cb061165c53fa6dba6e)
- [FolderWatcher: Always notify about conflict files #7073 ](https://github.com/owncloud/client/commit/6d8b27747b8d0d1ec76a39f6efb2eeffc5397826)
- [FolderWatcher linux: Make automatically recursive #7068 ](https://github.com/owncloud/client/commit/cb5a76729a65f6a474637a2b1578c8aaa7c878c3)
- [FolderWatcher: Become unreliable if test notification fails #7241](https://github.com/owncloud/client/commit/831e718b0c07fbfb2179eeebe25433575fac4d16)
- [FolderWatcher: Wait for ready before testing #7305](https://github.com/owncloud/client/commit/0277b2e478cc3dfa63f69b254566ac911b8f2024)
- [FolderWatcher: Usage of QTime for elapsed time is …

FolderWatcher: fixes and improvements

---

src/gui/CMakeLists.txt
src/gui/generalsettings.cpp
src/gui/generalsettings.h
src/gui/generalsettings.ui
src/gui/updater/ocupdater.cpp
src/gui/updater/ocupdater.h
src/gui/updater/sparkleupdater.h
src/gui/updater/sparkleupdater_mac.mm
src/gui/updater/updateinfo.cpp
src/gui/updater/updateinfo.h
src/gui/updater/updater.cpp
src/gui/updater/updater.h
src/libsync/configfile.cpp
src/libsync/configfile.h

This opens the door to the support for msi based updates (although the server side doesn't provide them yet). This should also get the sparkle based updates on Mac to work (this would need to be tested further though). 
Also contains nice improvements regarding the logging of the updater and error handling.

Cherry pick updater fixes and improvements

---

admin/linux/debian/drone-build.sh
admin/linux/debian/scripts/git2changelog.py

The Debian build determines the version by scanning the Git log and examining the contents of VERSION.cmake as well as any tags that may point to a commit. The tags have precedence over the contents of VERSION.cmake, so in case of v3.1.0-rc1 the version was correctly detected to be 3.1.0.
Based on this information an "orig" archive is created the name of which contains the version.
Then each target distribution is taken and the corresponding Debian branch is fetched and checked out and the commit to release (i.e. v3.1.0-rc1 in this case) is merged into the branch locally to create a mix of the code to release and the Debian additions. Then a changelog is generated based on the contents of the Git log where the version for a changelog entry is generated as described above. However, in this …

Handle the case when the release version differs from that in VERSION.cmake

---

src/gui/systray.cpp
src/gui/systray.h
src/gui/systray.mm

Closes #2332 
Let me know if there's any changes you need to the PR and I'll be happy to update my commit

Fix macOS bug where tray window causes spaces to switch

---

src/gui/folderwatcher_win.cpp

Add debug log to check which folders are being skipped during syncing.

---

src/gui/accountsettings.cpp
src/gui/accountsettings.h
src/gui/accountsettings.ui

Split widgets and slot to handle the refreshing of the view:
- refreshSelectiveSyncStatus is connected to signal dirtyChanged
and will handle big folder warning.
- slotSelectiveSyncChanged  which is connected to dataChanged signal
and will handle the selective sync warning. It fixes #1029 because
it looks for the checkbox state before showing the warning.

Handle the warning message when unchecking folders for syncing.

---

src/gui/accountsettings.cpp
src/gui/accountsettings.h
src/gui/systray.cpp

UserModel can't be connected to AccountSettings if the settings dialog
doesn't exist. This is the case now since we delay the creation of that
dialog and free it after use.
Instead it should be properly channeled through the Systray object all
the way up to OwncloudGui which knows how to handle this properly.
Fix #2706

Have the new account wizard open again

---

src/gui/tray/UserModel.cpp

The model was just checking for the user list being empty or not which
is overly optimistic. Indeed there might be cases where the id is
actually outside the boundaries so properly check for this.
Fix #2710

UserModel: check indices are inside the user list

---

src/gui/socketapi.cpp
src/gui/tray/ActivityListModel.cpp

You'd expect that after a conflict resolution the file watcher would
pick up the change and trigger a sync. For some reason it doesn't seem
to happen on at least some Ubuntu systems. In such cases the user would
then still have a stale conflict entry in the activity list and wouldn't
be able to do anything with it.

Ensure a sync happens after a conflict resolution

---

src/libsync/configfile.cpp

Unless it is branded with other icons.
See 1st item in #2721

Make monochrome icons the default on Linux and Mac OS.

---

src/common/utility_unix.cpp

For details please see the discussion in #2504. This fix sets the application path to the enviornment variable APPIMAGE, if the variable exists and points to an existing file. According to the discussion, this should fix #2504.
I cannot, however, check whether this fixes the bug, since I cannot build the AppImage, because the `build-appimage.sh` is aparently expecting to be run on a certain version of a certain Linux distribution under some CI/CD system. (And I do not know which one.)
Would be great, if someone could build the AppImage and test it.

Fixed the autostart for AppImages. See #2504.

---

doc/introduction.rst

Fixes https://github.com/nextcloud/desktop/issues/1506
Also when building a new version, make sure it refers to 2.6.0 correctly, currently it is still shown 2.4.0 in the documentation (even though it is the documentation for the 2.6.0 version: https://docs.nextcloud.com/desktop/2.6/introduction.html#improvements-and-new-features):

Fix changelog for 2.6.0 documentation

---

src/libsync/discovery.cpp
test/testremotediscovery.cpp

Shouldn't be translated.
Just checked https://en.wikipedia.org/wiki/HTTP_ETag and all available localized pages.

Removed translation for "etag" and changed spelling

---

src/gui/socketapi.cpp
src/libsync/CMakeLists.txt
src/libsync/discovery.cpp
src/libsync/theme.cpp
src/libsync/vfs/cfapi/cfapiwrapper.cpp
src/libsync/vfs/cfapi/cfapiwrapper.h
src/libsync/vfs/cfapi/hydrationjob.cpp
src/libsync/vfs/cfapi/hydrationjob.h
src/libsync/vfs/cfapi/vfs_cfapi.cpp
src/libsync/vfs/cfapi/vfs_cfapi.h
test/CMakeLists.txt
test/testsynccfapi.cpp

This introduce a test suite and a minimal backend for CfAPI support on Windows when the VFS is used. So far it seems to do the job all the way to implicit hydration. Some integration with the system could be improved (like status emblem on icons) but better keep this for later iterations on the feature, let's stabilize and QA what's in there.

Windows cfapi backend for vfs

---

src/libsync/vfs/cfapi/cfapiwrapper.cpp

For some reason MSVC manages to deduce the right constructor in Win64
mode but not in Win32 mode. So let's be more explicit about what we
return.

Fix CfAPI wrapper build in Win32 mode

---

src/libsync/vfs/cfapi/cfapiwrapper.cpp

This time for real it seems. :-)

Fix CfAPI Win32 build

---

src/libsync/CMakeLists.txt
src/libsync/abstractpropagateremotedeleteencrypted.cpp
src/libsync/abstractpropagateremotedeleteencrypted.h
src/libsync/clientsideencryption.cpp
src/libsync/clientsideencryption.h
src/libsync/clientsideencryptionjobs.cpp
src/libsync/clientsideencryptionjobs.h
src/libsync/deletejob.cpp
src/libsync/deletejob.h
src/libsync/encryptfolderjob.cpp
src/libsync/propagateremotedelete.cpp
src/libsync/propagateremotedelete.h
src/libsync/propagateremotedeleteencrypted.cpp
src/libsync/propagateremotedeleteencryptedrootfolder.cpp
src/libsync/propagateremotedeleteencryptedrootfolder.h
src/libsync/propagateremotemkdir.cpp
src/libsync/propagateupload.cpp
src/libsync/propagateuploadng.cpp
src/libsync/syncengine.cpp

Implement nested items removal when removing root encrypted folder.

E2ee root folder remove issue

---

src/libsync/propagateuploadng.cpp

There's been a confusion between the chunk number and the chunk
offset leading to corruptions... Let's pass the proper offset to
the UploadDevice again.
Fix #2822

Repair chunked uploads

---

src/common/vfs.cpp
src/common/vfs.h
src/csync/vio/csync_vio_local_unix.cpp
src/libsync/CMakeLists.txt
src/libsync/propagatedownload.cpp
src/libsync/vfs/xattr/vfs_xattr.cpp
src/libsync/vfs/xattr/vfs_xattr.h
src/libsync/vfs/xattr/xattrwrapper.h
src/libsync/vfs/xattr/xattrwrapper_linux.cpp
test/CMakeLists.txt
test/testsyncxattr.cpp

Plan is to use it on macOS and Linux but some extra work is required before making it the default choice. Indeed apart from the obvious "this needs more testing" there is also the need for growing Linux support for our attribute first and to implement the macOS support for the com.apple.LaunchServices.OpenWith attribute.

XAttr backend for VFS

---

src/csync/csync_exclude.cpp

Use QLatin1Char to prevent build error due to stricter QT_NO_CAST_FROM_ASCII

Fix build against Qt 5.15.3

---

src/libsync/vfs/cfapi/cfapiwrapper.cpp
src/libsync/vfs/cfapi/vfs_cfapi.cpp

In some fringe cases the client would crash while we could in fact somewhat gracefully handle them. So let's be a little less assert heavy since Windows likes to poke the client several times until it gets what it wants...

VFS CfAPI implementation shouldn't get stuck

---

src/gui/accountmanager.cpp
src/gui/connectionvalidator.cpp
src/libsync/account.cpp
src/libsync/clientsideencryption.cpp
src/libsync/clientsideencryption.h

This account object was really only used during the initialization phase
or for forgetting the sensitive data. So let's receive it as parameter
there and pass it on from job to job as needed.

Avoid keeping Account alive via a shared ptr in ClientSideEncryption

---

src/libsync/vfs/cfapi/vfs_cfapi.cpp
test/testsynccfapi.cpp

This would only happen if the parent of the newly created folder would
be explicitly set to online only, hence why it went under the radar
previously.

Don't treat new folders in unpinned folders as files to dehydrate

---

src/gui/tray/ActivityListModel.cpp
src/gui/tray/ActivityListModel.h

Fixes #2804
Signed-off-by: Felix Weilbach <felix.weilbach@t-online.de>

Start file conflict resolve dialog asynchronous

---

src/libsync/CMakeLists.txt

I went full steam on making it all public which is not really required,
it's only really QtWebSockets we're after. Could always be fine tuned
later on if this works as expected.

Specify PUBLIC for the link targets to make them visible to windeployqt

---

doc/troubleshooting.rst

Also make sure the following note is not displayed as one block with the
config example.

Documentation: break line in config example.

---

src/gui/main.cpp

Otherwise they won't be loaded automatically at startup leading to lots
of missing icons. Since they're now in a static library they need that
explicit loading.
This fix a regression introduced by #2834

Load the theme resource explictly

---

src/csync/CMakeLists.txt

Fix for Windows build error of not being able to locate #include <sqlite3.h> in tests.

Win tests compilation fix.

---

src/gui/CMakeLists.txt
src/gui/accountsettings.cpp
src/gui/accountsettings.h
src/gui/foldercreationdialog.cpp
src/gui/foldercreationdialog.h
src/gui/foldercreationdialog.ui
src/gui/folderstatusmodel.cpp
src/gui/folderstatusmodel.h

Also fixed incorrect path for SubFolderInfo that was resulting in an inability to open encrypted subfolder and create a new folder inside it via the Settings Dialog's context menu.

Allow creation of new folders from the Settings Dialog.

---

src/libsync/abstractpropagateremotedeleteencrypted.cpp
src/libsync/discovery.cpp

Found a couple of regressions related to the use of E2EE in the context of sync folders configured to not point to / but to some other subfolders on the server. They were introduced during the big changes in the discovery which made the content of the e2eMangledName field change in the database with a different convention to what almost all the jobs were expecting. The only exception was one place in the newer changes done by @allexzander around deletion.

Repair E2EE on sync folders which don't point to the root of the server on the remote end

---

src/gui/foldercreationdialog.cpp
src/gui/foldercreationdialog.h
src/gui/foldercreationdialog.ui

Compilation has started to fail recently with the following:
```In file included from /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/gui/nextcloudCore_autogen/EWIEGA46WW/moc_foldercreationdialog.cpp:10,
from /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/gui/nextcloudCore_autogen/mocs_compilation.cpp:24:
/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/gui/nextcloudCore_autogen/EWIEGA46WW/../../../../../src/gui/foldercreationdialog.h:38:5: error: reference to ‘Ui’ is ambiguous
38 |     Ui::FolderCreationDialog *ui;
|     ^~
In file included from /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/gui/nextcloudCore_autogen/EWIEGA46WW/moc_accountsettings.cpp:10,
from /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/gui/nextcloudCore_autogen/mocs_compilation.cpp:7:
/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/gui/nextcloudCore_a …
```

Move FolderCreationDialog into the OCC namespace

---

src/gui/accountsettings.cpp
src/gui/creds/flow2auth.cpp
src/gui/creds/oauth.cpp
src/gui/guiutility.cpp
src/gui/guiutility.h
src/gui/owncloudgui.cpp
src/gui/socketapi.cpp
src/gui/tray/ActivityListModel.cpp
src/gui/tray/UserModel.cpp
src/gui/wizard/owncloudwizardresultpage.cpp
src/gui/wizard/webview.cpp

Validate sensitive URLs to onle allow http(s) schemes.

---

src/gui/wizard/webview.cpp

Validate the providers ssl certificate

---

src/libsync/configfile.cpp
src/libsync/configfile.h

Hi,
I created this issue https://github.com/nextcloud/desktop/issues/2890 and tried to implement it.
I have added these configuration  options
-  confirmExternalStorage
-  crashReporter
-  newBigFolderSizeLimit
-   useNewBigFolderSizeLimit
to the Windows registry.
They should behave the same as when you change it in the GUI.
I used a REG File wih these Settings to test:
```
Windows Registry Editor Version 5.00
[HKEY_CURRENT_USER\Software\Policies\Nextcloud GmbH\Nextcloud]
"newBigFolderSizeLimit"=dword:00005000
"skipUpdateCheck"=dword:00000001
"confirmExternalStorage"=dword:00000000
"useNewBigFolderSizeLimit"=dword:00000000
```
This is what the Client UI looks like:

Configuration Options for Windows Registry

---

src/gui/creds/webflowcredentials.h

Noticed a warning during compilation. I think I introduced this warning recently.

Add missing override specifier

---

src/common/ownsql.h
src/common/syncjournaldb.cpp
src/common/syncjournalfilerecord.h
src/libsync/discovery.cpp
src/libsync/logger.cpp
src/libsync/syncengine.cpp
src/libsync/syncfileitem.cpp
test/syncenginetestutils.cpp

Fix incorrect logger output for non-Latin strings.

---

src/libsync/vfs/cfapi/cfapiwrapper.cpp

Without the conversion, just an address gets logged. Might be useful in the future.

Log error message from CFAPI

---

doc/README.md
doc/building.rst

I'm marking this as "WIP" even though it should basically be ready to merge because I'd like some feedback before it gets approved, and I'm not sure where else to have the conversation other than here.
Thus far my changes mainly incorporate the macOS build instructions discussed in #2893, but I'd be happy to broaden the scope to Linux and possibly even Windows if I'm able to set up a test environment.
I also plan on updating the main [README.md](https://github.com/nextcloud/desktop/blob/0bb6dcebd878e2b2236006295fa291c6d23ae857/README.md) and the [Wiki](https://github.com/nextcloud/desktop/wiki) to reference these build instructions, so that could be added to the pull request.
A few initial questions: 
1. I removed the step for installing PdfLatex because the document is titled "Appendix …

WIP: Build Instructions

---

src/libsync/vfs/cfapi/cfapiwrapper.cpp
src/libsync/vfs/cfapi/hydrationjob.cpp

VFS Windows: Fix download of large files

---

src/gui/tray/UserModel.cpp
src/gui/tray/UserModel.h
src/libsync/owncloudpropagator.cpp

Note: This PR is a draft. It fixes the problem but probably needs some polishing. I first wanted to hear your thoughts about this problem, my findings and my proposed solution before I investigate further.
Now to the actual problem:
When the client runs and a conflict gets detected, the sync engine runs
two times.
On the first run, the sync engine  detects the conflict, marks the
file as a conflict and propagates that to the GUI. This leads to an
error notification with the original filename in the main dialog.
The sync engine runs then a second time. On this second run, the file
that originally caused the conflict is not anymore a conflict
file. Instead, the sync engine detects the conflicted copy and
propagates that file as a conflict to the GUI.
When opening the conflict dialog with …

Fix crash when opening conflict dialog

---

src/gui/cloudproviders/cloudprovidermanager.cpp

Compilation fails on Hirsute with errors like:
```
In file included from /usr/include/glib-2.0/glib/gatomic.h:31,
from /usr/include/glib-2.0/glib/gthread.h:32,
from /usr/include/glib-2.0/glib/gasyncqueue.h:32,
from /usr/include/glib-2.0/glib.h:32,
from /<<PKGBUILDDIR>>/src/gui/cloudproviders/cloudprovidermanager.cpp:16:
/usr/include/c++/10/type_traits:56:3: error: template with C linkage
56 |   template<typename _Tp, _Tp __v>
|   ^~~~~~~~
/<<PKGBUILDDIR>>/src/gui/cloudproviders/cloudprovidermanager.cpp:15:1: note: ‘extern "C"’ linkage started here
15 | extern "C" {
| ^~~~~~~~~~
```
This is due to `glib/gatomic.h` now including `<type_traits>` when being compiled with C++. I think `glib.h` and similar headers can be safely included into C++ code without extern "C" nowadays. Hence this …

Do no include glib.h with extern C

---

src/gui/tray/UserModel.cpp
src/gui/tray/UserModel.h

Refactoring of User::isValueableactivity() because of changes
introduced with merge commit f17c52d.
I like splitting out the checks in separate methods because I find it more readable and the User::slotItemCompleted() is at the moment way to big for my taste.

Split content of User::isValueableActivity()

---

src/libsync/propagatedownloadencrypted.cpp
src/libsync/propagatedownloadencrypted.h

The missing error handlers can cause the sync to hang forever

Add missing error handling for downloads of client side encryption

---

src/libsync/configfile.cpp

Fix incorrect type when reading the 'logExpire' property from config.

---

src/gui/owncloudsetupwizard.cpp
src/gui/wizard/owncloudsetuppage.cpp
src/gui/wizard/owncloudwizardcommon.h
src/libsync/networkjobs.cpp
src/libsync/networkjobs.h

This PR cleans up the remnant of the shibboleth code in a first commit. Then it proceeds with repairing the support for basic auth which apparently got broken around the time the shibboleth code was first disabled. Changed a bit the logic we still apply the same priority order for the auth modes but if we get a basic auth error on the account URL we can safely assume basic auth is enabled on the server.
Since I'm now using daily a server with basic auth enabled this was easy to debug and figure out what was wrong. ;-)
Fix #2046

Repair basic auth support

---

src/gui/creds/webflowcredentials.cpp
src/gui/creds/webflowcredentialsdialog.cpp
src/gui/wizard/flow2authwidget.cpp

This adjustment is necessary because of the changes of the new account
wizard that were introduced with:
e0b7ef15b207f59d73884f8e1c12a206803c5c40
This is how the dialog looks with the fix:
https://cloud.nextcloud.com/s/9WEr7ZcxYrFPWAi
@jancborchardt Your input on this is would be valuable:) Is the dialog ok?
General note:
Maybe we should start to refactor the wizard a bit and remove these `void customizeStyle()` methods. They are not used at the moment and problems like the one this pr fixes right now would not exist.

Display the content of the login dialog correct

---

src/gui/foldercreationdialog.cpp

Fix crash when trying to open the folder creation dialog

---

src/csync/vio/csync_vio_local_win.cpp
src/libsync/vfs/cfapi/cfapiwrapper.cpp
src/libsync/vfs/cfapi/vfs_cfapi.cpp

This should fix https://github.com/nextcloud/desktop/issues/3006

Fix for Windows CreateFile long path

---

src/libsync/propagatedownload.cpp
src/libsync/propagatedownload.h
src/libsync/vfs/cfapi/cfapiwrapper.cpp
src/libsync/vfs/cfapi/hydrationjob.cpp
src/libsync/vfs/cfapi/hydrationjob.h
src/libsync/vfs/cfapi/vfs_cfapi.cpp
src/libsync/vfs/cfapi/vfs_cfapi.h

CFAPI: Handle cancelation of hydration requests

---

src/libsync/discovery.cpp
src/libsync/propagateremotedelete.cpp
src/libsync/propagatorjobs.cpp

To better see what is going on when and if files are removed by the
client.
See also: #260, #1433, #2913

Increase logging around file removal events

---

src/gui/main.cpp

Fixes #2295, #1079, #914
I'm unsure why this has been enabled only on Windows in the past? @er-vin @camilasan  you know more about that?

Enable high dpi scaling on all platforms

---

src/libsync/vfs/cfapi/vfs_cfapi.cpp

Check reading from journal was successful before remove placeholder

---

src/common/vfs.h
src/gui/accountmanager.cpp
src/gui/accountmanager.h
src/gui/folder.cpp
src/gui/folder.h
src/gui/folderman.cpp
src/gui/folderman.h
src/libsync/vfs/cfapi/cfapiwrapper.cpp
src/libsync/vfs/cfapi/cfapiwrapper.h
src/libsync/vfs/cfapi/vfs_cfapi.cpp

Documentation is here: https://docs.microsoft.com/en-us/windows/win32/shell/integrate-cloud-storage

Refresh Windows download dialog progress when hydrating a placeholder

---

src/libsync/vfs/cfapi/cfapiwrapper.cpp
src/libsync/vfs/cfapi/cfapiwrapper.h

Fix VFS CfAPI Syncroot Register Error.

---

src/gui/updater/ocupdater.cpp

The content of notifications on MacOS are not allowed to contain HTML
tags in it. Linux (Free Desktop) notifications may contain HTML tags
in their content. However, it is optional that the notification daemon
interprets the tags. The GNOME notification daemon does not interpret
HTML tags and even does not strip them off. KDE's daemon interprets
the tags. For now I think it's the best solution to remove the HTML
tags. In the future we should fire a action if the user clicks on the
notification and react on it and open the link then. This should work
on all platforms. But as this change involves working with the native
MacOS api and I don't have hardware for that at the moment for that I
will postpone it.
Fixes #2200

Remove html tags from strings that may appear in notifications

---

src/gui/socketapi.cpp

Reduced SocketAPI logging to fix this issue #3039. Only log essential and non-frequent messages via qCInfo. The rest of the messages are logged when **--logdebug** option is set only.

Reduce Socket API logging.

---

src/libsync/vfs/cfapi/cfapiwrapper.cpp
src/libsync/vfs/cfapi/cfapiwrapper.h

Another way to fix **const QString&** passing by reference, issue.
As an alternative solution. This also works. I haven't really come up with an idea of why this is happening.
FYI, calling **QString::toStdWString().data** directly in the place of usage (filling in the **info** structure with these strings) works too. So, I am wondering, if I should do that instead?

Create std::wstrings out of const wchar_t* so a copy is created every time

---

src/gui/accountsettings.cpp

on windos absolute path does not have to start with / . Remove failing assert
when editing ignored files list.

use QFileInfo to check if path is absolute to avoid assert on windows

---

src/gui/CMakeLists.txt

These changes are necessary because of changing the compilation
process for the gui from a single executable to static lib +
executable in commit 0521dce1743215633f6db3fb7fd184a5643f7779.
Otherwise the version and icon information will be lost.

Embed version and icon into windows executable

---

src/gui/CMakeLists.txt
src/gui/tray/ActivityListModel.cpp
src/gui/tray/NotificationCache.cpp
src/gui/tray/NotificationCache.h
src/gui/tray/UserModel.cpp
src/gui/tray/UserModel.h
src/libsync/discovery.cpp
src/libsync/syncfileitem.h
test/CMakeLists.txt
test/testnotificationcache.cpp

This pr displays a warning in the activity log if a file could not be created because of illegal characters. It looks like this:
Additionally it shows an operating system notification.
The pr is quick and dirty at the moment. Few things to consider:
- Do we want to group the warnings? Like for ignored files?
- Should an operating system notification only displayed once when the issue first gets detected? 
(At the moment with each sync run the notification gets displayed again)
Fixes: #3013, #3018, #464

Display invalid filenames as warning

---

admin/win/msi/Nextcloud.wxs

From version 3.2.1 and onwards, a minimum of Windows 10 version 1709 is supported. According to this https://docs.microsoft.com/en-us/windows/win32/cfapi/cloud-files-api-portal
This will fix https://github.com/nextcloud/desktop/issues/3083

Windows MSI. Do not allow installing Nextcloud client on < Windows 10 or < 1709

---

CMakeLists.txt

The same is done somewhere below

Remove redundant CMake code

---

cmake/modules/FindSharedMimeInfo.cmake
src/gui/CMakeLists.txt

Instead of relying on ECM being installed.
We copy other stuff from ECM so be consistent.

Copy FindSharedMimeInfo from ECM

---

src/libsync/propagatedownload.cpp

when canceling the sync of a big directory, I can get some network
request that are aborted before a Date reply header has been read
in this case we would always access
AbstractNetworkJob::responseTimestamp() and fire the assert even if we
know that the network reply has an error
delay the access to after the possible errors have been dealt with

avoid an assert by delaying access to response timestamp when in error

---

mirall.desktop.in

The "Name" field in `.desktop` files is the display name shown in the application launcher and sometimes other places. It should ideally be title case and succinct in order to avoid truncation.
Currently it looks like this:
If I use "Nextcloud Desktop" instead, it looks better in the top bar but still gets truncated in the GNOME Launcher (which is admittedly GNOME's fault):
By contrast, "Nextcloud Sync" is just short enough not to be truncated in the GNOME Launcher:
I'm on GNOME 3.38, and the Application Launcher still truncates text comedically short on higher DPIs, which [they were ostensibly supposed to fix](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2173):
Yikes!
I'm most partial to "Nextcloud Desktop" (as contrasted to "Nextcloud Server" and "Nextcloud Mobile"), but …

Use More Concise Display Name on Linux?

---

doc/navigating.rst

Updated the description on file manager integration on Linux with the new package names.
Closes https://github.com/nextcloud/desktop/issues/2203

Update Linux file manager integration

---

src/libsync/vfs/cfapi/cfapiwrapper.cpp

sets a reasonable size of the StructSize members in the struct passed to
CfRegisterSyncRoot function

fix errors when calling CfRegisterSyncRoot by setting more fields

---

src/libsync/vfs/cfapi/cfapiwrapper.cpp

status wrong for directories when using vfs and nextcloud desktop 3.2.0

---

src/gui/folder.cpp

While investigating #3172, I discovered that the sync will hang forever
if the user has deleted all files on the server. Calling the callback
resolves the problem.
Fixes #3172

Call finish() if going to remove all files

---

src/CMakeLists.txt

following settings of cmake/modules/Warnings.cmake
once applied, no more zillon of warning on building as below:
```
cc1plus: note: unrecognized command-line option '-Wno-gnu-zero-variadic-macro-arguments' may have been intended to silence earlier diagnostics
```
Edit: appeared on 3.1.3 or 3.2 release

clang's variadic macro warnings: only for clang

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature.md

Additionally, this commit adds functionality to label automatically
feature and bug reports.

Add separate GitHub templates for features and issues

---

src/libsync/theme.cpp

add missing call to tr to get a translated string

---

.github/workflows/stale.yml

increase number of operations per run to go through old issues

---

src/gui/wizard/owncloudwizard.cpp

Fallback to primary screen if screen under pointer not found

---

src/gui/legalnotice.cpp

Changed copyright year to 2021

---

src/libsync/propagatedownload.cpp

This fixes https://github.com/nextcloud/desktop/issues/3198

VFS. Display local file name clash error when syncing in VFS mode.

---

src/libsync/propagatedownload.cpp
src/libsync/vfs/cfapi/vfs_cfapi.cpp

This fixes https://github.com/nextcloud/desktop/issues/3156

VFS. Allow dehydartion of readonly files. Preserve 'readonly' flag when creating a placeholder.

---

.gitignore

These two bothered me for some time now. I know I could add them to the global ignore list, but I want `.dir-locals.el` committed in some projects.

Git ignore convert.exe and .dir-locals.el

---

src/gui/legalnotice.cpp

also update ownCloud years interval in copyright notice

---

src/common/utility.cpp
src/common/utility.h
src/gui/accountsettings.cpp
src/gui/folderwizard.cpp
src/gui/wizard/owncloudadvancedsetuppage.cpp
src/gui/wizard/owncloudadvancedsetuppage.h

This fixes https://github.com/nextcloud/desktop/issues/3158.
A temporary solution that we can implement quickly until the UX design is ready for this.
CfAPI doesn't work for root partitions on Windows (drive letters like c:/, d:/, e:/, etc.).
This is to be included in 3.2.2 as a quick solution.

Temporary! Windows. VFS. Block Virtual Files for partition root sync folders.

---

src/libsync/vfs/cfapi/cfapiwrapper.cpp

For big files that can add a lot lines to the log files.
This helps with https://github.com/nextcloud/desktop/issues/3287

Remove unnecessary cfapi logging statements

---

src/libsync/discovery.cpp

This fixes https://github.com/nextcloud/desktop/issues/3296 and https://github.com/nextcloud/desktop/issues/3270

Add remote folder prefix for renaming in a non-root local folder.

---

cmake/modules/DefineCMakeDefaults.cmake
test/CMakeLists.txt
test/nextcloud_add_test.cmake

This sets folders for targets to be visible in an IDE.
Before in VS (if tests ore on):
Now in VS:

use folders in CMake

---

.drone.yml

update most docker images to use Qt 5.12.10 in Drone

---

src/gui/accountsettings.cpp

Set button on QMessageBox before changing the text

---

.github/workflows/needsinfo.yml

each stale bot needs to have its own stale label such that it does not
remove the label added by the other bot
that can happen due to needs info bot removing stale label on issues
that have both bug and needs info labels

use a specific stale label for needs info handling to solve conflict

---

.github/workflows/needsinfohelper.yaml

should help handling needs info label in a more efficient way

automate removal of needs info labels when the issue is commented

---

.github/workflows/needsinfohelper.yaml

fix needs info label remover action by providing github token

---

src/libsync/clientsideencryption.cpp

Bugfix. Crash when printing OpenSSL decryption errors with no e2ee mnemonic,

---

doc/options.rst

Fix [#3374](https://github.com/nextcloud/desktop/issues/3374).

Document --background

---

src/libsync/propagatedownload.cpp

This one is more user-friendly and grammatically correct.

Improve error message

---

src/libsync/vfs/cfapi/cfapiwrapper.cpp

Set pin state correct after rename

---

src/gui/folder.cpp
src/gui/folder.h
src/gui/tray/ActivityData.h
src/gui/tray/UserModel.cpp
src/gui/tray/UserModel.h
src/libsync/discovery.cpp
src/libsync/discoveryphase.h
src/libsync/progressdispatcher.h
src/libsync/syncengine.cpp
src/libsync/syncengine.h

VFS wipe moved folder when conflict

---

.drone.yml
admin/linux/count_compiler_warnings.py

Additionally to that I can setup a cron job on the server which then builds master every few hours and updates the number of warnings.
It might be possible to setup drone in a way that a pipeline which updates the number of warnings gets only executed when something is merged to master, but I haven't found out how to do this yet, and we said that we want to keep it quick and dirty;) Adding some conditional logic to the `count_compiler_warnings.py` script which updates the number of warnings based on the active branch might be dangerous as we then would need to expose secrets to public pull requests.
Of course we can use an different server for this.

Enable clazy in drone

---

src/libsync/propagatedownload.cpp
src/libsync/propagatedownload.h
src/libsync/vfs/cfapi/cfapiwrapper.cpp
src/libsync/vfs/cfapi/hydrationjob.cpp
src/libsync/vfs/cfapi/hydrationjob.h
src/libsync/vfs/cfapi/vfs_cfapi.cpp
src/libsync/vfs/cfapi/vfs_cfapi.h

This a different version of https://github.com/nextcloud/desktop/pull/3289 that works without global variables.

Cfapi: Make sure no data is transfered after cancellation

---

test/syncenginetestutils.cpp
test/syncenginetestutils.h

Remove unused function declaration

---

src/gui/accountsettings.cpp
src/libsync/vfs/cfapi/vfs_cfapi.cpp

Spelling unification in Transifex.

l10n: Spelling unification

---

src/gui/accountsettings.cpp

I know the root cause of the problem lies in the fact that we use a pointer from a model too long, but I wanted to make this fix as non-invasive as possible.

Prevent crash in dialog that warns user about vfs and e2ee

---

admin/linux/debian/drone-build.sh

GPG in the new build image requires the full key identifier to be passed.

Use the full GPG key ID for signing Debian packages

---

src/libsync/discovery.cpp

If it's not checked that first is empty, crashes may happen.

Check if first is not empty

---

src/gui/tray/ActivityData.h
src/gui/tray/ActivityListModel.cpp
src/gui/tray/ActivityListModel.h

should allow usage of default cache from Image qml standard component

directly send the icon url for activities to the qml component

---

admin/win/msi/Nextcloud.wxs

`UninstallString` Registry property is created by NSIS installer. We must query it and then run the `Uninstall.exe` file that is contained within this property, or, do nothing if it is empty.

Run legacy uninstall exe in a secure way

---

src/common/result.h
src/libsync/discovery.cpp

This should do it. Just need to test a couple of times more and maybe come up with some additional scenarios...
Having said that, it works well now when creating new folder and still works as expected when renaming on 2 clients.

Fix VFS crash and false conflict on local new.

---

src/libsync/vfs/cfapi/cfapiwrapper.cpp

_com_error(cfExecuteresult).ErrorMessage() calls should be translated to
QString before use with qDebug and related logging facilities

fix all usage of _com_error(cfExecuteresult).ErrorMessage()

---

src/libsync/discovery.cpp

improve error message in case of trailing space in directory name

---

src/common/syncjournaldb.cpp
src/common/syncjournaldb.h
src/common/vfs.h
src/libsync/owncloudpropagator.cpp
src/libsync/owncloudpropagator.h
src/libsync/propagatedownload.cpp
src/libsync/propagateremotemkdir.cpp
src/libsync/propagateremotemove.cpp
src/libsync/propagateupload.cpp
src/libsync/propagatorjobs.cpp
src/libsync/vfs/cfapi/cfapiwrapper.cpp
src/libsync/vfs/cfapi/cfapiwrapper.h
src/libsync/vfs/cfapi/vfs_cfapi.cpp
src/libsync/vfs/cfapi/vfs_cfapi.h
src/libsync/vfs/suffix/vfs_suffix.cpp
src/libsync/vfs/suffix/vfs_suffix.h
src/libsync/vfs/xattr/vfs_xattr.cpp
src/libsync/vfs/xattr/vfs_xattr.h

Also properly handle the case the the file can't be converted to a placeholder
as it is locked

Improve the error message returned by updateMetadata

---

admin/win/msi/Nextcloud.wxs
src/common/common.cmake
src/common/plugin.cpp
src/common/plugin.h
src/common/vfs.cpp
src/common/vfs.h
src/libsync/CMakeLists.txt
src/libsync/propagatedownload.h
src/libsync/vfs/CMakeLists.txt
src/libsync/vfs/cfapi/CMakeLists.txt
src/libsync/vfs/cfapi/cfapiwrapper.cpp
src/libsync/vfs/cfapi/cfapiwrapper.h
src/libsync/vfs/cfapi/hydrationjob.h
src/libsync/vfs/cfapi/vfs_cfapi.cpp
src/libsync/vfs/cfapi/vfs_cfapi.h
src/libsync/vfs/suffix/CMakeLists.txt
src/libsync/vfs/suffix/vfs_suffix.cpp
src/libsync/vfs/suffix/vfs_suffix.h
src/libsync/vfs/xattr/CMakeLists.txt
src/libsync/vfs/xattr/vfs_xattr.cpp
src/libsync/vfs/xattr/vfs_xattr.h
src/libsync/vfs/xattr/xattrwrapper.h
test/CMakeLists.txt
test/nextcloud_add_test.cmake

bring back dynamic load of VFS plugins

---

src/libsync/discovery.cpp

id sync db think a file is cirtual (empty placeholder) but file system
has a real file (non empty file) once the server has a modified version
we can no longer update it
state of file on disk takes precedence over sync DB to allow recovery

avoid being stuck trying to create placeholder for existing file

---

src/libsync/vfs/xattr/CMakeLists.txt

for a reason a mac os platform specific file is missing and before xattr
plugin was compiled only for linux

only compile xattr virtual files backend for linux platform (not unices)

---

src/gui/connectionvalidator.cpp
src/gui/connectionvalidator.h

To fix https://github.com/nextcloud/server/issues/15688
`_userVisibleUrl` is always initialized in the `void Account::setUrl(const QUrl &url)`

Remove request to config for userVisibleURL.

---

src/gui/tray/Window.qml

ensure the label width is not higher than the parent to ensure log
string get elided as expected

fix size of the Label with user status

---

src/common/remotepermissions.h

print the real permissions string instead of its address

---

src/gui/updater/ocupdater.cpp

This should fix https://github.com/nextcloud/desktop/issues/2379 and https://github.com/nextcloud/desktop/issues/3538

Show custom QDialog instead of QMessageBox when update is ready.

---

src/gui/accountsettings.cpp

ignore availability that can be very slow to check with CfApi virtual
files plugin

do not block account menu: availability checking can be slow

---

src/gui/creds/flow2auth.cpp
src/gui/creds/flow2auth.h
src/gui/wizard/webview.cpp

Enforce https in flow2 for https connections

---

src/gui/folder.cpp
test/testfolderman.cpp

Fix crash in Folder::isSyncRunning()

---

CMakeLists.txt
cmake/modules/ECMCoverageOption.cmake

takes ECMCoverageOption from ECM to enable code coverage analysis

---

src/cmd/cmd.cpp
src/libsync/account.cpp
src/libsync/account.h
src/libsync/theme.cpp
src/libsync/theme.h
test/testallfilesdeleted.cpp
test/testremotediscovery.cpp

fixes listing being incorrect when using dav endpoint

in wizard always use the correct way to get dav path

---

src/gui/tray/ActivityItem.qml
theme/Style/Style.qml

If the main dialog is a regular window the size of the background when hovering over the activity list items should not be constrained. Otherwise, the hover effect will just be visible on the half of the activity list item.

Don't constrain size of hover background

---

admin/linux/debian/drone-build.sh

Groovy support ended recently and Launchpad ceased to support it.

Do not build for Groovy

---

src/libsync/account.cpp
test/CMakeLists.txt
test/testaccount.cpp

prevent crash in Accont::davPath without credentials

---

doc/conffile.rst
src/libsync/configfile.cpp
src/libsync/syncoptions.h

fix #3313
Superseds https://github.com/nextcloud/desktop/pull/3314
Signed-off-by: szaimen <szaimen@e.mail.de>

Set default maxChunkSize to 1000MB

---

src/libsync/logger.cpp

Changed grammar

---

src/gui/accountmanager.cpp
src/libsync/account.cpp
src/libsync/account.h

Delete apptoken after account removal.

---

src/libsync/discovery.cpp

Fix incorrect activity message on invalid char in the file name.

---

appveyor.yml

appveyor storage is limited and we ran into trouble with that
plan is to directly use github to do that and have links directly in PRs

no longer produce installers that would be stored by appveyor

---

src/gui/wizard/flow2authwidget.cpp
src/gui/wizard/owncloudadvancedsetuppage.cpp
src/gui/wizard/owncloudadvancedsetuppage.h

https://docs.nextcloud.com/server/latest/developer_manual/client_apis/LoginFlow/index.html#obtaining-the-login-credentials
states that the email address can be used for login but it's not
allowed to use the email address to access webdav.
Fixes #3628

Ensure that the users id is used for accessing webdav

---

src/gui/accountmanager.cpp
src/libsync/account.cpp

With the change of commit 3e61bdc4318827d486221e56fbca3804b639fdd7
users that had their email address stored as dav_user in nextcloud.cfg
would not be able to login anymore because only the user id can be
used for login. With this commit the dav_user entry in the
nextcloud.cfg file gets replaced with dav_user_id to enforce ONE TIME
fetching of the user id for every user. As the user id can not change
it should be enough to fetch it one time.

Enforce fetching of user id

---

src/gui/wizard/flow2authwidget.cpp

App password and login name need to match. If authResult() returns the
user id the user id will be stored in webdav_user

Return the login name instead of user id

---

admin/linux/build-appimage.sh

put VFS plugins into the correct path

---

CMakeLists.txt
src/CMakeLists.txt
src/cmd/CMakeLists.txt
src/csync/CMakeLists.txt
src/gui/CMakeLists.txt
src/libsync/CMakeLists.txt
src/libsync/vfs/cfapi/CMakeLists.txt
src/libsync/vfs/suffix/CMakeLists.txt
src/libsync/vfs/xattr/CMakeLists.txt
test/CMakeLists.txt
test/csync/CMakeLists.txt
test/nextcloud_add_test.cmake

This makes the code a bit nicer to read and maybe a bit more robust.
Set the relevant OUTPUT_NAME target properties to keep the ability to
customize the names of the installed binaries.

Don't use variables for CMake target identifiers

---

src/common/constants.h
src/libsync/clientsideencryption.cpp
src/libsync/clientsideencryption.h
src/libsync/discovery.cpp
src/libsync/discoveryphase.cpp
src/libsync/discoveryphase.h
src/libsync/propagatedownload.cpp
src/libsync/propagatedownload.h
src/libsync/vfs/cfapi/hydrationjob.cpp
src/libsync/vfs/cfapi/hydrationjob.h
src/libsync/vfs/cfapi/vfs_cfapi.cpp
src/libsync/vfs/cfapi/vfs_cfapi.h
test/testclientsideencryption.cpp

I had to change code in multiple places to make the implicit hydration of E2EE files work. The additional effort took place to make sure explicit hydration still works and does not conflict with implicit one.
This will fix https://github.com/nextcloud/desktop/issues/3176.

Allow hydration of VFS placeholders that are E2E encrypted.

---

src/libsync/abstractnetworkjob.cpp

it has been also removed from the original branch so no problem removing
it

remove broken assert that is not needed and break account setup

---

src/gui/updater/ocupdater.cpp

A line break is unnecessary in this message.

l10n: Remove line break

---

src/gui/CMakeLists.txt

fix build socket api Mac specific file is now in a subdirectory

---

src/gui/CMakeLists.txt

rsvg-convert uses the same arguments as inkscape, so it's really easy to support with the existing code. I went along and changed the inkscape-specific messages and variables along with it, which might be the main discussion point about this.
Didn't add a windows executable as I have no idea if one even exists or if it would be easier to get than inkscape there.
Briefly discussed in #3518. Used rsvg-convert in my own build scripts and pngs are generated fine (and also look fine best I can tell).

Allow using rsvg-convert to generate pngs instead of inkscape

---

src/gui/owncloudsetupwizard.cpp
src/gui/wizard/flow2authwidget.cpp

Setting the credentials of the account inside the auth widget is not a
good idea as that will destroy the previous credentials object which
may wait for a signal to be emitted by the credentials dialog that
was created by the credentials that are going to be deleted. Uff.
It should be enough to set the dav user only after login because the
dav user will never change.
See also the discussion here
https://github.com/nextcloud/desktop/issues/3677#issuecomment-907976839
Fixes #3677

Only set dav user after login

---

doc/autoupdate.rst

macOS client is not able to do auto updates

---

src/libsync/abstractnetworkjob.cpp

This assert does not add value. Utility::concatUrlPath() takes care of
appending paths correctly.

Remove assert that causes crashes

---

src/libsync/pushnotifications.cpp

the slots connected to the web socket can be called even during close
and lead to infinite calls to close -> error slot -> close -> ...

prevent infinte recursion when closing a websocket in case of SSL errors

---

src/gui/wizard/webview.cpp

Accept nc scheme in provider page

---

src/gui/main.cpp

should fix wrong OpenGL rendering after suspend on Linux with NVidia
binary OpenGL driver
close #3759

set default format for QSurface to handle NVidia context loss events

---

src/gui/CMakeLists.txt
src/gui/invalidfilenamedialog.cpp
src/gui/invalidfilenamedialog.h
src/gui/invalidfilenamedialog.ui
src/gui/tray/ActivityListModel.cpp
src/gui/tray/ActivityListModel.h
src/libsync/propagateremotemkdir.cpp
src/libsync/propagateremotemove.h

Add dialog to resolve invalid filenames

---

src/cmd/cmd.cpp

Fix incorrect db name for nextcloud command line client.

---

src/gui/owncloudgui.cpp
src/gui/shareusergroupwidget.cpp
src/libsync/capabilities.cpp
src/libsync/capabilities.h
test/testcapabilities.cpp

It should solve #3107.
Not really a feature, most of the logic was in place but we were not using the permissions set in the server settings.

Use default sharing permissions from server

---

.clang-format

Setup clang-format for cpp11 universal init

---

src/libsync/clientsideencryption.cpp

We deliver our builds to users with debug logging enabled to have an
easier time finding problems. However, logging all the encryption data
in this loop is too much and should not be done in release mode.
Helps with

Don't log encryption data in release mode

---

src/csync/ConfigureChecks.cmake

Signed-off-by: Guido Falsi <madpilot@freebsd.org>
In reference to issue #3200
Looks like the argp dependency was dropped some time ago, but some code lingers in the tests and the cmake checks.
This causes problems on FreeBSD when building on a system where argp is actually present. It is picked up by the build system, but the required arguments to actually link to it are missing, and the cmdline test fails to link, causing the build to fail.
This patch removes any remaining reference to argp.
I understand this leaves cmdline as an empty shell, but this is what is going to be compiled anyway if argp is not available on the system.
Otherwise the argument parsing should be reimplemented without argp or the proper argp arguments passed at link time.

Fix argp references on FreeBSD

---

src/gui/creds/flow2auth.cpp

At that point in time _pollEndpoint isn't set yet. All the checks are
against pollEndpoint so display that one in the warning. Otherwise one
always end up with an empty URL in the logs which is not very useful for
debugging purposes.
Signed-off-by: Kevin Ottens <kevin.ottens@enioka.com>

Display the right endpoint in the warning in case of error

---

src/libsync/discoveryphase.cpp
src/libsync/discoveryphase.h

properly extract the file id when querying server

---

src/gui/application.cpp

When using push notifications, it is not necessary to do regular
connection checks because the push notifications will take care of it.
I will remove the log statements once the logic is ready.

Don't do a connection checks when using push notifications

---

src/libsync/discovery.cpp
test/testremotediscovery.cpp

See https://www.transifex.com/nextcloud/nextcloud/translate/#hu_HU/client/309577611

Make argument singular to fix i18n issue

---

admin/osx/macosx.pkgproj.cmake

Ref: https://github.com/nextcloud/desktop/issues/2659

Let the macOS installer know that the application can run on Arm64

---

src/gui/CMakeLists.txt

I attempted to build this project on Debian, `cmake` succeeded, but then compilation failed because of missing `private/qzipwriter_p.h` header. Only then did I notice that CMake actually printed out a warning that `Qt5::GuiPrivate` target was not found. From there, it took me a minute to find out that I had to install qt5base-private-dev package.
This PR makes all of this easier by turning that warning into an error. I don't know how other distributions ship GuiPrivate, so I decided not to mention a specific Debian package in the error package.
I also updated `find_package` to mention all the components that `nextcloud` and `nextcloudCore` link against.

CMake: fail if `Qt5::GuiPrivate` is not found

---

shell_integration/MacOSX/CMakeLists.txt

Fix: https://github.com/nextcloud/desktop/issues/3967

Compile Finder extensions for arm and x86

---

src/gui/tray/notificationhandler.cpp
src/gui/tray/notificationhandler.h

avoid adding icon data in a cache we never use

---

src/common/syncjournaldb.cpp
src/common/syncjournaldb.h
src/gui/folder.cpp
src/gui/folder.h

In the past not all files were converted to placeholder files when
converting an existing sync folder to a virtual files folder. Because
some files were not converted to placeholder files, the status would
be wrong on the files. This code makes sure that every file in a
virtual files folder is a placeholder file. It could be removed in the
future.

Correct virtual files placeholder files if needed

---

src/gui/tray/unifiedsearchresultslistmodel.cpp

Use QUrl::fromLocalFile to open local files in Unified Search results

---

src/common/syncjournaldb.cpp
src/common/syncjournaldb.h
src/gui/folder.cpp

the new method added to query the db is not working and so the fix for
vfs is executed at each sync run
the new method for bool was not really needed so let's just remove it
(and that will make the usage of SqlQuery be correct

properly query sync journal DB to know when to run fix for VFS

---

src/libsync/discovery.cpp

One way to fix #3912, until a better solution is found (e.g. proper detection of rename)

Quick fix! Disable VFS folders removal for non-Windows VFS.

---

src/gui/systray.cpp
src/gui/systray.h

ensure network access made via qml are using our user agent

add a network access factory to qml engine

---

src/gui/wizard/owncloudadvancedsetuppage.cpp

fix button that should be disabled when force VFS

---

CMakeLists.txt
doc/building.rst
shell_integration/MacOSX/CMakeLists.txt

For development a app bundle is not needed. The app bundle is only
needed for distribution and macdeployqt takes a lot of time.

Only build app bundle if requested

---

src/libsync/bulkpropagatorjob.cpp

prevent sync engine being stuck because of an error when preparing bulk
upload

if BulkPropagatorJob abort after an error emit finished signal

---

src/libsync/discovery.cpp
test/testlocaldiscovery.cpp

do not forget the path when renaming files with invalid names

---

src/libsync/bulkpropagatorjob.cpp
src/libsync/owncloudpropagator.cpp
src/libsync/propagatedownload.cpp
src/libsync/propagateupload.cpp

be sure that even in release mode no errors when calling getModTime
could be ignored

ensure any errors after calling FileSystem::getModTime are handled

---

src/gui/tray/ActivityItem.qml
src/gui/tray/activitylistmodel.cpp
src/gui/tray/activitylistmodel.h

This fixes one of the issues brought up by #3660

Hide share button for deleted files and ignored files in tray activity 

---

src/libsync/discovery.cpp

Fix for #4093 as the message is just misleading, while nothing happens in reality. In case files are going to be cleared, there will be a separate message for every file later in this method.

Do not display 'Conflict when uploading some files to a folder

---

.drone.yml
CMakeLists.txt
src/gui/CMakeLists.txt

This PR adds the option of compiling the tray's QML code when compiling the client with CMake

Add option of enabling QtQuick compiler

---

src/common/checksums.cpp
src/common/checksums.h
src/libsync/account.cpp
src/libsync/account.h
src/libsync/deletejob.cpp
src/libsync/deletejob.h
src/libsync/networkjobs.cpp
src/libsync/networkjobs.h
src/libsync/propagatedownload.cpp
src/libsync/propagatedownload.h
src/libsync/propagatorjobs.h
test/testchecksumvalidator.cpp
test/testsyncengine.cpp

As https://github.com/nextcloud/server/pull/27378 is already merged and is going to be released in NC24.
This will fix #3409

Ask server to recalculate checksum(hash)

---

sync-exclude.lst

When dragging highlighted text to a folder or desktop location, macOS creates a file with a .textClipping. This file does not, howver, contain any data. "The files cannot easily be shared between Macs or sent to other machines like an attachment. Opening the textClipping file in most applications will show a 0 byte empty data file. " 
https://en.wikipedia.org/wiki/TextClipping
This produces errors during sync. Solution here is to add these files to the ignore list.
Fixes #1076

Add macOS *.textClipping files to ignore list

---

src/libsync/logger.cpp

The PR allows Visual Studio and DebugView utility to catch logs if client compiled for Windows in Debug mode.
Very useful for debugging in Visual Studio.

write logs to Output window of Visual Studio

---

src/gui/CMakeLists.txt
src/gui/passwordinputdialog.cpp
src/gui/passwordinputdialog.h
src/gui/passwordinputdialog.ui
src/gui/sharedialog.cpp
src/gui/sharedialog.h

Display error message when creating a link share with compromised password.

---

CMakeLists.txt

do not activate quick compiler by default

---

src/libsync/bulkpropagatorjob.cpp
src/libsync/owncloudpropagator.cpp
src/libsync/propagateupload.cpp
src/libsync/vfs/cfapi/cfapiwrapper.cpp
src/libsync/vfs/suffix/vfs_suffix.cpp
src/libsync/vfs/xattr/vfs_xattr.cpp

The strings at Transifex are not using correct grammar.
I know from technical side "modified time" as stand alone is ok.
Read few articles like https://www.howtogeek.com/517098/linux-file-timestamps-explained-atime-mtime-and-ctime/ and https://www.geeksforgeeks.org/file-timestamps-mtime-ctime-and-atime-in-linux . After reviewing strings and talked to others at Transifex I propose changes of this PR.

l10n: Change "modified time" to "modification time"

---

src/gui/sharedialog.cpp
src/gui/sharedialog.h

This should fix https://github.com/nextcloud/desktop/issues/4107

Bugfix. Re-init sharing manager to enable link sharing UI when receivng sharing permissions.

---

src/gui/tray/ActivityItem.qml
src/gui/tray/activitydata.h
src/gui/tray/activitylistmodel.cpp
src/gui/tray/activitylistmodel.h
src/gui/tray/usermodel.cpp

Showing the full filepath for files in the tray's activity view often makes it pretty difficult to tell exactly what files has been changed/added/deleted. This has been mentioned in #3660 .
This PR modifies the tray's activity items to behave like Nextcloud's activity items in the web UI. Only the filenames are shown in the item text, and on hover a tooltip displays the full path to the files in question.
To do this, the Activity class now stores data relating to subject rich text, including the parameters used by these rich text strings. Using these rich text strings not only allows us to change how files are displayed in the activity item subject text, but we should also be able to more easily format them if we choose to do so in the future

Show only filenames in tray activity items, with full path in tooltip

---

admin/linux/debian/drone-build.sh

Ubuntu Hirsute is obsolite, and Jammy is the next release.

Remove Hirsute, add Jammy

---

src/gui/tray/activitylistmodel.cpp
src/gui/tray/activitylistmodel.h
test/CMakeLists.txt
test/testactivitylistmodel.cpp

PR also adds fixes to issues brought up by the tests :)

Add testing for ActivityListModel

---

.github/workflows/generates_locales.yml

starts to implement this https://github.com/nextcloud/desktop/issues/3234
(I think this action will work, but well, this is the issue with dev actions, you never know before you run them :man_shrugging: )
Once pot files are in the git master branch, I'll configure [this folder in transifex](https://www.transifex.com/nextcloud/nextcloud-client-documentation/settings/integrations/) to come and pull from git automatically.
Then we'll have to modify the doc build to fetch from transifex at build time.
(and add a menu in the doc to choose lang in the doc template, we might need to change sphinx theme to ease that part)

Generates pot files automatically.

---

src/libsync/bulkpropagatorjob.cpp

makes sure that an error in bulk upload protocol jobs will be propagated
to sync engine and that the sync run will properly terminate
missing in a backport PR #4080

makes sure that sync engine terminates when an error happen

---

src/libsync/bulkpropagatorjob.cpp
test/testsyncengine.cpp

in case we get a network error during bulk propagator POST network
request, report all files within this upload as files in error that will
then be sent using the plain old WebDAV protocol

ensure that bulk upload network job errors are handled

---

shell_integration/dolphin/CMakeLists.txt
src/cmd/CMakeLists.txt
src/csync/CMakeLists.txt
src/gui/CMakeLists.txt
src/gui/socketapi/CMakeLists.txt
src/libsync/CMakeLists.txt
src/libsync/vfs/cfapi/CMakeLists.txt
src/libsync/vfs/suffix/CMakeLists.txt
src/libsync/vfs/xattr/CMakeLists.txt

qt creator for example requires that headers are explcitly given in the
source lists

add headers in cmake files to get them properly detected

---

src/libsync/propagateremotemove.cpp
test/testsyncengine.cpp
test/testsyncfilestatustracker.cpp
test/testsyncmove.cpp

Rollback local move on server move failure

---

src/libsync/owncloudpropagator.cpp
src/libsync/owncloudpropagator.h
test/testsyncengine.cpp

Do not remove a folder that has files that were not uploaded yet during propagation

---

src/gui/systray.cpp
src/gui/systray.h
src/gui/systray.mm

This fixes #4163 as we now get the actual height of the status bar rather than assume its 22px high

No longer assume status bar height, calculate, fixing notch borking

---

src/libsync/bulkpropagatorjob.cpp

l10n: Changed spelling

---

src/libsync/discovery.cpp
src/libsync/discovery.h
src/libsync/discoveryphase.cpp
src/libsync/discoveryphase.h
test/testpermissions.cpp

This should fix https://github.com/nextcloud/groupfolders/issues/1816

Do not remove files from a Group folder and its nested folders when it is renamed or removed while not allowed.

---

src/gui/main.cpp

should prevent context losses error with some opengl drivers
should prevent corruptions to occur with come opengl drivers

properly ask Qt to create qml opengl surface with proper options

---

src/gui/tray/FileActivityDialog.qml

This PR ensures that the file activity dialog appears in the centre of the screen on all platforms.
This is necessary as on macOS, the dialog would appear directly behind the tray popup

Ensure file activity dialog appears in centre of screen

---

src/gui/fileactivitylistmodel.cpp
src/gui/fileactivitylistmodel.h
src/gui/socketapi/socketapi.cpp
src/gui/socketapi/socketapi.h
src/gui/systray.h
src/gui/tray/ActivityList.qml
src/gui/tray/Window.qml
src/gui/tray/activitydata.h
src/gui/tray/activitylistmodel.cpp
src/gui/tray/activitylistmodel.h
src/gui/tray/usermodel.cpp
test/testactivitylistmodel.cpp

This PR fixes the file activity dialog, which shows up blank when clicking on certain file activities (e.g. deleted file activities). 

Fix file activity dialog

---

resources.qrc
src/gui/CMakeLists.txt
src/gui/systray.h
src/gui/tray/ActivityItem.qml
src/gui/tray/ActivityItemContent.qml
src/gui/tray/TalkReplyTextField.qml
src/gui/tray/activitydata.h
src/gui/tray/activitylistmodel.cpp
src/gui/tray/activitylistmodel.h
src/gui/tray/notificationhandler.cpp
src/gui/tray/talkreply.cpp
src/gui/tray/talkreply.h
src/gui/tray/usermodel.cpp
src/gui/tray/usermodel.h
test/CMakeLists.txt
test/testtalkreply.cpp
theme.qrc.in
theme/send.svg

#2908
You need Talk on the server - not sure yet against what version. I am testing against sermo.nextcloud com where they have the change Joas made - see https://github.com/nextcloud/desktop/issues/2908#issuecomment-983662320. If you only have Talk you can send a message to the chat, if you have sermo.nextcloud.com you can directly reply to a specific message.

Feature/Talk Reply v1

---

.gitmodules

see https://github.blog/2021-09-01-improving-git-protocol-security-github/
Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

old submodule url does not work anylonger

---

src/gui/folderwizard.cpp
src/gui/folderwizard.h

This PR fixes #3310 
How it looks with the fix:
Plasma:
Mac:
Also responds to light/dark mode switching on Linux and macOS.

Fix warn colour in dark mode

---

src/gui/systray.cpp
src/gui/tray/ActivityItem.qml
theme/Style/Style.qml

This PR should fix:
- Wrong colour of activity icons on Windows
- Too strong hihglight colour on Windows, obscuring accented buttons
- Some warnings not being highlighted properly

Fix icon color and highlight color issues

---

src/gui/tray/ActivityItem.qml
src/gui/tray/ActivityItemContent.qml
src/gui/tray/TalkReplyTextField.qml
src/gui/tray/activitydata.h
src/gui/tray/activitylistmodel.cpp
src/gui/tray/activitylistmodel.h
src/gui/tray/usermodel.cpp
src/gui/tray/usermodel.h

Improve talk reply

---

src/libsync/vfs/cfapi/cfapiwrapper.cpp
src/libsync/vfs/cfapi/hydrationjob.cpp

report status when the job is in error at end of hydration request
instead of doing the opposite
properly set status in db when a file failed to hydrate (still a virtual
file not a real one)

ensure we do properly failed hydration jobs

---

src/gui/tray/Window.qml
theme.qrc.in

A couple of small dark mode fixes:
- Added the correct path to white activity icon in the theme.qrc.in file, activity.svg icon now shows up in dark mode
- Fixed the colouring of the loading indicators on the unified search area

More dark mode fixes

---

src/libsync/discovery.cpp
src/libsync/propagateremotemkdir.cpp
src/libsync/propagateupload.cpp
test/testlocaldiscovery.cpp

ensure that normal sync engine will nto delete new file renamed due to
trailing/leading spaces in name
rename before upload in the same job to avoid having invalid state in
local desktop client database to ensure any subsequent run of the sync
engine will not make wrong decisions

avoid deleting renamed file with spaces in name

---

admin/linux/build-appimage.sh

makes sure we install files in the proper prefix
makes sure the name of files is able to adapt to branded names

fix build of appimage for branded clients

---

src/gui/tray/ActivityItemContent.qml
src/gui/tray/HeaderButton.qml
src/gui/tray/Window.qml

Mainly pertains to the header bar and share icons -- these are now coloured with contrasting black or white depending on the server theme colour.

Improve contrast on server color themed elements

---

src/gui/tray/activitydata.cpp
src/gui/tray/activitydata.h
src/gui/tray/usermodel.cpp

Previously, we would try to pull thumbnails for local changes made while the client was open. If this change was the creation of a new file, we would try to pull the thumbnail from the server before the thumbnail had been created there, leaving us with a blank square rather than the icon that we want.
This PR fixes this behaviour, ensuring that new files get an icon instead of a blank square

Fix thumbnails for new files made while client open

---

src/gui/tray/ActivityItemContent.qml
src/gui/tray/ActivityList.qml

This PR removes activity spacing in the activity list view and fixes the activity label alignment, which is now ensured to be centred

Fix positioning of activities in the activities list

---

src/gui/tray/ActivityItem.qml
src/gui/tray/ActivityItemContent.qml
src/gui/tray/SyncStatus.qml
theme/Style/Style.qml

This PR reduces the size of the mime type-only icons while keeping the size of the image thumbnails larger. It also reduces the minimum height of activity entries to increase information density. The size of the sync status icon has also been adjusted and made slightly smaller.

Realigned and resized thumbnails

---

src/gui/tray/activitylistmodel.cpp

l10n: Changed triple dot to ellipsis

---

src/gui/generalsettings.ui

Currently the button label for the debug archive creation, is: "Create debug archive ...".
The current label looks weird, since it makes it seem like something is missing / cut-off on that button.
The common UX approach with ellipsis in regards to menu option and buttons is that "..." is used to indicate that clicking the button requires then some further user input (but then the ellipsis should directly follow the label without a space in between). However, usually it is also said that buttons that open a dialog should not automatically have ellipsis.
In my current PR state, I removed them completely which might however be a step too far, so I would also be fine with adding them again, but getting rid of the blank in between => "Create debug archive..." to be in line with basically all …

Remove "…" from "Create Debug Archive" button

---

src/gui/sharedialog.ui

l10n: Remove string from translation

---

.github/ISSUE_TEMPLATE/BUG_REPORT.yml

Alongside with Server version.
Fix https://github.com/nextcloud/desktop/issues/4488
Signed-off-by: solracsf <yipsenelto@tozya.com>

Ask for Desktop Client version

---

admin/osx/make_universal.py

Small PR that fixes some typos and adds more console output to the `make_universal.py` script that creates our universal ARM/x86 macOS app bundles, which will help with debugging when things go awry

Make the make_universal.py script more verbose for easier debugging

---

src/gui/CMakeLists.txt
src/gui/application.cpp
src/gui/owncloudgui.cpp
src/gui/owncloudgui.h
src/gui/systray.cpp
src/gui/systray.h
src/gui/systray.mm
src/gui/updater/ocupdater.cpp
src/gui/updater/ocupdater.h

Our current implementation of macOS notification support uses deprecated code that prevents us from meaningfully customising notifications and making them more interactive (and thus more useful).
This PR reimplements our notification support by using Apple's UserNotifications framework, which allows us a lot more flexibility with what we can do with notifications.
Thanks to this, this PR also implements support for interactive update notifications which, upon clicking, redirect the user to the download page for the desktop client when we are not using the Sparkle auto-updater.

Revamp notifications for macOS and add support for actionable update notifications

---

src/gui/tray/activitylistmodel.cpp
test/testactivitylistmodel.cpp

Doing what I discussed with @nimishavijay in https://github.com/nextcloud/desktop/pull/4518#issuecomment-1124815066.
Just thought that we might not want to have this in a bugfix release so it would be better to have it in a different PR.

Do not replace strings in action links coming from the notification api.

---

shell_integration/MacOSX/OwnCloudFinderSync/FinderSyncExt/LocalSocketClient.m

This PR addresses crashing faced by some users of the Finder Sync extension. Stack traces indicate this crashing originates from a bad dispatch queue call, so we are guarding the calls to ensure they are only called if the `readSource` and `writeSource` queues are not null.
Addresses #4459

Fix crashing of finder sync extension caused by dispatch_source_cancel of nullptr

---

src/common/vfs.h
src/gui/systray.cpp
src/gui/systray.h

This PR fixes a bug where the tray context menu never displays "Open main dialog", only "Add account", making the tray inoperable on GNOME.
Fixes #4476

Fix tray icon not displaying "Open main dialog"

---

src/gui/tray/ActivityItem.qml
src/gui/tray/ActivityItemActions.qml
src/gui/tray/ActivityItemContent.qml
src/gui/tray/TalkReplyTextField.qml
src/gui/tray/activitydata.cpp
src/gui/tray/activitydata.h
src/gui/tray/activitylistmodel.cpp
src/gui/tray/asyncimageresponse.cpp
src/gui/tray/asyncimageresponse.h

This PR includes fixes for several critical issues with the activity list items, mainly:
- Wrong colouration of primary activity actions (e.g. the Reply button)
- Incorrect activity icon colour in dark mode (changes should also make the code around correct icon selection much cleaner and future proof, as the tray image provider can now recolour SVGs too)
- Several issues with the talk reply field relating to layout, particularly location of text field and height of activity item once the textfield is invoked and once the message has been sent, as well as readability of text
After fixes:
Before fixes:

Fix activity list item issues with colours/layout/etc.

---

src/gui/sharelinkwidget.cpp

This PR fixes a bug where on servers with no set share link expire days, the date input box for the expiry of the link would have its maximum date set to the current date, which is considered invalid by the server. With a higher minimum than maximum date the box would also be uneditable, preventing the user from fixing the date.
This PR fixes this by only applying a maximum date if the server has a set number of days to expire (i.e. if this value is larger than 0), 
Fixes #4068

Fixed share link expiration box being ineditable and always attempting to set invalid date

---

src/gui/tray/notificationhandler.cpp

add explicit capture for lambda

---

shell_integration/MacOSX/OwnCloudFinderSync/FinderSyncExt/LocalSocketClient.m

Instead of giving the `lineWritten` array a constant size, we size it depending on what we have actually written to the buffer

Fix crash caused by overflow in FinderSyncExtension

---

.github/workflows/fixup.yml

add new fixup workflow from nextcloud org

---

doc/installing.rst

The new notifications require a minimum macOS version of 10.14

Bump up minimum macOS version

---

src/gui/tray/ActivityItem.qml
src/gui/tray/ActivityItemContent.qml
theme/Style/Style.qml

Spacing is now the  same as space between lines in the text above.
It address the second item in https://github.com/nextcloud/desktop/issues/4435.
Before:
After:

Reduce spacing above the buttons: spacing should be same as space between lines in the text above

---

src/gui/tray/TalkReplyTextField.qml

Add a transparent background to the send reply button.

---

src/gui/sharedialog.cpp
src/gui/socketapi/socketapi.cpp

l10n: Fixed grammar

---

src/gui/systray.mm

Fix build on macOS versions pre-11 (down to 10.14)

---

src/gui/tray/usermodel.cpp

Prevent call dialogs from being presented when do not disturb is set as the user status

---

src/gui/wizard/welcomepage.cpp
src/gui/wizard/welcomepage.ui

Rephrase login dialog button text to be in line with clients on other platforms

---

src/libsync/vfs/cfapi/hydrationjob.cpp

It should fix the failing test in #4640.

Remove assert, it is no longer useful.

---

src/gui/tray/ActivityItemActions.qml

It is bad for accessibility.
See @jancborchardt 's comment: https://github.com/nextcloud/desktop/pull/4641#pullrequestreview-1009166937

Remove tooltip because it is only repeating the label of the link.

---

src/gui/wizard/owncloudadvancedsetuppage.cpp
src/gui/wizard/owncloudadvancedsetuppage.h
src/gui/wizard/owncloudadvancedsetuppage.ui

Redesign local folder information in the account-adding wizard

---

src/gui/UserStatusSelectorDialog.qml
src/gui/tray/UserLine.qml
src/gui/tray/Window.qml
src/gui/userstatusselectormodel.cpp

Previously, the signal handler for opening the user status selector dialog would try to trigger the loading of the selected user's user status connector for the user status selector model before the dialog had finished loading. This would cause the loading to never be triggered and the pointer to remain null, which, combined with the lack of a check for a null pointer, would cause a crash.
This PR fixes the user status connector loading behaviour to not be subject to this race condition, and adds checks for the null pointer in the user status selector model.
EDIT: upon testing this PR also fixes an issue where predefined statuses don't appear the first time the user status selector is invoked

Fix crashing when selecting user status and predefined statuses not appearing

---

src/gui/sharedialog.cpp
src/gui/sharedialog.h
src/gui/sharedialog.ui

https://user-images.githubusercontent.com/70155116/175035503-61904c6d-ee5b-4ece-b870-8aecdcc2d78a.mov
The default size of the dialog is now larger as well.
Closes #4134 and closes #4533

Make the share dialog resizeable

---

src/gui/systray.cpp

For some weird reason, setting the `QSystemTrayIcon`'s context menu after adding all the right actions will stop the previous context menu from being correctly replaced. This PR works around that by setting the context menu before all the actions are added. 
It's not clear why this issue happens -- maybe there is a faulty comparison checks when comparing the current menu and the one to be set, or some signals aren't correctly emitted in the background -- but I have double, triple, and quadruple checked and indeed changing when the context menu is set fixes the issue. 
This took quite a while to discover 😅 so I have added a comment explaining the issue
Fixes #3573

Fix the system tray menu not being correctly replaced in setupContextMenu on GNOME

---

src/gui/accountmanager.cpp
src/gui/creds/oauth.cpp
src/libsync/clientsideencryption.cpp

Correct spelling

---

src/gui/tray/ActivityItem.qml
src/gui/tray/TalkReplyTextField.qml
theme/Style/Style.qml

It should address the third and fourth item in https://github.com/nextcloud/desktop/issues/4435.
Text color:

Reply button size should be same as the input field, smaller + text color

---

src/gui/UserStatusSelector.qml

Just noticed in https://github.com/nextcloud/desktop/pull/4624
Signed-off-by: szaimen <szaimen@e.mail.de>

use an en-dash for the userstatus panel

---

src/gui/CMakeLists.txt
src/gui/callstatechecker.cpp
src/gui/callstatechecker.h
src/gui/systray.cpp
src/gui/systray.h
src/gui/tray/CallNotificationDialog.qml
src/gui/tray/usermodel.cpp
src/libsync/account.cpp
src/libsync/account.h

This PR adds a `CallStateChecker` that polls the state of the call being notified, much like the Talk iOS app, and stops the call notification if:
- The call has been joined by the user
- The call has been ended (i.e. all users have left the all)
- The notification timer has run out (60 seconds)
Fixes #4497

Close call notifications when the call has been joined by the user, or the call has ended

---

shell_integration/MacOSX/OwnCloudFinderSync/FinderSyncExt/LocalSocketClient.m

Since `dispatch_source_cancel` works asynchronously, deallocating the dispatch source synchronously runs the risk of deallocating it before `dispatch_source_cancel` has completed, causing a crash.
This PR sets a completion handler that holds a strong reference to the dispatch source to be deallocated, ensuring that the dispatch source is only deallocated after the `dispatch_source_cancel` is done.
Close #4459

Ensure the dispatch source only gets deallocated after the dispatch_source_cancel is done, avoiding crashing of the Finder Sync Extension on macOS

---

src/gui/systray.cpp
src/gui/systray.h
src/gui/tray/Window.qml

This specifically addresses a situation where upon adding a new account through the account wizard, the tray window is opened where the cursor is
Addresses a point in #4052

Work around issues with window positioning on Linux DEs, hardcode tray window to screen center when new account added

---

src/gui/wizard/owncloudwizard.cpp
src/gui/wizard/owncloudwizard.h

This PR adds a back button to the advanced setup page of the accounts wizard that returns the user to the beginning of the wizard.
Addresses a point in #4052
https://user-images.githubusercontent.com/70155116/176677235-0b865a4d-9ff2-4d13-a723-3923dfef08fd.mov

Add a custom back button to the account wizard's advanced setup page

---

src/gui/systray.cpp
src/gui/systray.h
src/gui/tray/Window.qml

The `Systray` class has at the moment several unnecessary `Q_INVOKABLE` methods, and other methods that could be simplified into properties
This PR cleans up and refactors these methods to make the code cleaner and more QML-friendly 

Clean up systray methods, make more QML-friendly

---

src/gui/CMakeLists.txt

Fix bad quote in CMakeLists PNG generation message

---

src/gui/BasicComboBox.qml
src/gui/UserStatusSelector.qml
src/gui/userstatusselectormodel.cpp
src/gui/userstatusselectormodel.h
src/libsync/ocsuserstatusconnector.cpp
src/libsync/userstatusconnector.h
test/testsetuserstatusdialog.cpp

Other changes include:
- Replaced some QML-incompatible STL containers with Qt ones
- Renamed some properties/methods to make them less confusing

Properly adapt the UserStatusSelectorModel to QML, eliminate hacks, make code more declarative

---

src/gui/owncloudgui.cpp
src/gui/systray.cpp
src/gui/systray.h
src/gui/tray/Window.qml

We now hold a reference to the QML tray window in `Systray` and handle window positioning, showing, and hiding within `Systray`
This makes what is going on much clearer 

Refactor tray window opening code for clarity and efficiency

---

src/gui/tray/usermodel.cpp
src/gui/tray/usermodel.h

Take ints by value rather than reference in UserModel methods

---

src/gui/systray.mm

While in #4563 we added an if statement to only send UNNotification types depending on the macOS version it seems that one of the values we used is not available at all on prior macOS versions.
This preprocessor directive should therefore fix compile on macOS 10.14-10.15

Use preprocessor directive rather than normal 'if' for UNNotification types

---

src/gui/settingsdialog.cpp
src/gui/systray.cpp
src/gui/systray.h
src/gui/tray/UserLine.qml
src/gui/tray/usermodel.cpp
src/gui/tray/usermodel.h

Make more use of properties over setter methods, move `Q_INVOKABLE void` methods to slots

QML-ify the UserModel, use properties rather than setter methods

---

src/gui/tray/ActivityItemContent.qml

This should fix the logs being littered with the following:
```
2022-07-15 12:48:57:132 [ warning default qrc:/qml/src/gui/tray/ActivityItemContent.qml:89 ]:	qrc:/qml/src/gui/tray/ActivityItemContent.qml:89: TypeError: Cannot read property 'paintedHeight' of null
2022-07-15 12:48:57:132 [ warning default qrc:/qml/src/gui/tray/ActivityItemContent.qml:84 ]:	qrc:/qml/src/gui/tray/ActivityItemContent.qml:84: TypeError: Cannot read property 'paintedWidth' of null
```

Fix ActivityItemContent QML paintedWidth errors

---

src/gui/tray/usermodel.cpp

With recent changes to notification handling we keep a set of already-notified notification ids and prevent these notifications from being emitted again
A hold-over from previous code is to clear all notifications and replace them with the new set of notifications. With the recent changes this causes a bug where all notifications except newly received ones are removed
This PR stops old notifications from being cleared

Stop clearing notifications when new notifications are received

---

cmake/modules/MacOSXBundleInfo.plist.in

This should prevent running the client on versions of macOS we no longer support
Fixes #4722

Update macOS Info.plist

---

src/gui/tray/UnifiedSearchResultFetchMoreTrigger.qml
src/gui/tray/UnifiedSearchResultItem.qml
src/gui/tray/UnifiedSearchResultItemSkeleton.qml
src/gui/tray/UnifiedSearchResultItemSkeletonContainer.qml
src/gui/tray/UnifiedSearchResultListItem.qml
src/gui/tray/UnifiedSearchResultNothingFound.qml
src/gui/tray/UnifiedSearchResultSectionItem.qml
src/gui/tray/Window.qml
theme/Style/Style.qml

This should make our QML code more maintainable:
1. We can reduce the amount of duplicate code quite substantially
2. QML items control their own styling, preventing situations where a styling element is changed in the item yet no visible change happens (because a parent element overrides the styling of the child item, which is unclear without a good grasp of the codebase)
3. All of our styling values are kept in one place, where they affect all components equally
This PR also fixes some typos in our variables

Stop styling QML unified search items hierarchically, use global Style constants

---

src/gui/tray/usermodel.cpp

#4706 introduced a bug where throttled notifications would not be added to the `ActivityListModel` correctly
This fixes that issue

Ensure that throttled notifications still appear in tray activity model

---

src/gui/tray/Window.qml

Addresses a point in #4432
This PR:
https://user-images.githubusercontent.com/70155116/178548606-bc086e5d-7658-4bc5-ab56-337195e3df84.mov
Before:

Make apps menu scrollable when content taller than available vertical space, preventing borking of layout

---

resources.qrc
src/gui/tray/NCBusyIndicator.qml
src/gui/tray/SyncStatus.qml
src/gui/tray/UnifiedSearchInputContainer.qml

Addresses a point in #4434 
New spinner:
https://user-images.githubusercontent.com/70155116/179546285-9cf6a3bc-f8b1-439c-92a8-ddb6e4a87669.mov
Old spinner:
https://user-images.githubusercontent.com/70155116/179546416-f1d7a79c-22b3-46b1-bcb6-f9f5e591e0a0.mov

Replace unified search text field busy indicator with custom indicator

---

src/gui/updater/ocupdater.cpp

Not rebooting when running the MSI may result in Explorer.exe failing to restart even though it is registered with Restart Manager by default. Running the MSI with full UI allows displaying the restart prompt and allows to cancel the update if accidentally started when not needed.
The downside is - the full UI sequence needs to be controlled by the user (selecting a folder, clicking next, etc.) making the update a bit less convenient, but, fully-controlled and reliable.
Switching to MSIX in future, would allows us to have a better UX with updates.

Always run MSI with full UI.

---

src/gui/tray/ActivityList.qml
src/gui/tray/Window.qml
src/gui/tray/activitydata.cpp
src/gui/tray/activitydata.h
src/gui/tray/activitylistmodel.cpp
src/gui/tray/activitylistmodel.h

If the activity refers to more than one item, it will open the containing folder (since activities with several files will contain files that are within the same folder)
Addresses a point in #4433 and fixes #4063

Clicking on an activity list item for a file opens the local file if available

---

doc/visualtour.rst
src/gui/owncloudgui.cpp

Double-clicking tray icon opens currently-selected user's local folder (if available)

---

admin/linux/debian/drone-build.sh

This patch adds a Debian Bullseye-specific build, since testing is no longer compatible with Bullseye.

Add Debian Bullseye build

---

src/gui/main.cpp

This is to fix the **"Error: Failed to create OpenGL context for format QSurfaceFormat(). This is most likely caused by not having the necessary graphics drivers installed"** on Windows 11.

Fix crash: 'Failed to create OpenGL context'.

---

src/gui/tray/UnifiedSearchResultItemSkeleton.qml
src/gui/tray/UnifiedSearchResultItemSkeletonContainer.qml
src/gui/tray/Window.qml
theme/Style/Style.qml

Addresses a point in #4432
New animation:
https://user-images.githubusercontent.com/70155116/178481904-1eaa1b6d-2287-41de-b830-d72c1cc622c9.mov
Old animation:
https://user-images.githubusercontent.com/70155116/178308771-e554cb1b-e088-4c81-a99a-3053e5c18f82.mov

Restyle unified search skeleton items animation and simplify their code

---

src/cmd/cmd.cpp
src/gui/folder.cpp
src/gui/folder.h
src/gui/socketapi/socketuploadjob.cpp
src/libsync/syncengine.cpp
src/libsync/syncengine.h
test/syncenginetestutils.cpp

will prevent nextcloudcmd command line client from ignoring the settings
handled by SyncOptions

ensure SyncEngine use an initialized instance of SyncOptions

---

src/gui/tray/Window.qml

A small PR for the visual adjustment of a separator
After changes:
Before changes:

Eliminate padding around the menu separator in the account menu

---

src/libsync/ocsuserstatusconnector.cpp

We have some bugs around setting the `Away` status due to bad parsing to string, this PR fixes these issues

Fix bugs with setting 'Away' user status

---

src/gui/tray/Window.qml

This PR fixes some QML warnings originating from a typo and a signal that had its name changed on the C++ side

Fix QML warnings

---

src/gui/tray/UserLine.qml

At the moment, the code in `UserLine.qml` is messy and has a lot of layout bugs.
This PR refactors `UserLine` so that it is sanely structured and properly considers layout restrictions and label widths. Labels should no longer elide randomly (or not at all).

Refactor user line

---

src/gui/tray/FileActivityDialog.qml

This should fix the file activity dialog window appearing underneath other windows and in weird places
@karlitschek 
With fix:
https://user-images.githubusercontent.com/70155116/185109189-e268a20c-4c7c-4026-805e-44011058d986.mov
Master:
https://user-images.githubusercontent.com/70155116/185109143-1a278826-e644-409e-8d1f-c5baff12a35c.mov

Ensure file activity dialog is centered on screen and appears at top of window stack

---

src/gui/systray.cpp

At the moment if we try to create a QML component (such as the call notification dialog) in systray.cpp which has an error, the client crashes. 
When we try to open the tray window, the client does not crash, but it always provides a generic and unhelpful "QQMLApplicationEngine failed to load component" error.
This PR fixes both of these issues by checking `QQmlComponent`s for errors before trying to create them, and logging the error message if there is one.

Prevent crashing when trying to create error-ing QML component in systray.cpp, output error to log

---

src/gui/PredefinedStatusButton.qml
src/gui/UserStatusSelector.qml

This should make the alignment correct with any set of emoji fonts
Plasma emoji fonts:
macOS emoji fonts:

Fix alignment of predefined status contents regardless of emoji fonts

---

src/gui/UserStatusSelector.qml

Prevent the 'Cancel' button of the user status selector getting squashed

---

admin/linux/build-appimage.sh

build script for AppImage should not assume Nextcloud is the name

---

src/gui/tray/FileActivityDialog.qml

Playing around with Systray by calling the following methods
```
Systray.forceWindowInit(dialog);
Systray.positionWindowAtScreenCenter(dialog);
```
leads to FileActivityDialog sometimes showing up and sometimes no, completely randomly.
I am not completely sure why this happens, but, removing those calls seems to fix the issue. The dialog shows up in the center of the screen without centering it.
**UPDATE:** I have added a second commit with an alternative solution.
https://user-images.githubusercontent.com/12224014/186694980-0f37bffc-5278-47f4-9fbb-c9ee3a084a17.mp4

Fix File Activities dialog not showing up.

---

src/libsync/bulkpropagatorjob.cpp

reads and store fileId and remote permissions during bulk upload

---

.drone.yml
.github/workflows/sonarcloud.yml
admin/linux/build-appimage.sh

clean up some cruft
adapt to the new paths in CI images

do not build qt keychain already included in the CI images

---

admin/linux/debian/drone-build.sh

As discussed, Focal should be not supported from 3.6 on. Since master has been moved to 3.6.0, this PR removes building for Focal.

Remove Ubuntu Focal

---

src/libsync/vfs/cfapi/cfapiwrapper.cpp
src/libsync/vfs/cfapi/cfapiwrapper.h
src/libsync/vfs/cfapi/vfs_cfapi.cpp

Fixes #3349
The problem was occurring because inside cldapi some of the functions (CfUpdatePlaceholder) internally call CfReferenceProtectedHandle and CfReleaseProtectedHandle which seems to make the memory the handle points to invalid sometimes, seems to depend on what kind of handle it gave in the first place. Then when we call again (CfSetPinState) with the same handle, due to the invalid memory there it ends up dereferencing it twice causing the crash. Seems like more of a bug in cldapi but there's not much we can do about that.
This solution is just to get a new handle each time we use it for a function. This at least prevents a hard crash as it was before, although as stated in the issue there seems to be quite a few other errors thrown up from my cldapi. Possibly related but it …

Fix crash in cldapi.dll

---

src/gui/UserStatusSelector.qml

This PR wraps the predefined statuses in a scrollview in cases where there is not enough vertical space to display all the entries.
In most setups there is no change and the predefined statuses appear exactly as they did before:
But to prevent big breakages on setups with custom font sizing, the predefined statuses become a scrollview:
This should prevent breakages for users using larger text sizes for display or accessibility reasons

Add a ScrollView to the predefined statuses area of the UserStatusSelector

---

.drone.yml
admin/linux/upload-appimage.sh

fix script that upload AppImage to go in correct path

---

resources.qrc
src/gui/tray/ActivityItem.qml
src/gui/tray/ActivityItemActions.qml
src/gui/tray/ActivityItemContent.qml
src/gui/tray/CustomButton.qml
src/gui/tray/CustomTextButton.qml
src/gui/tray/NCToolTip.qml
src/gui/tray/TalkReplyTextField.qml
src/gui/tray/UnifiedSearchResultListItem.qml

This prevents the need to duplicate our tooltip code (like setting the content item and background) everywhere.
This tangentially also fixes an issue with tooltip text in unified search list items clipping through the tooltip

Use same tooltip component everywhere, fix tooltip clipping bugs

---

resources.qrc
src/gui/tray/UnifiedSearchResultFetchMoreTrigger.qml
src/gui/tray/UnifiedSearchResultItem.qml
src/gui/tray/UnifiedSearchResultItemSkeleton.qml
src/gui/tray/UnifiedSearchResultItemSkeletonContainer.qml
src/gui/tray/UnifiedSearchResultItemSkeletonGradientRectangle.qml
src/gui/tray/UnifiedSearchResultListItem.qml
src/gui/tray/Window.qml
src/gui/tray/unifiedsearchresult.h
src/gui/tray/unifiedsearchresultslistmodel.cpp
src/gui/tray/unifiedsearchresultslistmodel.h
theme/Style/Style.qml

Addresses a point in #4434
https://user-images.githubusercontent.com/70155116/183524941-11727d68-505d-4630-9305-605bd9d9df21.mov

Align, resize, and layout everything uniformly in the unified search view

---

src/gui/folderstatusmodel.cpp
src/gui/folderstatusmodel.h

Fix wrong estimated time when doing sync.

---

src/gui/tray/Window.qml
src/gui/tray/unifiedsearchresultslistmodel.cpp
src/gui/tray/unifiedsearchresultslistmodel.h

Set UnifiedSearchResultNothingFound visibility less messily

---

src/gui/tray/ActivityItem.qml

Rather than use a `MouseArea` and some wacky workarounds to get the sizing we want, the `ItemDelegate` does exactly what we want to the proper way

Simplify activity list delegates by making them ItemDelegates, clean up

---

src/gui/tray/ActivityItem.qml
src/gui/tray/ActivityList.qml

This PR improves our keyboard navigation of activity list items in the activity list (especially in terms of highlights).
This partially addresses #4220 (navigation within activity list items, such as to highlight action buttons, is still a bit funky)
https://user-images.githubusercontent.com/70155116/181247416-a3a07e65-24e6-4ff3-bf0b-9f3929f10dbf.mov

Improve activity list highlighting/keyboard item selection

---

src/csync/std/c_private.h
src/gui/CMakeLists.txt
src/gui/generalsettings.cpp

Qt doesn't provide any public utilities for creating ZIP archives, and by using QZipWriter we are at the mercy of this API changing without warning. From `qzipwriter.h`:
```
//
//  W A R N I N G
//  -------------
//
// This file is not part of the Qt API.  It exists for the convenience
// of the QZipWriter class.  This header file may change from
// version to version without notice, or even be removed.
//
// We mean it.
//
```
KArchive exists as a Qt add-on that should let us easily replace our use of QZipWriter without dragging in any other dependencies. This will likely require a small addition to our build andCI infra to add KArchive to our CMake build, but it should fully eliminate the risk of depending on the private API.
Fixes #3723 
Signed-off-by: Claudio Cambra …

Replace private API QZipWriter with KArchive

---

src/CMakeLists.txt

should avoid distributing broken builds missing out web flow login that
is required by some cusotmers

makes Qt WebEngine optional only on macOS

---

doc/README.md

Link to 3.0 is not working
Signed-off-by: BMerz <benedikt.merz@web.de>

Updated link to documentation

---

src/gui/systray.cpp
src/gui/systray.h
src/gui/systray.mm

This should fix some of the issues in #4897

Fix menu bar height calculation on macOS

---

src/gui/tray/ActivityItem.qml

The `ActivityItem`'s `moreActionsButton` still pulls its colour from an item that now no longer exists, hence the error
Since we don't want it to have a background anyway, at least not when it isn't hovered, there is no need to set this value as internally in `ActivityItemActions` it is set to `transparent`, which is what we want anyway

Fix ActivityItem activityHover error

---

src/gui/wizard/slideshow.cpp

The enlargement of the text partially addresses #4896
Fixing the text layouting should make it easier for translators to change the text without the text view being broken. It also lets us use larger lettering without having to be careful not to break the text view
https://user-images.githubusercontent.com/70155116/188909214-1a7fc6b6-06b3-45b4-81f4-b708202df9df.mov
Below is master:
https://user-images.githubusercontent.com/70155116/188909971-b87e1fd8-1625-44ba-a9af-0d0557935bfc.mov

Fix add account window text clipping, enlarge text

---

src/libsync/discoveryphase.cpp
src/libsync/networkjobs.cpp

It seems we refuse some XML content type formats even though they are still valid and can be parsed by the parser
Fixes #4873

Accept valid lsColJob reply XML content types

---

src/gui/fileactivitylistmodel.h
src/gui/tray/activitydata.cpp
src/gui/tray/activitydata.h
src/gui/tray/activitylistmodel.cpp
src/gui/tray/activitylistmodel.h
test/testactivitylistmodel.cpp

As it stands, the `ActivityListModel` has two issues:
1. It updates coarsely, bulldozing all prior data and replacing with newly-acquired data
2. It has duplicated and messy code relating to inserting and removing rows from the model
This refactoring eliminates these issues, which in turn also prevents the activity list view resetting every time something changes (i.e. receiving new activities, dismissing notifications, etc.) by updating the core data list granularly rather than coarsely. This addresses a point in #4432 
NOTE: this PR depends on #4735 as it removes the `clearNotifications` method which goes unused after the internal refactoring of `ActivityListModel` and the removal of `clearNotifications` from the `UserModel` in …

Refactor ActivityListModel population mechanisms

---

src/gui/owncloudsetupwizard.cpp
src/gui/wizard/owncloudwizard.cpp
src/gui/wizard/owncloudwizard.h

This PR prevents the account setup wizard from being overly large for its first view. It can resize as needed as the pages are progressed
Compared to master:
Addresses point 2 in  #4896

Make account setup wizard's adjustWizardSize resize to current page size instead of largest wizard page
